/**
 * Source records for every structured value in the breed registry.
 *
 * `accessedAt` is the date the URL was actually retrieved and read, not the
 * date a record was written. All 40 were fetched on 2026-09-13 in one pass;
 * a later edit that adds a value from a fresh read must carry a fresh date.
 *
 * Generated from the acquisition run described in
 * docs/pet-intelligence/breed-recognition-methodology.md and re-checkable with
 * `npm run breeds:verify`.
 */
import type { BreedSource } from "./types.ts";

export const BREED_SOURCES: readonly BreedSource[] = [
  {
    id: "akc-labrador-retriever",
    title: "Labrador Retriever — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/labrador-retriever/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-labrador-retriever",
    title: "LABRADOR RETRIEVER — FCI Breed Nomenclature #122",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/LABRADOR-RETRIEVER-122.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-golden-retriever",
    title: "Golden Retriever — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/golden-retriever/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-golden-retriever",
    title: "GOLDEN RETRIEVER — FCI Breed Nomenclature #111",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/GOLDEN-RETRIEVER-111.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-german-shepherd",
    title: "German Shepherd Dog — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/german-shepherd-dog/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-german-shepherd",
    title: "GERMAN SHEPHERD DOG — FCI Breed Nomenclature #166",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/GERMAN-SHEPHERD-DOG-166.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-french-bulldog",
    title: "French Bulldog — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/french-bulldog/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-french-bulldog",
    title: "FRENCH BULLDOG — FCI Breed Nomenclature #101",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/FRENCH-BULLDOG-101.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-beagle",
    title: "Beagle — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/beagle/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-beagle",
    title: "BEAGLE — FCI Breed Nomenclature #161",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/BEAGLE-161.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-poodle",
    title: "Poodle (Standard) — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/poodle-standard/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-poodle",
    title: "POODLE — FCI Breed Nomenclature #172",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/POODLE-172.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-border-collie",
    title: "Border Collie — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/border-collie/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-border-collie",
    title: "BORDER COLLIE — FCI Breed Nomenclature #297",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/BORDER-COLLIE-297.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-dachshund",
    title: "Dachshund — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/dachshund/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-dachshund",
    title: "DACHSHUND — FCI Breed Nomenclature #148",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/DACHSHUND-148.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-siberian-husky",
    title: "Siberian Husky — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/siberian-husky/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-siberian-husky",
    title: "SIBERIAN HUSKY — FCI Breed Nomenclature #270",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/SIBERIAN-HUSKY-270.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-great-dane",
    title: "Great Dane — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/great-dane/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-great-dane",
    title: "GREAT DANE — FCI Breed Nomenclature #235",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/GREAT-DANE-235.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-chihuahua",
    title: "Chihuahua — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/chihuahua/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-chihuahua",
    title: "CHIHUAHUA — FCI Breed Nomenclature #218",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/CHIHUAHUA-218.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "akc-shih-tzu",
    title: "Shih Tzu — Breed Standard & Traits",
    organization: "American Kennel Club",
    url: "https://www.akc.org/dog-breeds/shih-tzu/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "AKC breed group, published height and weight ranges, life expectancy, coat length and type, and the AKC trait scale bands normalised into FaunaHub ordinal traits.",
  },
  {
    id: "fci-shih-tzu",
    title: "SHIH TZU — FCI Breed Nomenclature #208",
    organization: "Fédération Cynologique Internationale",
    url: "https://www.fci.be/en/nomenclature/SHIH-TZU-208.html",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "FCI group and section, breed number, country of origin, and recognition status.",
  },
  {
    id: "cfa-maine-coon",
    title: "Maine Coon — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/maine-coon-cat/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-maine-coon",
    title: "Maine Coon Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/maine-coon-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
  {
    id: "cfa-siamese",
    title: "Siamese — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/siamese/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-siamese",
    title: "Siamese Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/siamese-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
  {
    id: "cfa-british-shorthair",
    title: "British Shorthair — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/british-shorthair/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-british-shorthair",
    title: "British Shorthair Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/british-shorthair-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
  {
    id: "cfa-ragdoll",
    title: "Ragdoll — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/ragdoll/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-ragdoll",
    title: "Ragdoll Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/ragdoll-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
  {
    id: "cfa-persian-cat",
    title: "Persian — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/persian/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-persian-cat",
    title: "Persian Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/persian-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
  {
    id: "cfa-bengal-cat",
    title: "Bengal — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/bengal/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-bengal-cat",
    title: "Bengal Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/bengal-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
  {
    id: "cfa-norwegian-forest-cat",
    title: "Norwegian Forest Cat — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/norwegian-forest-cat/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-norwegian-forest-cat",
    title: "Norwegian Forest Cat Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/norwegian-forest-cat-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
  {
    id: "cfa-sphynx",
    title: "Sphynx — CFA Breed Profile",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/breed/sphynx/",
    sourceType: "registry-overview",
    accessedAt: "2026-09-13",
    scope: "CFA recognition, breed description, and coat wording.",
  },
  {
    id: "cfa-std-sphynx",
    title: "Sphynx Show Standard",
    organization: "The Cat Fanciers' Association",
    url: "https://cfa.org/wp-content/uploads/2024/03/sphynx-standard.pdf",
    sourceType: "registry-standard",
    accessedAt: "2026-09-13",
    scope: "The written CFA standard. Checked for numeric size: none of the eight pilot standards publishes a weight or height figure.",
  },
];

const BY_ID = new Map(BREED_SOURCES.map((s) => [s.id, s]));

export function getBreedSource(id: string): BreedSource | undefined {
  return BY_ID.get(id);
}
