import type { Metadata } from "next";
import AnimalProfileLayout from "@/components/AnimalProfileLayout";
import { ANIMAL_SOURCES } from "@/lib/educational/animal-sources";
import { getAnimalGalleryImages, getAnimalImage, getAnimalOgImage } from "@/lib/images/animal-images";
import { buildArticleMetadata } from "@/lib/metadata";

const PATH = "/animals/blue-morpho-butterfly";
const TITLE = "Blue Morpho: Iridescent Rainforest Insect";
const DESC =
  "Learn about the blue morpho butterfly, a large Neotropical insect known for iridescent blue wings produced by structural colour rather than pigment.";

export const metadata: Metadata = buildArticleMetadata({
  title: TITLE,
  description: DESC,
  path: PATH,
  publishedTime: "2026-06-28",
  modifiedTime: "2026-06-28",
  ogImage: getAnimalOgImage("blue-morpho-butterfly"),
});

export default function BlueMorphoButterflyPage() {
  return (
    <AnimalProfileLayout
      commonName="Blue Morpho Butterfly"
      scientificName="Morpho (e.g. Morpho menelaus)"
      pageTitle={TITLE}
      description={DESC}
      path={PATH}
      parentCategory="Insects & Invertebrates"
      parentCategoryHref="/animal-encyclopedia/insects"
      tags={["Insect","Butterfly","Rainforest"]}
      image={getAnimalImage("blue-morpho-butterfly") ?? undefined}
      galleryImages={getAnimalGalleryImages("blue-morpho-butterfly")}
      sources={ANIMAL_SOURCES["blue-morpho-butterfly"]}
      publishedDate="2026-06-28"
      modifiedDate="2026-06-28"
      overview={
        <>
          <p>
            The blue morpho is among the most recognizable insects of the Neotropical rainforest, celebrated for the brilliant, shifting blue of its upper wings. &quot;Blue morpho&quot; is not a single species but a common name applied to several large butterflies in the genus <em>Morpho</em>, with <em>Morpho menelaus</em> often cited as a representative example. These butterflies are associated with humid forests in parts of Central and South America, where they are most often noticed as a flash of blue gliding through patches of light and shade.
          </p>
          <p>
            The famous blue colour is not produced by pigment. Instead, it is a structural colour created by the microscopic architecture of the wing scales, which scatter and reflect light in a way that produces an intense, metallic blue. Because the effect depends on how light strikes the scales, the colour appears to flicker and change as the butterfly moves, an effect quite different from the steady tones of pigmented wings.
          </p>
          <p>
            This profile is intended as a general, educational introduction to blue morphos as a group. Because the name covers multiple species with differing details, descriptions here are kept broad, and specifics such as exact size or range can vary from one <em>Morpho</em> species to another.
          </p>
          <h3>Taxonomy and animal group</h3>
          <p>
            Blue morphos are butterflies, insects in the order Lepidoptera, and belong to the genus <em>Morpho</em>, which is placed in the brush-footed butterfly family Nymphalidae. The common name &quot;blue morpho&quot; does not refer to a single species but to a number of species within this genus, of which <em>Morpho menelaus</em> is one frequently used example. Because several distinct species share the name, statements about &quot;the&quot; blue morpho should be understood as describing a group of related butterflies rather than one uniform kind, and the precise scientific name depends on which <em>Morpho</em> species is meant.
          </p>
          <h3>Appearance and recognition</h3>
          <p>
            Blue morphos are large butterflies, and their most distinctive feature is the vivid iridescent blue of the upper surface of the wings, a structural colour generated by microscopic ridges and layers on the wing scales rather than by any blue pigment. The underside of the wings is strikingly different: a mottled pattern of browns marked with several round eyespots, which helps a resting butterfly with closed wings blend into leaf litter and dappled forest light. As a morpho flies, the alternating flash of brilliant blue and dull brown can make it appear to flicker and vanish. Exact wingspan, the extent of the blue, and pattern details vary among the different <em>Morpho</em> species.
          </p>
        </>
      }
      habitat={
        <p>
          Blue morphos are associated with humid tropical and subtropical forests in parts of Central and South America, where they occur in rainforest interiors, forest edges, clearings, and along light gaps and watercourses. They are not found across the entire continent; rather, different <em>Morpho</em> species occupy different portions of this broad Neotropical region, and their presence is tied to forested habitat rather than open or arid land. As with many forest insects, their distribution is shaped by the availability of suitable host plants for caterpillars and of food sources for adults, and it should be read as occurring in parts of these regions rather than everywhere within them.
        </p>
      }
      diet={
        <p>
          The diet differs markedly between life stages. Caterpillars are plant feeders that consume the leaves of certain host plants, with the specific plants varying among <em>Morpho</em> species. Adult blue morphos do not feed on flower nectar in the way many butterflies do; instead they are drawn to the juices of rotting fruit, tree sap, fermenting plant matter, and fluids from decaying material, which they take up through a coiled feeding tube called a proboscis. This reliance on fermenting and decomposing food is a notable feature of their feeding ecology.
        </p>
      }
      behavior={
        <>
          <p>
            Like other butterflies, blue morphos pass through a complete life cycle of egg, caterpillar (larva), pupa (chrysalis), and winged adult. Adults are typically active by day and are often seen gliding in a bobbing, unhurried flight through forest light gaps, with the rhythmic flashing of blue and brown as the wings open and close. When at rest with wings folded, the brown, eyespotted undersides make them far less conspicuous. Many details of behavior, including flight timing and local habits, vary among the different species grouped under the name.
          </p>
          <p>
            As members of rainforest insect communities, blue morphos contribute to ecological processes at several stages of their lives. Their caterpillars are herbivores that feed on particular host plants, while adults, by feeding on rotting fruit and fermenting plant matter, take part in the use of decaying material in the forest. At every stage, eggs, caterpillars, pupae, and adults form part of the food web and may be eaten by birds, other insects, and additional predators, so the eyespotted, camouflaged undersides and the startling flashes of blue are widely interpreted as features that influence how predators detect and respond to them.
          </p>
        </>
      }
      humanInteraction={
        <p>
          Blue morphos are harmless to people; they do not bite or sting, and they are valued mainly as striking and much-photographed symbols of tropical forest life. Because the name covers several species in the genus <em>Morpho</em>, there is no single IUCN Red List category that applies to the group, and it is more accurate to say the group is not assessed as a single unit than to assign one overall status; the situation of any particular species can change as forests and assessments change. Their continued presence depends on the health of the forests they inhabit, so habitat loss is a general concern for many rainforest insects. Anyone seeking authoritative, species-specific conservation or research information should consult qualified scientific and conservation sources, and this profile is educational rather than a guide to collecting or keeping these insects.
        </p>
      }
      faqs={[
        {
          question: "Why are blue morpho wings so blue?",
          answer:
            "The blue is a structural colour, not a pigment. Microscopic ridges and layers on the wing scales scatter and reflect light to produce an intense, shifting blue, which is why the colour seems to flicker as the butterfly moves.",
        },
        {
          question: "Is the blue morpho a single species?",
          answer:
            "No. \"Blue morpho\" is a common name for several species in the genus Morpho, such as Morpho menelaus. Because of this, details like size and range vary among the different species.",
        },
        {
          question: "What do blue morphos eat?",
          answer:
            "Caterpillars feed on the leaves of certain host plants, while adults are drawn to the juices of rotting fruit, tree sap, and fermenting plant matter rather than flower nectar.",
        },
        {
          question: "What is the conservation status of the blue morpho?",
          answer:
            "Because the name covers multiple Morpho species, there is no single IUCN Red List category for the group, and it is best described as not assessed as a single unit. Like many rainforest insects, individual species depend on healthy forest habitat.",
        },
      ]}
      quickFacts={[
        { label: "Scientific name", value: "Morpho (e.g. Morpho menelaus)" },
        { label: "Animal group", value: "Invertebrate (butterfly, insect)" },
        { label: "Family/order", value: "Nymphalidae; order Lepidoptera" },
        { label: "Size", value: "Large; wingspan varies by species" },
        { label: "Diet", value: "Caterpillars eat leaves; adults take rotting fruit and juices" },
        { label: "Habitat", value: "Humid tropical and subtropical forests" },
        { label: "Range", value: "Parts of Central and South America" },
        { label: "Conservation status", value: "Not assessed as a single group (multiple Morpho species)" },
      ]}
      relatedLinks={[
        { label: "Butterfly", href: "/animals/butterfly", description: "Butterflies more broadly" },
        { label: "Moth", href: "/animals/moth", description: "Moths, for contrast" },
        { label: "Monarch Butterfly", href: "/animals/monarch-butterfly", description: "Another famous butterfly" },
        { label: "South American fauna", href: "/fauna/continents/south-america", description: "Animals of South America" },
        { label: "Insects & Invertebrates", href: "/animal-encyclopedia/insects" },
      ]}
    />
  );
}
