export const metadata = { robots: { index: false, follow: false } };

/** Must return a real 404 through the routing boundary, not a 200 or a redirect. */
export default function NotFound() {
  return (
    <main>
      <p className="tag">Proof 404</p>
      <h1>Proof route not found</h1>
      <p>PROOF-APP-MARKER: faunahub-journal-proof — this 404 was generated by the proof app.</p>
    </main>
  );
}
