/**
 * Animal inventory for the Animal Compare Center.
 *
 * GENERATED from the real `src/app/animals/<slug>/page.tsx` route tree, plus a
 * small hand-maintained set of "hub" entries for animals that have a dedicated
 * FaunaHub cluster instead of a single species profile (dogs, cats).
 *
 * Rules (enforced by tests/animal-compare.test.ts):
 *  - Every `profilePath` MUST be a route that already exists in this repo.
 *    Nothing here may invent a profile. If a comparison needs an animal that is
 *    not in this file, the comparison is rejected or deferred to the private
 *    backlog — a new profile is NEVER fabricated to satisfy a comparison.
 *  - `profileKind: "hub"` marks a cluster landing page rather than a single
 *    species profile. Those entries are deliberately few.
 */

export type CompareAnimalProfileKind = "profile" | "hub";

export interface CompareAnimal {
  /** Stable identifier used in canonicalPairKey and comparison records. */
  slug: string;
  /** Display name used in the comparison finder and validation messages. */
  name: string;
  /** A real, already-existing FaunaHub route. */
  profilePath: string;
  profileKind: CompareAnimalProfileKind;
}

/** Animals with a dedicated cluster rather than one `/animals/<slug>` profile. */
const HUB_ANIMALS: CompareAnimal[] = [
  { slug: "dog", name: "Dog", profilePath: "/dogs", profileKind: "hub" },
  { slug: "cat", name: "Cat", profilePath: "/cats", profileKind: "hub" },
];

const SPECIES_ANIMALS: CompareAnimal[] = [
  { slug: "aardvark", name: "Aardvark", profilePath: "/animals/aardvark", profileKind: "profile" },
  { slug: "aardwolf", name: "Aardwolf", profilePath: "/animals/aardwolf", profileKind: "profile" },
  { slug: "abalone", name: "Abalone", profilePath: "/animals/abalone", profileKind: "profile" },
  { slug: "adelie-penguin", name: "Adelie Penguin", profilePath: "/animals/adelie-penguin", profileKind: "profile" },
  { slug: "african-buffalo", name: "African Buffalo", profilePath: "/animals/african-buffalo", profileKind: "profile" },
  { slug: "african-grey-parrot", name: "African Grey Parrot", profilePath: "/animals/african-grey-parrot", profileKind: "profile" },
  { slug: "agama", name: "Agama", profilePath: "/animals/agama", profileKind: "profile" },
  { slug: "agouti", name: "Agouti", profilePath: "/animals/agouti", profileKind: "profile" },
  { slug: "albatross", name: "Albatross", profilePath: "/animals/albatross", profileKind: "profile" },
  { slug: "aldabra-giant-tortoise", name: "Aldabra Giant Tortoise", profilePath: "/animals/aldabra-giant-tortoise", profileKind: "profile" },
  { slug: "alligator", name: "Alligator", profilePath: "/animals/alligator", profileKind: "profile" },
  { slug: "alligator-gar", name: "Alligator Gar", profilePath: "/animals/alligator-gar", profileKind: "profile" },
  { slug: "alligator-lizard", name: "Alligator Lizard", profilePath: "/animals/alligator-lizard", profileKind: "profile" },
  { slug: "alpine-ibex", name: "Alpine Ibex", profilePath: "/animals/alpine-ibex", profileKind: "profile" },
  { slug: "amazonian-giant-centipede", name: "Amazonian Giant Centipede", profilePath: "/animals/amazonian-giant-centipede", profileKind: "profile" },
  { slug: "american-alligator", name: "American Alligator", profilePath: "/animals/american-alligator", profileKind: "profile" },
  { slug: "american-black-bear", name: "American Black Bear", profilePath: "/animals/american-black-bear", profileKind: "profile" },
  { slug: "amphipod", name: "Amphipod", profilePath: "/animals/amphipod", profileKind: "profile" },
  { slug: "amphiuma", name: "Amphiuma", profilePath: "/animals/amphiuma", profileKind: "profile" },
  { slug: "anaconda", name: "Anaconda", profilePath: "/animals/anaconda", profileKind: "profile" },
  { slug: "andean-condor", name: "Andean Condor", profilePath: "/animals/andean-condor", profileKind: "profile" },
  { slug: "angelfish", name: "Angelfish", profilePath: "/animals/angelfish", profileKind: "profile" },
  { slug: "anglerfish", name: "Anglerfish", profilePath: "/animals/anglerfish", profileKind: "profile" },
  { slug: "anole", name: "Anole", profilePath: "/animals/anole", profileKind: "profile" },
  { slug: "ant", name: "Ant", profilePath: "/animals/ant", profileKind: "profile" },
  { slug: "antarctic-krill", name: "Antarctic Krill", profilePath: "/animals/antarctic-krill", profileKind: "profile" },
  { slug: "antarctic-toothfish", name: "Antarctic Toothfish", profilePath: "/animals/antarctic-toothfish", profileKind: "profile" },
  { slug: "antlion", name: "Antlion", profilePath: "/animals/antlion", profileKind: "profile" },
  { slug: "antpitta", name: "Antpitta", profilePath: "/animals/antpitta", profileKind: "profile" },
  { slug: "aphid", name: "Aphid", profilePath: "/animals/aphid", profileKind: "profile" },
  { slug: "arapaima", name: "Arapaima", profilePath: "/animals/arapaima", profileKind: "profile" },
  { slug: "archerfish", name: "Archerfish", profilePath: "/animals/archerfish", profileKind: "profile" },
  { slug: "arctic-fox", name: "Arctic Fox", profilePath: "/animals/arctic-fox", profileKind: "profile" },
  { slug: "armadillo", name: "Armadillo", profilePath: "/animals/armadillo", profileKind: "profile" },
  { slug: "arowana", name: "Arowana", profilePath: "/animals/arowana", profileKind: "profile" },
  { slug: "asian-black-bear", name: "Asian Black Bear", profilePath: "/animals/asian-black-bear", profileKind: "profile" },
  { slug: "asian-giant-hornet", name: "Asian Giant Hornet", profilePath: "/animals/asian-giant-hornet", profileKind: "profile" },
  { slug: "asian-giant-salamander", name: "Asian Giant Salamander", profilePath: "/animals/asian-giant-salamander", profileKind: "profile" },
  { slug: "atlantic-salmon", name: "Atlantic Salmon", profilePath: "/animals/atlantic-salmon", profileKind: "profile" },
  { slug: "axolotl", name: "Axolotl", profilePath: "/animals/axolotl", profileKind: "profile" },
  { slug: "aye-aye", name: "Aye-Aye", profilePath: "/animals/aye-aye", profileKind: "profile" },
  { slug: "babirusa", name: "Babirusa", profilePath: "/animals/babirusa", profileKind: "profile" },
  { slug: "baboon", name: "Baboon", profilePath: "/animals/baboon", profileKind: "profile" },
  { slug: "badger", name: "Badger", profilePath: "/animals/badger", profileKind: "profile" },
  { slug: "bald-eagle", name: "Bald Eagle", profilePath: "/animals/bald-eagle", profileKind: "profile" },
  { slug: "bandicoot", name: "Bandicoot", profilePath: "/animals/bandicoot", profileKind: "profile" },
  { slug: "barbet", name: "Barbet", profilePath: "/animals/barbet", profileKind: "profile" },
  { slug: "barn-owl", name: "Barn Owl", profilePath: "/animals/barn-owl", profileKind: "profile" },
  { slug: "barnacle", name: "Barnacle", profilePath: "/animals/barnacle", profileKind: "profile" },
  { slug: "barracuda", name: "Barracuda", profilePath: "/animals/barracuda", profileKind: "profile" },
  { slug: "barreleye-fish", name: "Barreleye Fish", profilePath: "/animals/barreleye-fish", profileKind: "profile" },
  { slug: "basilisk", name: "Basilisk", profilePath: "/animals/basilisk", profileKind: "profile" },
  { slug: "bat", name: "Bat", profilePath: "/animals/bat", profileKind: "profile" },
  { slug: "batfish", name: "Batfish", profilePath: "/animals/batfish", profileKind: "profile" },
  { slug: "bear", name: "Bear", profilePath: "/animals/bear", profileKind: "profile" },
  { slug: "beaver", name: "Beaver", profilePath: "/animals/beaver", profileKind: "profile" },
  { slug: "bee", name: "Bee", profilePath: "/animals/bee", profileKind: "profile" },
  { slug: "bee-eater", name: "Bee Eater", profilePath: "/animals/bee-eater", profileKind: "profile" },
  { slug: "beetle", name: "Beetle", profilePath: "/animals/beetle", profileKind: "profile" },
  { slug: "bellbird", name: "Bellbird", profilePath: "/animals/bellbird", profileKind: "profile" },
  { slug: "betta-fish", name: "Betta Fish", profilePath: "/animals/betta-fish", profileKind: "profile" },
  { slug: "bichir", name: "Bichir", profilePath: "/animals/bichir", profileKind: "profile" },
  { slug: "bighorn-sheep", name: "Bighorn Sheep", profilePath: "/animals/bighorn-sheep", profileKind: "profile" },
  { slug: "bilby", name: "Bilby", profilePath: "/animals/bilby", profileKind: "profile" },
  { slug: "binturong", name: "Binturong", profilePath: "/animals/binturong", profileKind: "profile" },
  { slug: "bird-of-paradise", name: "Bird-of-Paradise", profilePath: "/animals/bird-of-paradise", profileKind: "profile" },
  { slug: "bison", name: "Bison", profilePath: "/animals/bison", profileKind: "profile" },
  { slug: "black-dragonfish", name: "Black Dragonfish", profilePath: "/animals/black-dragonfish", profileKind: "profile" },
  { slug: "black-swan", name: "Black Swan", profilePath: "/animals/black-swan", profileKind: "profile" },
  { slug: "blenny", name: "Blenny", profilePath: "/animals/blenny", profileKind: "profile" },
  { slug: "blue-morpho-butterfly", name: "Blue Morpho Butterfly", profilePath: "/animals/blue-morpho-butterfly", profileKind: "profile" },
  { slug: "blue-ringed-octopus", name: "Blue-Ringed Octopus", profilePath: "/animals/blue-ringed-octopus", profileKind: "profile" },
  { slug: "blue-tongued-skink", name: "Blue-Tongued Skink", profilePath: "/animals/blue-tongued-skink", profileKind: "profile" },
  { slug: "boa", name: "Boa", profilePath: "/animals/boa", profileKind: "profile" },
  { slug: "boat-billed-heron", name: "Boat-Billed Heron", profilePath: "/animals/boat-billed-heron", profileKind: "profile" },
  { slug: "bobcat", name: "Bobcat", profilePath: "/animals/bobcat", profileKind: "profile" },
  { slug: "bowerbird", name: "Bowerbird", profilePath: "/animals/bowerbird", profileKind: "profile" },
  { slug: "box-jellyfish", name: "Box Jellyfish", profilePath: "/animals/box-jellyfish", profileKind: "profile" },
  { slug: "box-turtle", name: "Box Turtle", profilePath: "/animals/box-turtle", profileKind: "profile" },
  { slug: "boxfish", name: "Boxfish", profilePath: "/animals/boxfish", profileKind: "profile" },
  { slug: "brain-coral", name: "Brain Coral", profilePath: "/animals/brain-coral", profileKind: "profile" },
  { slug: "broadbill", name: "Broadbill", profilePath: "/animals/broadbill", profileKind: "profile" },
  { slug: "brown-trout", name: "Brown Trout", profilePath: "/animals/brown-trout", profileKind: "profile" },
  { slug: "bullfrog", name: "Bullfrog", profilePath: "/animals/bullfrog", profileKind: "profile" },
  { slug: "bumblebee", name: "Bumblebee", profilePath: "/animals/bumblebee", profileKind: "profile" },
  { slug: "burmese-python", name: "Burmese Python", profilePath: "/animals/burmese-python", profileKind: "profile" },
  { slug: "bush-dog", name: "Bush Dog", profilePath: "/animals/bush-dog", profileKind: "profile" },
  { slug: "bustard", name: "Bustard", profilePath: "/animals/bustard", profileKind: "profile" },
  { slug: "butterfly", name: "Butterfly", profilePath: "/animals/butterfly", profileKind: "profile" },
  { slug: "butterflyfish", name: "Butterflyfish", profilePath: "/animals/butterflyfish", profileKind: "profile" },
  { slug: "button-quail", name: "Button Quail", profilePath: "/animals/button-quail", profileKind: "profile" },
  { slug: "caecilian", name: "Caecilian", profilePath: "/animals/caecilian", profileKind: "profile" },
  { slug: "caiman", name: "Caiman", profilePath: "/animals/caiman", profileKind: "profile" },
  { slug: "caiman-lizard", name: "Caiman Lizard", profilePath: "/animals/caiman-lizard", profileKind: "profile" },
  { slug: "california-condor", name: "California Condor", profilePath: "/animals/california-condor", profileKind: "profile" },
  { slug: "camel", name: "Camel", profilePath: "/animals/camel", profileKind: "profile" },
  { slug: "cane-toad", name: "Cane Toad", profilePath: "/animals/cane-toad", profileKind: "profile" },
  { slug: "capercaillie", name: "Capercaillie", profilePath: "/animals/capercaillie", profileKind: "profile" },
  { slug: "capybara", name: "Capybara", profilePath: "/animals/capybara", profileKind: "profile" },
  { slug: "caracal", name: "Caracal", profilePath: "/animals/caracal", profileKind: "profile" },
  { slug: "cardinal", name: "Cardinal", profilePath: "/animals/cardinal", profileKind: "profile" },
  { slug: "carp", name: "Carp", profilePath: "/animals/carp", profileKind: "profile" },
  { slug: "carpenter-bee", name: "Carpenter Bee", profilePath: "/animals/carpenter-bee", profileKind: "profile" },
  { slug: "cassowary", name: "Cassowary", profilePath: "/animals/cassowary", profileKind: "profile" },
  { slug: "catfish", name: "Catfish", profilePath: "/animals/catfish", profileKind: "profile" },
  { slug: "centipede", name: "Centipede", profilePath: "/animals/centipede", profileKind: "profile" },
  { slug: "chachalaca", name: "Chachalaca", profilePath: "/animals/chachalaca", profileKind: "profile" },
  { slug: "chameleon", name: "Chameleon", profilePath: "/animals/chameleon", profileKind: "profile" },
  { slug: "cheetah", name: "Cheetah", profilePath: "/animals/cheetah", profileKind: "profile" },
  { slug: "chimpanzee", name: "Chimpanzee", profilePath: "/animals/chimpanzee", profileKind: "profile" },
  { slug: "chinook-salmon", name: "Chinook Salmon", profilePath: "/animals/chinook-salmon", profileKind: "profile" },
  { slug: "chiton", name: "Chiton", profilePath: "/animals/chiton", profileKind: "profile" },
  { slug: "chorus-frog", name: "Chorus Frog", profilePath: "/animals/chorus-frog", profileKind: "profile" },
  { slug: "chuckwalla", name: "Chuckwalla", profilePath: "/animals/chuckwalla", profileKind: "profile" },
  { slug: "cicada", name: "Cicada", profilePath: "/animals/cicada", profileKind: "profile" },
  { slug: "civet", name: "Civet", profilePath: "/animals/civet", profileKind: "profile" },
  { slug: "clam", name: "Clam", profilePath: "/animals/clam", profileKind: "profile" },
  { slug: "clawed-frog", name: "Clawed Frog", profilePath: "/animals/clawed-frog", profileKind: "profile" },
  { slug: "clouded-leopard", name: "Clouded Leopard", profilePath: "/animals/clouded-leopard", profileKind: "profile" },
  { slug: "clownfish", name: "Clownfish", profilePath: "/animals/clownfish", profileKind: "profile" },
  { slug: "coati", name: "Coati", profilePath: "/animals/coati", profileKind: "profile" },
  { slug: "cobra", name: "Cobra", profilePath: "/animals/cobra", profileKind: "profile" },
  { slug: "cock-of-the-rock", name: "Cock-of-the-Rock", profilePath: "/animals/cock-of-the-rock", profileKind: "profile" },
  { slug: "cockroach", name: "Cockroach", profilePath: "/animals/cockroach", profileKind: "profile" },
  { slug: "coconut-crab", name: "Coconut Crab", profilePath: "/animals/coconut-crab", profileKind: "profile" },
  { slug: "cod", name: "Cod", profilePath: "/animals/cod", profileKind: "profile" },
  { slug: "coelacanth", name: "Coelacanth", profilePath: "/animals/coelacanth", profileKind: "profile" },
  { slug: "colobus", name: "Colobus", profilePath: "/animals/colobus", profileKind: "profile" },
  { slug: "colugo", name: "Colugo", profilePath: "/animals/colugo", profileKind: "profile" },
  { slug: "comb-jelly", name: "Comb Jelly", profilePath: "/animals/comb-jelly", profileKind: "profile" },
  { slug: "commersons-dolphin", name: "Commerson's Dolphin", profilePath: "/animals/commersons-dolphin", profileKind: "profile" },
  { slug: "common-dolphin", name: "Common Dolphin", profilePath: "/animals/common-dolphin", profileKind: "profile" },
  { slug: "common-loon", name: "Common Loon", profilePath: "/animals/common-loon", profileKind: "profile" },
  { slug: "cone-snail", name: "Cone Snail", profilePath: "/animals/cone-snail", profileKind: "profile" },
  { slug: "coral", name: "Coral", profilePath: "/animals/coral", profileKind: "profile" },
  { slug: "coral-snake", name: "Coral Snake", profilePath: "/animals/coral-snake", profileKind: "profile" },
  { slug: "cotinga", name: "Cotinga", profilePath: "/animals/cotinga", profileKind: "profile" },
  { slug: "coucal", name: "Coucal", profilePath: "/animals/coucal", profileKind: "profile" },
  { slug: "cougar", name: "Cougar", profilePath: "/animals/cougar", profileKind: "profile" },
  { slug: "courser", name: "Courser", profilePath: "/animals/courser", profileKind: "profile" },
  { slug: "cow", name: "Cow", profilePath: "/animals/cow", profileKind: "profile" },
  { slug: "cowrie", name: "Cowrie", profilePath: "/animals/cowrie", profileKind: "profile" },
  { slug: "coyote", name: "Coyote", profilePath: "/animals/coyote", profileKind: "profile" },
  { slug: "crab", name: "Crab", profilePath: "/animals/crab", profileKind: "profile" },
  { slug: "crabeater-seal", name: "Crabeater Seal", profilePath: "/animals/crabeater-seal", profileKind: "profile" },
  { slug: "crayfish", name: "Crayfish", profilePath: "/animals/crayfish", profileKind: "profile" },
  { slug: "cricket", name: "Cricket", profilePath: "/animals/cricket", profileKind: "profile" },
  { slug: "crocodile", name: "Crocodile", profilePath: "/animals/crocodile", profileKind: "profile" },
  { slug: "crow", name: "Crow", profilePath: "/animals/crow", profileKind: "profile" },
  { slug: "crown-of-thorns-starfish", name: "Crown-of-Thorns Starfish", profilePath: "/animals/crown-of-thorns-starfish", profileKind: "profile" },
  { slug: "curassow", name: "Curassow", profilePath: "/animals/curassow", profileKind: "profile" },
  { slug: "cuscus", name: "Cuscus", profilePath: "/animals/cuscus", profileKind: "profile" },
  { slug: "cuttlefish", name: "Cuttlefish", profilePath: "/animals/cuttlefish", profileKind: "profile" },
  { slug: "damselfish", name: "Damselfish", profilePath: "/animals/damselfish", profileKind: "profile" },
  { slug: "deep-sea-coral", name: "Deep Sea Coral", profilePath: "/animals/deep-sea-coral", profileKind: "profile" },
  { slug: "deer", name: "Deer", profilePath: "/animals/deer", profileKind: "profile" },
  { slug: "dhole", name: "Dhole", profilePath: "/animals/dhole", profileKind: "profile" },
  { slug: "dik-dik", name: "Dik Dik", profilePath: "/animals/dik-dik", profileKind: "profile" },
  { slug: "dingo", name: "Dingo", profilePath: "/animals/dingo", profileKind: "profile" },
  { slug: "dolphin", name: "Dolphin", profilePath: "/animals/dolphin", profileKind: "profile" },
  { slug: "douc", name: "Douc", profilePath: "/animals/douc", profileKind: "profile" },
  { slug: "douroucouli", name: "Douroucouli (Night Monkey)", profilePath: "/animals/douroucouli", profileKind: "profile" },
  { slug: "dragonet", name: "Dragonet", profilePath: "/animals/dragonet", profileKind: "profile" },
  { slug: "dragonfly", name: "Dragonfly", profilePath: "/animals/dragonfly", profileKind: "profile" },
  { slug: "drongo", name: "Drongo", profilePath: "/animals/drongo", profileKind: "profile" },
  { slug: "duck", name: "Duck", profilePath: "/animals/duck", profileKind: "profile" },
  { slug: "dugong", name: "Dugong", profilePath: "/animals/dugong", profileKind: "profile" },
  { slug: "dumbo-octopus", name: "Dumbo Octopus", profilePath: "/animals/dumbo-octopus", profileKind: "profile" },
  { slug: "dung-beetle", name: "Dung Beetle", profilePath: "/animals/dung-beetle", profileKind: "profile" },
  { slug: "eagle", name: "Eagle", profilePath: "/animals/eagle", profileKind: "profile" },
  { slug: "earthworm", name: "Earthworm", profilePath: "/animals/earthworm", profileKind: "profile" },
  { slug: "earwig", name: "Earwig", profilePath: "/animals/earwig", profileKind: "profile" },
  { slug: "echidna", name: "Echidna", profilePath: "/animals/echidna", profileKind: "profile" },
  { slug: "eel", name: "Eel", profilePath: "/animals/eel", profileKind: "profile" },
  { slug: "electric-eel", name: "Electric Eel", profilePath: "/animals/electric-eel", profileKind: "profile" },
  { slug: "elephant", name: "Elephant", profilePath: "/animals/elephant", profileKind: "profile" },
  { slug: "elk", name: "Elk", profilePath: "/animals/elk", profileKind: "profile" },
  { slug: "elkhorn-coral", name: "Elkhorn Coral", profilePath: "/animals/elkhorn-coral", profileKind: "profile" },
  { slug: "emperor-penguin", name: "Emperor Penguin", profilePath: "/animals/emperor-penguin", profileKind: "profile" },
  { slug: "emu", name: "Emu", profilePath: "/animals/emu", profileKind: "profile" },
  { slug: "eurasian-lynx", name: "Eurasian Lynx", profilePath: "/animals/eurasian-lynx", profileKind: "profile" },
  { slug: "european-badger", name: "European Badger", profilePath: "/animals/european-badger", profileKind: "profile" },
  { slug: "european-bison", name: "European Bison", profilePath: "/animals/european-bison", profileKind: "profile" },
  { slug: "european-eel", name: "European Eel", profilePath: "/animals/european-eel", profileKind: "profile" },
  { slug: "european-hare", name: "European Hare", profilePath: "/animals/european-hare", profileKind: "profile" },
  { slug: "european-hedgehog", name: "European Hedgehog", profilePath: "/animals/european-hedgehog", profileKind: "profile" },
  { slug: "european-otter", name: "European Otter", profilePath: "/animals/european-otter", profileKind: "profile" },
  { slug: "european-tree-frog", name: "European Tree Frog", profilePath: "/animals/european-tree-frog", profileKind: "profile" },
  { slug: "european-viper", name: "European Viper", profilePath: "/animals/european-viper", profileKind: "profile" },
  { slug: "fairy-wren", name: "Fairy Wren", profilePath: "/animals/fairy-wren", profileKind: "profile" },
  { slug: "falcon", name: "Falcon", profilePath: "/animals/falcon", profileKind: "profile" },
  { slug: "fennec-fox", name: "Fennec Fox", profilePath: "/animals/fennec-fox", profileKind: "profile" },
  { slug: "fiddler-crab", name: "Fiddler Crab", profilePath: "/animals/fiddler-crab", profileKind: "profile" },
  { slug: "fig-wasp", name: "Fig Wasp", profilePath: "/animals/fig-wasp", profileKind: "profile" },
  { slug: "fire-bellied-toad", name: "Fire Bellied Toad", profilePath: "/animals/fire-bellied-toad", profileKind: "profile" },
  { slug: "fire-salamander", name: "Fire Salamander", profilePath: "/animals/fire-salamander", profileKind: "profile" },
  { slug: "fishing-cat", name: "Fishing Cat", profilePath: "/animals/fishing-cat", profileKind: "profile" },
  { slug: "flamingo", name: "Flamingo", profilePath: "/animals/flamingo", profileKind: "profile" },
  { slug: "flat-headed-cat", name: "Flat-Headed Cat", profilePath: "/animals/flat-headed-cat", profileKind: "profile" },
  { slug: "flounder", name: "Flounder", profilePath: "/animals/flounder", profileKind: "profile" },
  { slug: "flying-fish", name: "Flying Fish", profilePath: "/animals/flying-fish", profileKind: "profile" },
  { slug: "flying-snake", name: "Flying Snake", profilePath: "/animals/flying-snake", profileKind: "profile" },
  { slug: "fossa", name: "Fossa", profilePath: "/animals/fossa", profileKind: "profile" },
  { slug: "fox", name: "Fox", profilePath: "/animals/fox", profileKind: "profile" },
  { slug: "frigatebird", name: "Frigatebird", profilePath: "/animals/frigatebird", profileKind: "profile" },
  { slug: "frilled-lizard", name: "Frilled Lizard", profilePath: "/animals/frilled-lizard", profileKind: "profile" },
  { slug: "frilled-shark", name: "Frilled Shark", profilePath: "/animals/frilled-shark", profileKind: "profile" },
  { slug: "frog", name: "Frog", profilePath: "/animals/frog", profileKind: "profile" },
  { slug: "frogfish", name: "Frogfish", profilePath: "/animals/frogfish", profileKind: "profile" },
  { slug: "frogmouth", name: "Frogmouth", profilePath: "/animals/frogmouth", profileKind: "profile" },
  { slug: "funnel-web-spider", name: "Funnel Web Spider", profilePath: "/animals/funnel-web-spider", profileKind: "profile" },
  { slug: "galago", name: "Galago", profilePath: "/animals/galago", profileKind: "profile" },
  { slug: "galah", name: "Galah", profilePath: "/animals/galah", profileKind: "profile" },
  { slug: "galapagos-tortoise", name: "Galapagos Tortoise", profilePath: "/animals/galapagos-tortoise", profileKind: "profile" },
  { slug: "gar", name: "Gar", profilePath: "/animals/gar", profileKind: "profile" },
  { slug: "garter-snake", name: "Garter Snake", profilePath: "/animals/garter-snake", profileKind: "profile" },
  { slug: "gecko", name: "Gecko", profilePath: "/animals/gecko", profileKind: "profile" },
  { slug: "gelada", name: "Gelada", profilePath: "/animals/gelada", profileKind: "profile" },
  { slug: "genet", name: "Genet", profilePath: "/animals/genet", profileKind: "profile" },
  { slug: "gerenuk", name: "Gerenuk", profilePath: "/animals/gerenuk", profileKind: "profile" },
  { slug: "gharial", name: "Gharial", profilePath: "/animals/gharial", profileKind: "profile" },
  { slug: "giant-anteater", name: "Giant Anteater", profilePath: "/animals/giant-anteater", profileKind: "profile" },
  { slug: "giant-clam", name: "Giant Clam", profilePath: "/animals/giant-clam", profileKind: "profile" },
  { slug: "giant-isopod", name: "Giant Isopod", profilePath: "/animals/giant-isopod", profileKind: "profile" },
  { slug: "giant-otter", name: "Giant Otter", profilePath: "/animals/giant-otter", profileKind: "profile" },
  { slug: "giant-squid", name: "Giant Squid", profilePath: "/animals/giant-squid", profileKind: "profile" },
  { slug: "giant-weta", name: "Giant Weta", profilePath: "/animals/giant-weta", profileKind: "profile" },
  { slug: "gibbon", name: "Gibbon", profilePath: "/animals/gibbon", profileKind: "profile" },
  { slug: "gila-monster", name: "Gila Monster", profilePath: "/animals/gila-monster", profileKind: "profile" },
  { slug: "giraffe", name: "Giraffe", profilePath: "/animals/giraffe", profileKind: "profile" },
  { slug: "girdled-lizard", name: "Girdled Lizard", profilePath: "/animals/girdled-lizard", profileKind: "profile" },
  { slug: "glass-frog", name: "Glass Frog", profilePath: "/animals/glass-frog", profileKind: "profile" },
  { slug: "glass-lizard", name: "Glass Lizard", profilePath: "/animals/glass-lizard", profileKind: "profile" },
  { slug: "glass-sponge", name: "Glass Sponge", profilePath: "/animals/glass-sponge", profileKind: "profile" },
  { slug: "go-away-bird", name: "Go-Away-Bird", profilePath: "/animals/go-away-bird", profileKind: "profile" },
  { slug: "goat", name: "Goat", profilePath: "/animals/goat", profileKind: "profile" },
  { slug: "goby", name: "Goby", profilePath: "/animals/goby", profileKind: "profile" },
  { slug: "golden-eagle", name: "Golden Eagle", profilePath: "/animals/golden-eagle", profileKind: "profile" },
  { slug: "goldfish", name: "Goldfish", profilePath: "/animals/goldfish", profileKind: "profile" },
  { slug: "goliath-birdeater", name: "Goliath Birdeater", profilePath: "/animals/goliath-birdeater", profileKind: "profile" },
  { slug: "goliath-frog", name: "Goliath Frog", profilePath: "/animals/goliath-frog", profileKind: "profile" },
  { slug: "goose", name: "Goose", profilePath: "/animals/goose", profileKind: "profile" },
  { slug: "gorilla", name: "Gorilla", profilePath: "/animals/gorilla", profileKind: "profile" },
  { slug: "grass-snake", name: "Grass Snake", profilePath: "/animals/grass-snake", profileKind: "profile" },
  { slug: "grasshopper", name: "Grasshopper", profilePath: "/animals/grasshopper", profileKind: "profile" },
  { slug: "great-white-shark", name: "Great White Shark", profilePath: "/animals/great-white-shark", profileKind: "profile" },
  { slug: "green-iguana", name: "Green Iguana", profilePath: "/animals/green-iguana", profileKind: "profile" },
  { slug: "green-sea-turtle", name: "Green Sea Turtle", profilePath: "/animals/green-sea-turtle", profileKind: "profile" },
  { slug: "grouper", name: "Grouper", profilePath: "/animals/grouper", profileKind: "profile" },
  { slug: "guan", name: "Guan", profilePath: "/animals/guan", profileKind: "profile" },
  { slug: "guanaco", name: "Guanaco", profilePath: "/animals/guanaco", profileKind: "profile" },
  { slug: "guenon", name: "Guenon", profilePath: "/animals/guenon", profileKind: "profile" },
  { slug: "guinea-pig", name: "Guinea Pig", profilePath: "/animals/guinea-pig", profileKind: "profile" },
  { slug: "gulper-eel", name: "Gulper Eel", profilePath: "/animals/gulper-eel", profileKind: "profile" },
  { slug: "guppy", name: "Guppy", profilePath: "/animals/guppy", profileKind: "profile" },
  { slug: "hagfish", name: "Hagfish", profilePath: "/animals/hagfish", profileKind: "profile" },
  { slug: "hamerkop", name: "Hamerkop", profilePath: "/animals/hamerkop", profileKind: "profile" },
  { slug: "hammerhead-shark", name: "Hammerhead Shark", profilePath: "/animals/hammerhead-shark", profileKind: "profile" },
  { slug: "hamster", name: "Hamster", profilePath: "/animals/hamster", profileKind: "profile" },
  { slug: "harpy-eagle", name: "Harpy Eagle", profilePath: "/animals/harpy-eagle", profileKind: "profile" },
  { slug: "hatchetfish", name: "Hatchetfish", profilePath: "/animals/hatchetfish", profileKind: "profile" },
  { slug: "hawk", name: "Hawk", profilePath: "/animals/hawk", profileKind: "profile" },
  { slug: "hawk-moth", name: "Hawk Moth", profilePath: "/animals/hawk-moth", profileKind: "profile" },
  { slug: "hawkfish", name: "Hawkfish", profilePath: "/animals/hawkfish", profileKind: "profile" },
  { slug: "hedgehog", name: "Hedgehog", profilePath: "/animals/hedgehog", profileKind: "profile" },
  { slug: "hellbender", name: "Hellbender", profilePath: "/animals/hellbender", profileKind: "profile" },
  { slug: "hermit-crab", name: "Hermit Crab", profilePath: "/animals/hermit-crab", profileKind: "profile" },
  { slug: "heron", name: "Heron", profilePath: "/animals/heron", profileKind: "profile" },
  { slug: "hippopotamus", name: "Hippopotamus", profilePath: "/animals/hippopotamus", profileKind: "profile" },
  { slug: "hoatzin", name: "Hoatzin", profilePath: "/animals/hoatzin", profileKind: "profile" },
  { slug: "honeyeater", name: "Honeyeater", profilePath: "/animals/honeyeater", profileKind: "profile" },
  { slug: "honeyguide", name: "Honeyguide", profilePath: "/animals/honeyguide", profileKind: "profile" },
  { slug: "hoopoe", name: "Hoopoe", profilePath: "/animals/hoopoe", profileKind: "profile" },
  { slug: "hornbill", name: "Hornbill", profilePath: "/animals/hornbill", profileKind: "profile" },
  { slug: "horned-lizard", name: "Horned Lizard", profilePath: "/animals/horned-lizard", profileKind: "profile" },
  { slug: "hornero", name: "Hornero", profilePath: "/animals/hornero", profileKind: "profile" },
  { slug: "horse", name: "Horse", profilePath: "/animals/horse", profileKind: "profile" },
  { slug: "horseshoe-crab", name: "Horseshoe Crab", profilePath: "/animals/horseshoe-crab", profileKind: "profile" },
  { slug: "hoverfly", name: "Hoverfly", profilePath: "/animals/hoverfly", profileKind: "profile" },
  { slug: "howler-monkey", name: "Howler Monkey", profilePath: "/animals/howler-monkey", profileKind: "profile" },
  { slug: "hummingbird", name: "Hummingbird", profilePath: "/animals/hummingbird", profileKind: "profile" },
  { slug: "hummingbird-hawk-moth", name: "Hummingbird Hawk-Moth", profilePath: "/animals/hummingbird-hawk-moth", profileKind: "profile" },
  { slug: "humpback-whale", name: "Humpback Whale", profilePath: "/animals/humpback-whale", profileKind: "profile" },
  { slug: "hydrothermal-vent-tubeworm", name: "Hydrothermal Vent Tubeworm", profilePath: "/animals/hydrothermal-vent-tubeworm", profileKind: "profile" },
  { slug: "hyena", name: "Hyena", profilePath: "/animals/hyena", profileKind: "profile" },
  { slug: "icefish", name: "Icefish", profilePath: "/animals/icefish", profileKind: "profile" },
  { slug: "iguana", name: "Iguana", profilePath: "/animals/iguana", profileKind: "profile" },
  { slug: "indri", name: "Indri", profilePath: "/animals/indri", profileKind: "profile" },
  { slug: "jabiru", name: "Jabiru", profilePath: "/animals/jabiru", profileKind: "profile" },
  { slug: "jacamar", name: "Jacamar", profilePath: "/animals/jacamar", profileKind: "profile" },
  { slug: "jacana", name: "Jacana", profilePath: "/animals/jacana", profileKind: "profile" },
  { slug: "jaguar", name: "Jaguar", profilePath: "/animals/jaguar", profileKind: "profile" },
  { slug: "jaguarundi", name: "Jaguarundi", profilePath: "/animals/jaguarundi", profileKind: "profile" },
  { slug: "jellyfish", name: "Jellyfish", profilePath: "/animals/jellyfish", profileKind: "profile" },
  { slug: "kagu", name: "Kagu", profilePath: "/animals/kagu", profileKind: "profile" },
  { slug: "kakapo", name: "Kakapo", profilePath: "/animals/kakapo", profileKind: "profile" },
  { slug: "kangaroo", name: "Kangaroo", profilePath: "/animals/kangaroo", profileKind: "profile" },
  { slug: "kea", name: "Kea", profilePath: "/animals/kea", profileKind: "profile" },
  { slug: "king-cobra", name: "King Cobra", profilePath: "/animals/king-cobra", profileKind: "profile" },
  { slug: "king-vulture", name: "King Vulture", profilePath: "/animals/king-vulture", profileKind: "profile" },
  { slug: "kingfisher", name: "Kingfisher", profilePath: "/animals/kingfisher", profileKind: "profile" },
  { slug: "kinkajou", name: "Kinkajou", profilePath: "/animals/kinkajou", profileKind: "profile" },
  { slug: "kiwi", name: "Kiwi", profilePath: "/animals/kiwi", profileKind: "profile" },
  { slug: "koala", name: "Koala", profilePath: "/animals/koala", profileKind: "profile" },
  { slug: "kodkod", name: "Kodkod", profilePath: "/animals/kodkod", profileKind: "profile" },
  { slug: "koi", name: "Koi", profilePath: "/animals/koi", profileKind: "profile" },
  { slug: "komodo-dragon", name: "Komodo Dragon", profilePath: "/animals/komodo-dragon", profileKind: "profile" },
  { slug: "kookaburra", name: "Kookaburra", profilePath: "/animals/kookaburra", profileKind: "profile" },
  { slug: "krait", name: "Krait", profilePath: "/animals/krait", profileKind: "profile" },
  { slug: "krill", name: "Krill", profilePath: "/animals/krill", profileKind: "profile" },
  { slug: "lacewing", name: "Lacewing", profilePath: "/animals/lacewing", profileKind: "profile" },
  { slug: "ladybug", name: "Ladybug", profilePath: "/animals/ladybug", profileKind: "profile" },
  { slug: "lake-sturgeon", name: "Lake Sturgeon", profilePath: "/animals/lake-sturgeon", profileKind: "profile" },
  { slug: "lamprey", name: "Lamprey", profilePath: "/animals/lamprey", profileKind: "profile" },
  { slug: "lancelet", name: "Lancelet", profilePath: "/animals/lancelet", profileKind: "profile" },
  { slug: "langur", name: "Langur", profilePath: "/animals/langur", profileKind: "profile" },
  { slug: "lanternfish", name: "Lanternfish", profilePath: "/animals/lanternfish", profileKind: "profile" },
  { slug: "leafcutter-ant", name: "Leafcutter Ant", profilePath: "/animals/leafcutter-ant", profileKind: "profile" },
  { slug: "leafcutter-bee", name: "Leafcutter Bee", profilePath: "/animals/leafcutter-bee", profileKind: "profile" },
  { slug: "leafhopper", name: "Leafhopper", profilePath: "/animals/leafhopper", profileKind: "profile" },
  { slug: "leafy-seadragon", name: "Leafy Seadragon", profilePath: "/animals/leafy-seadragon", profileKind: "profile" },
  { slug: "leatherback-sea-turtle", name: "Leatherback Sea Turtle", profilePath: "/animals/leatherback-sea-turtle", profileKind: "profile" },
  { slug: "leech", name: "Leech", profilePath: "/animals/leech", profileKind: "profile" },
  { slug: "legless-lizard", name: "Legless Lizard", profilePath: "/animals/legless-lizard", profileKind: "profile" },
  { slug: "lemur", name: "Lemur", profilePath: "/animals/lemur", profileKind: "profile" },
  { slug: "leopard", name: "Leopard", profilePath: "/animals/leopard", profileKind: "profile" },
  { slug: "leopard-seal", name: "Leopard Seal", profilePath: "/animals/leopard-seal", profileKind: "profile" },
  { slug: "limpet", name: "Limpet", profilePath: "/animals/limpet", profileKind: "profile" },
  { slug: "limpkin", name: "Limpkin", profilePath: "/animals/limpkin", profileKind: "profile" },
  { slug: "lion", name: "Lion", profilePath: "/animals/lion", profileKind: "profile" },
  { slug: "lionfish", name: "Lionfish", profilePath: "/animals/lionfish", profileKind: "profile" },
  { slug: "llama", name: "Llama", profilePath: "/animals/llama", profileKind: "profile" },
  { slug: "lobster", name: "Lobster", profilePath: "/animals/lobster", profileKind: "profile" },
  { slug: "longhorn-beetle", name: "Longhorn Beetle", profilePath: "/animals/longhorn-beetle", profileKind: "profile" },
  { slug: "luna-moth", name: "Luna Moth", profilePath: "/animals/luna-moth", profileKind: "profile" },
  { slug: "lungfish", name: "Lungfish", profilePath: "/animals/lungfish", profileKind: "profile" },
  { slug: "lynx", name: "Lynx", profilePath: "/animals/lynx", profileKind: "profile" },
  { slug: "lyrebird", name: "Lyrebird", profilePath: "/animals/lyrebird", profileKind: "profile" },
  { slug: "macaque", name: "Macaque", profilePath: "/animals/macaque", profileKind: "profile" },
  { slug: "macaw", name: "Macaw", profilePath: "/animals/macaw", profileKind: "profile" },
  { slug: "mackerel", name: "Mackerel", profilePath: "/animals/mackerel", profileKind: "profile" },
  { slug: "magpie", name: "Magpie", profilePath: "/animals/magpie", profileKind: "profile" },
  { slug: "mahseer", name: "Mahseer", profilePath: "/animals/mahseer", profileKind: "profile" },
  { slug: "mamba", name: "Mamba", profilePath: "/animals/mamba", profileKind: "profile" },
  { slug: "manakin", name: "Manakin", profilePath: "/animals/manakin", profileKind: "profile" },
  { slug: "mandarin-duck", name: "Mandarin Duck", profilePath: "/animals/mandarin-duck", profileKind: "profile" },
  { slug: "mandrill", name: "Mandrill", profilePath: "/animals/mandrill", profileKind: "profile" },
  { slug: "maned-wolf", name: "Maned Wolf", profilePath: "/animals/maned-wolf", profileKind: "profile" },
  { slug: "mantella", name: "Mantella", profilePath: "/animals/mantella", profileKind: "profile" },
  { slug: "mantis-shrimp", name: "Mantis Shrimp", profilePath: "/animals/mantis-shrimp", profileKind: "profile" },
  { slug: "marabou-stork", name: "Marabou Stork", profilePath: "/animals/marabou-stork", profileKind: "profile" },
  { slug: "marbled-newt", name: "Marbled Newt", profilePath: "/animals/marbled-newt", profileKind: "profile" },
  { slug: "margay", name: "Margay", profilePath: "/animals/margay", profileKind: "profile" },
  { slug: "marine-iguana", name: "Marine Iguana", profilePath: "/animals/marine-iguana", profileKind: "profile" },
  { slug: "markhor", name: "Markhor", profilePath: "/animals/markhor", profileKind: "profile" },
  { slug: "marmoset", name: "Marmoset", profilePath: "/animals/marmoset", profileKind: "profile" },
  { slug: "mason-bee", name: "Mason Bee", profilePath: "/animals/mason-bee", profileKind: "profile" },
  { slug: "mayfly", name: "Mayfly", profilePath: "/animals/mayfly", profileKind: "profile" },
  { slug: "meerkat", name: "Meerkat", profilePath: "/animals/meerkat", profileKind: "profile" },
  { slug: "mekong-giant-catfish", name: "Mekong Giant Catfish", profilePath: "/animals/mekong-giant-catfish", profileKind: "profile" },
  { slug: "midwife-toad", name: "Midwife Toad", profilePath: "/animals/midwife-toad", profileKind: "profile" },
  { slug: "millipede", name: "Millipede", profilePath: "/animals/millipede", profileKind: "profile" },
  { slug: "mite", name: "Mite", profilePath: "/animals/mite", profileKind: "profile" },
  { slug: "mola", name: "Mola", profilePath: "/animals/mola", profileKind: "profile" },
  { slug: "mole", name: "Mole", profilePath: "/animals/mole", profileKind: "profile" },
  { slug: "mole-rat", name: "Mole Rat", profilePath: "/animals/mole-rat", profileKind: "profile" },
  { slug: "monarch-butterfly", name: "Monarch Butterfly", profilePath: "/animals/monarch-butterfly", profileKind: "profile" },
  { slug: "mongoose", name: "Mongoose", profilePath: "/animals/mongoose", profileKind: "profile" },
  { slug: "monitor-lizard", name: "Monitor Lizard", profilePath: "/animals/monitor-lizard", profileKind: "profile" },
  { slug: "moose", name: "Moose", profilePath: "/animals/moose", profileKind: "profile" },
  { slug: "moray-eel", name: "Moray Eel", profilePath: "/animals/moray-eel", profileKind: "profile" },
  { slug: "moth", name: "Moth", profilePath: "/animals/moth", profileKind: "profile" },
  { slug: "motmot", name: "Motmot", profilePath: "/animals/motmot", profileKind: "profile" },
  { slug: "mountain-goat", name: "Mountain Goat", profilePath: "/animals/mountain-goat", profileKind: "profile" },
  { slug: "mousebird", name: "Mousebird", profilePath: "/animals/mousebird", profileKind: "profile" },
  { slug: "mudpuppy", name: "Mudpuppy", profilePath: "/animals/mudpuppy", profileKind: "profile" },
  { slug: "mudskipper", name: "Mudskipper", profilePath: "/animals/mudskipper", profileKind: "profile" },
  { slug: "muriqui", name: "Muriqui", profilePath: "/animals/muriqui", profileKind: "profile" },
  { slug: "mushroom-coral", name: "Mushroom Coral", profilePath: "/animals/mushroom-coral", profileKind: "profile" },
  { slug: "musk-deer", name: "Musk Deer", profilePath: "/animals/musk-deer", profileKind: "profile" },
  { slug: "mussel", name: "Mussel", profilePath: "/animals/mussel", profileKind: "profile" },
  { slug: "nautilus", name: "Nautilus", profilePath: "/animals/nautilus", profileKind: "profile" },
  { slug: "nectar-bat", name: "Nectar Bat", profilePath: "/animals/nectar-bat", profileKind: "profile" },
  { slug: "newt", name: "Newt", profilePath: "/animals/newt", profileKind: "profile" },
  { slug: "nightjar", name: "Nightjar", profilePath: "/animals/nightjar", profileKind: "profile" },
  { slug: "nile-crocodile", name: "Nile Crocodile", profilePath: "/animals/nile-crocodile", profileKind: "profile" },
  { slug: "nile-perch", name: "Nile Perch", profilePath: "/animals/nile-perch", profileKind: "profile" },
  { slug: "nudibranch", name: "Nudibranch", profilePath: "/animals/nudibranch", profileKind: "profile" },
  { slug: "numbat", name: "Numbat", profilePath: "/animals/numbat", profileKind: "profile" },
  { slug: "oarfish", name: "Oarfish", profilePath: "/animals/oarfish", profileKind: "profile" },
  { slug: "ocelot", name: "Ocelot", profilePath: "/animals/ocelot", profileKind: "profile" },
  { slug: "octopus", name: "Octopus", profilePath: "/animals/octopus", profileKind: "profile" },
  { slug: "okapi", name: "Okapi", profilePath: "/animals/okapi", profileKind: "profile" },
  { slug: "olingo", name: "Olingo", profilePath: "/animals/olingo", profileKind: "profile" },
  { slug: "olm", name: "Olm", profilePath: "/animals/olm", profileKind: "profile" },
  { slug: "oncilla", name: "Oncilla", profilePath: "/animals/oncilla", profileKind: "profile" },
  { slug: "orangutan", name: "Orangutan", profilePath: "/animals/orangutan", profileKind: "profile" },
  { slug: "orca", name: "Orca", profilePath: "/animals/orca", profileKind: "profile" },
  { slug: "orchid-bee", name: "Orchid Bee", profilePath: "/animals/orchid-bee", profileKind: "profile" },
  { slug: "ostrich", name: "Ostrich", profilePath: "/animals/ostrich", profileKind: "profile" },
  { slug: "otter", name: "Otter", profilePath: "/animals/otter", profileKind: "profile" },
  { slug: "owl", name: "Owl", profilePath: "/animals/owl", profileKind: "profile" },
  { slug: "oxpecker", name: "Oxpecker", profilePath: "/animals/oxpecker", profileKind: "profile" },
  { slug: "oyster", name: "Oyster", profilePath: "/animals/oyster", profileKind: "profile" },
  { slug: "paca", name: "Paca", profilePath: "/animals/paca", profileKind: "profile" },
  { slug: "paddlefish", name: "Paddlefish", profilePath: "/animals/paddlefish", profileKind: "profile" },
  { slug: "painted-frog", name: "Painted Frog", profilePath: "/animals/painted-frog", profileKind: "profile" },
  { slug: "painted-lady-butterfly", name: "Painted Lady Butterfly", profilePath: "/animals/painted-lady-butterfly", profileKind: "profile" },
  { slug: "painted-snipe", name: "Painted Snipe", profilePath: "/animals/painted-snipe", profileKind: "profile" },
  { slug: "panda", name: "Panda", profilePath: "/animals/panda", profileKind: "profile" },
  { slug: "pangolin", name: "Pangolin", profilePath: "/animals/pangolin", profileKind: "profile" },
  { slug: "parrot", name: "Parrot", profilePath: "/animals/parrot", profileKind: "profile" },
  { slug: "parrotfish", name: "Parrotfish", profilePath: "/animals/parrotfish", profileKind: "profile" },
  { slug: "peacock", name: "Peacock", profilePath: "/animals/peacock", profileKind: "profile" },
  { slug: "peccary", name: "Peccary", profilePath: "/animals/peccary", profileKind: "profile" },
  { slug: "pelican", name: "Pelican", profilePath: "/animals/pelican", profileKind: "profile" },
  { slug: "penguin", name: "Penguin", profilePath: "/animals/penguin", profileKind: "profile" },
  { slug: "pig", name: "Pig", profilePath: "/animals/pig", profileKind: "profile" },
  { slug: "pigeon", name: "Pigeon", profilePath: "/animals/pigeon", profileKind: "profile" },
  { slug: "pilot-whale", name: "Pilot Whale", profilePath: "/animals/pilot-whale", profileKind: "profile" },
  { slug: "pine-marten", name: "Pine Marten", profilePath: "/animals/pine-marten", profileKind: "profile" },
  { slug: "pink-river-dolphin", name: "Pink River Dolphin", profilePath: "/animals/pink-river-dolphin", profileKind: "profile" },
  { slug: "piranha", name: "Piranha", profilePath: "/animals/piranha", profileKind: "profile" },
  { slug: "pitta", name: "Pitta", profilePath: "/animals/pitta", profileKind: "profile" },
  { slug: "plated-lizard", name: "Plated Lizard", profilePath: "/animals/plated-lizard", profileKind: "profile" },
  { slug: "platypus", name: "Platypus", profilePath: "/animals/platypus", profileKind: "profile" },
  { slug: "poison-dart-frog", name: "Poison Dart Frog", profilePath: "/animals/poison-dart-frog", profileKind: "profile" },
  { slug: "polar-bear", name: "Polar Bear", profilePath: "/animals/polar-bear", profileKind: "profile" },
  { slug: "pollen-wasp", name: "Pollen Wasp", profilePath: "/animals/pollen-wasp", profileKind: "profile" },
  { slug: "porcupine", name: "Porcupine", profilePath: "/animals/porcupine", profileKind: "profile" },
  { slug: "potoo", name: "Potoo", profilePath: "/animals/potoo", profileKind: "profile" },
  { slug: "pratincole", name: "Pratincole", profilePath: "/animals/pratincole", profileKind: "profile" },
  { slug: "praying-mantis", name: "Praying Mantis", profilePath: "/animals/praying-mantis", profileKind: "profile" },
  { slug: "proboscis-monkey", name: "Proboscis Monkey", profilePath: "/animals/proboscis-monkey", profileKind: "profile" },
  { slug: "pronghorn", name: "Pronghorn", profilePath: "/animals/pronghorn", profileKind: "profile" },
  { slug: "puff-adder", name: "Puff Adder", profilePath: "/animals/puff-adder", profileKind: "profile" },
  { slug: "puffbird", name: "Puffbird", profilePath: "/animals/puffbird", profileKind: "profile" },
  { slug: "pufferfish", name: "Pufferfish", profilePath: "/animals/pufferfish", profileKind: "profile" },
  { slug: "python", name: "Python", profilePath: "/animals/python", profileKind: "profile" },
  { slug: "quetzal", name: "Quetzal", profilePath: "/animals/quetzal", profileKind: "profile" },
  { slug: "quokka", name: "Quokka", profilePath: "/animals/quokka", profileKind: "profile" },
  { slug: "quoll", name: "Quoll", profilePath: "/animals/quoll", profileKind: "profile" },
  { slug: "rabbit", name: "Rabbit", profilePath: "/animals/rabbit", profileKind: "profile" },
  { slug: "raccoon", name: "Raccoon", profilePath: "/animals/raccoon", profileKind: "profile" },
  { slug: "rain-frog", name: "Rain Frog", profilePath: "/animals/rain-frog", profileKind: "profile" },
  { slug: "rattlesnake", name: "Rattlesnake", profilePath: "/animals/rattlesnake", profileKind: "profile" },
  { slug: "raven", name: "Raven", profilePath: "/animals/raven", profileKind: "profile" },
  { slug: "ray", name: "Ray", profilePath: "/animals/ray", profileKind: "profile" },
  { slug: "red-backed-salamander", name: "Red-Backed Salamander", profilePath: "/animals/red-backed-salamander", profileKind: "profile" },
  { slug: "red-deer", name: "Red Deer", profilePath: "/animals/red-deer", profileKind: "profile" },
  { slug: "red-eyed-tree-frog", name: "Red-Eyed Tree Frog", profilePath: "/animals/red-eyed-tree-frog", profileKind: "profile" },
  { slug: "red-panda", name: "Red Panda", profilePath: "/animals/red-panda", profileKind: "profile" },
  { slug: "redback-spider", name: "Redback Spider", profilePath: "/animals/redback-spider", profileKind: "profile" },
  { slug: "reed-frog", name: "Reed Frog", profilePath: "/animals/reed-frog", profileKind: "profile" },
  { slug: "reef-manta-ray", name: "Reef Manta Ray", profilePath: "/animals/reef-manta-ray", profileKind: "profile" },
  { slug: "remora", name: "Remora", profilePath: "/animals/remora", profileKind: "profile" },
  { slug: "reticulated-python", name: "Reticulated Python", profilePath: "/animals/reticulated-python", profileKind: "profile" },
  { slug: "rhea", name: "Rhea", profilePath: "/animals/rhea", profileKind: "profile" },
  { slug: "rhinoceros", name: "Rhinoceros", profilePath: "/animals/rhinoceros", profileKind: "profile" },
  { slug: "ribbon-worm", name: "Ribbon Worm", profilePath: "/animals/ribbon-worm", profileKind: "profile" },
  { slug: "rissos-dolphin", name: "Risso's Dolphin", profilePath: "/animals/rissos-dolphin", profileKind: "profile" },
  { slug: "roadrunner", name: "Roadrunner", profilePath: "/animals/roadrunner", profileKind: "profile" },
  { slug: "robin", name: "Robin", profilePath: "/animals/robin", profileKind: "profile" },
  { slug: "rock-python", name: "Rock Python", profilePath: "/animals/rock-python", profileKind: "profile" },
  { slug: "roe-deer", name: "Roe Deer", profilePath: "/animals/roe-deer", profileKind: "profile" },
  { slug: "roller", name: "Roller", profilePath: "/animals/roller", profileKind: "profile" },
  { slug: "saiga", name: "Saiga", profilePath: "/animals/saiga", profileKind: "profile" },
  { slug: "saki-monkey", name: "Saki Monkey", profilePath: "/animals/saki-monkey", profileKind: "profile" },
  { slug: "salamander", name: "Salamander", profilePath: "/animals/salamander", profileKind: "profile" },
  { slug: "salmon", name: "Salmon", profilePath: "/animals/salmon", profileKind: "profile" },
  { slug: "salp", name: "Salp", profilePath: "/animals/salp", profileKind: "profile" },
  { slug: "saltwater-crocodile", name: "Saltwater Crocodile", profilePath: "/animals/saltwater-crocodile", profileKind: "profile" },
  { slug: "sand-cat", name: "Sand Cat", profilePath: "/animals/sand-cat", profileKind: "profile" },
  { slug: "sandfish", name: "Sandfish", profilePath: "/animals/sandfish", profileKind: "profile" },
  { slug: "sandgrouse", name: "Sandgrouse", profilePath: "/animals/sandgrouse", profileKind: "profile" },
  { slug: "sandhill-crane", name: "Sandhill Crane", profilePath: "/animals/sandhill-crane", profileKind: "profile" },
  { slug: "sarus-crane", name: "Sarus Crane", profilePath: "/animals/sarus-crane", profileKind: "profile" },
  { slug: "saw-scaled-viper", name: "Saw-Scaled Viper", profilePath: "/animals/saw-scaled-viper", profileKind: "profile" },
  { slug: "scallop", name: "Scallop", profilePath: "/animals/scallop", profileKind: "profile" },
  { slug: "scarlet-ibis", name: "Scarlet Ibis", profilePath: "/animals/scarlet-ibis", profileKind: "profile" },
  { slug: "scorpion", name: "Scorpion", profilePath: "/animals/scorpion", profileKind: "profile" },
  { slug: "screamer", name: "Screamer", profilePath: "/animals/screamer", profileKind: "profile" },
  { slug: "sea-anemone", name: "Sea Anemone", profilePath: "/animals/sea-anemone", profileKind: "profile" },
  { slug: "sea-cucumber", name: "Sea Cucumber", profilePath: "/animals/sea-cucumber", profileKind: "profile" },
  { slug: "sea-fan", name: "Sea Fan", profilePath: "/animals/sea-fan", profileKind: "profile" },
  { slug: "sea-slug", name: "Sea Slug", profilePath: "/animals/sea-slug", profileKind: "profile" },
  { slug: "sea-snake", name: "Sea Snake", profilePath: "/animals/sea-snake", profileKind: "profile" },
  { slug: "sea-spider", name: "Sea Spider", profilePath: "/animals/sea-spider", profileKind: "profile" },
  { slug: "sea-squirt", name: "Sea Squirt", profilePath: "/animals/sea-squirt", profileKind: "profile" },
  { slug: "sea-turtle", name: "Sea Turtle", profilePath: "/animals/sea-turtle", profileKind: "profile" },
  { slug: "sea-urchin", name: "Sea Urchin", profilePath: "/animals/sea-urchin", profileKind: "profile" },
  { slug: "seadragon", name: "Seadragon", profilePath: "/animals/seadragon", profileKind: "profile" },
  { slug: "seagull", name: "Seagull", profilePath: "/animals/seagull", profileKind: "profile" },
  { slug: "seahorse", name: "Seahorse", profilePath: "/animals/seahorse", profileKind: "profile" },
  { slug: "seal", name: "Seal", profilePath: "/animals/seal", profileKind: "profile" },
  { slug: "secretary-bird", name: "Secretary Bird", profilePath: "/animals/secretary-bird", profileKind: "profile" },
  { slug: "seriema", name: "Seriema", profilePath: "/animals/seriema", profileKind: "profile" },
  { slug: "serval", name: "Serval", profilePath: "/animals/serval", profileKind: "profile" },
  { slug: "shark", name: "Shark", profilePath: "/animals/shark", profileKind: "profile" },
  { slug: "sheep", name: "Sheep", profilePath: "/animals/sheep", profileKind: "profile" },
  { slug: "shipworm", name: "Shipworm", profilePath: "/animals/shipworm", profileKind: "profile" },
  { slug: "shoebill", name: "Shoebill", profilePath: "/animals/shoebill", profileKind: "profile" },
  { slug: "shrew", name: "Shrew", profilePath: "/animals/shrew", profileKind: "profile" },
  { slug: "shrimp", name: "Shrimp", profilePath: "/animals/shrimp", profileKind: "profile" },
  { slug: "sifaka", name: "Sifaka", profilePath: "/animals/sifaka", profileKind: "profile" },
  { slug: "silkworm", name: "Silkworm", profilePath: "/animals/silkworm", profileKind: "profile" },
  { slug: "siren", name: "Siren", profilePath: "/animals/siren", profileKind: "profile" },
  { slug: "skink", name: "Skink", profilePath: "/animals/skink", profileKind: "profile" },
  { slug: "skunk", name: "Skunk", profilePath: "/animals/skunk", profileKind: "profile" },
  { slug: "sloth", name: "Sloth", profilePath: "/animals/sloth", profileKind: "profile" },
  { slug: "slow-loris", name: "Slow Loris", profilePath: "/animals/slow-loris", profileKind: "profile" },
  { slug: "slug", name: "Slug", profilePath: "/animals/slug", profileKind: "profile" },
  { slug: "snail", name: "Snail", profilePath: "/animals/snail", profileKind: "profile" },
  { slug: "snailfish", name: "Snailfish", profilePath: "/animals/snailfish", profileKind: "profile" },
  { slug: "snake", name: "Snake", profilePath: "/animals/snake", profileKind: "profile" },
  { slug: "snakehead", name: "Snakehead", profilePath: "/animals/snakehead", profileKind: "profile" },
  { slug: "snapping-turtle", name: "Snapping Turtle", profilePath: "/animals/snapping-turtle", profileKind: "profile" },
  { slug: "snow-leopard", name: "Snow Leopard", profilePath: "/animals/snow-leopard", profileKind: "profile" },
  { slug: "snow-petrel", name: "Snow Petrel", profilePath: "/animals/snow-petrel", profileKind: "profile" },
  { slug: "snowy-owl", name: "Snowy Owl", profilePath: "/animals/snowy-owl", profileKind: "profile" },
  { slug: "spadefoot-toad", name: "Spadefoot Toad", profilePath: "/animals/spadefoot-toad", profileKind: "profile" },
  { slug: "sparrow", name: "Sparrow", profilePath: "/animals/sparrow", profileKind: "profile" },
  { slug: "spectacled-bear", name: "Spectacled Bear", profilePath: "/animals/spectacled-bear", profileKind: "profile" },
  { slug: "spider", name: "Spider", profilePath: "/animals/spider", profileKind: "profile" },
  { slug: "spider-monkey", name: "Spider Monkey", profilePath: "/animals/spider-monkey", profileKind: "profile" },
  { slug: "spinner-dolphin", name: "Spinner Dolphin", profilePath: "/animals/spinner-dolphin", profileKind: "profile" },
  { slug: "spring-peeper", name: "Spring Peeper", profilePath: "/animals/spring-peeper", profileKind: "profile" },
  { slug: "springhare", name: "Springhare", profilePath: "/animals/springhare", profileKind: "profile" },
  { slug: "squid", name: "Squid", profilePath: "/animals/squid", profileKind: "profile" },
  { slug: "squirrel", name: "Squirrel", profilePath: "/animals/squirrel", profileKind: "profile" },
  { slug: "stag-beetle", name: "Stag Beetle", profilePath: "/animals/stag-beetle", profileKind: "profile" },
  { slug: "staghorn-coral", name: "Staghorn Coral", profilePath: "/animals/staghorn-coral", profileKind: "profile" },
  { slug: "starfish", name: "Starfish", profilePath: "/animals/starfish", profileKind: "profile" },
  { slug: "stick-insect", name: "Stick Insect", profilePath: "/animals/stick-insect", profileKind: "profile" },
  { slug: "stoat", name: "Stoat", profilePath: "/animals/stoat", profileKind: "profile" },
  { slug: "stonefish", name: "Stonefish", profilePath: "/animals/stonefish", profileKind: "profile" },
  { slug: "stork", name: "Stork", profilePath: "/animals/stork", profileKind: "profile" },
  { slug: "sturgeon", name: "Sturgeon", profilePath: "/animals/sturgeon", profileKind: "profile" },
  { slug: "sugar-glider", name: "Sugar Glider", profilePath: "/animals/sugar-glider", profileKind: "profile" },
  { slug: "sun-bear", name: "Sun Bear", profilePath: "/animals/sun-bear", profileKind: "profile" },
  { slug: "sunbird", name: "Sunbird", profilePath: "/animals/sunbird", profileKind: "profile" },
  { slug: "sunbittern", name: "Sunbittern", profilePath: "/animals/sunbittern", profileKind: "profile" },
  { slug: "sungrebe", name: "Sungrebe", profilePath: "/animals/sungrebe", profileKind: "profile" },
  { slug: "surinam-toad", name: "Surinam Toad", profilePath: "/animals/surinam-toad", profileKind: "profile" },
  { slug: "swan", name: "Swan", profilePath: "/animals/swan", profileKind: "profile" },
  { slug: "swift", name: "Swift", profilePath: "/animals/swift", profileKind: "profile" },
  { slug: "takahe", name: "Takahe", profilePath: "/animals/takahe", profileKind: "profile" },
  { slug: "takin", name: "Takin", profilePath: "/animals/takin", profileKind: "profile" },
  { slug: "tamandua", name: "Tamandua", profilePath: "/animals/tamandua", profileKind: "profile" },
  { slug: "tamarin", name: "Tamarin", profilePath: "/animals/tamarin", profileKind: "profile" },
  { slug: "tapir", name: "Tapir", profilePath: "/animals/tapir", profileKind: "profile" },
  { slug: "tarantula", name: "Tarantula", profilePath: "/animals/tarantula", profileKind: "profile" },
  { slug: "tardigrade", name: "Tardigrade", profilePath: "/animals/tardigrade", profileKind: "profile" },
  { slug: "tarsier", name: "Tarsier", profilePath: "/animals/tarsier", profileKind: "profile" },
  { slug: "tasmanian-devil", name: "Tasmanian Devil", profilePath: "/animals/tasmanian-devil", profileKind: "profile" },
  { slug: "tegu", name: "Tegu", profilePath: "/animals/tegu", profileKind: "profile" },
  { slug: "tenrec", name: "Tenrec", profilePath: "/animals/tenrec", profileKind: "profile" },
  { slug: "termite", name: "Termite", profilePath: "/animals/termite", profileKind: "profile" },
  { slug: "tetra", name: "Tetra", profilePath: "/animals/tetra", profileKind: "profile" },
  { slug: "thick-knee", name: "Thick-Knee", profilePath: "/animals/thick-knee", profileKind: "profile" },
  { slug: "thorny-devil", name: "Thorny Devil", profilePath: "/animals/thorny-devil", profileKind: "profile" },
  { slug: "thrips", name: "Thrips", profilePath: "/animals/thrips", profileKind: "profile" },
  { slug: "tick", name: "Tick", profilePath: "/animals/tick", profileKind: "profile" },
  { slug: "tiger", name: "Tiger", profilePath: "/animals/tiger", profileKind: "profile" },
  { slug: "tiger-salamander", name: "Tiger Salamander", profilePath: "/animals/tiger-salamander", profileKind: "profile" },
  { slug: "tilapia", name: "Tilapia", profilePath: "/animals/tilapia", profileKind: "profile" },
  { slug: "tinamou", name: "Tinamou", profilePath: "/animals/tinamou", profileKind: "profile" },
  { slug: "titi-monkey", name: "Titi Monkey", profilePath: "/animals/titi-monkey", profileKind: "profile" },
  { slug: "toad", name: "Toad", profilePath: "/animals/toad", profileKind: "profile" },
  { slug: "tody", name: "Tody", profilePath: "/animals/tody", profileKind: "profile" },
  { slug: "tokay-gecko", name: "Tokay Gecko", profilePath: "/animals/tokay-gecko", profileKind: "profile" },
  { slug: "tomato-frog", name: "Tomato Frog", profilePath: "/animals/tomato-frog", profileKind: "profile" },
  { slug: "tortoise", name: "Tortoise", profilePath: "/animals/tortoise", profileKind: "profile" },
  { slug: "toucan", name: "Toucan", profilePath: "/animals/toucan", profileKind: "profile" },
  { slug: "tree-frog", name: "Tree Frog", profilePath: "/animals/tree-frog", profileKind: "profile" },
  { slug: "tree-kangaroo", name: "Tree Kangaroo", profilePath: "/animals/tree-kangaroo", profileKind: "profile" },
  { slug: "triggerfish", name: "Triggerfish", profilePath: "/animals/triggerfish", profileKind: "profile" },
  { slug: "trogon", name: "Trogon", profilePath: "/animals/trogon", profileKind: "profile" },
  { slug: "tropicbird", name: "Tropicbird", profilePath: "/animals/tropicbird", profileKind: "profile" },
  { slug: "trumpeter", name: "Trumpeter", profilePath: "/animals/trumpeter", profileKind: "profile" },
  { slug: "tsetse-fly", name: "Tsetse Fly", profilePath: "/animals/tsetse-fly", profileKind: "profile" },
  { slug: "tuatara", name: "Tuatara", profilePath: "/animals/tuatara", profileKind: "profile" },
  { slug: "tuna", name: "Tuna", profilePath: "/animals/tuna", profileKind: "profile" },
  { slug: "turaco", name: "Turaco", profilePath: "/animals/turaco", profileKind: "profile" },
  { slug: "turtle", name: "Turtle", profilePath: "/animals/turtle", profileKind: "profile" },
  { slug: "uakari", name: "Uakari", profilePath: "/animals/uakari", profileKind: "profile" },
  { slug: "umbrellabird", name: "Umbrellabird", profilePath: "/animals/umbrellabird", profileKind: "profile" },
  { slug: "vampire-squid", name: "Vampire Squid", profilePath: "/animals/vampire-squid", profileKind: "profile" },
  { slug: "velvet-worm", name: "Velvet Worm", profilePath: "/animals/velvet-worm", profileKind: "profile" },
  { slug: "vicuna", name: "Vicuña", profilePath: "/animals/vicuna", profileKind: "profile" },
  { slug: "viper", name: "Viper", profilePath: "/animals/viper", profileKind: "profile" },
  { slug: "vulture", name: "Vulture", profilePath: "/animals/vulture", profileKind: "profile" },
  { slug: "wall-lizard", name: "Wall Lizard", profilePath: "/animals/wall-lizard", profileKind: "profile" },
  { slug: "wallaby", name: "Wallaby", profilePath: "/animals/wallaby", profileKind: "profile" },
  { slug: "walrus", name: "Walrus", profilePath: "/animals/walrus", profileKind: "profile" },
  { slug: "wandering-albatross", name: "Wandering Albatross", profilePath: "/animals/wandering-albatross", profileKind: "profile" },
  { slug: "warthog", name: "Warthog", profilePath: "/animals/warthog", profileKind: "profile" },
  { slug: "wasp", name: "Wasp", profilePath: "/animals/wasp", profileKind: "profile" },
  { slug: "weasel", name: "Weasel", profilePath: "/animals/weasel", profileKind: "profile" },
  { slug: "weaver", name: "Weaver", profilePath: "/animals/weaver", profileKind: "profile" },
  { slug: "weddell-seal", name: "Weddell Seal", profilePath: "/animals/weddell-seal", profileKind: "profile" },
  { slug: "wedge-tailed-eagle", name: "Wedge-Tailed Eagle", profilePath: "/animals/wedge-tailed-eagle", profileKind: "profile" },
  { slug: "weeverfish", name: "Weeverfish", profilePath: "/animals/weeverfish", profileKind: "profile" },
  { slug: "weevil", name: "Weevil", profilePath: "/animals/weevil", profileKind: "profile" },
  { slug: "whale", name: "Whale", profilePath: "/animals/whale", profileKind: "profile" },
  { slug: "whelk", name: "Whelk", profilePath: "/animals/whelk", profileKind: "profile" },
  { slug: "whiptail", name: "Whiptail", profilePath: "/animals/whiptail", profileKind: "profile" },
  { slug: "white-stork", name: "White Stork", profilePath: "/animals/white-stork", profileKind: "profile" },
  { slug: "whooping-crane", name: "Whooping Crane", profilePath: "/animals/whooping-crane", profileKind: "profile" },
  { slug: "wild-boar", name: "Wild Boar", profilePath: "/animals/wild-boar", profileKind: "profile" },
  { slug: "wild-turkey", name: "Wild Turkey", profilePath: "/animals/wild-turkey", profileKind: "profile" },
  { slug: "wildebeest", name: "Wildebeest", profilePath: "/animals/wildebeest", profileKind: "profile" },
  { slug: "wolf", name: "Wolf", profilePath: "/animals/wolf", profileKind: "profile" },
  { slug: "wolffish", name: "Wolffish", profilePath: "/animals/wolffish", profileKind: "profile" },
  { slug: "wolverine", name: "Wolverine", profilePath: "/animals/wolverine", profileKind: "profile" },
  { slug: "wombat", name: "Wombat", profilePath: "/animals/wombat", profileKind: "profile" },
  { slug: "wood-frog", name: "Wood Frog", profilePath: "/animals/wood-frog", profileKind: "profile" },
  { slug: "woodlouse", name: "Woodlouse", profilePath: "/animals/woodlouse", profileKind: "profile" },
  { slug: "woodpecker", name: "Woodpecker", profilePath: "/animals/woodpecker", profileKind: "profile" },
  { slug: "woolly-monkey", name: "Woolly Monkey", profilePath: "/animals/woolly-monkey", profileKind: "profile" },
  { slug: "worm-lizard", name: "Worm Lizard", profilePath: "/animals/worm-lizard", profileKind: "profile" },
  { slug: "wrasse", name: "Wrasse", profilePath: "/animals/wrasse", profileKind: "profile" },
  { slug: "yeti-crab", name: "Yeti Crab", profilePath: "/animals/yeti-crab", profileKind: "profile" },
  { slug: "zebra", name: "Zebra", profilePath: "/animals/zebra", profileKind: "profile" },
  { slug: "zorilla", name: "Zorilla", profilePath: "/animals/zorilla", profileKind: "profile" },
];

export const COMPARE_ANIMALS: CompareAnimal[] = [...SPECIES_ANIMALS, ...HUB_ANIMALS];

const BY_SLUG = new Map(COMPARE_ANIMALS.map((a) => [a.slug, a]));

export function compareAnimalBySlug(slug: string): CompareAnimal | undefined {
  return BY_SLUG.get(slug);
}

export function isKnownAnimalSlug(slug: string): boolean {
  return BY_SLUG.has(slug);
}

export const COMPARE_ANIMAL_COUNT = COMPARE_ANIMALS.length;
