/**
 * PRIVATE comparison backlog for the Animal Compare Center.
 *
 * ────────────────────────────────────────────────────────────────────────────
 * THIS FILE MUST NEVER BE IMPORTED BY ROUTE GENERATION, THE SITEMAP, OR ANY
 * RENDERED COMPONENT. It is editorial working state, not content.
 * ────────────────────────────────────────────────────────────────────────────
 *
 * Search engines must only ever see fully authored comparison pages. Nothing
 * here produces a route, a sitemap entry, a nav item, a generateStaticParams
 * value or a public link. Promotion is how a backlog row becomes visible: a row
 * reaches `status: "published"` only once its complete page exists in the
 * public registry, and `publishedSlug` records the exact public URL segment.
 *
 * `tests/animal-compare.test.ts` enforces all of that mechanically.
 */

/** Lifecycle of a comparison candidate. Only "published" is ever public. */
export type BacklogStatus =
  | "candidate"
  | "needs-sources"
  | "blocked-missing-profile"
  | "ready-for-review"
  | "approved"
  | "published"
  | "rejected";

export type SourceReadiness = "unknown" | "needs-sources" | "sourced";
export type ProfileReadiness = "unknown" | "missing-one" | "missing-both" | "both-exist";
export type QualityRisk = "low" | "medium" | "high";

export interface BacklogCandidate {
  id: string;
  proposedSlug: string;
  animalASlug: string;
  animalBSlug: string;
  /** sort([a, b]).join("--") — same canonicalisation as published records. */
  canonicalPairKey: string;
  proposedCategory: string;
  relationship: string;
  searchIntent: string;
  sourceReadiness: SourceReadiness;
  profileReadiness: ProfileReadiness;
  qualityRisk: QualityRisk;
  status: BacklogStatus;
  /** Why it cannot be built yet. Set when status is blocked-*. */
  blockerReason?: string;
  /** Why it will not be built. Set when status is "rejected". */
  rejectionReason?: string;
  /** The real public slug. Set if and only if status is "published". */
  publishedSlug?: string;
  reviewedAt: string;
  publishedAt?: string;
  note: string;
}

export const COMPARISON_BACKLOG: BacklogCandidate[] = [
  {
    id: "bk-001",
    proposedSlug: "hamster-vs-gerbil",
    animalASlug: "hamster",
    animalBSlug: "gerbil",
    canonicalPairKey: "gerbil--hamster",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "hamster-vs-gerbil",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both small pet rodents constantly grouped together; tail is the decisive cue.",
  },
  {
    id: "bk-002",
    proposedSlug: "hamster-vs-mouse",
    animalASlug: "hamster",
    animalBSlug: "mouse",
    canonicalPairKey: "hamster--mouse",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "hamster-vs-mouse",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both small rodents; body shape, tail and sociality differ.",
  },
  {
    id: "bk-003",
    proposedSlug: "gerbil-vs-mouse",
    animalASlug: "gerbil",
    animalBSlug: "mouse",
    canonicalPairKey: "gerbil--mouse",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "gerbil-vs-mouse",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Furred tufted tail vs long scaly tail; desert vs commensal.",
  },
  {
    id: "bk-004",
    proposedSlug: "rabbit-vs-chinchilla",
    animalASlug: "rabbit",
    animalBSlug: "chinchilla",
    canonicalPairKey: "chinchilla--rabbit",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "rabbit-vs-chinchilla",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Different orders; both kept, both need very different conditions.",
  },
  {
    id: "bk-005",
    proposedSlug: "chinchilla-vs-guinea-pig",
    animalASlug: "chinchilla",
    animalBSlug: "guinea-pig",
    canonicalPairKey: "chinchilla--guinea-pig",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "chinchilla-vs-guinea-pig",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both South American caviomorph rodents; fur density and altitude adaptation differ.",
  },
  {
    id: "bk-006",
    proposedSlug: "chinchilla-vs-hamster",
    animalASlug: "chinchilla",
    animalBSlug: "hamster",
    canonicalPairKey: "chinchilla--hamster",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "chinchilla-vs-hamster",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Long-lived Andean rodent vs short-lived solitary hamster.",
  },
  {
    id: "bk-007",
    proposedSlug: "ferret-vs-rabbit",
    animalASlug: "ferret",
    animalBSlug: "rabbit",
    canonicalPairKey: "ferret--rabbit",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ferret-vs-rabbit",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Obligate carnivore vs hindgut-fermenting herbivore; historically predator and prey.",
  },
  {
    id: "bk-008",
    proposedSlug: "ferret-vs-guinea-pig",
    animalASlug: "ferret",
    animalBSlug: "guinea-pig",
    canonicalPairKey: "ferret--guinea-pig",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ferret-vs-guinea-pig",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Carnivore vs herbivore; incompatible housing.",
  },
  {
    id: "bk-009",
    proposedSlug: "ferret-vs-hamster",
    animalASlug: "ferret",
    animalBSlug: "hamster",
    canonicalPairKey: "ferret--hamster",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ferret-vs-hamster",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Mustelid carnivore vs solitary rodent.",
  },
  {
    id: "bk-010",
    proposedSlug: "mouse-vs-guinea-pig",
    animalASlug: "mouse",
    animalBSlug: "guinea-pig",
    canonicalPairKey: "guinea-pig--mouse",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "mouse-vs-guinea-pig",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both rodents, opposite social and dietary biology.",
  },
  {
    id: "bk-011",
    proposedSlug: "gerbil-vs-guinea-pig",
    animalASlug: "gerbil",
    animalBSlug: "guinea-pig",
    canonicalPairKey: "gerbil--guinea-pig",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "gerbil-vs-guinea-pig",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Arid burrower vs social Andean grazer.",
  },
  {
    id: "bk-012",
    proposedSlug: "chicken-vs-duck",
    animalASlug: "chicken",
    animalBSlug: "duck",
    canonicalPairKey: "chicken--duck",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "chicken-vs-duck",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both poultry; feet, bill, plumage waterproofing and foraging differ.",
  },
  {
    id: "bk-013",
    proposedSlug: "chicken-vs-goose",
    animalASlug: "chicken",
    animalBSlug: "goose",
    canonicalPairKey: "chicken--goose",
    proposedCategory: "pets-domestic",
    relationship: "similar-ecological-role",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "chicken-vs-goose",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both kept birds; size, neck, grazing and defence differ.",
  },
  {
    id: "bk-014",
    proposedSlug: "chicken-vs-pigeon",
    animalASlug: "chicken",
    animalBSlug: "pigeon",
    canonicalPairKey: "chicken--pigeon",
    proposedCategory: "pets-domestic",
    relationship: "taxonomy-clarification",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "chicken-vs-pigeon",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two long-domesticated birds from different orders.",
  },
  {
    id: "bk-015",
    proposedSlug: "chicken-vs-wild-turkey",
    animalASlug: "chicken",
    animalBSlug: "wild-turkey",
    canonicalPairKey: "chicken--wild-turkey",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "chicken-vs-wild-turkey",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both galliforms; one domesticated, one wild North American.",
  },
  {
    id: "bk-016",
    proposedSlug: "donkey-vs-horse",
    animalASlug: "donkey",
    animalBSlug: "horse",
    canonicalPairKey: "donkey--horse",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "donkey-vs-horse",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Close equids; ears, mane, tail, voice and terrain differ.",
  },
  {
    id: "bk-017",
    proposedSlug: "donkey-vs-zebra",
    animalASlug: "donkey",
    animalBSlug: "zebra",
    canonicalPairKey: "donkey--zebra",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "donkey-vs-zebra",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Same genus; one domesticated and one never was.",
  },
  {
    id: "bk-018",
    proposedSlug: "alpaca-vs-llama",
    animalASlug: "alpaca",
    animalBSlug: "llama",
    canonicalPairKey: "alpaca--llama",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "alpaca-vs-llama",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The classic camelid confusion; size, ears, face and purpose.",
  },
  {
    id: "bk-019",
    proposedSlug: "alpaca-vs-sheep",
    animalASlug: "alpaca",
    animalBSlug: "sheep",
    canonicalPairKey: "alpaca--sheep",
    proposedCategory: "pets-domestic",
    relationship: "similar-ecological-role",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "alpaca-vs-sheep",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both fibre animals from different families.",
  },
  {
    id: "bk-020",
    proposedSlug: "alpaca-vs-goat",
    animalASlug: "alpaca",
    animalBSlug: "goat",
    canonicalPairKey: "alpaca--goat",
    proposedCategory: "pets-domestic",
    relationship: "similar-ecological-role",
    searchIntent: "general-comparison",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "alpaca-vs-goat",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both smallholding animals; browsing vs grazing camelid.",
  },
  {
    id: "bk-021",
    proposedSlug: "camel-vs-dromedary",
    animalASlug: "camel",
    animalBSlug: "dromedary",
    canonicalPairKey: "camel--dromedary",
    proposedCategory: "pets-domestic",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "camel-vs-dromedary",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Nested names: the dromedary is one camel species.",
  },
  {
    id: "bk-022",
    proposedSlug: "dromedary-vs-llama",
    animalASlug: "dromedary",
    animalBSlug: "llama",
    canonicalPairKey: "dromedary--llama",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "dromedary-vs-llama",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Old World and New World camelids compared.",
  },
  {
    id: "bk-023",
    proposedSlug: "cow-vs-goat",
    animalASlug: "cow",
    animalBSlug: "goat",
    canonicalPairKey: "cow--goat",
    proposedCategory: "pets-domestic",
    relationship: "similar-ecological-role",
    searchIntent: "general-comparison",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "cow-vs-goat",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two ruminant livestock species; grazing vs browsing.",
  },
  {
    id: "bk-024",
    proposedSlug: "cow-vs-sheep",
    animalASlug: "cow",
    animalBSlug: "sheep",
    canonicalPairKey: "cow--sheep",
    proposedCategory: "pets-domestic",
    relationship: "similar-ecological-role",
    searchIntent: "general-comparison",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "cow-vs-sheep",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both grazing ruminants at very different scales.",
  },
  {
    id: "bk-025",
    proposedSlug: "cow-vs-horse",
    animalASlug: "cow",
    animalBSlug: "horse",
    canonicalPairKey: "cow--horse",
    proposedCategory: "pets-domestic",
    relationship: "contrasting-adaptations",
    searchIntent: "general-comparison",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "cow-vs-horse",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Ruminant vs hindgut fermenter; two digestive strategies.",
  },
  {
    id: "bk-026",
    proposedSlug: "pig-vs-goat",
    animalASlug: "pig",
    animalBSlug: "goat",
    canonicalPairKey: "goat--pig",
    proposedCategory: "pets-domestic",
    relationship: "contrasting-adaptations",
    searchIntent: "general-comparison",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "pig-vs-goat",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Omnivorous rooter vs browsing ruminant.",
  },
  {
    id: "bk-027",
    proposedSlug: "dog-vs-ferret",
    animalASlug: "dog",
    animalBSlug: "ferret",
    canonicalPairKey: "dog--ferret",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "dog-vs-ferret",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two domesticated carnivorans with different working histories.",
  },
  {
    id: "bk-028",
    proposedSlug: "cat-vs-ferret",
    animalASlug: "cat",
    animalBSlug: "ferret",
    canonicalPairKey: "cat--ferret",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "cat-vs-ferret",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two obligate carnivores kept indoors; very different biology.",
  },
  {
    id: "bk-029",
    proposedSlug: "cat-vs-rabbit",
    animalASlug: "cat",
    animalBSlug: "rabbit",
    canonicalPairKey: "cat--rabbit",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "cat-vs-rabbit",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Predator and prey species kept in the same homes.",
  },
  {
    id: "bk-030",
    proposedSlug: "dog-vs-rabbit",
    animalASlug: "dog",
    animalBSlug: "rabbit",
    canonicalPairKey: "dog--rabbit",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "dog-vs-rabbit",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Predator and prey species; welfare implications of housing.",
  },
  {
    id: "bk-031",
    proposedSlug: "goldfish-vs-betta-fish",
    animalASlug: "goldfish",
    animalBSlug: "betta-fish",
    canonicalPairKey: "betta-fish--goldfish",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "goldfish-vs-betta-fish",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Coldwater cyprinid vs tropical labyrinth fish.",
  },
  {
    id: "bk-032",
    proposedSlug: "goldfish-vs-guppy",
    animalASlug: "goldfish",
    animalBSlug: "guppy",
    canonicalPairKey: "goldfish--guppy",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "goldfish-vs-guppy",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Egg-scattering coldwater fish vs tropical livebearer.",
  },
  {
    id: "bk-033",
    proposedSlug: "koi-vs-carp",
    animalASlug: "koi",
    animalBSlug: "carp",
    canonicalPairKey: "carp--koi",
    proposedCategory: "pets-domestic",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "koi-vs-carp",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Koi are ornamental common carp: a nested-name case.",
  },
  {
    id: "bk-034",
    proposedSlug: "betta-fish-vs-angelfish",
    animalASlug: "betta-fish",
    animalBSlug: "angelfish",
    canonicalPairKey: "angelfish--betta-fish",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "betta-fish-vs-angelfish",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Labyrinth fish vs cichlid; both territorial in different ways.",
  },
  {
    id: "bk-035",
    proposedSlug: "guppy-vs-tetra",
    animalASlug: "guppy",
    animalBSlug: "tetra",
    canonicalPairKey: "guppy--tetra",
    proposedCategory: "pets-domestic",
    relationship: "pet-decision",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "guppy-vs-tetra",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Livebearer vs egg-scattering shoaler.",
  },
  {
    id: "bk-036",
    proposedSlug: "angelfish-vs-clownfish",
    animalASlug: "angelfish",
    animalBSlug: "clownfish",
    canonicalPairKey: "angelfish--clownfish",
    proposedCategory: "pets-domestic",
    relationship: "taxonomy-clarification",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "angelfish-vs-clownfish",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Freshwater cichlid vs marine damselfish sharing a look.",
  },
  {
    id: "bk-037",
    proposedSlug: "parrot-vs-african-grey-parrot",
    animalASlug: "parrot",
    animalBSlug: "african-grey-parrot",
    canonicalPairKey: "african-grey-parrot--parrot",
    proposedCategory: "pets-domestic",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "parrot-vs-african-grey-parrot",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Nested names: the African grey is one parrot species.",
  },
  {
    id: "bk-038",
    proposedSlug: "parrot-vs-macaw",
    animalASlug: "parrot",
    animalBSlug: "macaw",
    canonicalPairKey: "macaw--parrot",
    proposedCategory: "pets-domestic",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "parrot-vs-macaw",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Macaws are a group within the parrots.",
  },
  {
    id: "bk-039",
    proposedSlug: "macaw-vs-african-grey-parrot",
    animalASlug: "macaw",
    animalBSlug: "african-grey-parrot",
    canonicalPairKey: "african-grey-parrot--macaw",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "pet-decision",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "macaw-vs-african-grey-parrot",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two large parrots with different social and vocal profiles.",
  },
  {
    id: "bk-040",
    proposedSlug: "parrot-vs-galah",
    animalASlug: "parrot",
    animalBSlug: "galah",
    canonicalPairKey: "galah--parrot",
    proposedCategory: "pets-domestic",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "parrot-vs-galah",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Cockatoos sit inside the parrot order.",
  },
  {
    id: "bk-041",
    proposedSlug: "duck-vs-swan",
    animalASlug: "duck",
    animalBSlug: "swan",
    canonicalPairKey: "duck--swan",
    proposedCategory: "pets-domestic",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "duck-vs-swan",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both waterfowl; neck, size and pair bonds differ.",
  },
  {
    id: "bk-042",
    proposedSlug: "horse-vs-llama",
    animalASlug: "horse",
    animalBSlug: "llama",
    canonicalPairKey: "horse--llama",
    proposedCategory: "pets-domestic",
    relationship: "similar-ecological-role",
    searchIntent: "general-comparison",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "horse-vs-llama",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two pack animals from different continents and families.",
  },
  {
    id: "bk-043",
    proposedSlug: "brown-bear-vs-polar-bear",
    animalASlug: "brown-bear",
    animalBSlug: "polar-bear",
    canonicalPairKey: "brown-bear--polar-bear",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "brown-bear-vs-polar-bear",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Recently diverged sister species; diet and habitat diverged sharply.",
  },
  {
    id: "bk-044",
    proposedSlug: "brown-bear-vs-american-black-bear",
    animalASlug: "brown-bear",
    animalBSlug: "american-black-bear",
    canonicalPairKey: "american-black-bear--brown-bear",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "brown-bear-vs-american-black-bear",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The genuine North American bear confusion; hump, claws, profile.",
  },
  {
    id: "bk-045",
    proposedSlug: "brown-bear-vs-asian-black-bear",
    animalASlug: "brown-bear",
    animalBSlug: "asian-black-bear",
    canonicalPairKey: "asian-black-bear--brown-bear",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "brown-bear-vs-asian-black-bear",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two Ursus species separated by continent and build.",
  },
  {
    id: "bk-046",
    proposedSlug: "sea-lion-vs-seal",
    animalASlug: "sea-lion",
    animalBSlug: "seal",
    canonicalPairKey: "sea-lion--seal",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "sea-lion-vs-seal",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Eared vs earless seals; the flagship pinniped confusion.",
  },
  {
    id: "bk-047",
    proposedSlug: "sea-lion-vs-walrus",
    animalASlug: "sea-lion",
    animalBSlug: "walrus",
    canonicalPairKey: "sea-lion--walrus",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "sea-lion-vs-walrus",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two of the three pinniped families compared.",
  },
  {
    id: "bk-048",
    proposedSlug: "seal-vs-walrus",
    animalASlug: "seal",
    animalBSlug: "walrus",
    canonicalPairKey: "seal--walrus",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "seal-vs-walrus",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "True seals and the walrus: locomotion and tusks.",
  },
  {
    id: "bk-049",
    proposedSlug: "otter-vs-beaver",
    animalASlug: "otter",
    animalBSlug: "beaver",
    canonicalPairKey: "beaver--otter",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "otter-vs-beaver",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Semi-aquatic mammals confused by silhouette; carnivore vs rodent.",
  },
  {
    id: "bk-050",
    proposedSlug: "weasel-vs-stoat",
    animalASlug: "weasel",
    animalBSlug: "stoat",
    canonicalPairKey: "stoat--weasel",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "weasel-vs-stoat",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Classic mustelid confusion; the black tail tip is decisive.",
  },
  {
    id: "bk-051",
    proposedSlug: "ferret-vs-weasel",
    animalASlug: "ferret",
    animalBSlug: "weasel",
    canonicalPairKey: "ferret--weasel",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ferret-vs-weasel",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Domesticated polecat vs wild least weasel.",
  },
  {
    id: "bk-052",
    proposedSlug: "hyena-vs-aardwolf",
    animalASlug: "hyena",
    animalBSlug: "aardwolf",
    canonicalPairKey: "aardwolf--hyena",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "hyena-vs-aardwolf",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The aardwolf is a hyaenid that eats termites.",
  },
  {
    id: "bk-053",
    proposedSlug: "jaguar-vs-cougar",
    animalASlug: "jaguar",
    animalBSlug: "cougar",
    canonicalPairKey: "cougar--jaguar",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "jaguar-vs-cougar",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two large American cats; build, coat and skull differ.",
  },
  {
    id: "bk-054",
    proposedSlug: "cougar-vs-leopard",
    animalASlug: "cougar",
    animalBSlug: "leopard",
    canonicalPairKey: "cougar--leopard",
    proposedCategory: "habitat-ecology",
    relationship: "similar-ecological-role",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "cougar-vs-leopard",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Ecological counterparts on different continents.",
  },
  {
    id: "bk-055",
    proposedSlug: "snow-leopard-vs-leopard",
    animalASlug: "snow-leopard",
    animalBSlug: "leopard",
    canonicalPairKey: "leopard--snow-leopard",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "snow-leopard-vs-leopard",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two Panthera species; altitude and coat.",
  },
  {
    id: "bk-056",
    proposedSlug: "clouded-leopard-vs-leopard",
    animalASlug: "clouded-leopard",
    animalBSlug: "leopard",
    canonicalPairKey: "clouded-leopard--leopard",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "clouded-leopard-vs-leopard",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Different genus despite the shared name.",
  },
  {
    id: "bk-057",
    proposedSlug: "lynx-vs-caracal",
    animalASlug: "lynx",
    animalBSlug: "caracal",
    canonicalPairKey: "caracal--lynx",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "lynx-vs-caracal",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both tufted-eared cats from different genera.",
  },
  {
    id: "bk-058",
    proposedSlug: "caracal-vs-serval",
    animalASlug: "caracal",
    animalBSlug: "serval",
    canonicalPairKey: "caracal--serval",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "caracal-vs-serval",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two African cats confused by ear and leg proportions.",
  },
  {
    id: "bk-059",
    proposedSlug: "gorilla-vs-chimpanzee",
    animalASlug: "gorilla",
    animalBSlug: "chimpanzee",
    canonicalPairKey: "chimpanzee--gorilla",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "gorilla-vs-chimpanzee",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two African great apes; size, diet and society.",
  },
  {
    id: "bk-060",
    proposedSlug: "chimpanzee-vs-orangutan",
    animalASlug: "chimpanzee",
    animalBSlug: "orangutan",
    canonicalPairKey: "chimpanzee--orangutan",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "chimpanzee-vs-orangutan",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "African and Asian great apes compared.",
  },
  {
    id: "bk-061",
    proposedSlug: "gorilla-vs-orangutan",
    animalASlug: "gorilla",
    animalBSlug: "orangutan",
    canonicalPairKey: "gorilla--orangutan",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "gorilla-vs-orangutan",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Terrestrial vs arboreal great ape body plans.",
  },
  {
    id: "bk-062",
    proposedSlug: "baboon-vs-mandrill",
    animalASlug: "baboon",
    animalBSlug: "mandrill",
    canonicalPairKey: "baboon--mandrill",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "baboon-vs-mandrill",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Mandrills are not baboons despite the resemblance.",
  },
  {
    id: "bk-063",
    proposedSlug: "macaque-vs-baboon",
    animalASlug: "macaque",
    animalBSlug: "baboon",
    canonicalPairKey: "baboon--macaque",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "macaque-vs-baboon",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two Old World monkey groups compared.",
  },
  {
    id: "bk-064",
    proposedSlug: "kangaroo-vs-wallaby",
    animalASlug: "kangaroo",
    animalBSlug: "wallaby",
    canonicalPairKey: "kangaroo--wallaby",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "kangaroo-vs-wallaby",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "A size-based distinction, not a taxonomic one.",
  },
  {
    id: "bk-065",
    proposedSlug: "koala-vs-wombat",
    animalASlug: "koala",
    animalBSlug: "wombat",
    canonicalPairKey: "koala--wombat",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "koala-vs-wombat",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two Australian marsupials; arboreal vs burrowing.",
  },
  {
    id: "bk-066",
    proposedSlug: "armadillo-vs-pangolin",
    animalASlug: "armadillo",
    animalBSlug: "pangolin",
    canonicalPairKey: "armadillo--pangolin",
    proposedCategory: "look-alikes",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "armadillo-vs-pangolin",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Armoured convergence across unrelated orders.",
  },
  {
    id: "bk-067",
    proposedSlug: "giant-anteater-vs-aardvark",
    animalASlug: "giant-anteater",
    animalBSlug: "aardvark",
    canonicalPairKey: "aardvark--giant-anteater",
    proposedCategory: "habitat-ecology",
    relationship: "similar-ecological-role",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "giant-anteater-vs-aardvark",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Ant-eating convergence on different continents.",
  },
  {
    id: "bk-068",
    proposedSlug: "hedgehog-vs-porcupine",
    animalASlug: "hedgehog",
    animalBSlug: "porcupine",
    canonicalPairKey: "hedgehog--porcupine",
    proposedCategory: "look-alikes",
    relationship: "similar-appearance",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "hedgehog-vs-porcupine",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Spines evolved separately; insectivore vs rodent.",
  },
  {
    id: "bk-069",
    proposedSlug: "porcupine-vs-echidna",
    animalASlug: "porcupine",
    animalBSlug: "echidna",
    canonicalPairKey: "echidna--porcupine",
    proposedCategory: "look-alikes",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "porcupine-vs-echidna",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Rodent vs egg-laying monotreme.",
  },
  {
    id: "bk-070",
    proposedSlug: "mole-vs-shrew",
    animalASlug: "mole",
    animalBSlug: "shrew",
    canonicalPairKey: "mole--shrew",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "mole-vs-shrew",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both small insectivores; fossorial vs surface-active.",
  },
  {
    id: "bk-071",
    proposedSlug: "beaver-vs-capybara",
    animalASlug: "beaver",
    animalBSlug: "capybara",
    canonicalPairKey: "beaver--capybara",
    proposedCategory: "habitat-ecology",
    relationship: "similar-ecological-role",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "beaver-vs-capybara",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two large semi-aquatic rodents on different continents.",
  },
  {
    id: "bk-072",
    proposedSlug: "rhinoceros-vs-hippopotamus",
    animalASlug: "rhinoceros",
    animalBSlug: "hippopotamus",
    canonicalPairKey: "hippopotamus--rhinoceros",
    proposedCategory: "look-alikes",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "rhinoceros-vs-hippopotamus",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both bulky and grey but distantly related.",
  },
  {
    id: "bk-073",
    proposedSlug: "giraffe-vs-okapi",
    animalASlug: "giraffe",
    animalBSlug: "okapi",
    canonicalPairKey: "giraffe--okapi",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "giraffe-vs-okapi",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The okapi is the giraffe's only living relative.",
  },
  {
    id: "bk-074",
    proposedSlug: "camel-vs-llama",
    animalASlug: "camel",
    animalBSlug: "llama",
    canonicalPairKey: "camel--llama",
    proposedCategory: "mammals",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "camel-vs-llama",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Old World and New World camelids.",
  },
  {
    id: "bk-075",
    proposedSlug: "wildebeest-vs-african-buffalo",
    animalASlug: "wildebeest",
    animalBSlug: "african-buffalo",
    canonicalPairKey: "african-buffalo--wildebeest",
    proposedCategory: "habitat-ecology",
    relationship: "similar-ecological-role",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "wildebeest-vs-african-buffalo",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two large African bovids sharing savanna.",
  },
  {
    id: "bk-076",
    proposedSlug: "pronghorn-vs-deer",
    animalASlug: "pronghorn",
    animalBSlug: "deer",
    canonicalPairKey: "deer--pronghorn",
    proposedCategory: "mammals",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "pronghorn-vs-deer",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The pronghorn is not an antelope or a deer.",
  },
  {
    id: "bk-077",
    proposedSlug: "puffin-vs-penguin",
    animalASlug: "puffin",
    animalBSlug: "penguin",
    canonicalPairKey: "penguin--puffin",
    proposedCategory: "birds",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "puffin-vs-penguin",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Northern auk vs southern flightless seabird; convergence.",
  },
  {
    id: "bk-078",
    proposedSlug: "puffin-vs-pelican",
    animalASlug: "puffin",
    animalBSlug: "pelican",
    canonicalPairKey: "pelican--puffin",
    proposedCategory: "taxonomy",
    relationship: "taxonomy-clarification",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "puffin-vs-pelican",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two very different bill designs for catching fish.",
  },
  {
    id: "bk-079",
    proposedSlug: "penguin-vs-albatross",
    animalASlug: "penguin",
    animalBSlug: "albatross",
    canonicalPairKey: "albatross--penguin",
    proposedCategory: "behavior-adaptations",
    relationship: "contrasting-adaptations",
    searchIntent: "behavior",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "penguin-vs-albatross",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Flightless diver vs the ultimate soaring seabird.",
  },
  {
    id: "bk-080",
    proposedSlug: "barn-owl-vs-snowy-owl",
    animalASlug: "barn-owl",
    animalBSlug: "snowy-owl",
    canonicalPairKey: "barn-owl--snowy-owl",
    proposedCategory: "birds",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "barn-owl-vs-snowy-owl",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two owls from different families and climates.",
  },
  {
    id: "bk-081",
    proposedSlug: "flamingo-vs-stork",
    animalASlug: "flamingo",
    animalBSlug: "stork",
    canonicalPairKey: "flamingo--stork",
    proposedCategory: "birds",
    relationship: "similar-appearance",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "flamingo-vs-stork",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Long-legged waders that are not close relatives.",
  },
  {
    id: "bk-082",
    proposedSlug: "heron-vs-stork",
    animalASlug: "heron",
    animalBSlug: "stork",
    canonicalPairKey: "heron--stork",
    proposedCategory: "birds",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "heron-vs-stork",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Neck position in flight is decisive.",
  },
  {
    id: "bk-083",
    proposedSlug: "heron-vs-sandhill-crane",
    animalASlug: "heron",
    animalBSlug: "sandhill-crane",
    canonicalPairKey: "heron--sandhill-crane",
    proposedCategory: "birds",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "heron-vs-sandhill-crane",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Herons fold the neck in flight, cranes extend it.",
  },
  {
    id: "bk-084",
    proposedSlug: "ostrich-vs-emu",
    animalASlug: "ostrich",
    animalBSlug: "emu",
    canonicalPairKey: "emu--ostrich",
    proposedCategory: "birds",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ostrich-vs-emu",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two large ratites; toes and continent differ.",
  },
  {
    id: "bk-085",
    proposedSlug: "emu-vs-cassowary",
    animalASlug: "emu",
    animalBSlug: "cassowary",
    canonicalPairKey: "cassowary--emu",
    proposedCategory: "birds",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "emu-vs-cassowary",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two Australasian ratites; casque and temperament.",
  },
  {
    id: "bk-086",
    proposedSlug: "ostrich-vs-rhea",
    animalASlug: "ostrich",
    animalBSlug: "rhea",
    canonicalPairKey: "ostrich--rhea",
    proposedCategory: "birds",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ostrich-vs-rhea",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "African and South American ratites compared.",
  },
  {
    id: "bk-087",
    proposedSlug: "swan-vs-pelican",
    animalASlug: "swan",
    animalBSlug: "pelican",
    canonicalPairKey: "pelican--swan",
    proposedCategory: "birds",
    relationship: "similar-appearance",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "swan-vs-pelican",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Large white waterbirds with different feeding gear.",
  },
  {
    id: "bk-088",
    proposedSlug: "hummingbird-vs-sunbird",
    animalASlug: "hummingbird",
    animalBSlug: "sunbird",
    canonicalPairKey: "hummingbird--sunbird",
    proposedCategory: "birds",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "hummingbird-vs-sunbird",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Nectar-feeding convergence across hemispheres.",
  },
  {
    id: "bk-089",
    proposedSlug: "toucan-vs-hornbill",
    animalASlug: "toucan",
    animalBSlug: "hornbill",
    canonicalPairKey: "hornbill--toucan",
    proposedCategory: "birds",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "toucan-vs-hornbill",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Huge bills evolved separately in the Americas and Old World.",
  },
  {
    id: "bk-090",
    proposedSlug: "vulture-vs-california-condor",
    animalASlug: "vulture",
    animalBSlug: "california-condor",
    canonicalPairKey: "california-condor--vulture",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "vulture-vs-california-condor",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The condor is a New World vulture.",
  },
  {
    id: "bk-091",
    proposedSlug: "andean-condor-vs-california-condor",
    animalASlug: "andean-condor",
    animalBSlug: "california-condor",
    canonicalPairKey: "andean-condor--california-condor",
    proposedCategory: "birds",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "andean-condor-vs-california-condor",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two New World condors compared.",
  },
  {
    id: "bk-092",
    proposedSlug: "peacock-vs-chicken",
    animalASlug: "peacock",
    animalBSlug: "chicken",
    canonicalPairKey: "chicken--peacock",
    proposedCategory: "birds",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "peacock-vs-chicken",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both galliforms; ornament and domestication differ.",
  },
  {
    id: "bk-093",
    proposedSlug: "tortoise-vs-box-turtle",
    animalASlug: "tortoise",
    animalBSlug: "box-turtle",
    canonicalPairKey: "box-turtle--tortoise",
    proposedCategory: "reptiles-amphibians",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "tortoise-vs-box-turtle",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Terrestrial chelonians confused on land; hinged plastron is the cue.",
  },
  {
    id: "bk-094",
    proposedSlug: "viper-vs-european-viper",
    animalASlug: "viper",
    animalBSlug: "european-viper",
    canonicalPairKey: "european-viper--viper",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "viper-vs-european-viper",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Nested naming within the viper family.",
  },
  {
    id: "bk-095",
    proposedSlug: "komodo-dragon-vs-monitor-lizard",
    animalASlug: "komodo-dragon",
    animalBSlug: "monitor-lizard",
    canonicalPairKey: "komodo-dragon--monitor-lizard",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "komodo-dragon-vs-monitor-lizard",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The Komodo dragon is the largest monitor.",
  },
  {
    id: "bk-096",
    proposedSlug: "saltwater-crocodile-vs-nile-crocodile",
    animalASlug: "saltwater-crocodile",
    animalBSlug: "nile-crocodile",
    canonicalPairKey: "nile-crocodile--saltwater-crocodile",
    proposedCategory: "reptiles-amphibians",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "saltwater-crocodile-vs-nile-crocodile",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two large crocodiles on different continents.",
  },
  {
    id: "bk-097",
    proposedSlug: "rattlesnake-vs-viper",
    animalASlug: "rattlesnake",
    animalBSlug: "viper",
    canonicalPairKey: "rattlesnake--viper",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "rattlesnake-vs-viper",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Rattlesnakes are pit vipers within Viperidae.",
  },
  {
    id: "bk-098",
    proposedSlug: "garter-snake-vs-grass-snake",
    animalASlug: "garter-snake",
    animalBSlug: "grass-snake",
    canonicalPairKey: "garter-snake--grass-snake",
    proposedCategory: "reptiles-amphibians",
    relationship: "similar-appearance",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "garter-snake-vs-grass-snake",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "New and Old World colubrids that look alike.",
  },
  {
    id: "bk-099",
    proposedSlug: "gecko-vs-tokay-gecko",
    animalASlug: "gecko",
    animalBSlug: "tokay-gecko",
    canonicalPairKey: "gecko--tokay-gecko",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "gecko-vs-tokay-gecko",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "A species within the gecko group.",
  },
  {
    id: "bk-100",
    proposedSlug: "tuatara-vs-iguana",
    animalASlug: "tuatara",
    animalBSlug: "iguana",
    canonicalPairKey: "iguana--tuatara",
    proposedCategory: "taxonomy",
    relationship: "taxonomy-clarification",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "tuatara-vs-iguana",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The tuatara is not a lizard at all.",
  },
  {
    id: "bk-101",
    proposedSlug: "caecilian-vs-snake",
    animalASlug: "caecilian",
    animalBSlug: "snake",
    canonicalPairKey: "caecilian--snake",
    proposedCategory: "reptiles-amphibians",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "caecilian-vs-snake",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "A limbless amphibian mistaken for a snake.",
  },
  {
    id: "bk-102",
    proposedSlug: "olm-vs-axolotl",
    animalASlug: "olm",
    animalBSlug: "axolotl",
    canonicalPairKey: "axolotl--olm",
    proposedCategory: "habitat-ecology",
    relationship: "similar-ecological-role",
    searchIntent: "behavior",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "olm-vs-axolotl",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two neotenic cave and lake salamanders.",
  },
  {
    id: "bk-103",
    proposedSlug: "hellbender-vs-asian-giant-salamander",
    animalASlug: "hellbender",
    animalBSlug: "asian-giant-salamander",
    canonicalPairKey: "asian-giant-salamander--hellbender",
    proposedCategory: "reptiles-amphibians",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "hellbender-vs-asian-giant-salamander",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The two giant salamander lineages compared.",
  },
  {
    id: "bk-104",
    proposedSlug: "glass-frog-vs-red-eyed-tree-frog",
    animalASlug: "glass-frog",
    animalBSlug: "red-eyed-tree-frog",
    canonicalPairKey: "glass-frog--red-eyed-tree-frog",
    proposedCategory: "reptiles-amphibians",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "glass-frog-vs-red-eyed-tree-frog",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two Neotropical tree frogs with different concealment strategies.",
  },
  {
    id: "bk-105",
    proposedSlug: "poison-dart-frog-vs-mantella",
    animalASlug: "poison-dart-frog",
    animalBSlug: "mantella",
    canonicalPairKey: "mantella--poison-dart-frog",
    proposedCategory: "reptiles-amphibians",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "poison-dart-frog-vs-mantella",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Toxic bright frogs convergent across continents.",
  },
  {
    id: "bk-106",
    proposedSlug: "dolphin-vs-porpoise",
    animalASlug: "dolphin",
    animalBSlug: "porpoise",
    canonicalPairKey: "dolphin--porpoise",
    proposedCategory: "fish-marine",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "dolphin-vs-porpoise",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The flagship cetacean confusion; beak, teeth and fin.",
  },
  {
    id: "bk-107",
    proposedSlug: "porpoise-vs-orca",
    animalASlug: "porpoise",
    animalBSlug: "orca",
    canonicalPairKey: "orca--porpoise",
    proposedCategory: "fish-marine",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "porpoise-vs-orca",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both toothed whales at opposite size extremes.",
  },
  {
    id: "bk-108",
    proposedSlug: "great-white-shark-vs-hammerhead-shark",
    animalASlug: "great-white-shark",
    animalBSlug: "hammerhead-shark",
    canonicalPairKey: "great-white-shark--hammerhead-shark",
    proposedCategory: "fish-marine",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "great-white-shark-vs-hammerhead-shark",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two large sharks with very different head designs.",
  },
  {
    id: "bk-109",
    proposedSlug: "shark-vs-great-white-shark",
    animalASlug: "shark",
    animalBSlug: "great-white-shark",
    canonicalPairKey: "great-white-shark--shark",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "shark-vs-great-white-shark",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "One species inside a very large group.",
  },
  {
    id: "bk-110",
    proposedSlug: "ray-vs-reef-manta-ray",
    animalASlug: "ray",
    animalBSlug: "reef-manta-ray",
    canonicalPairKey: "ray--reef-manta-ray",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ray-vs-reef-manta-ray",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Manta rays within the wider ray group.",
  },
  {
    id: "bk-111",
    proposedSlug: "seahorse-vs-leafy-seadragon",
    animalASlug: "seahorse",
    animalBSlug: "leafy-seadragon",
    canonicalPairKey: "leafy-seadragon--seahorse",
    proposedCategory: "fish-marine",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "seahorse-vs-leafy-seadragon",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two syngnathids; camouflage and brooding differ.",
  },
  {
    id: "bk-112",
    proposedSlug: "eel-vs-moray-eel",
    animalASlug: "eel",
    animalBSlug: "moray-eel",
    canonicalPairKey: "eel--moray-eel",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "eel-vs-moray-eel",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Morays inside the true eel order.",
  },
  {
    id: "bk-113",
    proposedSlug: "octopus-vs-nautilus",
    animalASlug: "octopus",
    animalBSlug: "nautilus",
    canonicalPairKey: "nautilus--octopus",
    proposedCategory: "fish-marine",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "octopus-vs-nautilus",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Shelled and shell-less cephalopods compared.",
  },
  {
    id: "bk-114",
    proposedSlug: "squid-vs-giant-squid",
    animalASlug: "squid",
    animalBSlug: "giant-squid",
    canonicalPairKey: "giant-squid--squid",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "squid-vs-giant-squid",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "A single deep-sea species within the squid group.",
  },
  {
    id: "bk-115",
    proposedSlug: "tuna-vs-mackerel",
    animalASlug: "tuna",
    animalBSlug: "mackerel",
    canonicalPairKey: "mackerel--tuna",
    proposedCategory: "fish-marine",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "tuna-vs-mackerel",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two scombrids; size and endothermy differ.",
  },
  {
    id: "bk-116",
    proposedSlug: "salmon-vs-atlantic-salmon",
    animalASlug: "salmon",
    animalBSlug: "atlantic-salmon",
    canonicalPairKey: "atlantic-salmon--salmon",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "salmon-vs-atlantic-salmon",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "One species within a wider common name.",
  },
  {
    id: "bk-117",
    proposedSlug: "anglerfish-vs-frogfish",
    animalASlug: "anglerfish",
    animalBSlug: "frogfish",
    canonicalPairKey: "anglerfish--frogfish",
    proposedCategory: "fish-marine",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "anglerfish-vs-frogfish",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two lure-using ambush fish; deep sea vs reef.",
  },
  {
    id: "bk-118",
    proposedSlug: "pufferfish-vs-boxfish",
    animalASlug: "pufferfish",
    animalBSlug: "boxfish",
    canonicalPairKey: "boxfish--pufferfish",
    proposedCategory: "fish-marine",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "pufferfish-vs-boxfish",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two tetraodontiform defence strategies.",
  },
  {
    id: "bk-119",
    proposedSlug: "coral-vs-sea-anemone",
    animalASlug: "coral",
    animalBSlug: "sea-anemone",
    canonicalPairKey: "coral--sea-anemone",
    proposedCategory: "fish-marine",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "coral-vs-sea-anemone",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Both anthozoan cnidarians; skeleton is the difference.",
  },
  {
    id: "bk-120",
    proposedSlug: "starfish-vs-crown-of-thorns-starfish",
    animalASlug: "starfish",
    animalBSlug: "crown-of-thorns-starfish",
    canonicalPairKey: "crown-of-thorns-starfish--starfish",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "starfish-vs-crown-of-thorns-starfish",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "A reef-damaging species within the sea stars.",
  },
  {
    id: "bk-121",
    proposedSlug: "jellyfish-vs-comb-jelly",
    animalASlug: "jellyfish",
    animalBSlug: "comb-jelly",
    canonicalPairKey: "comb-jelly--jellyfish",
    proposedCategory: "fish-marine",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "jellyfish-vs-comb-jelly",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Different phyla despite the shared gelatinous look.",
  },
  {
    id: "bk-122",
    proposedSlug: "krill-vs-shrimp",
    animalASlug: "krill",
    animalBSlug: "shrimp",
    canonicalPairKey: "krill--shrimp",
    proposedCategory: "fish-marine",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "krill-vs-shrimp",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two crustacean groups confused by name and shape.",
  },
  {
    id: "bk-123",
    proposedSlug: "bee-vs-bumblebee",
    animalASlug: "bee",
    animalBSlug: "bumblebee",
    canonicalPairKey: "bee--bumblebee",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "bee-vs-bumblebee",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Bumblebees are one group of bees.",
  },
  {
    id: "bk-124",
    proposedSlug: "wasp-vs-asian-giant-hornet",
    animalASlug: "wasp",
    animalBSlug: "asian-giant-hornet",
    canonicalPairKey: "asian-giant-hornet--wasp",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "wasp-vs-asian-giant-hornet",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Hornets are large social wasps.",
  },
  {
    id: "bk-125",
    proposedSlug: "ant-vs-leafcutter-ant",
    animalASlug: "ant",
    animalBSlug: "leafcutter-ant",
    canonicalPairKey: "ant--leafcutter-ant",
    proposedCategory: "taxonomy",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ant-vs-leafcutter-ant",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Fungus-farming ants within the wider family.",
  },
  {
    id: "bk-126",
    proposedSlug: "grasshopper-vs-cricket",
    animalASlug: "grasshopper",
    animalBSlug: "cricket",
    canonicalPairKey: "cricket--grasshopper",
    proposedCategory: "insects-invertebrates",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "grasshopper-vs-cricket",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Antenna length and sound production differ.",
  },
  {
    id: "bk-127",
    proposedSlug: "cicada-vs-grasshopper",
    animalASlug: "cicada",
    animalBSlug: "grasshopper",
    canonicalPairKey: "cicada--grasshopper",
    proposedCategory: "insects-invertebrates",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "cicada-vs-grasshopper",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "True bug vs orthopteran; different sound mechanisms.",
  },
  {
    id: "bk-128",
    proposedSlug: "praying-mantis-vs-mantis-shrimp",
    animalASlug: "praying-mantis",
    animalBSlug: "mantis-shrimp",
    canonicalPairKey: "mantis-shrimp--praying-mantis",
    proposedCategory: "taxonomy",
    relationship: "taxonomy-clarification",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "praying-mantis-vs-mantis-shrimp",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "A shared name across an insect and a crustacean.",
  },
  {
    id: "bk-129",
    proposedSlug: "ladybug-vs-stag-beetle",
    animalASlug: "ladybug",
    animalBSlug: "stag-beetle",
    canonicalPairKey: "ladybug--stag-beetle",
    proposedCategory: "insects-invertebrates",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "ladybug-vs-stag-beetle",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Two beetles at opposite ends of the order.",
  },
  {
    id: "bk-130",
    proposedSlug: "moth-vs-hawk-moth",
    animalASlug: "moth",
    animalBSlug: "hawk-moth",
    canonicalPairKey: "hawk-moth--moth",
    proposedCategory: "insects-invertebrates",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "moth-vs-hawk-moth",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Hawk-moths within the wider moth grouping.",
  },
  {
    id: "bk-131",
    proposedSlug: "earthworm-vs-velvet-worm",
    animalASlug: "earthworm",
    animalBSlug: "velvet-worm",
    canonicalPairKey: "earthworm--velvet-worm",
    proposedCategory: "insects-invertebrates",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "earthworm-vs-velvet-worm",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Segmented annelid vs onychophoran predator.",
  },
  {
    id: "bk-132",
    proposedSlug: "tick-vs-mite",
    animalASlug: "tick",
    animalBSlug: "mite",
    canonicalPairKey: "mite--tick",
    proposedCategory: "insects-invertebrates",
    relationship: "close-relatives",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "tick-vs-mite",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Ticks are large parasitic mites.",
  },
  {
    id: "bk-133",
    proposedSlug: "barnacle-vs-limpet",
    animalASlug: "barnacle",
    animalBSlug: "limpet",
    canonicalPairKey: "barnacle--limpet",
    proposedCategory: "insects-invertebrates",
    relationship: "similar-appearance",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "barnacle-vs-limpet",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Crustacean vs gastropod under similar cones.",
  },
  {
    id: "bk-134",
    proposedSlug: "nudibranch-vs-sea-slug",
    animalASlug: "nudibranch",
    animalBSlug: "sea-slug",
    canonicalPairKey: "nudibranch--sea-slug",
    proposedCategory: "insects-invertebrates",
    relationship: "species-vs-group",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "nudibranch-vs-sea-slug",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Nudibranchs within the wider sea slug grouping.",
  },
  {
    id: "bk-135",
    proposedSlug: "horseshoe-crab-vs-crab",
    animalASlug: "horseshoe-crab",
    animalBSlug: "crab",
    canonicalPairKey: "crab--horseshoe-crab",
    proposedCategory: "insects-invertebrates",
    relationship: "taxonomy-clarification",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "horseshoe-crab-vs-crab",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The horseshoe crab is not a crab.",
  },
  {
    id: "bk-136",
    proposedSlug: "hermit-crab-vs-crab",
    animalASlug: "hermit-crab",
    animalBSlug: "crab",
    canonicalPairKey: "crab--hermit-crab",
    proposedCategory: "insects-invertebrates",
    relationship: "taxonomy-clarification",
    searchIntent: "taxonomy",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "hermit-crab-vs-crab",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "Hermit crabs are decapods but not true crabs.",
  },
  {
    id: "bk-137",
    proposedSlug: "coconut-crab-vs-hermit-crab",
    animalASlug: "coconut-crab",
    animalBSlug: "hermit-crab",
    canonicalPairKey: "coconut-crab--hermit-crab",
    proposedCategory: "insects-invertebrates",
    relationship: "close-relatives",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "low",
    status: "published",
    publishedSlug: "coconut-crab-vs-hermit-crab",
    reviewedAt: "2026-08-04",
    publishedAt: "2026-08-04",
    note: "The largest land arthropod is a hermit crab relative.",
  },
  {
    id: "bk-138",
    proposedSlug: "parrot-vs-canary",
    animalASlug: "parrot",
    animalBSlug: "canary",
    canonicalPairKey: "canary--parrot",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No canary profile exists. Companion-bird comparisons use parrot, African grey parrot, macaw and galah instead.",
    reviewedAt: "2026-08-04",
    note: "No canary profile exists. Companion-bird comparisons use parrot, African grey parrot, macaw and galah instead.",
  },
  {
    id: "bk-139",
    proposedSlug: "cow-vs-yak",
    animalASlug: "cow",
    animalBSlug: "yak",
    canonicalPairKey: "cow--yak",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No yak profile exists.",
    reviewedAt: "2026-08-04",
    note: "No yak profile exists.",
  },
  {
    id: "bk-140",
    proposedSlug: "snake-vs-lizard",
    animalASlug: "snake",
    animalBSlug: "lizard",
    canonicalPairKey: "lizard--snake",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No generic lizard profile exists — only specific lizards. Snake vs legless lizard is published instead, which is the sharper question anyway.",
    reviewedAt: "2026-08-04",
    note: "No generic lizard profile exists — only specific lizards. Snake vs legless lizard is published instead, which is the sharper question anyway.",
  },
  {
    id: "bk-141",
    proposedSlug: "lizard-vs-gecko",
    animalASlug: "lizard",
    animalBSlug: "gecko",
    canonicalPairKey: "gecko--lizard",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No generic lizard profile exists. Gecko vs skink is published instead.",
    reviewedAt: "2026-08-04",
    note: "No generic lizard profile exists. Gecko vs skink is published instead.",
  },
  {
    id: "bk-142",
    proposedSlug: "monkey-vs-ape",
    animalASlug: "monkey",
    animalBSlug: "ape",
    canonicalPairKey: "ape--monkey",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "Neither a generic monkey nor a generic ape profile exists. The distinction is covered by pairing specific profiled primates.",
    reviewedAt: "2026-08-04",
    note: "Neither a generic monkey nor a generic ape profile exists. The distinction is covered by pairing specific profiled primates.",
  },
  {
    id: "bk-143",
    proposedSlug: "lion-vs-tiger",
    animalASlug: "lion",
    animalBSlug: "tiger",
    canonicalPairKey: "lion--tiger",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "legacy-compare-collision",
    reviewedAt: "2026-08-04",
    note: "Published at /compare/lion-vs-tiger.",
  },
  {
    id: "bk-144",
    proposedSlug: "leopard-vs-jaguar",
    animalASlug: "leopard",
    animalBSlug: "jaguar",
    canonicalPairKey: "jaguar--leopard",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "legacy-compare-collision",
    reviewedAt: "2026-08-04",
    note: "Published at /compare/leopard-vs-jaguar.",
  },
  {
    id: "bk-145",
    proposedSlug: "cheetah-vs-leopard",
    animalASlug: "cheetah",
    animalBSlug: "leopard",
    canonicalPairKey: "cheetah--leopard",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "legacy-compare-collision",
    reviewedAt: "2026-08-04",
    note: "Published at /compare/cheetah-vs-leopard.",
  },
  {
    id: "bk-146",
    proposedSlug: "wolf-vs-dog",
    animalASlug: "wolf",
    animalBSlug: "dog",
    canonicalPairKey: "dog--wolf",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "legacy-compare-collision",
    reviewedAt: "2026-08-04",
    note: "Published at /compare/wolf-vs-dog.",
  },
  {
    id: "bk-147",
    proposedSlug: "alligator-vs-crocodile",
    animalASlug: "alligator",
    animalBSlug: "crocodile",
    canonicalPairKey: "alligator--crocodile",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "legacy-compare-collision",
    reviewedAt: "2026-08-04",
    note: "Published at /compare/alligator-vs-crocodile.",
  },
  {
    id: "bk-148",
    proposedSlug: "falcon-vs-eagle",
    animalASlug: "falcon",
    animalBSlug: "eagle",
    canonicalPairKey: "eagle--falcon",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "legacy-compare-collision",
    reviewedAt: "2026-08-04",
    note: "Published at /compare/falcon-vs-eagle.",
  },
  {
    id: "bk-149",
    proposedSlug: "rabbit-vs-guinea-pig",
    animalASlug: "rabbit",
    animalBSlug: "guinea-pig",
    canonicalPairKey: "guinea-pig--rabbit",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "legacy-compare-collision",
    reviewedAt: "2026-08-04",
    note: "Published at /compare/rabbit-vs-guinea-pig.",
  },
  {
    id: "bk-150",
    proposedSlug: "crocodile-vs-hippopotamus",
    animalASlug: "crocodile",
    animalBSlug: "hippopotamus",
    canonicalPairKey: "crocodile--hippopotamus",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "conflict-framing",
    reviewedAt: "2026-08-04",
    note: "Search intent for this pair is overwhelmingly confrontational. A shared-habitat page is possible in principle but the framing risk outweighs the value.",
  },
  {
    id: "bk-151",
    proposedSlug: "lion-vs-hyena",
    animalASlug: "lion",
    animalBSlug: "hyena",
    canonicalPairKey: "hyena--lion",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "conflict-framing",
    reviewedAt: "2026-08-04",
    note: "Dominated by confrontation intent. The genuinely useful content — kleptoparasitism and carnivore guild competition — is better served by the hyena profile than by a versus page.",
  },
  {
    id: "bk-152",
    proposedSlug: "wolf-vs-hyena",
    animalASlug: "wolf",
    animalBSlug: "hyena",
    canonicalPairKey: "hyena--wolf",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "conflict-framing",
    reviewedAt: "2026-08-04",
    note: "Convergent-carnivore comparison has merit, but the query is almost entirely a fight question. Deferred rather than built with that intent attached.",
  },
  {
    id: "bk-153",
    proposedSlug: "gorilla-vs-bear",
    animalASlug: "gorilla",
    animalBSlug: "bear",
    canonicalPairKey: "bear--gorilla",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "conflict-framing",
    reviewedAt: "2026-08-04",
    note: "Pure confrontation query with no identification, taxonomic or ecological value.",
  },
  {
    id: "bk-154",
    proposedSlug: "elephant-vs-whale",
    animalASlug: "elephant",
    animalBSlug: "whale",
    canonicalPairKey: "elephant--whale",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "not-meaningful",
    reviewedAt: "2026-08-04",
    note: "Both are large, and that is the entire premise. No confusion, no shared habitat, no meaningful ecological contrast.",
  },
  {
    id: "bk-155",
    proposedSlug: "giraffe-vs-ostrich",
    animalASlug: "giraffe",
    animalBSlug: "ostrich",
    canonicalPairKey: "giraffe--ostrich",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "both-exist",
    qualityRisk: "high",
    status: "rejected",
    rejectionReason: "not-meaningful",
    reviewedAt: "2026-08-04",
    note: "Both tall; nothing else connects them. Would produce generic content.",
  },
  {
    id: "bk-156",
    proposedSlug: "crow-vs-rook",
    animalASlug: "crow",
    animalBSlug: "rook",
    canonicalPairKey: "crow--rook",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "unknown",
    qualityRisk: "medium",
    status: "candidate",
    reviewedAt: "2026-08-04",
    note: "No rook profile yet; revisit with corvid expansion.",
  },
  {
    id: "bk-157",
    proposedSlug: "badger-vs-european-badger",
    animalASlug: "badger",
    animalBSlug: "european-badger",
    canonicalPairKey: "badger--european-badger",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "unknown",
    qualityRisk: "medium",
    status: "candidate",
    reviewedAt: "2026-08-04",
    note: "Nested/regional naming case; needs careful framing.",
  },
  {
    id: "bk-158",
    proposedSlug: "dolphin-vs-pilot-whale",
    animalASlug: "dolphin",
    animalBSlug: "pilot-whale",
    canonicalPairKey: "dolphin--pilot-whale",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "sourced",
    profileReadiness: "unknown",
    qualityRisk: "medium",
    status: "candidate",
    reviewedAt: "2026-08-04",
    note: "Nested-name cetacean case; both profiled.",
  },
  {
    id: "bk-159",
    proposedSlug: "damselfly-vs-dragonfly",
    animalASlug: "damselfly",
    animalBSlug: "dragonfly",
    canonicalPairKey: "damselfly--dragonfly",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No damselfly profile exists; dragonfly vs damselfly is a strong identification pair and should return once damselfly is profiled.",
    reviewedAt: "2026-08-04",
    note: "No damselfly profile exists; dragonfly vs damselfly is a strong identification pair and should return once damselfly is profiled.",
  },
  {
    id: "bk-160",
    proposedSlug: "rat-vs-mouse",
    animalASlug: "rat",
    animalBSlug: "mouse",
    canonicalPairKey: "mouse--rat",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No rat profile exists. Now that mouse is profiled this becomes a high-value pair the moment rat is added.",
    reviewedAt: "2026-08-04",
    note: "No rat profile exists. Now that mouse is profiled this becomes a high-value pair the moment rat is added.",
  },
  {
    id: "bk-161",
    proposedSlug: "osprey-vs-eagle",
    animalASlug: "osprey",
    animalBSlug: "eagle",
    canonicalPairKey: "eagle--osprey",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No osprey profile exists.",
    reviewedAt: "2026-08-04",
    note: "No osprey profile exists.",
  },
  {
    id: "bk-162",
    proposedSlug: "sea-lion-vs-fur-seal",
    animalASlug: "sea-lion",
    animalBSlug: "fur-seal",
    canonicalPairKey: "fur-seal--sea-lion",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No fur seal profile exists; would complete the otariid set.",
    reviewedAt: "2026-08-04",
    note: "No fur seal profile exists; would complete the otariid set.",
  },
  {
    id: "bk-163",
    proposedSlug: "alpaca-vs-vicuna",
    animalASlug: "alpaca",
    animalBSlug: "vicuna",
    canonicalPairKey: "alpaca--vicuna",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "both-exist",
    qualityRisk: "medium",
    status: "candidate",
    reviewedAt: "2026-08-04",
    note: "Wild ancestor against domesticated descendant; both now profiled.",
  },
  {
    id: "bk-164",
    proposedSlug: "donkey-vs-mule",
    animalASlug: "donkey",
    animalBSlug: "mule",
    canonicalPairKey: "donkey--mule",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "No mule profile exists; the sterile-hybrid explanation needs one.",
    reviewedAt: "2026-08-04",
    note: "No mule profile exists; the sterile-hybrid explanation needs one.",
  },
  {
    id: "bk-165",
    proposedSlug: "chicken-vs-quail",
    animalASlug: "chicken",
    animalBSlug: "quail",
    canonicalPairKey: "chicken--quail",
    proposedCategory: "look-alikes",
    relationship: "commonly-confused",
    searchIntent: "identification",
    sourceReadiness: "unknown",
    profileReadiness: "missing-one",
    qualityRisk: "medium",
    status: "blocked-missing-profile",
    blockerReason: "Only button-quail is profiled; a generic quail page would be needed.",
    reviewedAt: "2026-08-04",
    note: "Only button-quail is profiled; a generic quail page would be needed.",
  },
];

export const BACKLOG_COUNT = COMPARISON_BACKLOG.length;

export function backlogByStatus(status: BacklogStatus): BacklogCandidate[] {
  return COMPARISON_BACKLOG.filter((c) => c.status === status);
}

/** Every pair key in the backlog, published or not. */
export function backlogPairKeys(): Set<string> {
  return new Set(COMPARISON_BACKLOG.map((c) => c.canonicalPairKey));
}

/** Pair keys that must NOT be publicly routable. */
export function unpublishedPairKeys(): Set<string> {
  return new Set(
    COMPARISON_BACKLOG.filter((c) => c.status !== "published").map((c) => c.canonicalPairKey),
  );
}

/** Precomputed lookup so promotion checks never rescan the array. */
const BY_PAIR_KEY = new Map(COMPARISON_BACKLOG.map((c) => [c.canonicalPairKey, c]));

export function backlogByPairKey(pairKey: string): BacklogCandidate | undefined {
  return BY_PAIR_KEY.get(pairKey);
}

export function statusDistribution(): Record<string, number> {
  const out: Record<string, number> = {};
  for (const c of COMPARISON_BACKLOG) out[c.status] = (out[c.status] ?? 0) + 1;
  return out;
}
