/**
 * Breed pairs where the AKC lists EACH breed as related to the other.
 *
 * GENERATED from the related_breeds field on every AKC breed page, kept only
 * where the relationship is MUTUAL and both breeds are published in FaunaHub's
 * registry, then deduplicated with each pair alphabetically ordered so a pair
 * has exactly one key.
 *
 * Mutuality is the quality bar. The raw field yields 1,058 directed names
 * across the 219 published breeds, 908 of which resolve to a breed FaunaHub
 * publishes, giving 634 undirected pairs; requiring both pages to name each
 * other cuts that to 274 and removes the long tail where one breed's page
 * mentions a much better-known relative that does not reciprocate. A page
 * asserting two breeds are worth comparing should rest on both registry
 * entries agreeing, not one.
 *
 * THE EARLIER FIGURES IN THIS DOCSTRING WERE WRONG (770 directed, 569
 * undirected, 201 mutual), and so was the list beneath them. The extractor read
 * a "breed_data" key at the TOP LEVEL of the AKC page's data-js-props blob. The
 * field actually lives at settings.breed_data.basics.<key>, and each page
 * carries three such blobs of which only the last holds breed data. The
 * extractor therefore recovered a partial set per breed instead of failing
 * outright, so nothing reported an error and 73 mutual pairs were simply
 * absent. Sixteen breeds — the Beagle and the Bulldog among them — had NO
 * comparison page at all while naming 2-5 partners that named them back.
 *
 * This is why the comparison corpus is SOURCED rather than inferred. Deriving
 * which breeds a reader might compare from shared attributes would have
 * FaunaHub inventing the premise of every comparison page as well as answering
 * it. Here the registry supplies the question.
 *
 * Re-derived from all 219 AKC breed pages on 2026-09-13.
 */
export const AKC_RELATED_PAIRS: readonly (readonly [string, string])[] = [
  ["affenpinscher", "brussels-griffon"],
  ["afghan-hound", "saluki"],
  ["afghan-hound", "scottish-deerhound"],
  ["airedale-terrier", "irish-terrier"],
  ["airedale-terrier", "kerry-blue-terrier"],
  ["airedale-terrier", "lakeland-terrier"],
  ["airedale-terrier", "welsh-terrier"],
  ["akita", "shiba-inu"],
  ["alaskan-malamute", "chinook"],
  ["alaskan-malamute", "siberian-husky"],
  ["alaskan-malamute", "yakutian-laika"],
  ["american-english-coonhound", "american-foxhound"],
  ["american-english-coonhound", "bluetick-coonhound"],
  ["american-english-coonhound", "redbone-coonhound"],
  ["american-eskimo-dog", "german-spitz"],
  ["american-foxhound", "beagle"],
  ["american-foxhound", "english-foxhound"],
  ["american-foxhound", "harrier"],
  ["american-hairless-terrier", "chinese-crested"],
  ["american-hairless-terrier", "peruvian-inca-orchid"],
  ["american-hairless-terrier", "rat-terrier"],
  ["american-hairless-terrier", "xoloitzcuintli"],
  ["american-staffordshire-terrier", "boxer"],
  ["american-staffordshire-terrier", "bull-terrier"],
  ["american-staffordshire-terrier", "bulldog"],
  ["american-staffordshire-terrier", "miniature-bull-terrier"],
  ["american-staffordshire-terrier", "staffordshire-bull-terrier"],
  ["american-water-spaniel", "irish-water-spaniel"],
  ["american-water-spaniel", "portuguese-water-dog"],
  ["american-water-spaniel", "spanish-water-dog"],
  ["australian-shepherd", "border-collie"],
  ["australian-shepherd", "miniature-american-shepherd"],
  ["australian-terrier", "norwich-terrier"],
  ["australian-terrier", "silky-terrier"],
  ["australian-terrier", "yorkshire-terrier"],
  ["azawakh", "borzoi"],
  ["azawakh", "greyhound"],
  ["azawakh", "saluki"],
  ["azawakh", "sloughi"],
  ["barbet", "irish-water-spaniel"],
  ["barbet", "portuguese-water-dog"],
  ["barbet", "spanish-water-dog"],
  ["basenji", "ibizan-hound"],
  ["basset-fauve-de-bretagne", "basset-hound"],
  ["basset-hound", "dachshund"],
  ["beagle", "english-foxhound"],
  ["beagle", "harrier"],
  ["bearded-collie", "collie"],
  ["beauceron", "briard"],
  ["belgian-laekenois", "belgian-malinois"],
  ["belgian-laekenois", "belgian-sheepdog"],
  ["belgian-laekenois", "belgian-tervuren"],
  ["belgian-laekenois", "dutch-shepherd"],
  ["belgian-malinois", "belgian-sheepdog"],
  ["belgian-malinois", "belgian-tervuren"],
  ["belgian-malinois", "dutch-shepherd"],
  ["belgian-sheepdog", "belgian-tervuren"],
  ["belgian-sheepdog", "dutch-shepherd"],
  ["belgian-tervuren", "dutch-shepherd"],
  ["bergamasco-sheepdog", "komondor"],
  ["bergamasco-sheepdog", "old-english-sheepdog"],
  ["berger-picard", "briard"],
  ["berger-picard", "pyrenean-shepherd"],
  ["bernese-mountain-dog", "entlebucher-mountain-dog"],
  ["bernese-mountain-dog", "greater-swiss-mountain-dog"],
  ["bichon-frise", "bolognese"],
  ["bichon-frise", "coton-de-tulear"],
  ["bichon-frise", "maltese"],
  ["biewer-terrier", "silky-terrier"],
  ["biewer-terrier", "yorkshire-terrier"],
  ["black-and-tan-coonhound", "bluetick-coonhound"],
  ["black-and-tan-coonhound", "redbone-coonhound"],
  ["black-russian-terrier", "bouvier-des-flandres"],
  ["black-russian-terrier", "giant-schnauzer"],
  ["bluetick-coonhound", "redbone-coonhound"],
  ["bluetick-coonhound", "treeing-walker-coonhound"],
  ["bolognese", "coton-de-tulear"],
  ["bolognese", "havanese"],
  ["bolognese", "lhasa-apso"],
  ["border-collie", "collie"],
  ["border-terrier", "cairn-terrier"],
  ["border-terrier", "norwich-terrier"],
  ["borzoi", "irish-wolfhound"],
  ["borzoi", "scottish-deerhound"],
  ["boston-terrier", "french-bulldog"],
  ["boston-terrier", "pug"],
  ["bouvier-des-flandres", "giant-schnauzer"],
  ["boxer", "doberman-pinscher"],
  ["boxer", "staffordshire-bull-terrier"],
  ["bracco-italiano", "spinone-italiano"],
  ["brittany", "welsh-springer-spaniel"],
  ["bull-terrier", "bulldog"],
  ["bull-terrier", "miniature-bull-terrier"],
  ["bull-terrier", "staffordshire-bull-terrier"],
  ["bulldog", "french-bulldog"],
  ["bulldog", "staffordshire-bull-terrier"],
  ["bullmastiff", "cane-corso"],
  ["bullmastiff", "dogue-de-bordeaux"],
  ["bullmastiff", "mastiff"],
  ["bullmastiff", "neapolitan-mastiff"],
  ["cairn-terrier", "norwich-terrier"],
  ["cairn-terrier", "scottish-terrier"],
  ["cairn-terrier", "skye-terrier"],
  ["cairn-terrier", "west-highland-white-terrier"],
  ["cane-corso", "neapolitan-mastiff"],
  ["cane-corso", "rottweiler"],
  ["cardigan-welsh-corgi", "lancashire-heeler"],
  ["cardigan-welsh-corgi", "pembroke-welsh-corgi"],
  ["cavalier-king-charles-spaniel", "cocker-spaniel"],
  ["cavalier-king-charles-spaniel", "english-toy-spaniel"],
  ["cesky-terrier", "dandie-dinmont-terrier"],
  ["cesky-terrier", "skye-terrier"],
  ["chesapeake-bay-retriever", "curly-coated-retriever"],
  ["chesapeake-bay-retriever", "flat-coated-retriever"],
  ["chesapeake-bay-retriever", "golden-retriever"],
  ["chesapeake-bay-retriever", "labrador-retriever"],
  ["chihuahua", "japanese-chin"],
  ["chihuahua", "papillon"],
  ["chihuahua", "toy-fox-terrier"],
  ["chinese-crested", "peruvian-inca-orchid"],
  ["chinese-crested", "xoloitzcuintli"],
  ["chinese-shar-pei", "chow-chow"],
  ["chinook", "siberian-husky"],
  ["clumber-spaniel", "field-spaniel"],
  ["clumber-spaniel", "sussex-spaniel"],
  ["cocker-spaniel", "english-cocker-spaniel"],
  ["coton-de-tulear", "havanese"],
  ["coton-de-tulear", "maltese"],
  ["coton-de-tulear", "russian-tsvetnaya-bolonka"],
  ["curly-coated-retriever", "flat-coated-retriever"],
  ["curly-coated-retriever", "golden-retriever"],
  ["curly-coated-retriever", "labrador-retriever"],
  ["curly-coated-retriever", "nova-scotia-duck-tolling-retriever"],
  ["dachshund", "pembroke-welsh-corgi"],
  ["dachshund", "teddy-roosevelt-terrier"],
  ["dalmatian", "weimaraner"],
  ["dandie-dinmont-terrier", "glen-of-imaal-terrier"],
  ["dandie-dinmont-terrier", "sealyham-terrier"],
  ["danish-swedish-farmdog", "parson-russell-terrier"],
  ["doberman-pinscher", "german-pinscher"],
  ["doberman-pinscher", "rottweiler"],
  ["dogue-de-bordeaux", "neapolitan-mastiff"],
  ["english-cocker-spaniel", "english-springer-spaniel"],
  ["english-cocker-spaniel", "field-spaniel"],
  ["english-cocker-spaniel", "sussex-spaniel"],
  ["english-cocker-spaniel", "welsh-springer-spaniel"],
  ["english-foxhound", "harrier"],
  ["english-setter", "gordon-setter"],
  ["english-setter", "irish-red-and-white-setter"],
  ["english-setter", "irish-setter"],
  ["english-springer-spaniel", "field-spaniel"],
  ["english-springer-spaniel", "sussex-spaniel"],
  ["english-springer-spaniel", "welsh-springer-spaniel"],
  ["english-toy-spaniel", "japanese-chin"],
  ["english-toy-spaniel", "pekingese"],
  ["entlebucher-mountain-dog", "greater-swiss-mountain-dog"],
  ["field-spaniel", "sussex-spaniel"],
  ["finnish-lapphund", "finnish-spitz"],
  ["finnish-lapphund", "icelandic-sheepdog"],
  ["finnish-spitz", "norwegian-buhund"],
  ["finnish-spitz", "norwegian-elkhound"],
  ["flat-coated-retriever", "golden-retriever"],
  ["flat-coated-retriever", "labrador-retriever"],
  ["flat-coated-retriever", "nova-scotia-duck-tolling-retriever"],
  ["french-bulldog", "miniature-bull-terrier"],
  ["french-bulldog", "pug"],
  ["german-pinscher", "miniature-pinscher"],
  ["german-shorthaired-pointer", "german-wirehaired-pointer"],
  ["german-shorthaired-pointer", "pointer"],
  ["german-spitz", "pomeranian"],
  ["german-wirehaired-pointer", "wirehaired-pointing-griffon"],
  ["german-wirehaired-pointer", "wirehaired-vizsla"],
  ["giant-schnauzer", "miniature-schnauzer"],
  ["giant-schnauzer", "standard-schnauzer"],
  ["glen-of-imaal-terrier", "norfolk-terrier"],
  ["glen-of-imaal-terrier", "sealyham-terrier"],
  ["glen-of-imaal-terrier", "skye-terrier"],
  ["golden-retriever", "labrador-retriever"],
  ["golden-retriever", "nova-scotia-duck-tolling-retriever"],
  ["gordon-setter", "irish-red-and-white-setter"],
  ["gordon-setter", "irish-setter"],
  ["grand-basset-griffon-vendeen", "otterhound"],
  ["great-pyrenees", "kuvasz"],
  ["greyhound", "italian-greyhound"],
  ["greyhound", "saluki"],
  ["greyhound", "sloughi"],
  ["greyhound", "whippet"],
  ["havanese", "lhasa-apso"],
  ["havanese", "russian-tsvetnaya-bolonka"],
  ["ibizan-hound", "pharaoh-hound"],
  ["ibizan-hound", "portuguese-podengo"],
  ["irish-red-and-white-setter", "irish-setter"],
  ["irish-red-and-white-setter", "welsh-springer-spaniel"],
  ["irish-terrier", "kerry-blue-terrier"],
  ["irish-terrier", "lakeland-terrier"],
  ["irish-terrier", "soft-coated-wheaten-terrier"],
  ["irish-terrier", "welsh-terrier"],
  ["irish-water-spaniel", "portuguese-water-dog"],
  ["irish-water-spaniel", "spanish-water-dog"],
  ["irish-wolfhound", "scottish-deerhound"],
  ["italian-greyhound", "miniature-pinscher"],
  ["italian-greyhound", "whippet"],
  ["japanese-chin", "pekingese"],
  ["japanese-chin", "tibetan-spaniel"],
  ["kai-ken", "shiba-inu"],
  ["kerry-blue-terrier", "soft-coated-wheaten-terrier"],
  ["kerry-blue-terrier", "standard-schnauzer"],
  ["kerry-blue-terrier", "welsh-terrier"],
  ["komondor", "puli"],
  ["labrador-retriever", "nova-scotia-duck-tolling-retriever"],
  ["lakeland-terrier", "soft-coated-wheaten-terrier"],
  ["lakeland-terrier", "welsh-terrier"],
  ["leonberger", "newfoundland"],
  ["lhasa-apso", "russian-tsvetnaya-bolonka"],
  ["lhasa-apso", "shih-tzu"],
  ["lowchen", "tibetan-terrier"],
  ["maltese", "silky-terrier"],
  ["maltese", "yorkshire-terrier"],
  ["manchester-terrier-standard", "whippet"],
  ["manchester-terrier-toy", "miniature-pinscher"],
  ["manchester-terrier-toy", "toy-fox-terrier"],
  ["mastiff", "neapolitan-mastiff"],
  ["mastiff", "tibetan-mastiff"],
  ["miniature-bull-terrier", "staffordshire-bull-terrier"],
  ["miniature-pinscher", "toy-fox-terrier"],
  ["miniature-schnauzer", "standard-schnauzer"],
  ["mudi", "pumi"],
  ["mudi", "pyrenean-shepherd"],
  ["nederlandse-kooikerhondje", "nova-scotia-duck-tolling-retriever"],
  ["nederlandse-kooikerhondje", "welsh-springer-spaniel"],
  ["norfolk-terrier", "norwich-terrier"],
  ["norfolk-terrier", "sealyham-terrier"],
  ["norfolk-terrier", "west-highland-white-terrier"],
  ["norrbottenspets", "norwegian-lundehund"],
  ["norwegian-buhund", "norwegian-elkhound"],
  ["norwegian-lundehund", "swedish-vallhund"],
  ["norwich-terrier", "west-highland-white-terrier"],
  ["old-english-sheepdog", "polish-lowland-sheepdog"],
  ["papillon", "russian-toy"],
  ["parson-russell-terrier", "russell-terrier"],
  ["parson-russell-terrier", "smooth-fox-terrier"],
  ["parson-russell-terrier", "wire-fox-terrier"],
  ["pekingese", "tibetan-spaniel"],
  ["pembroke-welsh-corgi", "swedish-vallhund"],
  ["peruvian-inca-orchid", "xoloitzcuintli"],
  ["pharaoh-hound", "portuguese-podengo"],
  ["pharaoh-hound", "saluki"],
  ["portuguese-podengo", "portuguese-podengo-pequeno"],
  ["portuguese-water-dog", "spanish-water-dog"],
  ["puli", "pumi"],
  ["pyrenean-mastiff", "st-bernard"],
  ["pyrenean-mastiff", "tibetan-mastiff"],
  ["rat-terrier", "teddy-roosevelt-terrier"],
  ["redbone-coonhound", "treeing-walker-coonhound"],
  ["russell-terrier", "smooth-fox-terrier"],
  ["russell-terrier", "wire-fox-terrier"],
  ["russian-toy", "toy-fox-terrier"],
  ["russian-tsvetnaya-bolonka", "shih-tzu"],
  ["saluki", "sloughi"],
  ["samoyed", "siberian-husky"],
  ["samoyed", "yakutian-laika"],
  ["scottish-terrier", "skye-terrier"],
  ["scottish-terrier", "west-highland-white-terrier"],
  ["shih-tzu", "tibetan-terrier"],
  ["siberian-husky", "yakutian-laika"],
  ["silky-terrier", "yorkshire-terrier"],
  ["smooth-fox-terrier", "teddy-roosevelt-terrier"],
  ["smooth-fox-terrier", "toy-fox-terrier"],
  ["smooth-fox-terrier", "wire-fox-terrier"],
  ["spinone-italiano", "wirehaired-pointing-griffon"],
  ["tibetan-spaniel", "tibetan-terrier"],
  ["vizsla", "weimaraner"],
  ["vizsla", "wirehaired-vizsla"],
  ["wirehaired-pointing-griffon", "wirehaired-vizsla"],
];
