import type { AnimalImage } from "./types";

/**
 * Verified animal images.
 *
 * Each entry has been confirmed via Wikimedia Commons' MediaWiki API
 * (action=query, prop=imageinfo, extmetadata) on the date noted in
 * `verifiedAt`. Only Public Domain, CC BY, and CC BY-SA images are listed —
 * GFDL-only, CC BY-NC, CC BY-ND, and unclear-license files are explicitly
 * excluded by FaunaHub editorial policy.
 *
 * Files were downloaded via Wikimedia's thumbnail service (which is a
 * permitted derivative) and converted to WebP locally with sharp (quality 82,
 * max width 1600). The WebP conversion is itself a derivative and is allowed
 * under every license used below.
 */
export const ANIMAL_IMAGES: readonly AnimalImage[] = [
  {
    id: "tiger-wikimedia-001",
    animalSlug: "tiger",
    pagePath: "/animals/tiger",
    role: "hero",
    localPath: "/images/animals/tiger/tiger-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Walking_tiger_female.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Adult female Bengal tiger (Panthera tigris) walking through dry grassland.",
    caption: "Bengal tiger walking through grassland habitat.",
    width: 1600,
    height: 883,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Share-alike license — derivative works must also be released under CC BY-SA 4.0. Author is a recognised Wikimedia wildlife photographer; species identification is unambiguous.",
  },
  {
    id: "lion-wikimedia-001",
    animalSlug: "lion",
    pagePath: "/animals/lion",
    role: "hero",
    localPath: "/images/animals/lion/lion-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lion_d%27Afrique_(Panthera_leo).jpg",
    author: "Gzen92",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Gzen92, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Adult African lion (Panthera leo) resting in golden grassland.",
    caption: "African lion (Panthera leo).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Share-alike license. Species ID consistent with file description (Panthera leo).",
  },
  {
    id: "elephant-wikimedia-001",
    animalSlug: "elephant",
    pagePath: "/animals/elephant",
    role: "hero",
    localPath: "/images/animals/elephant/elephant-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Elephant_near_ndutu.jpg",
    author: "nickandmel2006 (Flickr)",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution:
      "Photo by nickandmel2006 (Flickr), CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "African bush elephant (Loxodonta africana) standing on dry savanna near Lake Ndutu, Tanzania.",
    caption: "African bush elephant (Loxodonta africana) near Lake Ndutu, Tanzania.",
    width: 1600,
    height: 2133,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Share-alike license. Location and species ID consistent with Wikimedia file description.",
  },
  {
    id: "dolphin-wikimedia-001",
    animalSlug: "dolphin",
    pagePath: "/animals/dolphin",
    role: "hero",
    localPath: "/images/animals/dolphin/dolphin-hero.webp",
    sourceName: "Wikimedia Commons (NASA)",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tursiops_truncatus_01.jpg",
    author: "NASA",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by NASA, Public domain, via Wikimedia Commons.",
    alt: "Common bottlenose dolphin (Tursiops truncatus) surfacing in clear water.",
    caption: "Common bottlenose dolphin (Tursiops truncatus).",
    width: 1600,
    height: 1064,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-20",
    riskNotes:
      "US federal government work — Public domain. Attribution provided for transparency though not legally required.",
  },
  {
    id: "shark-wikimedia-001",
    animalSlug: "shark",
    pagePath: "/animals/shark",
    role: "hero",
    localPath: "/images/animals/shark/shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Carcharhinus_melanopterus_Luc_Viatour.jpg",
    author: "Luc Viatour",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Luc Viatour, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Blacktip reef shark (Carcharhinus melanopterus) swimming in shallow coral reef water.",
    caption: "Blacktip reef shark (Carcharhinus melanopterus) — used here to represent the broader shark group.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Share-alike license. Reference species (blacktip reef shark) clearly identified in the file description.",
  },
  {
    id: "penguin-wikimedia-001",
    animalSlug: "penguin",
    pagePath: "/animals/penguin",
    role: "hero",
    localPath: "/images/animals/penguin/penguin-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Penguin_in_Antarctica_jumping_out_of_the_water.jpg",
    author: "Christopher Michel",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution:
      "Photo by Christopher Michel, CC BY 2.0, via Wikimedia Commons.",
    alt: "Emperor penguin (Aptenodytes forsteri) leaping out of icy Antarctic water onto pack ice.",
    caption: "Emperor penguin (Aptenodytes forsteri) emerging from Antarctic water.",
    width: 1600,
    height: 1063,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Attribution-only license. Antarctic context and species ID consistent with file description.",
  },
  {
    id: "eagle-wikimedia-001",
    animalSlug: "eagle",
    pagePath: "/animals/eagle",
    role: "hero",
    localPath: "/images/animals/eagle/eagle-hero.webp",
    sourceName: "Wikimedia Commons (USFWS)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Haliaeetus_leucocephalus2.jpg",
    author: "David Menke / U.S. Fish and Wildlife Service",
    license: "Public domain",
    licenseUrl: "",
    attribution:
      "Photo by David Menke, U.S. Fish and Wildlife Service, Public domain, via Wikimedia Commons.",
    alt: "Adult bald eagle (Haliaeetus leucocephalus) perched against a clear background.",
    caption: "Bald eagle (Haliaeetus leucocephalus).",
    width: 1600,
    height: 1997,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-20",
    riskNotes:
      "US federal government work — Public domain. Used as the lead reference image for the broader eagle profile.",
  },
  {
    id: "wolf-wikimedia-001",
    animalSlug: "wolf",
    pagePath: "/animals/wolf",
    role: "hero",
    localPath: "/images/animals/wolf/wolf-hero.webp",
    sourceName: "Wikimedia Commons (USFWS)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Front_view_of_a_resting_Canis_lupus_ssp.jpg",
    author: "Gary Kramer / U.S. Fish and Wildlife Service",
    license: "Public domain",
    licenseUrl: "",
    attribution:
      "Photo by Gary Kramer, U.S. Fish and Wildlife Service, Public domain, via Wikimedia Commons.",
    alt: "Gray wolf (Canis lupus) resting and facing the camera.",
    caption: "Gray wolf (Canis lupus) at rest.",
    width: 1600,
    height: 1997,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-20",
    riskNotes:
      "U.S. federal work — Public domain. Original filename references C. lupus ssp.; species identification is consistent with USFWS captioning.",
  },
  {
    id: "panda-wikimedia-001",
    animalSlug: "panda",
    pagePath: "/animals/panda",
    role: "hero",
    localPath: "/images/animals/panda/panda-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Grosser_Panda.JPG",
    author: "J. Patrick Fischer",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution:
      "Photo by J. Patrick Fischer, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Giant panda (Ailuropoda melanoleuca) sitting and feeding on bamboo.",
    caption: "Giant panda (Ailuropoda melanoleuca) feeding on bamboo.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Share-alike license — derivatives must be released under the same or a compatible CC BY-SA license.",
  },
  {
    id: "cheetah-wikimedia-001",
    animalSlug: "cheetah",
    pagePath: "/animals/cheetah",
    role: "hero",
    localPath: "/images/animals/cheetah/cheetah-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cheetah_Kruger.jpg",
    author: "Mukul2u",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    attribution: "Photo by Mukul2u, CC BY 3.0, via Wikimedia Commons.",
    alt: "Adult cheetah (Acinonyx jubatus) standing in dry grassland in Kruger National Park.",
    caption: "Cheetah (Acinonyx jubatus) in Kruger National Park, South Africa.",
    width: 1600,
    height: 1048,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Attribution-only license, no share-alike constraint. Park location and species ID consistent with file description.",
  },
  {
    id: "leopard-wikimedia-001",
    animalSlug: "leopard",
    pagePath: "/animals/leopard",
    role: "hero",
    localPath: "/images/animals/leopard/leopard-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Persian_leopard_1.jpg",
    author: "Benoit.boudeville",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Benoit.boudeville, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Persian leopard (Panthera pardus tulliana) resting on a rocky outcrop.",
    caption: "Persian leopard (Panthera pardus tulliana subspecies).",
    width: 1600,
    height: 1068,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Share-alike license. Persian leopard is a recognised subspecies of Panthera pardus; the broader species page can use this image with appropriate caption.",
  },
  {
    id: "crocodile-wikimedia-001",
    animalSlug: "crocodile",
    pagePath: "/animals/crocodile",
    role: "hero",
    localPath: "/images/animals/crocodile/crocodile-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nile_crocodile_head.jpg",
    author: "Leigh Bedford",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Leigh Bedford, CC BY 2.0, via Wikimedia Commons.",
    alt: "Close-up of a Nile crocodile (Crocodylus niloticus) showing the V-shaped snout and visible upper teeth.",
    caption: "Nile crocodile (Crocodylus niloticus) — note the V-shaped snout typical of true crocodiles.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Attribution-only license. Species identification consistent with Nile crocodile morphology in the image.",
  },
  {
    id: "alligator-wikimedia-001",
    animalSlug: "alligator",
    pagePath: "/animals/alligator",
    role: "hero",
    localPath: "/images/animals/alligator/alligator-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:American_Alligator.jpg",
    author: "User:Postdlf",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution:
      "Photo by Postdlf (Wikimedia Commons), CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "American alligator (Alligator mississippiensis) head close-up showing the broad U-shaped snout.",
    caption: "American alligator (Alligator mississippiensis) — note the broad U-shaped snout that distinguishes alligators from crocodiles.",
    width: 1600,
    height: 2133,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-20",
    riskNotes:
      "Share-alike license. Author identified only by Wikimedia username; attribution uses that username as published.",
  },
  {
    id: "giraffe-wikimedia-001",
    animalSlug: "giraffe",
    pagePath: "/animals/giraffe",
    role: "hero",
    localPath: "/images/animals/giraffe/giraffe-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:South_African_giraffe_(Giraffa_camelopardalis_giraffa)_Kruger.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "South African giraffe (Giraffa camelopardalis giraffa) standing in dry savanna in Kruger National Park.",
    caption: "South African giraffe (Giraffa camelopardalis giraffa) in Kruger National Park.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Same trusted Wikimedia wildlife photographer used for the tiger and jaguar entries.",
  },
  {
    id: "koala-wikimedia-001",
    animalSlug: "koala",
    pagePath: "/animals/koala",
    role: "hero",
    localPath: "/images/animals/koala/koala-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Koala_(Phascolarctos_cinereus)_(9994356646).jpg",
    author: "Bernard DUPONT",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution:
      "Photo by Bernard DUPONT, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Adult koala (Phascolarctos cinereus) wedged in the fork of a eucalyptus tree.",
    caption: "Koala (Phascolarctos cinereus) in eucalyptus habitat.",
    width: 1600,
    height: 1066,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Bernard Dupont is a prolific Wikimedia wildlife contributor; species ID consistent with file description.",
  },
  {
    id: "chimpanzee-wikimedia-001",
    animalSlug: "chimpanzee",
    pagePath: "/animals/chimpanzee",
    role: "hero",
    localPath: "/images/animals/chimpanzee/chimpanzee-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chimpanzee_in_the_wild.jpg",
    author: "D.G. Kulakov",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by D.G. Kulakov, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Adult chimpanzee (Pan troglodytes) sitting in a wild forest setting.",
    caption: "Chimpanzee (Pan troglodytes) in natural forest habitat.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Wild-context photograph; preferred over captive-context alternatives.",
  },
  {
    id: "gorilla-wikimedia-001",
    animalSlug: "gorilla",
    pagePath: "/animals/gorilla",
    role: "hero",
    localPath: "/images/animals/gorilla/gorilla-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Mountain_Gorilla,_Bwindi_(24490249134).jpg",
    author: "Rod Waddington",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution:
      "Photo by Rod Waddington, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Mountain gorilla (Gorilla beringei beringei) in Bwindi Impenetrable National Park, Uganda.",
    caption: "Mountain gorilla (Gorilla beringei beringei) in Bwindi Impenetrable National Park, Uganda.",
    width: 1600,
    height: 1068,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Wild mountain gorilla in named protected area; species and location both verifiable.",
  },
  {
    id: "bear-wikimedia-001",
    animalSlug: "bear",
    pagePath: "/animals/bear",
    role: "hero",
    localPath: "/images/animals/bear/bear-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Grizzlyb%C3%A4r_(Ursus_arctos_horribilis),_jagt_Lachse_2.jpg",
    author: "marneejill",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by marneejill, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Grizzly bear (Ursus arctos horribilis) hunting salmon in a shallow river.",
    caption: "Grizzly bear (Ursus arctos horribilis) hunting salmon — used here as a reference image for the broader bear profile.",
    width: 1600,
    height: 1039,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Wild grizzly subspecies (U. a. horribilis); used as a generic reference for the umbrella bear profile.",
  },
  {
    id: "jaguar-wikimedia-001",
    animalSlug: "jaguar",
    pagePath: "/animals/jaguar",
    role: "hero",
    localPath: "/images/animals/jaguar/jaguar-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Jaguar_(Panthera_onca_palustris)_male_Three_Brothers_River.JPG",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Male jaguar (Panthera onca palustris) on the bank of the Three Brothers River, Pantanal, Brazil.",
    caption: "Male jaguar (Panthera onca palustris) on the Three Brothers River, Pantanal, Brazil.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Pantanal jaguar — clearly identified subspecies, used as reference image for the broader jaguar profile.",
  },
  {
    id: "owl-wikimedia-001",
    animalSlug: "owl",
    pagePath: "/animals/owl",
    role: "hero",
    localPath: "/images/animals/owl/owl-hero.webp",
    sourceName: "Wikimedia Commons (Glacier NPS)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Great_Horned_Owl_(Bubo_virginianus)_(48920155928).jpg",
    author: "Glacier National Park Service (GlacierNPS)",
    license: "Public domain",
    licenseUrl: "",
    attribution:
      "Photo by Glacier National Park Service, Public domain, via Wikimedia Commons.",
    alt: "Great horned owl (Bubo virginianus) perched on a tree branch.",
    caption: "Great horned owl (Bubo virginianus) — used as a reference image for the broader owl profile.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-21",
    riskNotes:
      "US National Park Service work — Public domain. Attribution retained for transparency.",
  },
  {
    id: "fox-wikimedia-001",
    animalSlug: "fox",
    pagePath: "/animals/fox",
    role: "hero",
    localPath: "/images/animals/fox/fox-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Red_Fox_in_Ireland.jpg",
    author: "Greg Clarke",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Greg Clarke, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult red fox (Vulpes vulpes) standing on a grassy slope in Ireland.",
    caption: "Red fox (Vulpes vulpes) in Ireland.",
    width: 1600,
    height: 1239,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Attribution-only license. Species and location consistent with file description.",
  },
  {
    id: "zebra-wikimedia-001",
    animalSlug: "zebra",
    pagePath: "/animals/zebra",
    role: "hero",
    localPath: "/images/animals/zebra/zebra-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Line_of_Zebra_on_the_Plains_(49688548783).jpg",
    author: "Eric Kilby",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Eric Kilby, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Line of plains zebras (Equus quagga) crossing open grassland in single file.",
    caption: "Plains zebras (Equus quagga) on open grassland.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Plains zebra is the most widespread of three zebra species; image used as reference for the umbrella zebra profile.",
  },
  {
    id: "kangaroo-wikimedia-001",
    animalSlug: "kangaroo",
    pagePath: "/animals/kangaroo",
    role: "hero",
    localPath: "/images/animals/kangaroo/kangaroo-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Forester_kangaroo_(Macropus_giganteus_tasmaniensis)_Esk_Valley.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Forester kangaroo (Macropus giganteus tasmaniensis) standing alert in the Esk Valley, Tasmania.",
    caption: "Forester kangaroo (Macropus giganteus tasmaniensis), a Tasmanian subspecies of the eastern grey kangaroo.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes:
      "Share-alike license. Forester kangaroo is a recognised subspecies of Macropus giganteus and used here as a reference image for the broader kangaroo profile.",
  },

  // ----- GALLERY -----

  {
    id: "tiger-wikimedia-002",
    animalSlug: "tiger",
    pagePath: "/animals/tiger",
    role: "gallery",
    localPath: "/images/animals/tiger/tiger-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Royal_bengal_tiger_Swimming.jpg",
    author: "Badal Chandra Sarker",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Badal Chandra Sarker, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Bengal tiger (Panthera tigris) swimming through a shallow channel of the Sundarbans mangroves.",
    caption: "Bengal tiger swimming — tigers are strong swimmers and frequently enter water.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "tiger-wikimedia-003",
    animalSlug: "tiger",
    pagePath: "/animals/tiger",
    role: "gallery",
    localPath: "/images/animals/tiger/tiger-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sundarbans_Tigress_swimming_West_Bengal_08.jpg",
    author: "Dr. Raju Kasambe",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Dr. Raju Kasambe, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Adult tigress (Panthera tigris tigris) crossing a tidal channel in the Sundarbans, West Bengal.",
    caption: "Tigress crossing a tidal channel in the Sundarbans, West Bengal.",
    width: 1500,
    height: 1125,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "lion-wikimedia-002",
    animalSlug: "lion",
    pagePath: "/animals/lion",
    role: "gallery",
    localPath: "/images/animals/lion/lion-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mating_Lions_Serengeti_NP,_Tanzania_(48773627916).jpg",
    author: "Ankit Gita from Mumbai, Maharashtra, India, India",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Ankit Gita from Mumbai, Maharashtra, India, India, CC BY 2.0, via Wikimedia Commons.",
    alt: "Pair of African lions (Panthera leo) in Serengeti National Park, Tanzania.",
    caption: "African lions in the Serengeti — prides typically consist of related females, their cubs, and a small coalition of males.",
    width: 1500,
    height: 1071,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "lion-wikimedia-003",
    animalSlug: "lion",
    pagePath: "/animals/lion",
    role: "gallery",
    localPath: "/images/animals/lion/lion-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:African_Lion_Mating_pair_Serengeti_NP,_Tanzania_(48891220877).jpg",
    author: "Ankit Gita from Mumbai, Maharashtra, India, India",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Ankit Gita from Mumbai, Maharashtra, India, India, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult male and female African lion (Panthera leo) on open grassland in Serengeti National Park.",
    caption: "Adult male and female lion together on the Serengeti plains.",
    width: 1500,
    height: 1071,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "elephant-wikimedia-002",
    animalSlug: "elephant",
    pagePath: "/animals/elephant",
    role: "gallery",
    localPath: "/images/animals/elephant/elephant-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sitting_Asian_elephant_(Elephas_maximus)_bathing_in_Tad_Lo_river,_Laos.jpg",
    author: "Basile Morin",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Basile Morin, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Asian elephant (Elephas maximus) bathing in the Tad Lo river, Laos.",
    caption: "Asian elephant (Elephas maximus) bathing in a river in Laos.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "elephant-wikimedia-003",
    animalSlug: "elephant",
    pagePath: "/animals/elephant",
    role: "gallery",
    localPath: "/images/animals/elephant/elephant-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Elefante_asi%C3%A1tico_(Elephas_maximus),_Tierpark_Hellabrunn,_M%C3%BAnich,_Alemania,_2012-06-17,_DD_05.JPG",
    author: "Diego Delso",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Diego Delso, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Asian elephant (Elephas maximus) standing in an enclosure in Tierpark Hellabrunn, Munich.",
    caption: "Asian elephant (Elephas maximus), a separate species from the African bush elephant.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "dolphin-wikimedia-002",
    animalSlug: "dolphin",
    pagePath: "/animals/dolphin",
    role: "gallery",
    localPath: "/images/animals/dolphin/dolphin-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bottlenose_dolphin_(Tursiops_truncatus)_swimming_alongside_the_ferry_from_Pico_to_Faial,_Azores,_Portugal_(PPL1-Corrected)_julesvernex2.jpg",
    author: "Jules Verne Times Two",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Jules Verne Times Two, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Common bottlenose dolphin (Tursiops truncatus) bow-riding a ferry between Pico and Faial, Azores.",
    caption: "Bottlenose dolphin (Tursiops truncatus) bow-riding a ferry, Azores.",
    width: 1500,
    height: 847,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "dolphin-wikimedia-003",
    animalSlug: "dolphin",
    pagePath: "/animals/dolphin",
    role: "gallery",
    localPath: "/images/animals/dolphin/dolphin-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Two_bottlenose_dolphins_(Tursiops_truncatus)_swimming_alongside_the_ferry_from_Pico_to_Faial,_Azores,_Portugal_(PPL1-Corrected)_julesvernex2.jpg",
    author: "Jules Verne Times Two",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Jules Verne Times Two, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Two common bottlenose dolphins (Tursiops truncatus) swimming together near the Azores ferry.",
    caption: "A pair of bottlenose dolphins moving in close formation alongside a vessel.",
    width: 1500,
    height: 859,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "shark-wikimedia-002",
    animalSlug: "shark",
    pagePath: "/animals/shark",
    role: "gallery",
    localPath: "/images/animals/shark/shark-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Great_White_Shark_(Carcharodon_carcharias)_attacking_a_seal_shaped_decoy_..._(29724038004).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Great white shark (Carcharodon carcharias) launching out of the water at a decoy off South Africa.",
    caption: "Great white shark (Carcharodon carcharias) breaching at a decoy.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "shark-wikimedia-003",
    animalSlug: "shark",
    pagePath: "/animals/shark",
    role: "gallery",
    localPath: "/images/animals/shark/shark-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Great_White_Shark_(Carcharodon_carcharias)_(32872284396).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Great white shark (Carcharodon carcharias) breaching at the surface in pursuit of prey.",
    caption: "Great white shark (Carcharodon carcharias) — a contrasting species to the blacktip reef shark in the hero image.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "penguin-wikimedia-002",
    animalSlug: "penguin",
    pagePath: "/animals/penguin",
    role: "gallery",
    localPath: "/images/animals/penguin/penguin-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pygoscelis_adeliae_(Adelie_Penguin)_(48720159652).jpg",
    author: "Auckland Museum Collections from Auckland, Aotearoa New Zealand",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Auckland Museum Collections from Auckland, Aotearoa New Zealand, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adélie penguin (Pygoscelis adeliae) standing on rock at the edge of pack ice.",
    caption: "Adélie penguin (Pygoscelis adeliae) — one of the species commonly grouped under \"penguin\".",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "penguin-wikimedia-003",
    animalSlug: "penguin",
    pagePath: "/animals/penguin",
    role: "gallery",
    localPath: "/images/animals/penguin/penguin-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pygoscelis_Adeliae_20250105.jpg",
    author: "Rjcastillo",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Rjcastillo, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Group of Adélie penguins (Pygoscelis adeliae) on snow in Antarctica.",
    caption: "Adélie penguins gathered on Antarctic snow.",
    width: 1500,
    height: 949,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "eagle-wikimedia-002",
    animalSlug: "eagle",
    pagePath: "/animals/eagle",
    role: "gallery",
    localPath: "/images/animals/eagle/eagle-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:016_Wild_Golden_Eagle_in_flight_at_Pfyn-Finges_(Switzerland)_Photo_by_Giles_Laurent.jpg",
    author: "Giles Laurent",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Giles Laurent, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Wild golden eagle (Aquila chrysaetos) in flight above Pfyn-Finges, Switzerland.",
    caption: "Wild golden eagle (Aquila chrysaetos) in flight, the reference species for this profile.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "eagle-wikimedia-003",
    animalSlug: "eagle",
    pagePath: "/animals/eagle",
    role: "gallery",
    localPath: "/images/animals/eagle/eagle-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:001_Wild_Golden_Eagle_and_Majinghorn_Pfyn-Finges_Photo_by_Giles_Laurent.jpg",
    author: "Giles Laurent",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Giles Laurent, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Wild golden eagle (Aquila chrysaetos) circling near the Majinghorn, Pfyn-Finges, Switzerland.",
    caption: "Golden eagle circling near the Majinghorn in the Swiss Alps.",
    width: 1500,
    height: 819,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "alligator-wikimedia-002",
    animalSlug: "alligator",
    pagePath: "/animals/alligator",
    role: "gallery",
    localPath: "/images/animals/alligator/alligator-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Alligator_posing_on_the_Econlockhatchee_River_(Central_Florida).jpg",
    author: "Trougnouf",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "Photo by Trougnouf, CC BY 4.0, via Wikimedia Commons.",
    alt: "American alligator (Alligator mississippiensis) resting on a log on the Econlockhatchee River, Florida.",
    caption: "American alligator (Alligator mississippiensis) resting on a fallen log in a central Florida river.",
    width: 1500,
    height: 1100,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "wolf-wikimedia-002",
    animalSlug: "wolf",
    pagePath: "/animals/wolf",
    role: "gallery",
    localPath: "/images/animals/wolf/wolf-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Niko,_Male_Gray_Wolf,_Wolf_Park_(51096705005).jpg",
    author: "Raed Mansour from Chicago, USA",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Raed Mansour from Chicago, USA, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult gray wolf (Canis lupus) standing in a wooded enclosure at Wolf Park, Indiana.",
    caption: "Adult gray wolf (Canis lupus) — full-body view complementing the resting portrait in the hero image.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "wolf-wikimedia-003",
    animalSlug: "wolf",
    pagePath: "/animals/wolf",
    role: "gallery",
    localPath: "/images/animals/wolf/wolf-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Niko,_Male_Gray_Wolf,_Wolf_Park_(51095977869).jpg",
    author: "Raed Mansour from Chicago, USA",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Raed Mansour from Chicago, USA, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult gray wolf (Canis lupus) close-up portrait at Wolf Park, Indiana.",
    caption: "Gray wolf close-up portrait.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "leopard-wikimedia-002",
    animalSlug: "leopard",
    pagePath: "/animals/leopard",
    role: "gallery",
    localPath: "/images/animals/leopard/leopard-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:African_Leopard_(Panthera_pardus_ssp._pardus)_and_African_bush_elephant_(Loxodonta_africana).jpg",
    author: "Thomas Fuhrmann",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Thomas Fuhrmann, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "African leopard (Panthera pardus pardus) approaching an African bush elephant in Etosha National Park.",
    caption: "African leopard near an African bush elephant — leopards often share habitat with larger megafauna.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "leopard-wikimedia-003",
    animalSlug: "leopard",
    pagePath: "/animals/leopard",
    role: "gallery",
    localPath: "/images/animals/leopard/leopard-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Leopard_(Panthera_pardus)_female_in_a_tree_(16457443325).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Female leopard (Panthera pardus) resting on a tree branch in Kruger National Park, South Africa.",
    caption: "Female leopard resting in a tree, a typical resting behaviour.",
    width: 1500,
    height: 988,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "cheetah-wikimedia-002",
    animalSlug: "cheetah",
    pagePath: "/animals/cheetah",
    role: "gallery",
    localPath: "/images/animals/cheetah/cheetah-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cheetah_with_cubs_-_Masaai_Mara,_Kenya_-_2014.JPG",
    author: "Fabiola Leyton and Carlos Castillo",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Photo by Fabiola Leyton and Carlos Castillo, CC0, via Wikimedia Commons.",
    alt: "Adult cheetah (Acinonyx jubatus) with two cubs in the Masai Mara, Kenya.",
    caption: "Cheetah (Acinonyx jubatus) with cubs in the Masai Mara, Kenya.",
    width: 1500,
    height: 996,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-22",
    riskNotes: "CC0 — public-domain dedication; no attribution legally required. Attribution provided for transparency.",
  },
  {
    id: "cheetah-wikimedia-003",
    animalSlug: "cheetah",
    pagePath: "/animals/cheetah",
    role: "gallery",
    localPath: "/images/animals/cheetah/cheetah-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cheetah_Portrait,_Ol_Pejeta_Conservancy,_Kenya_(51165925965).jpg",
    author: ". Ray in Manila",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by . Ray in Manila, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult cheetah (Acinonyx jubatus) portrait, Ol Pejeta Conservancy, Kenya.",
    caption: "Cheetah portrait at Ol Pejeta Conservancy, Kenya.",
    width: 1500,
    height: 1192,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "crocodile-wikimedia-002",
    animalSlug: "crocodile",
    pagePath: "/animals/crocodile",
    role: "gallery",
    localPath: "/images/animals/crocodile/crocodile-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Saltwater_Crocodile_-_Crocodylus_porosus_-_Ninoy_Aquino_Parks_%26_Wildlife_Center_02.jpg",
    author: "Ramon FVelasquez",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Ramon FVelasquez, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Saltwater crocodile (Crocodylus porosus) resting at the Ninoy Aquino Parks & Wildlife Center, Philippines.",
    caption: "Saltwater crocodile (Crocodylus porosus) — the largest living reptile.",
    width: 1500,
    height: 1125,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "crocodile-wikimedia-003",
    animalSlug: "crocodile",
    pagePath: "/animals/crocodile",
    role: "gallery",
    localPath: "/images/animals/crocodile/crocodile-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Saltwater_Crocodile_-_Crocodylus_porosus_-_Ninoy_Aquino_Parks_%26_Wildlife_Center_01.jpg",
    author: "Ramon FVelasquez",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Ramon FVelasquez, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Saltwater crocodile (Crocodylus porosus) close-up at the Ninoy Aquino Parks & Wildlife Center.",
    caption: "Close-up of a saltwater crocodile showing the V-shaped snout characteristic of true crocodiles.",
    width: 1500,
    height: 1125,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "panda-wikimedia-002",
    animalSlug: "panda",
    pagePath: "/animals/panda",
    role: "gallery",
    localPath: "/images/animals/panda/panda-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Yun_Zi_-_Baby_Giant_Panda_-_IMG_1456_(4305497181).jpg",
    author: "fortherock",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by fortherock, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Young giant panda (Ailuropoda melanoleuca) climbing in an enclosure at San Diego Zoo.",
    caption: "Young giant panda climbing — captive setting, used here for visual context.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "panda-wikimedia-003",
    animalSlug: "panda",
    pagePath: "/animals/panda",
    role: "gallery",
    localPath: "/images/animals/panda/panda-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Giant_Pandas_playing_2.jpg",
    author: "Chi King",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Chi King, CC BY 2.0, via Wikimedia Commons.",
    alt: "Two giant pandas (Ailuropoda melanoleuca) playing together in an enclosure.",
    caption: "Giant pandas play-wrestling, a common behaviour in young animals.",
    width: 1500,
    height: 1402,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "fox-wikimedia-002",
    animalSlug: "fox",
    pagePath: "/animals/fox",
    role: "gallery",
    localPath: "/images/animals/fox/fox-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vulpes_vulpes,_Lodz(Poland)03(js).jpg",
    author: "Jerzy Strzelecki",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    attribution: "Photo by Jerzy Strzelecki, CC BY 3.0, via Wikimedia Commons.",
    alt: "Red fox (Vulpes vulpes) walking through a grassy area in Łódź, Poland.",
    caption: "Red fox (Vulpes vulpes) in an urban-adjacent environment in Łódź, Poland.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "fox-wikimedia-003",
    animalSlug: "fox",
    pagePath: "/animals/fox",
    role: "gallery",
    localPath: "/images/animals/fox/fox-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Newfoundland_red_fox_Vulpes_vulpes_deletrix_in_snow_(33749582021).jpg",
    author: "Paul Asman and Jill Lenoble",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Paul Asman and Jill Lenoble, CC BY 2.0, via Wikimedia Commons.",
    alt: "Newfoundland red fox (Vulpes vulpes deletrix) walking through snow.",
    caption: "Newfoundland red fox — a regional subspecies of Vulpes vulpes — in winter conditions.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "owl-wikimedia-002",
    animalSlug: "owl",
    pagePath: "/animals/owl",
    role: "gallery",
    localPath: "/images/animals/owl/owl-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bubo_scandiacus_-_Karlsruhe_Zoo_02.jpg",
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by H. Zell, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Snowy owl (Bubo scandiacus) at Karlsruhe Zoo, Germany.",
    caption: "Snowy owl (Bubo scandiacus) — a different owl species from the hero great horned owl.",
    width: 1500,
    height: 1236,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "owl-wikimedia-003",
    animalSlug: "owl",
    pagePath: "/animals/owl",
    role: "gallery",
    localPath: "/images/animals/owl/owl-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bubo_scandiacus_MHNT.ZOO.2010.11.157.3.jpg",
    author: "Roger Culos",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Roger Culos, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Adult snowy owl (Bubo scandiacus) shown in profile.",
    caption: "Snowy owl in profile — note the heavily feathered legs and rounded head.",
    width: 1500,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "jaguar-wikimedia-002",
    animalSlug: "jaguar",
    pagePath: "/animals/jaguar",
    role: "gallery",
    localPath: "/images/animals/jaguar/jaguar-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jaguar_in_the_Water_(29473216917).jpg",
    author: "Gerry Zambonini",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Gerry Zambonini, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Jaguar (Panthera onca) wading through shallow water in the Pantanal, Brazil.",
    caption: "Jaguar wading in water — jaguars are unusually water-tolerant for a big cat.",
    width: 1500,
    height: 995,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "jaguar-wikimedia-003",
    animalSlug: "jaguar",
    pagePath: "/animals/jaguar",
    role: "gallery",
    localPath: "/images/animals/jaguar/jaguar-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jaguar_(8455639548).jpg",
    author: "shankar s. from Dubai, united arab emirates",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by shankar s. from Dubai, united arab emirates, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult jaguar (Panthera onca) on a sandy river bank.",
    caption: "Adult jaguar on a sandy river bank.",
    width: 1500,
    height: 1125,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "bear-wikimedia-002",
    animalSlug: "bear",
    pagePath: "/animals/bear",
    role: "gallery",
    localPath: "/images/animals/bear/bear-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Polar_Bear_with_its_tongue_sticking_out.jpg",
    author: "Christopher Michel",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Christopher Michel, CC BY 2.0, via Wikimedia Commons.",
    alt: "Polar bear (Ursus maritimus) on Arctic sea ice with its tongue out.",
    caption: "Polar bear (Ursus maritimus) — one of the eight living bear species, distinct from the grizzly in the hero image.",
    width: 1500,
    height: 1001,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "bear-wikimedia-003",
    animalSlug: "bear",
    pagePath: "/animals/bear",
    role: "gallery",
    localPath: "/images/animals/bear/bear-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Polar_bear_after_unlucky_hunt_for_a_seal.jpg",
    author: "Andreas Weith",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Andreas Weith, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Polar bear (Ursus maritimus) walking across Arctic pack ice.",
    caption: "Polar bear walking across pack ice.",
    width: 1500,
    height: 844,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "giraffe-wikimedia-002",
    animalSlug: "giraffe",
    pagePath: "/animals/giraffe",
    role: "gallery",
    localPath: "/images/animals/giraffe/giraffe-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rothschild%27s_giraffes_drinking_water.jpg",
    author: "Timothy Akolamazima",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Timothy Akolamazima, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Rothschild's giraffes (Giraffa camelopardalis rothschildi) splaying their legs to drink at a waterhole.",
    caption: "Rothschild's giraffes drinking — the characteristic splayed-leg posture lets giraffes reach water.",
    width: 1500,
    height: 1001,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "giraffe-wikimedia-003",
    animalSlug: "giraffe",
    pagePath: "/animals/giraffe",
    role: "gallery",
    localPath: "/images/animals/giraffe/giraffe-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Attack_of_a_lioness_on_a_giraffe_2.jpg",
    author: "Buiobuione",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    attribution: "Photo by Buiobuione, CC BY 4.0, via Wikimedia Commons.",
    alt: "Lioness attacking an adult giraffe (Giraffa camelopardalis) on the African savanna.",
    caption: "Lioness attempting to take down a giraffe — predator pressure is a real factor for giraffes despite their size.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "zebra-wikimedia-002",
    animalSlug: "zebra",
    pagePath: "/animals/zebra",
    role: "gallery",
    localPath: "/images/animals/zebra/zebra-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Plains_Zebras_(Equus_quagga)_mare_and_foal_..._(52705220171).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Adult plains zebra (Equus quagga) with her foal in African savanna.",
    caption: "Plains zebra (Equus quagga) mare with foal.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "zebra-wikimedia-003",
    animalSlug: "zebra",
    pagePath: "/animals/zebra",
    role: "gallery",
    localPath: "/images/animals/zebra/zebra-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Burchell%27s_Zebras_(Equus_quagga_burchellii)_mare_and_foal_..._(51790824612).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Burchell's zebra (Equus quagga burchellii) mare with her foal.",
    caption: "Burchell's zebra (a subspecies of the plains zebra) mare with foal.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "gorilla-wikimedia-002",
    animalSlug: "gorilla",
    pagePath: "/animals/gorilla",
    role: "gallery",
    localPath: "/images/animals/gorilla/gorilla-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Silver_back.jpg",
    author: "TKnoxB from Chemainus, BC, Canada",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by TKnoxB from Chemainus, BC, Canada, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult silverback western gorilla (Gorilla gorilla) seated in a forest setting.",
    caption: "Adult silverback gorilla — a contrasting view to the mountain-gorilla hero image.",
    width: 1518,
    height: 2278,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "chimpanzee-wikimedia-002",
    animalSlug: "chimpanzee",
    pagePath: "/animals/chimpanzee",
    role: "gallery",
    localPath: "/images/animals/chimpanzee/chimpanzee-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pan_(genus)_in_Jardim_Zool%C3%B3gico_de_Curitiba_using_tool.jpg",
    author: "Wilfredor",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Photo by Wilfredor, CC0, via Wikimedia Commons.",
    alt: "Chimpanzee (Pan troglodytes) using a stick as a tool in a zoo enrichment setting.",
    caption: "Chimpanzee using a stick as a tool — captive setting, demonstrating documented tool-use behaviour.",
    width: 1500,
    height: 983,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-22",
    riskNotes: "CC0 — public-domain dedication; no attribution legally required. Attribution provided for transparency.",
  },
  {
    id: "chimpanzee-wikimedia-003",
    animalSlug: "chimpanzee",
    pagePath: "/animals/chimpanzee",
    role: "gallery",
    localPath: "/images/animals/chimpanzee/chimpanzee-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Second_chimpanzee_using_enrichment_box.jpg",
    author: "Damien Neadle",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Damien Neadle, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Chimpanzee (Pan troglodytes) interacting with an enrichment box.",
    caption: "Chimpanzee solving an enrichment task.",
    width: 1500,
    height: 2000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "kangaroo-wikimedia-002",
    animalSlug: "kangaroo",
    pagePath: "/animals/kangaroo",
    role: "gallery",
    localPath: "/images/animals/kangaroo/kangaroo-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Grey_kangaroo_with_Joey.jpg",
    author: "nh53",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by nh53, CC BY 2.0, via Wikimedia Commons.",
    alt: "Adult eastern grey kangaroo (Macropus giganteus) with a joey peering out from her pouch.",
    caption: "Eastern grey kangaroo with a joey in the pouch.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Attribution-only license, no share-alike constraint.",
  },
  {
    id: "kangaroo-wikimedia-003",
    animalSlug: "kangaroo",
    pagePath: "/animals/kangaroo",
    role: "gallery",
    localPath: "/images/animals/kangaroo/kangaroo-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kangaroo_joey.jpg",
    author: "825545",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Photo by 825545, CC0, via Wikimedia Commons.",
    alt: "Kangaroo joey looking out from its mother's pouch.",
    caption: "Kangaroo joey emerging from the pouch.",
    width: 1500,
    height: 2265,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-22",
    riskNotes: "CC0 — public-domain dedication; no attribution legally required. Attribution provided for transparency.",
  },
  {
    id: "koala-wikimedia-002",
    animalSlug: "koala",
    pagePath: "/animals/koala",
    role: "gallery",
    localPath: "/images/animals/koala/koala-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Koala_and_joey.jpg",
    author: "Benjamint444",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Benjamint444, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Adult koala (Phascolarctos cinereus) carrying a joey on her back in a tree.",
    caption: "Koala with a joey on her back.",
    width: 1200,
    height: 1347,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-22",
    riskNotes: "Share-alike license — derivative works (e.g. WebP conversion, crops) must also be released under the same or compatible CC BY-SA terms.",
  },
  {
    id: "koala-wikimedia-003",
    animalSlug: "koala",
    pagePath: "/animals/koala",
    role: "gallery",
    localPath: "/images/animals/koala/koala-gallery-2.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:The_World_Factbook_-_Australia_-_Flickr_-_The_Central_Intelligence_Agency_(19).jpg",
    author: "The Central Intelligence Agency",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by The Central Intelligence Agency, Public domain, via Wikimedia Commons.",
    alt: "Wild koala (Phascolarctos cinereus) photographed in Australia.",
    caption: "Wild koala (Phascolarctos cinereus) in Australian eucalyptus habitat.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-22",
    riskNotes: "Public domain. Attribution provided for transparency though not legally required.",
  },
];

/**
 * Animal slugs we intend to cover but have not yet sourced a verified image
 * for. Currently empty — every existing animal profile page has a verified
 * hero image. Add entries here when new animal pages are introduced.
 */
export const ANIMAL_IMAGE_TODOS: readonly string[] = [];

const HERO_BY_SLUG: Record<string, AnimalImage> = Object.fromEntries(
  ANIMAL_IMAGES.filter((img) => img.role === "hero").map((img) => [
    img.animalSlug,
    img,
  ]),
);

const GALLERY_BY_SLUG: Record<string, AnimalImage[]> = ANIMAL_IMAGES.reduce(
  (acc, img) => {
    if (img.role !== "gallery") return acc;
    (acc[img.animalSlug] ??= []).push(img);
    return acc;
  },
  {} as Record<string, AnimalImage[]>,
);

/** Returns the verified hero image for an animal slug, or null if none. */
export function getAnimalImage(slug: string): AnimalImage | null {
  return HERO_BY_SLUG[slug] ?? null;
}

/** Alias of {@link getAnimalImage} for clarity at call sites that explicitly
 * want the hero. */
export function getAnimalHeroImage(slug: string): AnimalImage | null {
  return HERO_BY_SLUG[slug] ?? null;
}

/** Returns the verified gallery images for an animal slug, in insertion order.
 * Returns an empty array if none. */
export function getAnimalGalleryImages(slug: string): AnimalImage[] {
  return GALLERY_BY_SLUG[slug] ?? [];
}

/** Returns hero + gallery images for an animal, hero first. */
export function getAnimalImages(slug: string): AnimalImage[] {
  const hero = HERO_BY_SLUG[slug];
  const gallery = GALLERY_BY_SLUG[slug] ?? [];
  return hero ? [hero, ...gallery] : gallery;
}

/** Returns every image record across every animal. */
export function getAllAnimalImages(): readonly AnimalImage[] {
  return ANIMAL_IMAGES;
}

/** Absolute URL helper for OG image tags. */
export function getAnimalImageAbsoluteUrl(slug: string): string | null {
  const img = getAnimalImage(slug);
  if (!img) return null;
  return `https://faunahub.com${img.localPath}`;
}

/** Builds an OG image input for `buildArticleMetadata`. Returns undefined if no
 * image is available, so callers can spread it conditionally. */
export function getAnimalOgImage(
  slug: string,
):
  | { url: string; width: number; height: number; alt: string }
  | undefined {
  const img = getAnimalImage(slug);
  if (!img) return undefined;
  return {
    url: `https://faunahub.com${img.localPath}`,
    width: img.width,
    height: img.height,
    alt: img.alt,
  };
}
