/**
 * Dog and cat breed image metadata. Schema mirrors AnimalImage but adds
 * `breedSlug` and `species`, and the role is always `"hero"` (one image per
 * breed page).
 *
 * Every entry has been verified against the Wikimedia Commons MediaWiki API
 * (action=query, prop=imageinfo, extmetadata) for license + author on the
 * date in `verifiedAt`. Only Public domain, CC0, CC BY, and CC BY-SA images
 * are accepted — never CC BY-NC, CC BY-ND, GFDL-only, or unclear-license.
 */
export type BreedSpecies = "dog" | "cat";

export interface BreedImage {
  id: string;
  breedSlug: string;
  species: BreedSpecies;
  pagePath: string;
  role: "hero";
  localPath: string;
  sourceName: string;
  sourceUrl: string;
  author: string;
  license: string;
  licenseUrl: string;
  attribution: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
  commercialUseAllowed: boolean;
  modificationsAllowed: boolean;
  attributionRequired: boolean;
  verifiedAt: string;
  riskNotes: string;
}

export const BREED_IMAGES: readonly BreedImage[] = [
  {
    id: "dog-labrador-retriever-001",
    breedSlug: "labrador-retriever",
    species: "dog",
    pagePath: "/dogs/breeds/labrador-retriever",
    role: "hero",
    localPath: "/images/breeds/dogs/labrador-retriever/labrador-retriever-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Portrait_of_a_labrador_retriever.jpg",
    author: "Dktue",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Photo by Dktue, CC0, via Wikimedia Commons.",
    alt: "Portrait of an adult Labrador Retriever dog.",
    caption: "Labrador Retriever portrait.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-21",
    riskNotes: "CC0 public-domain dedication; attribution provided for transparency.",
  },
  {
    id: "dog-golden-retriever-001",
    breedSlug: "golden-retriever",
    species: "dog",
    pagePath: "/dogs/breeds/golden-retriever",
    role: "hero",
    localPath: "/images/breeds/dogs/golden-retriever/golden-retriever-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:D%C3%BClmen,_Hausd%C3%BClmen,_Golden_Retriever_--_2022_--_5530.jpg",
    author: "Dietmar Rabich",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Dietmar Rabich, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Adult Golden Retriever standing outdoors in Hausdülmen, Germany.",
    caption: "Golden Retriever standing outdoors.",
    width: 1500,
    height: 1500,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Photographer is a prolific Wikimedia contributor.",
  },
  {
    id: "dog-german-shepherd-001",
    breedSlug: "german-shepherd",
    species: "dog",
    pagePath: "/dogs/breeds/german-shepherd",
    role: "hero",
    localPath: "/images/breeds/dogs/german-shepherd/german-shepherd-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Adult_male_German_shepherd_dog_standing_at_the_beach.jpg",
    author: "gomagoti",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by gomagoti, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Adult male German Shepherd standing on a beach.",
    caption: "Adult German Shepherd on a beach.",
    width: 1500,
    height: 2250,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Breed identity clearly described in file metadata.",
  },
  {
    id: "dog-french-bulldog-001",
    breedSlug: "french-bulldog",
    species: "dog",
    pagePath: "/dogs/breeds/french-bulldog",
    role: "hero",
    localPath: "/images/breeds/dogs/french-bulldog/french-bulldog-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brindle_french_bulldog.jpg",
    author: "Arthur Brody",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Arthur Brody, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Brindle French Bulldog standing indoors.",
    caption: "Brindle French Bulldog.",
    width: 1500,
    height: 2251,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Brindle coat pattern and breed identity consistent with file description.",
  },
  {
    id: "dog-beagle-001",
    breedSlug: "beagle",
    species: "dog",
    pagePath: "/dogs/breeds/beagle",
    role: "hero",
    localPath: "/images/breeds/dogs/beagle/beagle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Beagle-Girl.JPG",
    author: "Floodmfx",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Floodmfx, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Adult Beagle dog photographed outdoors.",
    caption: "Adult Beagle.",
    width: 1500,
    height: 1125,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Breed identity consistent with file name and description.",
  },
  {
    id: "dog-poodle-001",
    breedSlug: "poodle",
    species: "dog",
    pagePath: "/dogs/breeds/poodle",
    role: "hero",
    localPath: "/images/breeds/dogs/poodle/poodle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Caniche_Kali.jpg",
    author: "Daremo TM",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Photo by Daremo TM, CC0, via Wikimedia Commons.",
    alt: "Adult Poodle (caniche) photographed outdoors.",
    caption: "Poodle (Caniche).",
    width: 1500,
    height: 2308,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-21",
    riskNotes: "CC0 public-domain dedication; attribution provided for transparency.",
  },
  {
    id: "dog-border-collie-001",
    breedSlug: "border-collie",
    species: "dog",
    pagePath: "/dogs/breeds/border-collie",
    role: "hero",
    localPath: "/images/breeds/dogs/border-collie/border-collie-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tarascon-sur-Ari%C3%A8ge_-_Conduite_de_troupeau_50.jpg",
    author: "Tylwyth Eldar",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Tylwyth Eldar, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Border Collie working with sheep near Tarascon-sur-Ariège, France.",
    caption: "Border Collie working a flock — a use the breed is widely associated with.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Working-dog context consistent with the breed's traditional role.",
  },
  {
    id: "dog-dachshund-001",
    breedSlug: "dachshund",
    species: "dog",
    pagePath: "/dogs/breeds/dachshund",
    role: "hero",
    localPath: "/images/breeds/dogs/dachshund/dachshund-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_Dachshund_on_the_streets_of_Budapest.jpg",
    author: "Slyronit",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Slyronit, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Dachshund on a city street in Budapest.",
    caption: "Dachshund.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Standard-build Dachshund consistent with breed.",
  },
  {
    id: "cat-maine-coon-001",
    breedSlug: "maine-coon",
    species: "cat",
    pagePath: "/cats/breeds/maine-coon",
    role: "hero",
    localPath: "/images/breeds/cats/maine-coon/maine-coon-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tortie_maine_coon_in_grass.jpg",
    author: "Cobaltxstrike",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Photo by Cobaltxstrike, CC0, via Wikimedia Commons.",
    alt: "Tortoiseshell Maine Coon cat sitting in grass.",
    caption: "Tortoiseshell Maine Coon.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-21",
    riskNotes: "CC0 public-domain dedication; attribution provided for transparency.",
  },
  {
    id: "cat-siamese-001",
    breedSlug: "siamese",
    species: "cat",
    pagePath: "/cats/breeds/siamese",
    role: "hero",
    localPath: "/images/breeds/cats/siamese/siamese-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_traditional_Seal_Point_Siamese_Cat.jpg",
    author: "Drokokieo",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Drokokieo, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Seal-point Siamese cat with blue eyes.",
    caption: "Seal-point Siamese cat — a traditional colour pattern for the breed.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Seal-point Siamese identity consistent with file description.",
  },
  {
    id: "cat-british-shorthair-001",
    breedSlug: "british-shorthair",
    species: "cat",
    pagePath: "/cats/breeds/british-shorthair",
    role: "hero",
    localPath: "/images/breeds/cats/british-shorthair/british-shorthair-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:British_shorthair_cat.jpg",
    author: "Blümchenkäfer",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Blümchenkäfer, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "British Shorthair cat with dense blue-grey fur.",
    caption: "British Shorthair.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Breed identity consistent with file description.",
  },
  {
    id: "cat-persian-cat-001",
    breedSlug: "persian-cat",
    species: "cat",
    pagePath: "/cats/breeds/persian-cat",
    role: "hero",
    localPath: "/images/breeds/cats/persian-cat/persian-cat-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Persian_Cat_Trio_(51016541380).jpg",
    author: "Reba Spike",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Reba Spike, CC BY 2.0, via Wikimedia Commons.",
    alt: "Three Persian cats resting together on a soft surface.",
    caption: "Persian cats — note the long coat and flat-faced profile.",
    width: 1500,
    height: 938,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Attribution-only license. Breed identity consistent with file description.",
  },
  {
    id: "cat-ragdoll-001",
    breedSlug: "ragdoll",
    species: "cat",
    pagePath: "/cats/breeds/ragdoll",
    role: "hero",
    localPath: "/images/breeds/cats/ragdoll/ragdoll-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_Lazy_Ragdoll_(Unsplash).jpg",
    author: "Josh Couch",
    license: "CC0",
    licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    attribution: "Photo by Josh Couch, CC0, via Wikimedia Commons.",
    alt: "Ragdoll cat lying down at rest.",
    caption: "Ragdoll cat.",
    width: 1500,
    height: 1000,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-05-21",
    riskNotes: "CC0 public-domain dedication; attribution provided for transparency.",
  },
  {
    id: "cat-bengal-cat-001",
    breedSlug: "bengal-cat",
    species: "cat",
    pagePath: "/cats/breeds/bengal-cat",
    role: "hero",
    localPath: "/images/breeds/cats/bengal-cat/bengal-cat-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:BEN_Bali-Bengal_Nina_Hagen_of_ZooCat%2ARU_(8642551491).jpg",
    author: "Nickolas Titkov",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Nickolas Titkov, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Bengal cat with spotted-rosetted coat.",
    caption: "Bengal cat.",
    width: 1500,
    height: 1105,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-05-21",
    riskNotes: "Share-alike license. Bengal breed identity consistent with file metadata.",
  },
];

const BY_KEY: Record<string, BreedImage> = Object.fromEntries(
  BREED_IMAGES.map((img) => [`${img.species}:${img.breedSlug}`, img]),
);

/** Returns the verified hero image for a (species, breedSlug) pair, or null. */
export function getBreedHeroImage(
  species: BreedSpecies,
  breedSlug: string,
): BreedImage | null {
  return BY_KEY[`${species}:${breedSlug}`] ?? null;
}

/** Returns every breed image record. */
export function getAllBreedImages(): readonly BreedImage[] {
  return BREED_IMAGES;
}

/** Builds an OG image input for `buildArticleMetadata` from a breed record. */
export function getBreedOgImage(
  species: BreedSpecies,
  breedSlug: string,
):
  | { url: string; width: number; height: number; alt: string }
  | undefined {
  const img = getBreedHeroImage(species, breedSlug);
  if (!img) return undefined;
  return {
    url: `https://faunahub.com${img.localPath}`,
    width: img.width,
    height: img.height,
    alt: img.alt,
  };
}
