import type { AnimalImage } from "./types";

/**
 * Images for the five animal profiles added in Compare Center batch three.
 *
 * Every entry was verified against the Wikimedia Commons MediaWiki API
 * (action=query, prop=imageinfo, extmetadata) on the verifiedAt date. Only
 * Public Domain, CC0, CC BY and CC BY-SA files are included; CC BY-NC,
 * CC BY-ND and GFDL-only candidates are rejected by the acquisition gate.
 *
 * Long side is capped at 1600px. Captions were reviewed image by image rather
 * than generated: the damselfly gallery was deliberately swapped to a second
 * family so the page does not imply every damselfly resembles a broad-winged
 * demoiselle, and both mule images disclose the working harness because a mule
 * exists only as a human-bred hybrid and has no wild form to photograph.
 */
export const COMPARE_BATCH_THREE_IMAGES: readonly AnimalImage[] = [
  {
    id: "damselfly-wikimedia-002",
    animalSlug: "damselfly",
    pagePath: "/animals/damselfly",
    role: "gallery",
    localPath: "/images/animals/damselfly/damselfly-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Coenagrionidae2.jpg",
    author: "Richard Bartz , Munich aka Makro Freak Image:MFB.jpg",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5",
    attribution: "Photo by Richard Bartz , Munich aka Makro Freak Image:MFB.jpg, CC BY-SA 2.5, via Wikimedia Commons.",
    alt: "Blue and black damselfly of the family Coenagrionidae perched on vegetation, showing a very slender abdomen and widely separated eyes.",
    caption: "A narrow-winged damselfly in the family Coenagrionidae, the group most people picture. The widely separated eyes are a reliable damselfly feature.",
    width: 1062,
    height: 1600,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 2.5. Wild animal. Wild insect from a different family than the hero image, chosen so the page does not imply that all damselflies resemble the broad-winged demoiselles. Identified to family rather than species because the source description does not name one.",
  },
  {
    id: "damselfly-wikimedia-001",
    animalSlug: "damselfly",
    pagePath: "/animals/damselfly",
    role: "hero",
    localPath: "/images/animals/damselfly/damselfly-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Calopteryx_splendens_20050729_504.jpg",
    author: "Georg Slickers",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Georg Slickers, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Male banded demoiselle damselfly (Calopteryx splendens) resting on a leaf, showing a metallic blue body and dark wing bands held closed above the abdomen.",
    caption: "A male banded demoiselle. Damselflies hold their wings closed above the body at rest, which is the clearest way to separate them from dragonflies.",
    width: 1152,
    height: 864,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Wild animal. Wild insect. Calopteryx splendens is one of the broader-winged damselflies, so the wing-folding cue is shown clearly but the species is not typical of the whole suborder.",
  },
  {
    id: "mule-wikimedia-002",
    animalSlug: "mule",
    pagePath: "/animals/mule",
    role: "gallery",
    localPath: "/images/animals/mule/mule-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mule_in_Morocco.JPG",
    author: "Ab5602 ( talk )",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Ab5602 ( talk ), Public domain, via Wikimedia Commons.",
    alt: "Mule harnessed to a two-wheeled cart on a street in Morocco.",
    caption: "A mule in harness in Morocco. Mules remain widely used as draught and pack animals where terrain or cost makes vehicles impractical.",
    width: 1024,
    height: 768,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-08-04",
    riskNotes: "Domestic animal. Domestic working animal in harness. Lower resolution than the other images in this batch but sharp at display size; retained because it documents the working role honestly.",
  },
  {
    id: "mule-wikimedia-001",
    animalSlug: "mule",
    pagePath: "/animals/mule",
    role: "hero",
    localPath: "/images/animals/mule/mule-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mule_-_Kat%C4%B1r_1.JPG",
    author: "Zeynel Cebeci",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Zeynel Cebeci, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Working mule wearing a pack saddle standing on open ground, showing long ears, a horse-like body and a short upright mane.",
    caption: "A working mule carrying a pack saddle. Mules inherit long ears and sure-footedness from the donkey sire and body size from the horse dam.",
    width: 1600,
    height: 1015,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 4.0. Domestic animal. Domestic working animal in harness; the pack saddle is visible in the frame and is not cropped out. Mules exist only as human-bred hybrids, so no wild image of this animal is possible.",
  },
  {
    id: "osprey-wikimedia-002",
    animalSlug: "osprey",
    pagePath: "/animals/osprey",
    role: "gallery",
    localPath: "/images/animals/osprey/osprey-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Osprey_landing_in_the_nest_at_Camp_Echockotee.JPG",
    author: "159766 - dr. Tibor Duliskovich - http://www.duliskovich.com",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by 159766 - dr. Tibor Duliskovich - http://www.duliskovich.com, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Osprey landing at a large stick nest built on a dead tree, with a second osprey perched below.",
    caption: "An osprey landing at its nest on a dead tree in Florida. Ospreys build bulky stick nests in the open and reuse them across seasons.",
    width: 1600,
    height: 1476,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Wild animal. Wild nesting birds photographed at a distance. No handling or nest disturbance is implied, and this page gives no guidance on approaching nests.",
  },
  {
    id: "osprey-wikimedia-001",
    animalSlug: "osprey",
    pagePath: "/animals/osprey",
    role: "hero",
    localPath: "/images/animals/osprey/osprey-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:OspreyNASA.jpg",
    author: "NASA",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by NASA, Public domain, via Wikimedia Commons.",
    alt: "Osprey (Pandion haliaetus) in flight with wings raised, showing white underparts, dark carpal patches and a pale head with a dark eye stripe.",
    caption: "An osprey in flight. The white underparts, dark wrist patches and bowed wings distinguish it from the broad-winged eagles.",
    width: 1500,
    height: 1146,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-08-04",
    riskNotes: "Wild animal. Wild bird. Public-domain image from a United States federal agency; no captive or rehabilitation context indicated.",
  },
  {
    id: "rat-wikimedia-002",
    animalSlug: "rat",
    pagePath: "/animals/rat",
    role: "gallery",
    localPath: "/images/animals/rat/rat-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brown_Rat_Swimming_Across_Santragachi_Jheel_-_Howrah_2017-12-25_5624.JPG",
    author: "Biswarup Ganguly",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    attribution: "Photo by Biswarup Ganguly, CC BY 3.0, via Wikimedia Commons.",
    alt: "Brown rat (Rattus norvegicus) swimming across open water with only its head and back above the surface.",
    caption: "A brown rat swimming at Santragachi Jheel, Howrah, India. Brown rats swim and dive readily, which is one reason they colonise sewers and waterways so successfully.",
    width: 1600,
    height: 1064,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Wild animal. Free-living animal in a natural wetland. Behaviour shown (swimming) is documented for the species and is not a staged or trained action.",
  },
  {
    id: "rat-wikimedia-001",
    animalSlug: "rat",
    pagePath: "/animals/rat",
    role: "hero",
    localPath: "/images/animals/rat/rat-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rattus_norvegicus_-Fairlands_Valley_Park,_Stevenage,_England-8.jpg",
    author: "AnemoneProjectors ( talk )",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    attribution: "Photo by AnemoneProjectors ( talk ), CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Brown rat (Rattus norvegicus) foraging on bare ground, showing a blunt muzzle, small furred ears and coarse grey-brown fur.",
    caption: "A brown rat foraging in a public park in Stevenage, England. The blunt muzzle and small, thickly furred ears separate a rat from a mouse at close range.",
    width: 1600,
    height: 1199,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 2.0. Wild animal. Free-living animal photographed in an urban park, not a laboratory or captive strain. Species identification consistent with the file description.",
  },
  {
    id: "rook-wikimedia-002",
    animalSlug: "rook",
    pagePath: "/animals/rook",
    role: "gallery",
    localPath: "/images/animals/rook/rook-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Corvus_frugilegus_-Dartmoor,_Devon,_England-8.jpg",
    author: "Brian Snelson from Hockley, Essex, England",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    attribution: "Photo by Brian Snelson from Hockley, Essex, England, CC BY 2.0, via Wikimedia Commons.",
    alt: "Rook (Corvus frugilegus) walking across short grass in Devon, England, showing loose shaggy feathering on the upper legs.",
    caption: "A rook foraging on grassland in Dartmoor, Devon. The loose, shaggy thigh feathering gives rooks a baggy-trousered look that crows lack.",
    width: 1600,
    height: 1114,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Wild animal. Wild bird in open farmland habitat, by a different author from the hero image.",
  },
  {
    id: "rook-wikimedia-001",
    animalSlug: "rook",
    pagePath: "/animals/rook",
    role: "hero",
    localPath: "/images/animals/rook/rook-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rook_-_Corvus_frugilegus_(476445950).jpg",
    author: "John Haslam from Dornoch, Scotland",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    attribution: "Photo by John Haslam from Dornoch, Scotland, CC BY 2.0, via Wikimedia Commons.",
    alt: "Rook (Corvus frugilegus) standing on grass, showing glossy black plumage and the bare pale grey-white skin at the base of a long pointed bill.",
    caption: "A rook. The bare pale face at the base of the bill is the single most reliable way to tell an adult rook from a carrion crow.",
    width: 1600,
    height: 1069,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Wild animal. Wild bird. The diagnostic bare facial skin is clearly visible, which is why this image was chosen.",
  },
];
