import type { AnimalImage } from "./types";

/**
 * Images for the twelve animal profiles added in Compare Center batch two.
 *
 * Every entry was verified against the Wikimedia Commons MediaWiki API
 * (action=query, prop=imageinfo, extmetadata) on the verifiedAt date. Only
 * Public Domain, CC0, CC BY and CC BY-SA files are included; CC BY-NC,
 * CC BY-ND and GFDL-only candidates were rejected automatically.
 *
 * Captions and risk notes were reviewed image by image rather than generated.
 * That review changed three picks: a museum-mounted mouse specimen was
 * replaced with a live animal, a chinchilla gallery duplicate of the hero was
 * replaced, and a brown bear photographed at a Danish animal park was
 * re-flagged as captive after the automatic keyword screen missed the Danish
 * word "Dyrepark". Captive, domestic and feral contexts are stated in the
 * caption rather than left implied.
 */
export const COMPARE_BATCH_TWO_IMAGES: readonly AnimalImage[] = [
  {
    id: "alpaca-wikimedia-002",
    animalSlug: "alpaca",
    pagePath: "/animals/alpaca",
    role: "gallery",
    localPath: "/images/animals/alpaca/alpaca-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vicugna_pacos_-Hamerton_Zoo,_Cambridgeshire,_England-8a.jpg",
    author: "DANIEL HUNTLEY from FRANKFURT AM MAIN, GERMANY",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    attribution: "Photo by DANIEL HUNTLEY from FRANKFURT AM MAIN, GERMANY, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Small herd of alpacas of several fleece colours standing in a fenced paddock.",
    caption: "A managed alpaca herd. Alpacas are domestic animals and are kept in groups; this photograph was taken at a wildlife park in England.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 2.0. Photographed under human care. Taken at Hamerton Zoo Park, Cambridgeshire — captive/managed setting, disclosed in the caption.",
  },
  {
    id: "alpaca-wikimedia-001",
    animalSlug: "alpaca",
    pagePath: "/animals/alpaca",
    role: "hero",
    localPath: "/images/animals/alpaca/alpaca-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Unshorn_alpaca_grazing.jpg",
    author: "Johann Dréo from Château-Thierry, France",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    attribution: "Photo by Johann Dréo from Château-Thierry, France, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Unshorn black and white alpaca (Vicugna pacos) grazing on pasture, showing dense fleece and a short blunt face.",
    caption: "An unshorn alpaca grazing. The dense fleece and short, blunt face distinguish alpacas from the larger, longer-faced llama.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 2.0. Domestic animal. Domestic animal on managed pasture. Species identification unambiguous from fleece and facial proportions.",
  },
  {
    id: "brown-bear-wikimedia-002",
    animalSlug: "brown-bear",
    pagePath: "/animals/brown-bear",
    role: "gallery",
    localPath: "/images/animals/brown-bear/brown-bear-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brown_Bears_Nationalpark_Bayerischer_Wald_14.jpg",
    author: "Aconcagua ( talk )",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Aconcagua ( talk ), CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Two brown bears (Ursus arctos) interacting on snow, one with its mouth open.",
    caption: "Brown bears in an open-air enclosure at Bavarian Forest National Park, Germany. Their coat colour ranges from pale blonde to almost black despite the name.",
    width: 1600,
    height: 1063,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Photographed under human care. Open-air enclosure at a national park visitor facility, stated in the source description and disclosed in the caption.",
  },
  {
    id: "brown-bear-wikimedia-001",
    animalSlug: "brown-bear",
    pagePath: "/animals/brown-bear",
    role: "hero",
    localPath: "/images/animals/brown-bear/brown-bear-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brown_bear_(Ursus_arctos_arctos)_running.jpg",
    author: "Malene Thyssen",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    attribution: "Photo by Malene Thyssen, CC BY 2.5, via Wikimedia Commons.",
    alt: "Brown bear (Ursus arctos) running across grass beside water, showing the prominent shoulder hump and long claws.",
    caption: "Brown bear running. The muscular shoulder hump that powers digging is the most reliable structural cue separating brown bears from black bears. Photographed at a Danish animal park.",
    width: 1600,
    height: 1205,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Photographed under human care. Photographed at Skandinavisk Dyrepark, Denmark — a captive animal park. Captivity is disclosed; the automatic keyword screen missed the Danish word 'Dyrepark' and this was corrected in editorial review.",
  },
  {
    id: "chicken-wikimedia-002",
    animalSlug: "chicken",
    pagePath: "/animals/chicken",
    role: "gallery",
    localPath: "/images/animals/chicken/chicken-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gallus_gallus_domesticus_LC0262.jpg",
    author: "Jörg Hempel",
    license: "CC BY-SA 3.0 de",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
    attribution: "Photo by Jörg Hempel, CC BY-SA 3.0 de, via Wikimedia Commons.",
    alt: "Buff and white domestic hen (Gallus gallus domesticus) standing in grass with wings partly lowered.",
    caption: "A domestic hen foraging in grass. Chickens are ground-foraging omnivores that scratch for seeds and invertebrates.",
    width: 1600,
    height: 1600,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0 de. Domestic animal. Domestic bird outdoors. Breed is not asserted because the source description does not state one.",
  },
  {
    id: "chicken-wikimedia-001",
    animalSlug: "chicken",
    pagePath: "/animals/chicken",
    role: "hero",
    localPath: "/images/animals/chicken/chicken-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sitting_hen.jpeg",
    author: "Leoadec",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Leoadec, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Brown domestic hens (Gallus gallus domesticus) resting and standing on bare earth.",
    caption: "Domestic hens. Chickens descend primarily from the red junglefowl of South and Southeast Asia.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Domestic animal. Domestic birds in a managed outdoor setting. No husbandry, housing or production guidance is implied.",
  },
  {
    id: "chinchilla-wikimedia-002",
    animalSlug: "chinchilla",
    pagePath: "/animals/chinchilla",
    role: "gallery",
    localPath: "/images/animals/chinchilla/chinchilla-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chinchilla-Patchouli.jpg",
    author: "Salix",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Salix, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Domestic chinchilla with grey fur and prominent whiskers sitting upright.",
    caption: "Domestic chinchilla. Wild chinchillas are restricted to the Andes and are far rarer than the domestic population suggests.",
    width: 1095,
    height: 1055,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Photographed under human care. Domestic animal by a different author from the hero image, so the two photographs show different individuals.",
  },
  {
    id: "chinchilla-wikimedia-001",
    animalSlug: "chinchilla",
    pagePath: "/animals/chinchilla",
    role: "hero",
    localPath: "/images/animals/chinchilla/chinchilla-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Chinchilla_lanigera_11.jpg",
    author: "Luis Miguel Bugallo Sánchez ( Commons )( Galipedia )",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Luis Miguel Bugallo Sánchez ( Commons )( Galipedia ), CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Grey domestic chinchilla with large rounded ears and dense fur resting on a cloth surface.",
    caption: "A domestic chinchilla. The source describes this animal as a Chinchilla lanigera and C. brevicaudata cross, which is common among domestic chinchillas.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Photographed under human care. Domestic animal, and the source description explicitly records mixed lanigera/brevicaudata ancestry. The caption states this rather than presenting it as a pure wild-type Chinchilla lanigera.",
  },
  {
    id: "donkey-wikimedia-002",
    animalSlug: "donkey",
    pagePath: "/animals/donkey",
    role: "gallery",
    localPath: "/images/animals/donkey/donkey-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Equus_asinus_Kadzid%C5%82owo_001.jpg",
    author: "Lilly M",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Lilly M, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Three-week-old donkey foal (Equus asinus) standing on bare ground with woodland behind.",
    caption: "A three-week-old donkey foal in Poland. Foals are precocial and stand and follow the mother within hours of birth.",
    width: 1600,
    height: 1071,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Domestic animal. Domestic foal at a managed site. Age stated in the source description.",
  },
  {
    id: "donkey-wikimedia-001",
    animalSlug: "donkey",
    pagePath: "/animals/donkey",
    role: "hero",
    localPath: "/images/animals/donkey/donkey-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Equus_asinus.002_-_A_Coru%C3%B1a.jpg",
    author: "Fernando Losada Rodríguez",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Fernando Losada Rodríguez, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Domestic donkey (Equus asinus) with a dark coat and long ears standing behind a wire fence in Galicia, Spain.",
    caption: "A domestic donkey in Galicia, Spain. Donkeys descend from the African wild ass and have longer ears and a shorter mane than horses.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 4.0. Domestic animal. Domestic animal in a fenced enclosure; the fence is visible in the frame and is not obscured or cropped out.",
  },
  {
    id: "dromedary-wikimedia-002",
    animalSlug: "dromedary",
    pagePath: "/animals/dromedary",
    role: "gallery",
    localPath: "/images/animals/dromedary/dromedary-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Camelus_dromedarius_in_Nuweiba.jpg",
    author: "Florian Prischl",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Florian Prischl, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Dromedary camel (Camelus dromedarius) with a head rope standing on sand near desert hills in Nuweiba, Egypt.",
    caption: "A working dromedary in Nuweiba, Egypt. The single hump is the clearest difference from the two-humped Bactrian camel.",
    width: 1600,
    height: 1071,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Domestic animal. Working domestic animal wearing a head rope, visible in the frame. Within the species' long-established domestic range.",
  },
  {
    id: "dromedary-wikimedia-001",
    animalSlug: "dromedary",
    pagePath: "/animals/dromedary",
    role: "hero",
    localPath: "/images/animals/dromedary/dromedary-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:07._Camel_Profile,_near_Silverton,_NSW,_07.07.2007.jpg",
    author: "Jjron",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Jjron, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Dromedary camel (Camelus dromedarius) standing in arid scrub, showing a single hump and long legs.",
    caption: "A dromedary in arid country near Silverton, New South Wales, Australia — part of the feral population descended from imported working camels.",
    width: 1300,
    height: 1600,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Feral (introduced) population. Australia has no native camels; this animal belongs to the introduced feral population, which the caption states rather than implying a native range.",
  },
  {
    id: "ferret-wikimedia-002",
    animalSlug: "ferret",
    pagePath: "/animals/ferret",
    role: "gallery",
    localPath: "/images/animals/ferret/ferret-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ferret_2008.png",
    author: "Alfredo Gutiérrez",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Alfredo Gutiérrez, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Domestic ferret lying stretched out on a pale fabric surface, showing its long body and short legs.",
    caption: "The long, low body plan of a ferret suits following prey into burrows — the trait behind its historical working use.",
    width: 1600,
    height: 933,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 4.0. Photographed under human care. Domestic animal indoors. No handling, housing or care guidance is implied by the image or caption.",
  },
  {
    id: "ferret-wikimedia-001",
    animalSlug: "ferret",
    pagePath: "/animals/ferret",
    role: "hero",
    localPath: "/images/animals/ferret/ferret-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Fret_-_Mustela_putorius_furo.jpg",
    author: "Kizmo at Dutch Wikipedia Later versions were uploaded by Siebrand at nl.wikipedia .",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Kizmo at Dutch Wikipedia Later versions were uploaded by Siebrand at nl.wikipedia ., CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Domestic ferret (Mustela putorius furo) with polecat-patterned fur feeding from a shallow container indoors.",
    caption: "A domestic ferret showing the dark mask and pale guard hairs of the polecat colour pattern.",
    width: 1134,
    height: 678,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Photographed under human care. Domestic animal photographed indoors. Species identification unambiguous; ferrets are a domesticated form of the European polecat.",
  },
  {
    id: "gerbil-wikimedia-002",
    animalSlug: "gerbil",
    pagePath: "/animals/gerbil",
    role: "gallery",
    localPath: "/images/animals/gerbil/gerbil-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Agoutigerbilstanding.jpg",
    author: "Elina",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Elina, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Agouti-coloured Mongolian gerbil (Meriones unguiculatus) standing upright on its hind legs.",
    caption: "An agouti-coated Mongolian gerbil standing upright, the sandy colouring typical of the species in the wild.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Photographed under human care. Captive animal showing the wild-type agouti coat. Different individual and author from the hero image.",
  },
  {
    id: "gerbil-wikimedia-001",
    animalSlug: "gerbil",
    pagePath: "/animals/gerbil",
    role: "hero",
    localPath: "/images/animals/gerbil/gerbil-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Black_Meriones_unguiculatus.JPG",
    author: "Maria Krüger",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5",
    attribution: "Photo by Maria Krüger, CC BY-SA 2.5, via Wikimedia Commons.",
    alt: "Dark-coated Mongolian gerbil (Meriones unguiculatus) on wood-shaving bedding.",
    caption: "A Mongolian gerbil in a captive enclosure. Unlike most pet rodents, gerbils have a fully furred tail with a tufted tip.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 2.5. Photographed under human care. Captive animal on commercial bedding. Colour form is a domestic variety rather than the wild agouti coat.",
  },
  {
    id: "mouse-wikimedia-002",
    animalSlug: "mouse",
    pagePath: "/animals/mouse",
    role: "gallery",
    localPath: "/images/animals/mouse/mouse-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Apodemus_sylvaticus_in_tin.jpg",
    author: "Simon Eugster --– Simon / ?! 12:38, 2 July 2007 (UTC)",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Simon Eugster --– Simon / ?! 12:38, 2 July 2007 (UTC), CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Wood mouse (Apodemus sylvaticus) with large dark eyes and prominent ears sheltering inside a discarded metal tin.",
    caption: "A wood mouse, a different species from the house mouse and one of the commonest wild mice in Europe.",
    width: 1600,
    height: 1064,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Wild animal. This is Apodemus sylvaticus, NOT Mus musculus. The caption names the species explicitly so the page does not imply that all mice are house mice.",
  },
  {
    id: "mouse-wikimedia-001",
    animalSlug: "mouse",
    pagePath: "/animals/mouse",
    role: "hero",
    localPath: "/images/animals/mouse/mouse-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mus_musculus_2010.JPG",
    author: "4028mdk09",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by 4028mdk09, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "House mouse (Mus musculus) with grey-brown fur, large rounded ears and a long scaly tail.",
    caption: "A house mouse photographed in Heidelberg, Germany. Large ears and a long, sparsely haired tail distinguish mice from voles.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Wild animal. Live animal photographed outside a laboratory or museum context. An earlier candidate from a natural-history museum display was rejected during review because it was a mounted specimen rather than a live mouse.",
  },
  {
    id: "porpoise-wikimedia-002",
    animalSlug: "porpoise",
    pagePath: "/animals/porpoise",
    role: "gallery",
    localPath: "/images/animals/porpoise/porpoise-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Harbor_Porpoise_Fjord_Baelt_Denmark.JPG",
    author: "Rene at da.wikipedia",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Rene at da.wikipedia, Public domain, via Wikimedia Commons.",
    alt: "Harbour porpoise (Phocoena phocoena) breaking the surface of a seawater pool at a Danish marine centre.",
    caption: "Harbour porpoise at the Fjord&Bælt centre, Denmark. Wild harbour porpoises are difficult to photograph because they surface briefly and avoid boats.",
    width: 1600,
    height: 2400,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-08-04",
    riskNotes: "Photographed under human care. Same captive Danish facility as the hero image, by a different author. Captivity disclosed; no wild-behaviour claim is made from this image.",
  },
  {
    id: "porpoise-wikimedia-001",
    animalSlug: "porpoise",
    pagePath: "/animals/porpoise",
    role: "hero",
    localPath: "/images/animals/porpoise/porpoise-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Marsvin_(Phocoena_phocoena).jpg",
    author: "Malene Thyssen",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Malene Thyssen, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Harbour porpoise (Phocoena phocoena) leaping clear of the water, showing a blunt head with no beak and a small triangular dorsal fin.",
    caption: "A harbour porpoise leaping at a Danish marine research and rehabilitation centre. Note the blunt, beakless head — the clearest field difference from a dolphin.",
    width: 1381,
    height: 2072,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 3.0. Photographed under human care. Photographed at the Fjord&Bælt centre in Kerteminde, Denmark — a captive research facility. Captivity is disclosed because enclosure structures are visible and the behaviour is trained.",
  },
  {
    id: "puffin-wikimedia-002",
    animalSlug: "puffin",
    pagePath: "/animals/puffin",
    role: "gallery",
    localPath: "/images/animals/puffin/puffin-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Atlantic_Puffin_Fratercula_arctica.jpg",
    author: "Andreas Trepte",
    license: "CC BY-SA 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.5",
    attribution: "Photo by Andreas Trepte, CC BY-SA 2.5, via Wikimedia Commons.",
    alt: "Close-up head portrait of an Atlantic puffin (Fratercula arctica) showing the orange, yellow and blue-grey bill plates.",
    caption: "Close-up of an Atlantic puffin's breeding bill. Puffins are auks, not penguins, and they fly strongly.",
    width: 1600,
    height: 1143,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 2.5. Wild animal. Wild bird; species identification unambiguous from bill structure and facial pattern.",
  },
  {
    id: "puffin-wikimedia-001",
    animalSlug: "puffin",
    pagePath: "/animals/puffin",
    role: "hero",
    localPath: "/images/animals/puffin/puffin-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Puffin_Latrabjarg_Iceland.jpg",
    author: "Boaworm",
    license: "CC BY 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0",
    attribution: "Photo by Boaworm, CC BY 3.0, via Wikimedia Commons.",
    alt: "Atlantic puffin (Fratercula arctica) standing on a clifftop rock with wings spread, showing its brightly coloured breeding bill.",
    caption: "Atlantic puffin at Látrabjarg, Iceland. The vivid bill plates are grown for the breeding season and shed afterwards.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Wild animal. Wild clifftop colony at a well-known Icelandic seabird site. Species identification unambiguous.",
  },
  {
    id: "sea-lion-wikimedia-002",
    animalSlug: "sea-lion",
    pagePath: "/animals/sea-lion",
    role: "gallery",
    localPath: "/images/animals/sea-lion/sea-lion-gallery.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Steller_sealions_bc_1.jpg",
    author: "Yummifruitbat",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Yummifruitbat, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Steller sea lions (Eumetopias jubatus) resting on a rocky shoreline in British Columbia, Canada.",
    caption: "Steller sea lions on a rocky shore in British Columbia — a second otariid species, larger than the California sea lion.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 4.0. Wild animal. Shows Eumetopias jubatus rather than Zalophus; captioned as such so the page does not imply a single sea lion species. Wild haul-out.",
  },
  {
    id: "sea-lion-wikimedia-001",
    animalSlug: "sea-lion",
    pagePath: "/animals/sea-lion",
    role: "hero",
    localPath: "/images/animals/sea-lion/sea-lion-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Zalophus_californianus2.jpg",
    author: "Calibas",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Calibas, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Group of California sea lions (Zalophus californianus) hauled out on a coastal rock, several holding their heads and chests upright on rotated hind flippers.",
    caption: "California sea lions hauled out on a coastal rock. The upright posture is possible because eared seals can rotate their hind flippers forward.",
    width: 1600,
    height: 1095,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-08-04",
    riskNotes: "Share-alike license — derivative works must also be released under CC BY-SA 4.0. Wild animal. Species identification consistent with the file description (Zalophus californianus). Wild coastal haul-out; no captive context indicated.",
  },
];
