/**
 * Endangered-species image metadata.
 *
 * Each entry describes a photograph downloaded into the repository for a
 * detailed endangered-species profile. Every file was confirmed via the
 * Wikimedia Commons API to carry a commercially reusable, derivative-friendly
 * license — Public Domain, CC0, CC BY, or CC BY-SA only. CC BY-NC, CC BY-ND,
 * GFDL-only, and unclear-license files are excluded by editorial policy.
 *
 * Files were downloaded via Wikimedia's thumbnail service (a permitted
 * derivative), resized to a max width of 1600px, and converted to WebP with
 * sharp (quality 82) on the `verifiedAt` date. The conversion is itself a
 * permitted derivative under every license used below.
 */

export type EndangeredImageRole = "hero" | "gallery";

export interface EndangeredAnimalImage {
  /** Stable internal id. */
  id: string;
  /** Red List species slug this image belongs to. */
  speciesSlug: string;
  /** Page the image is displayed on. */
  pagePath: string;
  role: EndangeredImageRole;
  /** Public path under /public. */
  localPath: string;
  sourceName: string;
  /** Canonical file description page URL. */
  sourceUrl: string;
  author: string;
  license: string;
  /** License deed URL; empty for public-domain works. */
  licenseUrl: string;
  attribution: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
  commercialUseAllowed: boolean;
  modificationsAllowed: boolean;
  attributionRequired: boolean;
  verifiedAt: string;
  riskNotes: string;
}

const VERIFIED = "2026-06-16";

export const ENDANGERED_ANIMAL_IMAGES: readonly EndangeredAnimalImage[] = [
  // --- Sumatran orangutan ---
  {
    id: "sumatran-orangutan-hero",
    speciesSlug: "sumatran-orangutan",
    pagePath: "/endangered-animals/species/sumatran-orangutan",
    role: "hero",
    localPath:
      "/images/endangered-animals/sumatran-orangutan/sumatran-orangutan-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sumatran_Orangutan_(Pongo_abelii)_at_Perth_Zoo,_October_2024_18.jpg",
    author: "Calistemon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Calistemon, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Sumatran orangutan (Pongo abelii) with long shaggy orange-brown hair.",
    caption: "Sumatran orangutan (Pongo abelii).",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Photographed at Perth Zoo; species ID per the Wikimedia file description.",
  },
  {
    id: "sumatran-orangutan-gallery-1",
    speciesSlug: "sumatran-orangutan",
    pagePath: "/endangered-animals/species/sumatran-orangutan",
    role: "gallery",
    localPath:
      "/images/endangered-animals/sumatran-orangutan/sumatran-orangutan-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sumatran_Orangutan_(Pongo_abelii)_at_Perth_Zoo,_October_2024_02.jpg",
    author: "Calistemon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Calistemon, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Sumatran orangutan resting, showing its expressive face and long arms.",
    caption: "A Sumatran orangutan — Critically Endangered in the wild.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },

  // --- California condor ---
  {
    id: "california-condor-hero",
    speciesSlug: "california-condor",
    pagePath: "/endangered-animals/species/california-condor",
    role: "hero",
    localPath:
      "/images/endangered-animals/california-condor/california-condor-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Gymnogyps_californianus_(California_condor).jpg",
    author: "James St. John",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by James St. John, CC BY 2.0, via Wikimedia Commons.",
    alt: "California condor (Gymnogyps californianus) perched, showing its bald head and a numbered wing tag.",
    caption: "California condor (Gymnogyps californianus).",
    width: 1600,
    height: 1229,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes:
      "Attribution license. Wing tag visible — consistent with the intensively managed wild population.",
  },
  {
    id: "california-condor-gallery-1",
    speciesSlug: "california-condor",
    pagePath: "/endangered-animals/species/california-condor",
    role: "gallery",
    localPath:
      "/images/endangered-animals/california-condor/california-condor-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Gymnogyps_californianus_-Bitter_Creek_National_Wildlife_Refuge,_California,_USA_-flying-8.jpg",
    author: "U.S. Fish & Wildlife Service (Pacific Southwest Region)",
    license: "Public domain",
    licenseUrl: "",
    attribution:
      "Photo by the U.S. Fish & Wildlife Service (Pacific Southwest Region), public domain, via Wikimedia Commons.",
    alt: "California condor in flight over Bitter Creek National Wildlife Refuge, California.",
    caption: "A California condor in flight (U.S. Fish & Wildlife Service).",
    width: 1600,
    height: 1999,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: VERIFIED,
    riskNotes:
      "U.S. federal government work — public domain. No license restrictions.",
  },

  // --- Hawksbill turtle ---
  {
    id: "hawksbill-turtle-hero",
    speciesSlug: "hawksbill-turtle",
    pagePath: "/endangered-animals/species/hawksbill-turtle",
    role: "hero",
    localPath:
      "/images/endangered-animals/hawksbill-turtle/hawksbill-turtle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Tortuga_carey_(Eretmochelys_imbricata),_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-28,_DD_56.jpg",
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Diego Delso (delso.photo), CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Hawksbill turtle (Eretmochelys imbricata) swimming above a coral reef.",
    caption: "Hawksbill turtle (Eretmochelys imbricata).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes:
      "Share-alike license. Photographed in Ras Muhammad National Park, Egypt; species ID per file description.",
  },
  {
    id: "hawksbill-turtle-gallery-1",
    speciesSlug: "hawksbill-turtle",
    pagePath: "/endangered-animals/species/hawksbill-turtle",
    role: "gallery",
    localPath:
      "/images/endangered-animals/hawksbill-turtle/hawksbill-turtle-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Tortuga_carey_(Eretmochelys_imbricata),_islas_Ad_Dimaniyat,_Om%C3%A1n,_2024-08-13,_DD_68.jpg",
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Diego Delso (delso.photo), CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Hawksbill turtle near a reef in the Ad Dimaniyat Islands, Oman.",
    caption: "A hawksbill turtle on a tropical reef.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },

  // --- Whale shark ---
  {
    id: "whale-shark-hero",
    speciesSlug: "whale-shark",
    pagePath: "/endangered-animals/species/whale-shark",
    role: "hero",
    localPath: "/images/endangered-animals/whale-shark/whale-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Whale_Shark_AdF.jpg",
    author: "Arturo de Frias Marques",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Arturo de Frias Marques, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Whale shark (Rhincodon typus) swimming, showing its checkerboard of pale spots.",
    caption: "Whale shark (Rhincodon typus) — the largest living fish.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "whale-shark-gallery-1",
    speciesSlug: "whale-shark",
    pagePath: "/endangered-animals/species/whale-shark",
    role: "gallery",
    localPath:
      "/images/endangered-animals/whale-shark/whale-shark-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Whale_Shark_(Rhincodon_typus)_with_open_mouth_in_La_Paz,_Mexico.jpg",
    author: "Matthew T Rader",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Matthew T Rader (matthewtrader.com), CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Whale shark filter-feeding with its mouth open near La Paz, Mexico.",
    caption: "A whale shark filter-feeding.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },

  // --- Staghorn coral ---
  {
    id: "staghorn-coral-hero",
    speciesSlug: "staghorn-coral",
    pagePath: "/endangered-animals/species/staghorn-coral",
    role: "hero",
    localPath:
      "/images/endangered-animals/staghorn-coral/staghorn-coral-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Acropora_cervicornis_(Staghorn_Coral_-_Haiti).jpg",
    author: "Nick Hobgood",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Nick Hobgood, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Branching staghorn coral (Acropora cervicornis) colony on a reef in Haiti.",
    caption: "Staghorn coral (Acropora cervicornis).",
    width: 1600,
    height: 1202,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "staghorn-coral-gallery-1",
    speciesSlug: "staghorn-coral",
    pagePath: "/endangered-animals/species/staghorn-coral",
    role: "gallery",
    localPath:
      "/images/endangered-animals/staghorn-coral/staghorn-coral-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Restored_staghorn_coral_(Acropora_cervicornis)_at_Looe_Key_reef_(106714).jpg",
    author: "Lauren Toth, USGS",
    license: "Public domain",
    licenseUrl: "",
    attribution:
      "Photo by Lauren Toth, U.S. Geological Survey, public domain, via Wikimedia Commons.",
    alt: "Restored staghorn coral colony at Looe Key reef, Florida.",
    caption: "Restored staghorn coral at Looe Key reef (USGS).",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: VERIFIED,
    riskNotes:
      "U.S. federal government work — public domain. No license restrictions.",
  },

  // --- Axolotl ---
  {
    id: "axolotl-hero",
    speciesSlug: "axolotl",
    pagePath: "/endangered-animals/species/axolotl",
    role: "hero",
    localPath: "/images/endangered-animals/axolotl/axolotl-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Ambystoma_mexicanum_in_Ouwehands_Dierenpark_01.jpg",
    author: "FakirNL",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by FakirNL, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Axolotl (Ambystoma mexicanum) showing its feathery external gills.",
    caption: "Axolotl (Ambystoma mexicanum).",
    width: 1600,
    height: 1308,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "axolotl-gallery-1",
    speciesSlug: "axolotl",
    pagePath: "/endangered-animals/species/axolotl",
    role: "gallery",
    localPath: "/images/endangered-animals/axolotl/axolotl-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Ambystoma_mexicanum_(6337857516).jpg",
    author: "Ruben Undheim",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Ruben Undheim, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Axolotl resting on the bottom of an aquarium.",
    caption: "An axolotl — Critically Endangered in the wild.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "snow-leopard-hero",
    speciesSlug: "snow-leopard",
    pagePath: "/endangered-animals/species/snow-leopard",
    role: "hero",
    localPath: "/images/endangered-animals/snow-leopard/snow-leopard-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3APanthera_uncia_-_Zoo_Karlsruhe_03.jpg",
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by H. Zell, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Snow leopard (Panthera uncia) with thick pale spotted coat.",
    caption: "Snow leopard (Panthera uncia).",
    width: 1600,
    height: 1279,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "snow-leopard-gallery-1",
    speciesSlug: "snow-leopard",
    pagePath: "/endangered-animals/species/snow-leopard",
    role: "gallery",
    localPath: "/images/endangered-animals/snow-leopard/snow-leopard-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ASnow_leopard_portrait.jpg",
    author: "Tambako The Jaguar",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Tambako The Jaguar, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Close portrait of a snow leopard.",
    caption: "A snow leopard — Vulnerable on the IUCN Red List.",
    width: 1600,
    height: 1508,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "polar-bear-hero",
    speciesSlug: "polar-bear",
    pagePath: "/endangered-animals/species/polar-bear",
    role: "hero",
    localPath: "/images/endangered-animals/polar-bear/polar-bear-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3APolar_bear_(Ursus_maritimus)_in_the_drift_ice_region_north_of_Svalbard.jpg",
    author: "Andreas Weith",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Andreas Weith, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Polar bear (Ursus maritimus) on drift ice north of Svalbard.",
    caption: "Polar bear (Ursus maritimus) on Arctic sea ice.",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "polar-bear-gallery-1",
    speciesSlug: "polar-bear",
    pagePath: "/endangered-animals/species/polar-bear",
    role: "gallery",
    localPath: "/images/endangered-animals/polar-bear/polar-bear-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3APolar_Bear_AdF.jpg",
    author: "Arturo de Frias Marques",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Arturo de Frias Marques, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Polar bear standing on snow and ice.",
    caption: "A polar bear — Vulnerable, and dependent on sea ice.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "african-wild-dog-hero",
    speciesSlug: "african-wild-dog",
    pagePath: "/endangered-animals/species/african-wild-dog",
    role: "hero",
    localPath: "/images/endangered-animals/african-wild-dog/african-wild-dog-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAfrican_wild_dog_(Lycaon_pictus_pictus).jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "African wild dog (Lycaon pictus) with mottled coat and large rounded ears.",
    caption: "African wild dog (Lycaon pictus).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "african-wild-dog-gallery-1",
    speciesSlug: "african-wild-dog",
    pagePath: "/endangered-animals/species/african-wild-dog",
    role: "gallery",
    localPath: "/images/endangered-animals/african-wild-dog/african-wild-dog-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAfrican_wild_dog_(Lycaon_pictus_pictus)_head.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Head of an African wild dog showing its large ears.",
    caption: "An African wild dog — Endangered across much of its range.",
    width: 1600,
    height: 1168,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "giant-otter-hero",
    speciesSlug: "giant-otter",
    pagePath: "/endangered-animals/species/giant-otter",
    role: "hero",
    localPath: "/images/endangered-animals/giant-otter/giant-otter-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGiant_otters_(Pteronura_brasiliensis).jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Two giant otters (Pteronura brasiliensis) in the water.",
    caption: "Giant otters (Pteronura brasiliensis).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "giant-otter-gallery-1",
    speciesSlug: "giant-otter",
    pagePath: "/endangered-animals/species/giant-otter",
    role: "gallery",
    localPath: "/images/endangered-animals/giant-otter/giant-otter-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3A018_Giant_otter_eating_a_fish_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg",
    author: "Giles Laurent",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Giles Laurent, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Giant otter eating a fish in a Brazilian river.",
    caption: "A giant otter feeding — Endangered in the wild.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "andean-condor-hero",
    speciesSlug: "andean-condor",
    pagePath: "/endangered-animals/species/andean-condor",
    role: "hero",
    localPath: "/images/endangered-animals/andean-condor/andean-condor-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAndean_condor_(Vultur_gryphus)_male_in_flight_Torres_del_Paine.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Andean condor (Vultur gryphus) in flight over Torres del Paine.",
    caption: "Andean condor (Vultur gryphus) in flight.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "andean-condor-gallery-1",
    speciesSlug: "andean-condor",
    pagePath: "/endangered-animals/species/andean-condor",
    role: "gallery",
    localPath: "/images/endangered-animals/andean-condor/andean-condor-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAndean_condor_(Vultur_gryphus)_male_Farellones.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Male Andean condor showing its white neck ruff and head comb.",
    caption: "A male Andean condor.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "kakapo-hero",
    speciesSlug: "kakapo",
    pagePath: "/endangered-animals/species/kakapo",
    role: "hero",
    localPath: "/images/endangered-animals/kakapo/kakapo-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AKakapo_Sirocco_1.jpg",
    author: "Department of Conservation",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Department of Conservation, CC BY 2.0, via Wikimedia Commons.",
    alt: "Kākāpō (Strigops habroptila), a large green flightless parrot.",
    caption: "Kākāpō (Strigops habroptila) — the parrot Sirocco.",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Attribution license. Species ID per the Wikimedia file description.",
  },
  {
    id: "kakapo-gallery-1",
    speciesSlug: "kakapo",
    pagePath: "/endangered-animals/species/kakapo",
    role: "gallery",
    localPath: "/images/endangered-animals/kakapo/kakapo-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AStrigops_habroptila_ULaval_1.jpg",
    author: "Cephas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Cephas, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Kākāpō perched among foliage.",
    caption: "A kākāpō — Critically Endangered, managed on predator-free islands.",
    width: 1600,
    height: 1970,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "leatherback-turtle-hero",
    speciesSlug: "leatherback-turtle",
    pagePath: "/endangered-animals/species/leatherback-turtle",
    role: "hero",
    localPath: "/images/endangered-animals/leatherback-turtle/leatherback-turtle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ALeatherback_Sea_Turtle_(Dermochelys_coriacea)_(24622605130).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Leatherback turtle (Dermochelys coriacea) on a nesting beach.",
    caption: "Leatherback turtle (Dermochelys coriacea).",
    width: 1600,
    height: 1097,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "leatherback-turtle-gallery-1",
    speciesSlug: "leatherback-turtle",
    pagePath: "/endangered-animals/species/leatherback-turtle",
    role: "gallery",
    localPath: "/images/endangered-animals/leatherback-turtle/leatherback-turtle-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AClose_up_of_dermochelys_coriacea_leatherback_turtle.jpg",
    author: "Rabon David, U.S. Fish and Wildlife Service",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Rabon David, U.S. Fish and Wildlife Service, public domain, via Wikimedia Commons.",
    alt: "Close-up of a leatherback turtle's head and ridged shell.",
    caption: "A leatherback turtle (U.S. Fish & Wildlife Service).",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-06-16",
    riskNotes: "Public-domain work; no license restrictions. Species ID per the Wikimedia file description.",
  },
  {
    id: "great-white-shark-hero",
    speciesSlug: "great-white-shark",
    pagePath: "/endangered-animals/species/great-white-shark",
    role: "hero",
    localPath: "/images/endangered-animals/great-white-shark/great-white-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGreat_White_Shark_(Carcharodon_carcharias)_(32872319266).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Great white shark (Carcharodon carcharias) swimming near the surface.",
    caption: "Great white shark (Carcharodon carcharias).",
    width: 1600,
    height: 1038,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "great-white-shark-gallery-1",
    speciesSlug: "great-white-shark",
    pagePath: "/endangered-animals/species/great-white-shark",
    role: "gallery",
    localPath: "/images/endangered-animals/great-white-shark/great-white-shark-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGreat_White_Shark_(Carcharodon_carcharias).jpg",
    author: "Godot13",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Godot13, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Great white shark showing its conical snout.",
    caption: "A great white shark — Vulnerable on the IUCN Red List.",
    width: 1600,
    height: 1152,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
];

export function getEndangeredImages(
  speciesSlug: string,
): EndangeredAnimalImage[] {
  return ENDANGERED_ANIMAL_IMAGES.filter((i) => i.speciesSlug === speciesSlug);
}

export function getEndangeredHero(
  speciesSlug: string,
): EndangeredAnimalImage | undefined {
  return ENDANGERED_ANIMAL_IMAGES.find(
    (i) => i.speciesSlug === speciesSlug && i.role === "hero",
  );
}

export function getEndangeredGallery(
  speciesSlug: string,
): EndangeredAnimalImage[] {
  return ENDANGERED_ANIMAL_IMAGES.filter(
    (i) => i.speciesSlug === speciesSlug && i.role === "gallery",
  );
}
