/**
 * Endangered-species image metadata.
 *
 * Each entry describes a photograph downloaded into the repository for a
 * detailed endangered-species profile. Every file was confirmed via the
 * Wikimedia Commons API to carry a commercially reusable, derivative-friendly
 * license — Public Domain, CC0, CC BY, or CC BY-SA only. CC BY-NC, CC BY-ND,
 * GFDL-only, and unclear-license files are excluded by editorial policy.
 *
 * Files were downloaded via Wikimedia's thumbnail service (a permitted
 * derivative), resized to a max width of 1600px, and converted to WebP with
 * sharp (quality 82) on the `verifiedAt` date. The conversion is itself a
 * permitted derivative under every license used below.
 */

export type EndangeredImageRole = "hero" | "gallery";

export interface EndangeredAnimalImage {
  /** Stable internal id. */
  id: string;
  /** Red List species slug this image belongs to. */
  speciesSlug: string;
  /** Page the image is displayed on. */
  pagePath: string;
  role: EndangeredImageRole;
  /** Public path under /public. */
  localPath: string;
  sourceName: string;
  /** Canonical file description page URL. */
  sourceUrl: string;
  author: string;
  license: string;
  /** License deed URL; empty for public-domain works. */
  licenseUrl: string;
  attribution: string;
  alt: string;
  caption: string;
  width: number;
  height: number;
  commercialUseAllowed: boolean;
  modificationsAllowed: boolean;
  attributionRequired: boolean;
  verifiedAt: string;
  riskNotes: string;
}

const VERIFIED = "2026-06-16";

export const ENDANGERED_ANIMAL_IMAGES: readonly EndangeredAnimalImage[] = [
  // --- Sumatran orangutan ---
  {
    id: "sumatran-orangutan-hero",
    speciesSlug: "sumatran-orangutan",
    pagePath: "/endangered-animals/species/sumatran-orangutan",
    role: "hero",
    localPath:
      "/images/endangered-animals/sumatran-orangutan/sumatran-orangutan-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sumatran_Orangutan_(Pongo_abelii)_at_Perth_Zoo,_October_2024_18.jpg",
    author: "Calistemon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Calistemon, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Sumatran orangutan (Pongo abelii) with long shaggy orange-brown hair.",
    caption: "Sumatran orangutan (Pongo abelii).",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Photographed at Perth Zoo; species ID per the Wikimedia file description.",
  },
  {
    id: "sumatran-orangutan-gallery-1",
    speciesSlug: "sumatran-orangutan",
    pagePath: "/endangered-animals/species/sumatran-orangutan",
    role: "gallery",
    localPath:
      "/images/endangered-animals/sumatran-orangutan/sumatran-orangutan-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sumatran_Orangutan_(Pongo_abelii)_at_Perth_Zoo,_October_2024_02.jpg",
    author: "Calistemon",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Calistemon, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Sumatran orangutan resting, showing its expressive face and long arms.",
    caption: "A Sumatran orangutan — Critically Endangered in the wild.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },

  // --- California condor ---
  {
    id: "california-condor-hero",
    speciesSlug: "california-condor",
    pagePath: "/endangered-animals/species/california-condor",
    role: "hero",
    localPath:
      "/images/endangered-animals/california-condor/california-condor-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Gymnogyps_californianus_(California_condor).jpg",
    author: "James St. John",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by James St. John, CC BY 2.0, via Wikimedia Commons.",
    alt: "California condor (Gymnogyps californianus) perched, showing its bald head and a numbered wing tag.",
    caption: "California condor (Gymnogyps californianus).",
    width: 1600,
    height: 1229,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes:
      "Attribution license. Wing tag visible — consistent with the intensively managed wild population.",
  },
  {
    id: "california-condor-gallery-1",
    speciesSlug: "california-condor",
    pagePath: "/endangered-animals/species/california-condor",
    role: "gallery",
    localPath:
      "/images/endangered-animals/california-condor/california-condor-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Gymnogyps_californianus_-Bitter_Creek_National_Wildlife_Refuge,_California,_USA_-flying-8.jpg",
    author: "U.S. Fish & Wildlife Service (Pacific Southwest Region)",
    license: "Public domain",
    licenseUrl: "",
    attribution:
      "Photo by the U.S. Fish & Wildlife Service (Pacific Southwest Region), public domain, via Wikimedia Commons.",
    alt: "California condor in flight over Bitter Creek National Wildlife Refuge, California.",
    caption: "A California condor in flight (U.S. Fish & Wildlife Service).",
    width: 1600,
    height: 1999,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: VERIFIED,
    riskNotes:
      "U.S. federal government work — public domain. No license restrictions.",
  },

  // --- Hawksbill turtle ---
  {
    id: "hawksbill-turtle-hero",
    speciesSlug: "hawksbill-turtle",
    pagePath: "/endangered-animals/species/hawksbill-turtle",
    role: "hero",
    localPath:
      "/images/endangered-animals/hawksbill-turtle/hawksbill-turtle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Tortuga_carey_(Eretmochelys_imbricata),_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-28,_DD_56.jpg",
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Diego Delso (delso.photo), CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Hawksbill turtle (Eretmochelys imbricata) swimming above a coral reef.",
    caption: "Hawksbill turtle (Eretmochelys imbricata).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes:
      "Share-alike license. Photographed in Ras Muhammad National Park, Egypt; species ID per file description.",
  },
  {
    id: "hawksbill-turtle-gallery-1",
    speciesSlug: "hawksbill-turtle",
    pagePath: "/endangered-animals/species/hawksbill-turtle",
    role: "gallery",
    localPath:
      "/images/endangered-animals/hawksbill-turtle/hawksbill-turtle-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Tortuga_carey_(Eretmochelys_imbricata),_islas_Ad_Dimaniyat,_Om%C3%A1n,_2024-08-13,_DD_68.jpg",
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Diego Delso (delso.photo), CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Hawksbill turtle near a reef in the Ad Dimaniyat Islands, Oman.",
    caption: "A hawksbill turtle on a tropical reef.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },

  // --- Whale shark ---
  {
    id: "whale-shark-hero",
    speciesSlug: "whale-shark",
    pagePath: "/endangered-animals/species/whale-shark",
    role: "hero",
    localPath: "/images/endangered-animals/whale-shark/whale-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Whale_Shark_AdF.jpg",
    author: "Arturo de Frias Marques",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Arturo de Frias Marques, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Whale shark (Rhincodon typus) swimming, showing its checkerboard of pale spots.",
    caption: "Whale shark (Rhincodon typus) — the largest living fish.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "whale-shark-gallery-1",
    speciesSlug: "whale-shark",
    pagePath: "/endangered-animals/species/whale-shark",
    role: "gallery",
    localPath:
      "/images/endangered-animals/whale-shark/whale-shark-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Whale_Shark_(Rhincodon_typus)_with_open_mouth_in_La_Paz,_Mexico.jpg",
    author: "Matthew T Rader",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution:
      "Photo by Matthew T Rader (matthewtrader.com), CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Whale shark filter-feeding with its mouth open near La Paz, Mexico.",
    caption: "A whale shark filter-feeding.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },

  // --- Staghorn coral ---
  {
    id: "staghorn-coral-hero",
    speciesSlug: "staghorn-coral",
    pagePath: "/endangered-animals/species/staghorn-coral",
    role: "hero",
    localPath:
      "/images/endangered-animals/staghorn-coral/staghorn-coral-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Acropora_cervicornis_(Staghorn_Coral_-_Haiti).jpg",
    author: "Nick Hobgood",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Nick Hobgood, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Branching staghorn coral (Acropora cervicornis) colony on a reef in Haiti.",
    caption: "Staghorn coral (Acropora cervicornis).",
    width: 1600,
    height: 1202,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "staghorn-coral-gallery-1",
    speciesSlug: "staghorn-coral",
    pagePath: "/endangered-animals/species/staghorn-coral",
    role: "gallery",
    localPath:
      "/images/endangered-animals/staghorn-coral/staghorn-coral-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Restored_staghorn_coral_(Acropora_cervicornis)_at_Looe_Key_reef_(106714).jpg",
    author: "Lauren Toth, USGS",
    license: "Public domain",
    licenseUrl: "",
    attribution:
      "Photo by Lauren Toth, U.S. Geological Survey, public domain, via Wikimedia Commons.",
    alt: "Restored staghorn coral colony at Looe Key reef, Florida.",
    caption: "Restored staghorn coral at Looe Key reef (USGS).",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: VERIFIED,
    riskNotes:
      "U.S. federal government work — public domain. No license restrictions.",
  },

  // --- Axolotl ---
  {
    id: "axolotl-hero",
    speciesSlug: "axolotl",
    pagePath: "/endangered-animals/species/axolotl",
    role: "hero",
    localPath: "/images/endangered-animals/axolotl/axolotl-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Ambystoma_mexicanum_in_Ouwehands_Dierenpark_01.jpg",
    author: "FakirNL",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by FakirNL, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Axolotl (Ambystoma mexicanum) showing its feathery external gills.",
    caption: "Axolotl (Ambystoma mexicanum).",
    width: 1600,
    height: 1308,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "axolotl-gallery-1",
    speciesSlug: "axolotl",
    pagePath: "/endangered-animals/species/axolotl",
    role: "gallery",
    localPath: "/images/endangered-animals/axolotl/axolotl-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Ambystoma_mexicanum_(6337857516).jpg",
    author: "Ruben Undheim",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Ruben Undheim, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Axolotl resting on the bottom of an aquarium.",
    caption: "An axolotl — Critically Endangered in the wild.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: VERIFIED,
    riskNotes: "Share-alike license. Species ID per Wikimedia file description.",
  },
  {
    id: "snow-leopard-hero",
    speciesSlug: "snow-leopard",
    pagePath: "/endangered-animals/species/snow-leopard",
    role: "hero",
    localPath: "/images/endangered-animals/snow-leopard/snow-leopard-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3APanthera_uncia_-_Zoo_Karlsruhe_03.jpg",
    author: "H. Zell",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by H. Zell, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Snow leopard (Panthera uncia) with thick pale spotted coat.",
    caption: "Snow leopard (Panthera uncia).",
    width: 1600,
    height: 1279,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "snow-leopard-gallery-1",
    speciesSlug: "snow-leopard",
    pagePath: "/endangered-animals/species/snow-leopard",
    role: "gallery",
    localPath: "/images/endangered-animals/snow-leopard/snow-leopard-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ASnow_leopard_portrait.jpg",
    author: "Tambako The Jaguar",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Tambako The Jaguar, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Close portrait of a snow leopard.",
    caption: "A snow leopard — Vulnerable on the IUCN Red List.",
    width: 1600,
    height: 1508,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "polar-bear-hero",
    speciesSlug: "polar-bear",
    pagePath: "/endangered-animals/species/polar-bear",
    role: "hero",
    localPath: "/images/endangered-animals/polar-bear/polar-bear-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3APolar_bear_(Ursus_maritimus)_in_the_drift_ice_region_north_of_Svalbard.jpg",
    author: "Andreas Weith",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Andreas Weith, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Polar bear (Ursus maritimus) on drift ice north of Svalbard.",
    caption: "Polar bear (Ursus maritimus) on Arctic sea ice.",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "polar-bear-gallery-1",
    speciesSlug: "polar-bear",
    pagePath: "/endangered-animals/species/polar-bear",
    role: "gallery",
    localPath: "/images/endangered-animals/polar-bear/polar-bear-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3APolar_Bear_AdF.jpg",
    author: "Arturo de Frias Marques",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Arturo de Frias Marques, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Polar bear standing on snow and ice.",
    caption: "A polar bear — Vulnerable, and dependent on sea ice.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "african-wild-dog-hero",
    speciesSlug: "african-wild-dog",
    pagePath: "/endangered-animals/species/african-wild-dog",
    role: "hero",
    localPath: "/images/endangered-animals/african-wild-dog/african-wild-dog-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAfrican_wild_dog_(Lycaon_pictus_pictus).jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "African wild dog (Lycaon pictus) with mottled coat and large rounded ears.",
    caption: "African wild dog (Lycaon pictus).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "african-wild-dog-gallery-1",
    speciesSlug: "african-wild-dog",
    pagePath: "/endangered-animals/species/african-wild-dog",
    role: "gallery",
    localPath: "/images/endangered-animals/african-wild-dog/african-wild-dog-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAfrican_wild_dog_(Lycaon_pictus_pictus)_head.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Head of an African wild dog showing its large ears.",
    caption: "An African wild dog — Endangered across much of its range.",
    width: 1600,
    height: 1168,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "giant-otter-hero",
    speciesSlug: "giant-otter",
    pagePath: "/endangered-animals/species/giant-otter",
    role: "hero",
    localPath: "/images/endangered-animals/giant-otter/giant-otter-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGiant_otters_(Pteronura_brasiliensis).jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Two giant otters (Pteronura brasiliensis) in the water.",
    caption: "Giant otters (Pteronura brasiliensis).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "giant-otter-gallery-1",
    speciesSlug: "giant-otter",
    pagePath: "/endangered-animals/species/giant-otter",
    role: "gallery",
    localPath: "/images/endangered-animals/giant-otter/giant-otter-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3A018_Giant_otter_eating_a_fish_in_Encontro_das_%C3%81guas_State_Park_Photo_by_Giles_Laurent.jpg",
    author: "Giles Laurent",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Giles Laurent, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Giant otter eating a fish in a Brazilian river.",
    caption: "A giant otter feeding — Endangered in the wild.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "andean-condor-hero",
    speciesSlug: "andean-condor",
    pagePath: "/endangered-animals/species/andean-condor",
    role: "hero",
    localPath: "/images/endangered-animals/andean-condor/andean-condor-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAndean_condor_(Vultur_gryphus)_male_in_flight_Torres_del_Paine.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Andean condor (Vultur gryphus) in flight over Torres del Paine.",
    caption: "Andean condor (Vultur gryphus) in flight.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "andean-condor-gallery-1",
    speciesSlug: "andean-condor",
    pagePath: "/endangered-animals/species/andean-condor",
    role: "gallery",
    localPath: "/images/endangered-animals/andean-condor/andean-condor-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AAndean_condor_(Vultur_gryphus)_male_Farellones.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Male Andean condor showing its white neck ruff and head comb.",
    caption: "A male Andean condor.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "kakapo-hero",
    speciesSlug: "kakapo",
    pagePath: "/endangered-animals/species/kakapo",
    role: "hero",
    localPath: "/images/endangered-animals/kakapo/kakapo-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AKakapo_Sirocco_1.jpg",
    author: "Department of Conservation",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Department of Conservation, CC BY 2.0, via Wikimedia Commons.",
    alt: "Kākāpō (Strigops habroptila), a large green flightless parrot.",
    caption: "Kākāpō (Strigops habroptila) — the parrot Sirocco.",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Attribution license. Species ID per the Wikimedia file description.",
  },
  {
    id: "kakapo-gallery-1",
    speciesSlug: "kakapo",
    pagePath: "/endangered-animals/species/kakapo",
    role: "gallery",
    localPath: "/images/endangered-animals/kakapo/kakapo-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AStrigops_habroptila_ULaval_1.jpg",
    author: "Cephas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Cephas, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Kākāpō perched among foliage.",
    caption: "A kākāpō — Critically Endangered, managed on predator-free islands.",
    width: 1600,
    height: 1970,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "leatherback-turtle-hero",
    speciesSlug: "leatherback-turtle",
    pagePath: "/endangered-animals/species/leatherback-turtle",
    role: "hero",
    localPath: "/images/endangered-animals/leatherback-turtle/leatherback-turtle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ALeatherback_Sea_Turtle_(Dermochelys_coriacea)_(24622605130).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Leatherback turtle (Dermochelys coriacea) on a nesting beach.",
    caption: "Leatherback turtle (Dermochelys coriacea).",
    width: 1600,
    height: 1097,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "leatherback-turtle-gallery-1",
    speciesSlug: "leatherback-turtle",
    pagePath: "/endangered-animals/species/leatherback-turtle",
    role: "gallery",
    localPath: "/images/endangered-animals/leatherback-turtle/leatherback-turtle-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AClose_up_of_dermochelys_coriacea_leatherback_turtle.jpg",
    author: "Rabon David, U.S. Fish and Wildlife Service",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Rabon David, U.S. Fish and Wildlife Service, public domain, via Wikimedia Commons.",
    alt: "Close-up of a leatherback turtle's head and ridged shell.",
    caption: "A leatherback turtle (U.S. Fish & Wildlife Service).",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-06-16",
    riskNotes: "Public-domain work; no license restrictions. Species ID per the Wikimedia file description.",
  },
  {
    id: "great-white-shark-hero",
    speciesSlug: "great-white-shark",
    pagePath: "/endangered-animals/species/great-white-shark",
    role: "hero",
    localPath: "/images/endangered-animals/great-white-shark/great-white-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGreat_White_Shark_(Carcharodon_carcharias)_(32872319266).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Great white shark (Carcharodon carcharias) swimming near the surface.",
    caption: "Great white shark (Carcharodon carcharias).",
    width: 1600,
    height: 1038,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "great-white-shark-gallery-1",
    speciesSlug: "great-white-shark",
    pagePath: "/endangered-animals/species/great-white-shark",
    role: "gallery",
    localPath: "/images/endangered-animals/great-white-shark/great-white-shark-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGreat_White_Shark_(Carcharodon_carcharias).jpg",
    author: "Godot13",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Godot13, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Great white shark showing its conical snout.",
    caption: "A great white shark — Vulnerable on the IUCN Red List.",
    width: 1600,
    height: 1152,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "okapi-hero",
    speciesSlug: "okapi",
    pagePath: "/endangered-animals/species/okapi",
    role: "hero",
    localPath: "/images/endangered-animals/okapi/okapi-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AOkapi_(Okapia_johnstoni).jpg",
    author: "k7hpn",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by k7hpn, CC BY 2.0, via Wikimedia Commons.",
    alt: "Okapi (Okapia johnstoni) showing its dark body and striped hindquarters.",
    caption: "Okapi (Okapia johnstoni).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Attribution license. Species ID per the Wikimedia file description.",
  },
  {
    id: "okapi-gallery-1",
    speciesSlug: "okapi",
    pagePath: "/endangered-animals/species/okapi",
    role: "gallery",
    localPath: "/images/endangered-animals/okapi/okapi-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AOkapi_and_son.jpg",
    author: "Alan Eng from Brussels, Belgium",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Alan Eng from Brussels, Belgium, CC BY 2.0, via Wikimedia Commons.",
    alt: "Okapi adult with a young calf.",
    caption: "An okapi and calf — Endangered in the wild.",
    width: 1600,
    height: 1170,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Attribution license. Species ID per the Wikimedia file description.",
  },
  {
    id: "bonobo-hero",
    speciesSlug: "bonobo",
    pagePath: "/endangered-animals/species/bonobo",
    role: "hero",
    localPath: "/images/endangered-animals/bonobo/bonobo-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3APan_paniscus_(female).jpg",
    author: "Hans Hillewaert",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Hans Hillewaert, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Bonobo (Pan paniscus), a great ape of the Congo Basin.",
    caption: "Bonobo (Pan paniscus).",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "bonobo-gallery-1",
    speciesSlug: "bonobo",
    pagePath: "/endangered-animals/species/bonobo",
    role: "gallery",
    localPath: "/images/endangered-animals/bonobo/bonobo-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ABonobo_(Pan_paniscus)_at_Lola_Ya_Bonobo_-_3.JPG",
    author: "Christina Bergey",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Christina Bergey, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Bonobo at a sanctuary in the Democratic Republic of the Congo.",
    caption: "A bonobo — Endangered, found only south of the Congo River.",
    width: 1600,
    height: 1236,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "proboscis-monkey-hero",
    speciesSlug: "proboscis-monkey",
    pagePath: "/endangered-animals/species/proboscis-monkey",
    role: "hero",
    localPath: "/images/endangered-animals/proboscis-monkey/proboscis-monkey-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AProboscis_monkey_(Nasalis_larvatus)_male_Labuk_Bay.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Male proboscis monkey (Nasalis larvatus) with its distinctive large nose.",
    caption: "Proboscis monkey (Nasalis larvatus).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "proboscis-monkey-gallery-1",
    speciesSlug: "proboscis-monkey",
    pagePath: "/endangered-animals/species/proboscis-monkey",
    role: "gallery",
    localPath: "/images/endangered-animals/proboscis-monkey/proboscis-monkey-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AProboscis_monkey_(Nasalis_larvatus)_female_and_baby.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Female proboscis monkey with a baby.",
    caption: "A proboscis monkey and infant — endemic to Borneo.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "dhole-hero",
    speciesSlug: "dhole",
    pagePath: "/endangered-animals/species/dhole",
    role: "hero",
    localPath: "/images/endangered-animals/dhole/dhole-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ADhole(Asiatic_wild_dog).jpg",
    author: "Davidvraju",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Davidvraju, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Dhole (Cuon alpinus), an Asiatic wild dog with a rusty-red coat.",
    caption: "Dhole (Cuon alpinus).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "dhole-gallery-1",
    speciesSlug: "dhole",
    pagePath: "/endangered-animals/species/dhole",
    role: "gallery",
    localPath: "/images/endangered-animals/dhole/dhole-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ADholes_Cuon_alpinus_hunting_a_Spotted_Deer_image_by_Raju_Kasambe_DSCN4225_01.jpg",
    author: "Dr. Raju Kasambe",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Dr. Raju Kasambe, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Dholes hunting cooperatively in an Indian forest.",
    caption: "Dholes hunting as a pack — Endangered across Asia.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "gharial-hero",
    speciesSlug: "gharial",
    pagePath: "/endangered-animals/species/gharial",
    role: "hero",
    localPath: "/images/endangered-animals/gharial/gharial-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGharial_(Gavialis_gangeticus)_male.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Male gharial (Gavialis gangeticus) showing its narrow snout and bulbous tip.",
    caption: "Gharial (Gavialis gangeticus).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "gharial-gallery-1",
    speciesSlug: "gharial",
    pagePath: "/endangered-animals/species/gharial",
    role: "gallery",
    localPath: "/images/endangered-animals/gharial/gharial-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3AGharial_(Gavialis_gangeticus)_female_and_juvenile.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Female gharial with juveniles.",
    caption: "A female gharial with young — Critically Endangered.",
    width: 1600,
    height: 672,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "shoebill-hero",
    speciesSlug: "shoebill",
    pagePath: "/endangered-animals/species/shoebill",
    role: "hero",
    localPath: "/images/endangered-animals/shoebill/shoebill-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ABalaeniceps_rex_(Schuhschnabel_-_Shoebill)_-_Weltvogelpark_Walsrode_2010-10.jpg",
    author: "Olaf Oliviero Riemer",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Olaf Oliviero Riemer, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Shoebill (Balaeniceps rex) showing its massive shoe-shaped bill.",
    caption: "Shoebill (Balaeniceps rex).",
    width: 1600,
    height: 1063,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "shoebill-gallery-1",
    speciesSlug: "shoebill",
    pagePath: "/endangered-animals/species/shoebill",
    role: "gallery",
    localPath: "/images/endangered-animals/shoebill/shoebill-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File%3ABalaeniceps_rex_-East_Africa-8.jpg",
    author: "Eric Inafuku",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Eric Inafuku, CC BY 2.0, via Wikimedia Commons.",
    alt: "Shoebill standing in East African wetland.",
    caption: "A shoebill in wetland habitat — Vulnerable.",
    width: 1600,
    height: 1308,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-16",
    riskNotes: "Attribution license. Species ID per the Wikimedia file description.",
  },
  {
    id: "amur-leopard-hero",
    speciesSlug: "amur-leopard",
    pagePath: "/endangered-animals/species/amur-leopard",
    role: "hero",
    localPath:
      "/images/endangered-animals/amur-leopard/amur-leopard-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Panthera_pardus_orientalis_Colchester_Zoo_(1).jpg",
    author: "William Warby",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by William Warby, CC BY 2.0, via Wikimedia Commons.",
    alt: "Amur leopard (Panthera pardus orientalis), a pale, thick-coated leopard with widely spaced rosettes.",
    caption: "Amur leopard (Panthera pardus orientalis); this individual is in a zoo.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Photographed at Colchester Zoo; species ID per the Wikimedia file description.",
  },
  {
    id: "amur-leopard-gallery-1",
    speciesSlug: "amur-leopard",
    pagePath: "/endangered-animals/species/amur-leopard",
    role: "gallery",
    localPath:
      "/images/endangered-animals/amur-leopard/amur-leopard-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Amur_Leopard_Pittsburgh_Zoo.jpg",
    author: "Colin Hines www.ColinHinesPhotography.com",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5/",
    attribution: "Photo by Colin Hines www.ColinHinesPhotography.com, CC BY 2.5, via Wikimedia Commons.",
    alt: "An Amur leopard showing its long winter coat.",
    caption: "Amur leopard (Panthera pardus orientalis); a zoo individual.",
    width: 1600,
    height: 859,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Attribution license. Photographed at Pittsburgh Zoo; species ID per the Wikimedia file description.",
  },
  {
    id: "iberian-lynx-hero",
    speciesSlug: "iberian-lynx",
    pagePath: "/endangered-animals/species/iberian-lynx",
    role: "hero",
    localPath:
      "/images/endangered-animals/iberian-lynx/iberian-lynx-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Lince_ib%C3%A9rico_(Lynx_pardinus),_Almuradiel,_Ciudad_Real,_Espa%C3%B1a,_2021-12-19,_DD_07.jpg",
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Diego Delso, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Iberian lynx (Lynx pardinus), a spotted lynx with prominent ear tufts and cheek ruff.",
    caption: "Iberian lynx (Lynx pardinus), Spain.",
    width: 1600,
    height: 1600,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Wild individual in Spain; species ID per the Wikimedia file description.",
  },
  {
    id: "iberian-lynx-gallery-1",
    speciesSlug: "iberian-lynx",
    pagePath: "/endangered-animals/species/iberian-lynx",
    role: "gallery",
    localPath:
      "/images/endangered-animals/iberian-lynx/iberian-lynx-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Iberian_Lynx_stretching.jpg",
    author: "http://www.lynxexsitu.es",
    license: "CC BY 3.0 es",
    licenseUrl: "https://creativecommons.org/licenses/by/3.0/",
    attribution: "Photo by http://www.lynxexsitu.es, CC BY 3.0 es, via Wikimedia Commons.",
    alt: "An Iberian lynx stretching, showing its leopard-like spots and short tail.",
    caption: "Iberian lynx (Lynx pardinus); a conservation-breeding individual.",
    width: 975,
    height: 1462,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Attribution license. Image from a conservation-breeding programme; species ID per the Wikimedia file description.",
  },
  {
    id: "philippine-eagle-hero",
    speciesSlug: "philippine-eagle",
    pagePath: "/endangered-animals/species/philippine-eagle",
    role: "hero",
    localPath:
      "/images/endangered-animals/philippine-eagle/philippine-eagle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Pithecophaga_jefferyi,_Mindanao,_Philippines_1.jpg",
    author: "Francesco Veronesi from Italy",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Francesco Veronesi from Italy, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Philippine eagle (Pithecophaga jefferyi), a huge forest eagle with a shaggy crest.",
    caption: "Philippine eagle (Pithecophaga jefferyi), Mindanao.",
    width: 1600,
    height: 1066,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Mindanao, Philippines; species ID per the Wikimedia file description.",
  },
  {
    id: "philippine-eagle-gallery-1",
    speciesSlug: "philippine-eagle",
    pagePath: "/endangered-animals/species/philippine-eagle",
    role: "gallery",
    localPath:
      "/images/endangered-animals/philippine-eagle/philippine-eagle-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Pithecophaga_jefferyi_-Philippine_Eagle_Center,_Davao_City,_Philippines-8a.jpg",
    author: "Constantine Agustin from Manila, Philippines",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    attribution: "Photo by Constantine Agustin from Manila, Philippines, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "A Philippine eagle showing its powerful bill and crest.",
    caption: "Philippine eagle (Pithecophaga jefferyi) at the Philippine Eagle Center, Davao.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Photographed at the Philippine Eagle Center; species ID per the Wikimedia file description.",
  },
  {
    id: "addax-hero",
    speciesSlug: "addax",
    pagePath: "/endangered-animals/species/addax",
    role: "hero",
    localPath:
      "/images/endangered-animals/addax/addax-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Addax_(Addax_nasomaculatus)_female.jpg",
    author: "Charles J. Sharp",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by Charles J. Sharp, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Addax (Addax nasomaculatus), a pale desert antelope with long spiral horns.",
    caption: "Addax (Addax nasomaculatus), a critically endangered desert antelope.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "addax-gallery-1",
    speciesSlug: "addax",
    pagePath: "/endangered-animals/species/addax",
    role: "gallery",
    localPath:
      "/images/endangered-animals/addax/addax-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:A_big_male_Addax_showing_as_the_power_of_his_horns.jpg",
    author: "HaytemBouchri93",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    attribution: "Photo by HaytemBouchri93, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A male addax showing its long, twisted horns.",
    caption: "Male addax (Addax nasomaculatus) with its spiral horns.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Species ID per the Wikimedia file description.",
  },
  {
    id: "vaquita-hero",
    speciesSlug: "vaquita",
    pagePath: "/endangered-animals/species/vaquita",
    role: "hero",
    localPath:
      "/images/endangered-animals/vaquita/vaquita-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Vaquita4_Olson_NOAA.jpg",
    author: "Paula Olson, NOAA",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Paula Olson, NOAA (public domain), via Wikimedia Commons.",
    alt: "Vaquita (Phocoena sinus), a small porpoise with dark eye and lip patches, at the sea surface.",
    caption: "Vaquita (Phocoena sinus) — one of very few photographs of this rarely seen porpoise.",
    width: 1600,
    height: 786,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Public-domain work by a U.S. government (NOAA) photographer. Real photograph of a vaquita, which is very rarely seen; species ID per the Wikimedia file description and NOAA source.",
  },
  {
    id: "vaquita-gallery-1",
    speciesSlug: "vaquita",
    pagePath: "/endangered-animals/species/vaquita",
    role: "gallery",
    localPath:
      "/images/endangered-animals/vaquita/vaquita-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Vaquita2_Olson_NOAA.jpg",
    author: "Paula Olson, NOAA",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Paula Olson, NOAA (public domain), via Wikimedia Commons.",
    alt: "A vaquita surfacing in the Gulf of California.",
    caption: "Vaquita (Phocoena sinus) surfacing; photographed by NOAA researchers.",
    width: 860,
    height: 508,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Public-domain work by a U.S. government (NOAA) photographer; species ID per the Wikimedia file description and NOAA source.",
  },
  {
    id: "sumatran-rhinoceros-hero",
    speciesSlug: "sumatran-rhinoceros",
    pagePath: "/endangered-animals/species/sumatran-rhinoceros",
    role: "hero",
    localPath:
      "/images/endangered-animals/sumatran-rhinoceros/sumatran-rhinoceros-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sumatran_Rhinoceros_at_Sumatran_Rhino_Sanctuary_Lampung_Indonesia_2013.JPG",
    author: "26Isabella",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by 26Isabella, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Sumatran rhinoceros (Dicerorhinus sumatrensis), a small, hairy two-horned rhino.",
    caption: "Sumatran rhinoceros (Dicerorhinus sumatrensis) at the Sumatran Rhino Sanctuary, Indonesia.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Share-alike license — derivatives must use a compatible license. Photographed at the Sumatran Rhino Sanctuary; species ID per the Wikimedia file description.",
  },
  {
    id: "sumatran-rhinoceros-gallery-1",
    speciesSlug: "sumatran-rhinoceros",
    pagePath: "/endangered-animals/species/sumatran-rhinoceros",
    role: "gallery",
    localPath:
      "/images/endangered-animals/sumatran-rhinoceros/sumatran-rhinoceros-gallery-1.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Sumatran_Rhino_2.jpg",
    author: "Charles W. Hardin",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    attribution: "Photo by Charles W. Hardin, CC BY 2.0, via Wikimedia Commons.",
    alt: "A Sumatran rhinoceros showing its hairy hide and folded skin.",
    caption: "Sumatran rhinoceros (Dicerorhinus sumatrensis); a captive individual.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-06-23",
    riskNotes:
      "Attribution license. Captive individual; species ID per the Wikimedia file description.",
  },
];

export function getEndangeredImages(
  speciesSlug: string,
): EndangeredAnimalImage[] {
  return ENDANGERED_ANIMAL_IMAGES.filter((i) => i.speciesSlug === speciesSlug);
}

export function getEndangeredHero(
  speciesSlug: string,
): EndangeredAnimalImage | undefined {
  return ENDANGERED_ANIMAL_IMAGES.find(
    (i) => i.speciesSlug === speciesSlug && i.role === "hero",
  );
}

export function getEndangeredGallery(
  speciesSlug: string,
): EndangeredAnimalImage[] {
  return ENDANGERED_ANIMAL_IMAGES.filter(
    (i) => i.speciesSlug === speciesSlug && i.role === "gallery",
  );
}
