import type { AnimalImage } from "./types";

/**
 * Images for the design-polish + animal-expansion wave (2026-09-06).
 *
 * Every file was located through the Wikimedia Commons API, and its licence was
 * re-read from `extmetadata` at download time rather than trusted from the
 * search result. Only CC0, public-domain, CC BY and CC BY-SA files are listed;
 * NC, ND, GFDL-only and unclear-licence files were rejected outright.
 *
 * Species identity was NOT taken from filenames. Each file's own description
 * and category list was read for the binomial, and every image was then
 * inspected visually before it was accepted — a pass that caught, among other
 * things, two files titled "Common cuckoo" that actually depict Coracina
 * javensis, a "sea otter" frame in which the animal is a barely visible speck,
 * and a watermarked harvestman photograph.
 *
 * Where an animal was photographed in an aquarium or zoo, or where the subject
 * is a dead specimen rather than the living animal, the caption says so.
 *
 * Files were fetched through Commons' thumbnail service, resized to 1600 px
 * wide and converted to WebP (quality 82) with sharp. Both operations are
 * derivative works and are permitted under every licence used here.
 */
export const EXPANSION_WAVE_IMAGES: readonly AnimalImage[] = [
  {
    id: "narwhal-wikimedia-001",
    animalSlug: "narwhal",
    pagePath: "/animals/narwhal",
    role: "hero",
    localPath: "/images/animals/narwhal/narwhal-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Monodon_monoceros_pod.jpg",
    author: "Dr. Kristin Laidre, Polar Science Center, UW NOAA/OAR/OER",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Dr. Kristin Laidre, Polar Science Center, UW NOAA/OAR/OER, public domain, via Wikimedia Commons.",
    alt: "Aerial view of a pod of narwhals (Monodon monoceros) swimming at the surface off Greenland, several showing long tusks.",
    caption: "A pod of narwhals off Greenland; the long tusks of several animals are visible.",
    width: 1600,
    height: 1268,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "reindeer-wikimedia-001",
    animalSlug: "reindeer",
    pagePath: "/animals/reindeer",
    role: "hero",
    localPath: "/images/animals/reindeer/reindeer-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Reindeer_of_Mongolia_02.jpg",
    author: "Bernard Gagnon",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Bernard Gagnon, released under CC0, via Wikimedia Commons.",
    alt: "A reindeer (Rangifer tarandus) grazing on grass beside fallen timber near Lake Khövsgöl, Mongolia.",
    caption: "Reindeer (Rangifer tarandus) near Lake Khövsgöl, Mongolia.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "chipmunk-wikimedia-001",
    animalSlug: "chipmunk",
    pagePath: "/animals/chipmunk",
    role: "hero",
    localPath: "/images/animals/chipmunk/chipmunk-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Adult_Tamias_striatus_Eastern_Chipmunk.jpg",
    author: "Tyler Savitski",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Tyler Savitski, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "An adult eastern chipmunk (Tamias striatus) sitting on a fallen branch, showing the striped back.",
    caption: "Eastern chipmunk (Tamias striatus) on a fallen branch.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "prairie-dog-wikimedia-001",
    animalSlug: "prairie-dog",
    pagePath: "/animals/prairie-dog",
    role: "hero",
    localPath: "/images/animals/prairie-dog/prairie-dog-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Prairie_dog_(54121609869).jpg",
    author: "U.S. Fish and Wildlife Service - Midwest Region",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by U.S. Fish and Wildlife Service - Midwest Region, public domain, via Wikimedia Commons.",
    alt: "A black-tailed prairie dog standing alert on bare ground at Theodore Roosevelt National Park.",
    caption: "A prairie dog at Theodore Roosevelt National Park, North Dakota.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "groundhog-wikimedia-001",
    animalSlug: "groundhog",
    pagePath: "/animals/groundhog",
    role: "hero",
    localPath: "/images/animals/groundhog/groundhog-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Marmota_monax_UL_02.jpg",
    author: "Cephas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Cephas, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A groundhog (Marmota monax) resting on gravel, showing its heavy body and coarse grizzled fur.",
    caption: "Groundhog (Marmota monax) on the Laval University campus, Quebec.",
    width: 1600,
    height: 983,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "muskox-wikimedia-001",
    animalSlug: "muskox",
    pagePath: "/animals/muskox",
    role: "hero",
    localPath: "/images/animals/muskox/muskox-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Musk_ox_(54425862237).jpg",
    author: "BLM Alaska",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by BLM Alaska, public domain, via Wikimedia Commons.",
    alt: "Close view of two muskoxen (Ovibos moschatus) showing the heavy horn boss and long shaggy outer coat.",
    caption: "Two muskoxen photographed in Alaska; the long guard hairs and horn boss are clearly visible.",
    width: 1600,
    height: 1079,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "pika-wikimedia-001",
    animalSlug: "pika",
    pagePath: "/animals/pika",
    role: "hero",
    localPath: "/images/animals/pika/pika-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pika_-_Ochotona_princeps_(38240594396).jpg",
    author: "Yellowstone National Park by Jacob W. Frank",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Yellowstone National Park by Jacob W. Frank, public domain, via Wikimedia Commons.",
    alt: "A pika (Ochotona princeps) sitting among rocks, showing its round ears and compact tailless body.",
    caption: "A pika (Ochotona princeps) among talus rocks in Yellowstone National Park.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "impala-wikimedia-001",
    animalSlug: "impala",
    pagePath: "/animals/impala",
    role: "hero",
    localPath: "/images/animals/impala/impala-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aepyceros_melampus_petersi_%E2%99%82.jpg",
    author: "Hans Hillewaert",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Hans Hillewaert, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Portrait of a male black-faced impala (Aepyceros melampus petersi) showing the long ridged lyre-shaped horns.",
    caption: "A black-faced impala ram in Etosha National Park, Namibia. Only males carry horns.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "beluga-whale-wikimedia-001",
    animalSlug: "beluga-whale",
    pagePath: "/animals/beluga-whale",
    role: "hero",
    localPath: "/images/animals/beluga-whale/beluga-whale-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Belugaschule_1999-07-02.jpg",
    author: "Ansgar Walk",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    attribution: "Photo by Ansgar Walk, CC BY 2.5, via Wikimedia Commons.",
    alt: "Aerial view of a group of white beluga whales (Delphinapterus leucas) swimming near the surface.",
    caption: "A group of belugas in Hudson Bay near Churchill, Manitoba.",
    width: 1600,
    height: 1020,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "manatee-wikimedia-001",
    animalSlug: "manatee",
    pagePath: "/animals/manatee",
    role: "hero",
    localPath: "/images/animals/manatee/manatee-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Manatee_with_calf.PD_-_colour_corrected.jpg",
    author: "Galen Rathbun",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Galen Rathbun, public domain, via Wikimedia Commons.",
    alt: "A West Indian manatee (Trichechus manatus) swimming underwater with a calf close beside her.",
    caption: "A West Indian manatee with her calf.",
    width: 1600,
    height: 1049,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "sea-otter-wikimedia-001",
    animalSlug: "sea-otter",
    pagePath: "/animals/sea-otter",
    role: "hero",
    localPath: "/images/animals/sea-otter/sea-otter-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Adult_Sea_Otter_in_Morro_Bay.jpg",
    author: "Mike Baird from Morro Bay, USA",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    attribution: "Photo by Mike Baird from Morro Bay, USA, CC BY 2.0, via Wikimedia Commons.",
    alt: "An adult sea otter (Enhydra lutris) floating on its back at the surface of a calm bay.",
    caption: "An adult sea otter floating in Morro Bay, California.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "blue-whale-wikimedia-001",
    animalSlug: "blue-whale",
    pagePath: "/animals/blue-whale",
    role: "hero",
    localPath: "/images/animals/blue-whale/blue-whale-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Blue_whale_tail_fluke.JPG",
    author: "Shulman at English Wikipedia",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Shulman at English Wikipedia, public domain, via Wikimedia Commons.",
    alt: "The raised tail fluke of a blue whale (Balaenoptera musculus) above the sea surface, with islands behind.",
    caption: "A blue whale's tail fluke, Santa Barbara Channel, California.",
    width: 1600,
    height: 1099,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "sperm-whale-wikimedia-001",
    animalSlug: "sperm-whale",
    pagePath: "/animals/sperm-whale",
    role: "hero",
    localPath: "/images/animals/sperm-whale/sperm-whale-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:6(3)_Sperm_whale_(Physeter_macrocephalus).JPG",
    author: "Marion & Christoph Aistleitner",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Marion & Christoph Aistleitner, released under CC0, via Wikimedia Commons.",
    alt: "A sperm whale (Physeter macrocephalus) at the surface with its angled forward blow visible.",
    caption: "A sperm whale at the surface off Kaikoura, New Zealand.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "whale-shark-wikimedia-001",
    animalSlug: "whale-shark",
    pagePath: "/animals/whale-shark",
    role: "hero",
    localPath: "/images/animals/whale-shark/whale-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jonathan_Green_whale_shark.jpg",
    author: "Jonathan Green",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    attribution: "Photo by Jonathan Green, CC BY 4.0, via Wikimedia Commons.",
    alt: "A whale shark (Rhincodon typus) swimming in open blue water among smaller fish, showing its spotted back.",
    caption: "A whale shark in the Galápagos, near the Darwin and Wolf islets.",
    width: 1600,
    height: 1068,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "tiger-shark-wikimedia-001",
    animalSlug: "tiger-shark",
    pagePath: "/animals/tiger-shark",
    role: "hero",
    localPath: "/images/animals/tiger-shark/tiger-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tiger_shark.jpg",
    author: "Albert kok",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Albert kok, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A tiger shark (Galeocerdo cuvier) swimming in clear shallow water, showing its blunt snout and faint flank bars.",
    caption: "A tiger shark in the Bahamas; the flank bars fade as the shark matures.",
    width: 1600,
    height: 1187,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "bull-shark-wikimedia-001",
    animalSlug: "bull-shark",
    pagePath: "/animals/bull-shark",
    role: "hero",
    localPath: "/images/animals/bull-shark/bull-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bull_shark_(2007).jpg",
    author: "Albert Kok",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Albert Kok, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A bull shark (Carcharhinus leucas) seen head-on in shallow water, showing its stocky body and broad blunt snout.",
    caption: "A bull shark, showing the heavy build and blunt snout that give the species its name.",
    width: 1600,
    height: 1187,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "basking-shark-wikimedia-001",
    animalSlug: "basking-shark",
    pagePath: "/animals/basking-shark",
    role: "hero",
    localPath: "/images/animals/basking-shark/basking-shark-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cetorhinus_maximus_scotland.jpg",
    author: "Hermés from Perth, Scotland",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    attribution: "Photo by Hermés from Perth, Scotland, CC BY 2.0, via Wikimedia Commons.",
    alt: "A basking shark (Cetorhinus maximus) cruising at the surface with its dorsal fin above the water.",
    caption: "A basking shark off the Isle of Coll, Scotland.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "portuguese-man-o-war-wikimedia-001",
    animalSlug: "portuguese-man-o-war",
    pagePath: "/animals/portuguese-man-o-war",
    role: "hero",
    localPath: "/images/animals/portuguese-man-o-war/portuguese-man-o-war-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Caravela-portuguesa-APA_da_Costa_dos_Corais-Rafaelgivsilva(001).jpg",
    author: "Rafaelgivsilva",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Rafaelgivsilva, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A Portuguese man o' war (Physalia physalis) stranded on sand, showing the translucent gas-filled float with a pink and blue crest.",
    caption: "A Portuguese man o' war stranded on a Brazilian beach. Stranded animals and detached tentacles can still sting.",
    width: 1600,
    height: 1161,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "sand-dollar-wikimedia-001",
    animalSlug: "sand-dollar",
    pagePath: "/animals/sand-dollar",
    role: "hero",
    localPath: "/images/animals/sand-dollar/sand-dollar-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Eccentrik_Sand_Dollar_-_Dendraster_excentricus_(42662621301).jpg",
    author: "Björn S...",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    attribution: "Photo by Björn S..., CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "The bleached white skeleton, or test, of a sand dollar lying on wet sand, showing the five-petalled pattern.",
    caption: "The bleached test of a sand dollar (Dendraster excentricus) — this is the dead skeleton usually found on beaches, not the living animal, which is covered in dark moving spines.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use. Subject is the bleached test of a dead animal, which the caption states explicitly so the image is not read as the living animal.",
  },
  {
    id: "brittle-star-wikimedia-001",
    animalSlug: "brittle-star",
    pagePath: "/animals/brittle-star",
    role: "hero",
    localPath: "/images/animals/brittle-star/brittle-star-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Brittle_star_in_the_intertidal_zone_of_Glacier_Bay_(2f1b7bb9-1dd8-b71c-0796-d76a8824c5f1).jpg",
    author: "National Park Service",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by National Park Service, public domain, via Wikimedia Commons.",
    alt: "An orange brittle star on a rock in a tidal zone, showing a small central disc and five long thin arms.",
    caption: "An orange brittle star in the intertidal zone of Glacier Bay, Alaska. The small central disc and thin whip-like arms distinguish it from a true sea star.",
    width: 1600,
    height: 1063,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "kestrel-wikimedia-001",
    animalSlug: "kestrel",
    pagePath: "/animals/kestrel",
    role: "hero",
    localPath: "/images/animals/kestrel/kestrel-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Turmfalke_maennchen.jpg",
    author: "Andreas Trepte",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Andreas Trepte, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Two common kestrels (Falco tinnunculus) in flight beside a wooden post, wings spread.",
    caption: "Common kestrels (Falco tinnunculus) at a nest box post in Germany.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "barn-swallow-wikimedia-001",
    animalSlug: "barn-swallow",
    pagePath: "/animals/barn-swallow",
    role: "hero",
    localPath: "/images/animals/barn-swallow/barn-swallow-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Landsvale.jpg",
    author: "Malene Thyssen",
    license: "CC BY 2.5",
    licenseUrl: "https://creativecommons.org/licenses/by/2.5",
    attribution: "Photo by Malene Thyssen, CC BY 2.5, via Wikimedia Commons.",
    alt: "A barn swallow (Hirundo rustica) perched on a rail, showing its glossy blue back, rufous throat and long forked tail.",
    caption: "A barn swallow photographed in Denmark.",
    width: 1600,
    height: 1024,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "budgerigar-wikimedia-001",
    animalSlug: "budgerigar",
    pagePath: "/animals/budgerigar",
    role: "hero",
    localPath: "/images/animals/budgerigar/budgerigar-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Budgerigar_1_(20123571788).jpg",
    author: "Jim Bendon from Karratha, Australia",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    attribution: "Photo by Jim Bendon from Karratha, Australia, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "Two wild-type green and yellow budgerigars (Melopsittacus undulatus) perched on a branch, showing black barring on the wings.",
    caption: "Wild-type budgerigars in Australia. Wild birds are green and yellow with black barring; other colours are captive-bred varieties.",
    width: 1600,
    height: 1191,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "cockatiel-wikimedia-001",
    animalSlug: "cockatiel",
    pagePath: "/animals/cockatiel",
    role: "hero",
    localPath: "/images/animals/cockatiel/cockatiel-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cockatiel_2.jpg",
    author: "Jim Bendon from Karratha, Australia",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    attribution: "Photo by Jim Bendon from Karratha, Australia, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "A wild cockatiel (Nymphicus hollandicus) perched on a branch with its crest raised, showing the orange cheek patch.",
    caption: "A cockatiel in Australia, crest raised.",
    width: 1600,
    height: 1205,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "starling-wikimedia-001",
    animalSlug: "starling",
    pagePath: "/animals/starling",
    role: "hero",
    localPath: "/images/animals/starling/starling-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sturnus_vulgaris_-California-8.jpg",
    author: "Ingrid Taylar",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    attribution: "Photo by Ingrid Taylar, CC BY 2.0, via Wikimedia Commons.",
    alt: "A common starling (Sturnus vulgaris) standing on a rock, showing iridescent plumage marked with pale spots.",
    caption: "A common starling (Sturnus vulgaris) in California, showing the pale spotting of fresh plumage.",
    width: 1600,
    height: 1156,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "cuckoo-wikimedia-001",
    animalSlug: "cuckoo",
    pagePath: "/animals/cuckoo",
    role: "hero",
    localPath: "/images/animals/cuckoo/cuckoo-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Common_cuckoo_(Cuculus_canorus)_bird.jpg",
    author: "Shino jacob koottanad",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Shino jacob koottanad, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A common cuckoo (Cuculus canorus) perched on a branch, showing its grey upperparts and barred underparts.",
    caption: "A common cuckoo (Cuculus canorus) photographed in Kerala, India.",
    width: 1600,
    height: 1023,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "pheasant-wikimedia-001",
    animalSlug: "pheasant",
    pagePath: "/animals/pheasant",
    role: "hero",
    localPath: "/images/animals/pheasant/pheasant-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jagdfasan-Hahn_(M%C3%A4rz_2025)_2.jpg",
    author: "Romzig",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Romzig, released under CC0, via Wikimedia Commons.",
    alt: "A male common pheasant (Phasianus colchicus) standing in grass, showing its coppery body, green head and red facial wattles.",
    caption: "A male common pheasant. Females are mottled brown and much shorter-tailed.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "eurasian-jay-wikimedia-001",
    animalSlug: "eurasian-jay",
    pagePath: "/animals/eurasian-jay",
    role: "hero",
    localPath: "/images/animals/eurasian-jay/eurasian-jay-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Garrulus_glandarius_1_Luc_Viatour.jpg",
    author: "Luc Viatour",
    license: "CC BY-SA 3.0",
    licenseUrl: "http://creativecommons.org/licenses/by-sa/3.0/",
    attribution: "Photo by Luc Viatour, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A Eurasian jay (Garrulus glandarius) perched on a lichen-covered branch, showing its pinkish body and black moustache stripe.",
    caption: "A Eurasian jay (Garrulus glandarius).",
    width: 1600,
    height: 1093,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "cormorant-wikimedia-001",
    animalSlug: "cormorant",
    pagePath: "/animals/cormorant",
    role: "hero",
    localPath: "/images/animals/cormorant/cormorant-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Great_cormorant_(Phalacrocorax_carbo),_Travem%C3%BCnde.jpg",
    author: "Hobbyfotowiki",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Hobbyfotowiki, released under CC0, via Wikimedia Commons.",
    alt: "A great cormorant (Phalacrocorax carbo) standing on a rock beside water, showing its long neck and hooked bill.",
    caption: "A great cormorant (Phalacrocorax carbo) at Travemünde, Germany.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "great-crested-grebe-wikimedia-001",
    animalSlug: "great-crested-grebe",
    pagePath: "/animals/great-crested-grebe",
    role: "hero",
    localPath: "/images/animals/great-crested-grebe/great-crested-grebe-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Great_Crested_Grebe_(Podiceps_cristatus)_(14).JPG",
    author: "Ken Billington",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Ken Billington, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A great crested grebe (Podiceps cristatus) swimming with a striped chick beside it.",
    caption: "A great crested grebe with a chick, Rhine Delta, Austria.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "canada-goose-wikimedia-001",
    animalSlug: "canada-goose",
    pagePath: "/animals/canada-goose",
    role: "hero",
    localPath: "/images/animals/canada-goose/canada-goose-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Canada_Goose_(Branta_canadensis)_with_goslings.JPG",
    author: "The High Fin Sperm Whale",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by The High Fin Sperm Whale, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "An adult Canada goose (Branta canadensis) with goslings on a beach, showing the black neck and white chinstrap.",
    caption: "A Canada goose family at Cultus Lake, British Columbia.",
    width: 1600,
    height: 1063,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "northern-lapwing-wikimedia-001",
    animalSlug: "northern-lapwing",
    pagePath: "/animals/northern-lapwing",
    role: "hero",
    localPath: "/images/animals/northern-lapwing/northern-lapwing-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Vanellus_vanellus_-_Northern_lapwing,_Mersin_2016-12-11_03-6.jpg",
    author: "Zeynel Cebeci",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Zeynel Cebeci, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A northern lapwing (Vanellus vanellus) standing in short grass, showing its long upturned crest and dark iridescent back.",
    caption: "A northern lapwing (Vanellus vanellus) in the Göksu Delta, Turkey.",
    width: 1600,
    height: 1104,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "black-capped-chickadee-wikimedia-001",
    animalSlug: "black-capped-chickadee",
    pagePath: "/animals/black-capped-chickadee",
    role: "hero",
    localPath: "/images/animals/black-capped-chickadee/black-capped-chickadee-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Poecile_atricapillus_CT.jpg",
    author: "Cephas",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Cephas, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A black-capped chickadee (Poecile atricapillus) perched on a branch, showing its black cap and bib and white cheeks.",
    caption: "A black-capped chickadee at Cap Tourmente National Wildlife Area, Quebec.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "bearded-dragon-wikimedia-001",
    animalSlug: "bearded-dragon",
    pagePath: "/animals/bearded-dragon",
    role: "hero",
    localPath: "/images/animals/bearded-dragon/bearded-dragon-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pogona_vitticeps_2009_G1.jpg",
    author: "George Chernilevsky",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by George Chernilevsky, public domain, via Wikimedia Commons.",
    alt: "A central bearded dragon (Pogona vitticeps) resting on sand, showing the rows of soft spines along its flanks.",
    caption: "A central bearded dragon (Pogona vitticeps).",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "corn-snake-wikimedia-001",
    animalSlug: "corn-snake",
    pagePath: "/animals/corn-snake",
    role: "hero",
    localPath: "/images/animals/corn-snake/corn-snake-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Corn_Snake_Face.jpg",
    author: "Ethan Porcaro",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Ethan Porcaro, released under CC0, via Wikimedia Commons.",
    alt: "Close view of a corn snake's head (Pantherophis guttatus), showing the rounded pupil and orange-brown markings.",
    caption: "Close-up of a wild-type corn snake (Pantherophis guttatus).",
    width: 1600,
    height: 1205,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "kingsnake-wikimedia-001",
    animalSlug: "kingsnake",
    pagePath: "/animals/kingsnake",
    role: "hero",
    localPath: "/images/animals/kingsnake/kingsnake-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:KINGSNAKE,_COMMON_(lampropeltis_getula)_(6-4-09)_cerro_alto_c_g_rd,_slo_co,_ca_-02_(3599545824).jpg",
    author: "ALAN SCHMIERER",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by ALAN SCHMIERER, released under CC0, via Wikimedia Commons.",
    alt: "A common kingsnake (Lampropeltis getula) on gravel, showing its glossy dark body with pale bands.",
    caption: "A common kingsnake (Lampropeltis getula) in San Luis Obispo County, California.",
    width: 1600,
    height: 1078,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "hawksbill-turtle-wikimedia-001",
    animalSlug: "hawksbill-turtle",
    pagePath: "/animals/hawksbill-turtle",
    role: "hero",
    localPath: "/images/animals/hawksbill-turtle/hawksbill-turtle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tortuga_carey_(Eretmochelys_imbricata),_parque_nacional_Ras_Muhammad,_Egipto,_2022-03-28,_DD_28.jpg",
    author: "Diego Delso",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Diego Delso, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A hawksbill sea turtle (Eretmochelys imbricata) swimming over a coral reef, showing its pointed beak and overlapping shell scutes.",
    caption: "A hawksbill sea turtle over reef in Ras Muhammad National Park, Egypt.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "loggerhead-turtle-wikimedia-001",
    animalSlug: "loggerhead-turtle",
    pagePath: "/animals/loggerhead-turtle",
    role: "hero",
    localPath: "/images/animals/loggerhead-turtle/loggerhead-turtle-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Female_loggerhead_sea_turtle_caretta_caretta.jpg",
    author: "U.S. Fish and Wildlife Service",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by U.S. Fish and Wildlife Service, public domain, via Wikimedia Commons.",
    alt: "A loggerhead sea turtle (Caretta caretta) on a sandy beach at the water's edge, showing its large broad head.",
    caption: "A female loggerhead sea turtle on a nesting beach.",
    width: 1600,
    height: 1077,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "red-eared-slider-wikimedia-001",
    animalSlug: "red-eared-slider",
    pagePath: "/animals/red-eared-slider",
    role: "hero",
    localPath: "/images/animals/red-eared-slider/red-eared-slider-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Red-eared_sliders_(Trachemys_scripta_elegans).jpg",
    author: "George E. Koronaios",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by George E. Koronaios, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "Red-eared sliders (Trachemys scripta elegans) basking stacked together on rocks beside water.",
    caption: "Red-eared sliders basking at the National Garden of Athens, Greece — an introduced population well outside the species' native range.",
    width: 1600,
    height: 1083,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use. Free-living animals well outside the native range; the caption states that the population is introduced.",
  },
  {
    id: "common-frog-wikimedia-001",
    animalSlug: "common-frog",
    pagePath: "/animals/common-frog",
    role: "hero",
    localPath: "/images/animals/common-frog/common-frog-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2014.07.17.-29-Zadlitzgraben_Pressel--Grasfrosch-Weibchen.jpg",
    author: "Andreas Eichler",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Andreas Eichler, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A common frog (Rana temporaria) sitting among brown leaf litter, showing the dark patch behind the eye.",
    caption: "A female common frog (Rana temporaria) photographed in Germany.",
    width: 1600,
    height: 1121,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "leopard-frog-wikimedia-001",
    animalSlug: "leopard-frog",
    pagePath: "/animals/leopard-frog",
    role: "hero",
    localPath: "/images/animals/leopard-frog/leopard-frog-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Lithobates_pipiens_160225857.jpg",
    author: "David Bird",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by David Bird, released under CC0, via Wikimedia Commons.",
    alt: "A northern leopard frog (Lithobates pipiens) showing rounded dark spots with pale halos on a green back.",
    caption: "A northern leopard frog (Lithobates pipiens).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "slow-worm-wikimedia-001",
    animalSlug: "slow-worm",
    pagePath: "/animals/slow-worm",
    role: "hero",
    localPath: "/images/animals/slow-worm/slow-worm-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Anguis_fragilis_(curled_up).jpg",
    author: "Hans Hillewaert",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Hans Hillewaert, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A slow worm (Anguis fragilis) coiled on a stone, showing its smooth, glossy, limbless body.",
    caption: "A slow worm (Anguis fragilis) — a legless lizard, not a snake — near Nismes, Belgium.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "leopard-gecko-wikimedia-001",
    animalSlug: "leopard-gecko",
    pagePath: "/animals/leopard-gecko",
    role: "hero",
    localPath: "/images/animals/leopard-gecko/leopard-gecko-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Eublepharis_macularius_2009_G5.jpg",
    author: "George Chernilevsky",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by George Chernilevsky, public domain, via Wikimedia Commons.",
    alt: "A leopard gecko (Eublepharis macularius) on sand, showing its spotted pattern and thick tail.",
    caption: "A leopard gecko (Eublepharis macularius); the thick tail stores fat reserves.",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "blue-marlin-wikimedia-001",
    animalSlug: "blue-marlin",
    pagePath: "/animals/blue-marlin",
    role: "hero",
    localPath: "/images/animals/blue-marlin/blue-marlin-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Atlantic_blue_marlin.jpg",
    author: "NOAA",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by NOAA, public domain, via Wikimedia Commons.",
    alt: "An Atlantic blue marlin (Makaira nigricans) at the surface, showing its long bill and tall dorsal fin.",
    caption: "An Atlantic blue marlin (Makaira nigricans).",
    width: 1600,
    height: 1166,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "sailfish-wikimedia-001",
    animalSlug: "sailfish",
    pagePath: "/animals/sailfish",
    role: "hero",
    localPath: "/images/animals/sailfish/sailfish-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Istiophorus_platypterus_in_an_aquarium.jpg",
    author: "出羽雀台",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by 出羽雀台, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A sailfish (Istiophorus platypterus) swimming with its long bill and tall dorsal sail visible.",
    caption: "A sailfish photographed in an aquarium at Aquamarine Fukushima, Japan — sailfish are very rarely photographed underwater in the wild.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use. Animal photographed in an aquarium; the caption discloses this rather than implying a wild setting.",
  },
  {
    id: "pike-wikimedia-001",
    animalSlug: "pike",
    pagePath: "/animals/pike",
    role: "hero",
    localPath: "/images/animals/pike/pike-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Esox_lucius_Prague_Vltava_2.jpg",
    author: "Karelj",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Karelj, public domain, via Wikimedia Commons.",
    alt: "A northern pike (Esox lucius) in clear water, showing its long green body, pale flank spots and rearward fins.",
    caption: "A northern pike (Esox lucius) photographed at the Subaqueous Vltava aquarium exhibition in Prague.",
    width: 1600,
    height: 917,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use. Animal photographed in an aquarium; the caption discloses this rather than implying a wild setting.",
  },
  {
    id: "zebrafish-wikimedia-001",
    animalSlug: "zebrafish",
    pagePath: "/animals/zebrafish",
    role: "hero",
    localPath: "/images/animals/zebrafish/zebrafish-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Danio_rerio.JPG",
    author: "Pogrebnoj-Alexandroff",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Pogrebnoj-Alexandroff, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Zebrafish (Danio rerio) swimming, showing the horizontal blue-silver stripes along the body.",
    caption: "Zebrafish (Danio rerio); the horizontal stripes give the species its name.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "discus-wikimedia-001",
    animalSlug: "discus",
    pagePath: "/animals/discus",
    role: "hero",
    localPath: "/images/animals/discus/discus-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Symphysodon_discus_in_Minsk_Zoo.JPG",
    author: "Хомелка",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Хомелка, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "Several discus fish (Symphysodon) among aquatic plants, showing their flattened near-circular bodies.",
    caption: "Discus (Symphysodon) photographed at Minsk Zoo. Aquarium colour varieties are selectively bred and differ from wild fish.",
    width: 1600,
    height: 1071,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use. Animal photographed in a zoo aquarium; the caption discloses this rather than implying a wild setting.",
  },
  {
    id: "rainbow-trout-wikimedia-001",
    animalSlug: "rainbow-trout",
    pagePath: "/animals/rainbow-trout",
    role: "hero",
    localPath: "/images/animals/rainbow-trout/rainbow-trout-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rainbow_Trout_(Oncorhynchus_mykiss).jpg",
    author: "Liquid Art",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Liquid Art, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A rainbow trout (Oncorhynchus mykiss) swimming above a stony riverbed, showing the pink flank stripe and dark spotting.",
    caption: "A rainbow trout (Oncorhynchus mykiss) underwater.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "blue-tang-wikimedia-001",
    animalSlug: "blue-tang",
    pagePath: "/animals/blue-tang",
    role: "hero",
    localPath: "/images/animals/blue-tang/blue-tang-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cirujano_azul_Buin_Zoo.jpg",
    author: "Practica Buin Zoo",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Practica Buin Zoo, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A blue tang (Paracanthurus hepatus) swimming, showing its royal-blue body and yellow tail.",
    caption: "A blue tang (Paracanthurus hepatus) photographed at Buin Zoo, Chile.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use. Animal photographed in a zoo aquarium; the caption discloses this rather than implying a wild setting.",
  },
  {
    id: "moorish-idol-wikimedia-001",
    animalSlug: "moorish-idol",
    pagePath: "/animals/moorish-idol",
    role: "hero",
    localPath: "/images/animals/moorish-idol/moorish-idol-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Moorish_Idol_(Zanclus_cornutus)_(6059038522).jpg",
    author: "Bernard DUPONT from FRANCE",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    attribution: "Photo by Bernard DUPONT from FRANCE, CC BY-SA 2.0, via Wikimedia Commons.",
    alt: "A Moorish idol (Zanclus cornutus) over a coral reef, showing black, white and yellow banding and a long trailing dorsal filament.",
    caption: "A Moorish idol (Zanclus cornutus) at Bunaken Island, Sulawesi, Indonesia.",
    width: 1600,
    height: 960,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "firefly-wikimedia-001",
    animalSlug: "firefly",
    pagePath: "/animals/firefly",
    role: "hero",
    localPath: "/images/animals/firefly/firefly-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:202505_%E7%B4%85%E8%83%B8%E9%BB%91%E7%BF%85%E8%9E%A2%E7%89%B9%E5%AF%AB_(Luciola_kagiana_).jpg",
    author: "Junyu-K",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    attribution: "Photo by Junyu-K, CC BY 4.0, via Wikimedia Commons.",
    alt: "Close view of a firefly beetle (Lampyridae) resting on a green leaf at night.",
    caption: "A firefly (Luciola kagiana), one of over two thousand species in the beetle family Lampyridae.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "locust-wikimedia-001",
    animalSlug: "locust",
    pagePath: "/animals/locust",
    role: "hero",
    localPath: "/images/animals/locust/locust-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Schistocerca_gregaria.jpg",
    author: "Joachim Frische",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Joachim Frische, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A desert locust (Schistocerca gregaria) clinging to a branch, showing its yellow and brown patterning and long hind legs.",
    caption: "A desert locust (Schistocerca gregaria).",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "katydid-wikimedia-001",
    animalSlug: "katydid",
    pagePath: "/animals/katydid",
    role: "hero",
    localPath: "/images/animals/katydid/katydid-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Katydid_(Bush_cricket_or_Long-horned_grasshopper).jpg",
    author: "Nayanjain1306",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    attribution: "Photo by Nayanjain1306, CC BY-SA 4.0, via Wikimedia Commons.",
    alt: "A green katydid (Tettigoniidae) resting on foliage, its leaf-like wings and very long antennae visible.",
    caption: "A katydid mimicking a green leaf, photographed at Kaas, Maharashtra, India.",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "jumping-spider-wikimedia-001",
    animalSlug: "jumping-spider",
    pagePath: "/animals/jumping-spider",
    role: "hero",
    localPath: "/images/animals/jumping-spider/jumping-spider-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Phidippus_regius_female_01.jpg",
    author: "Nosferattus",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Nosferattus, released under CC0, via Wikimedia Commons.",
    alt: "Close frontal view of a jumping spider (Phidippus regius) showing its large forward-facing central eyes.",
    caption: "An immature female regal jumping spider (Phidippus regius) in Florida.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "wolf-spider-wikimedia-001",
    animalSlug: "wolf-spider",
    pagePath: "/animals/wolf-spider",
    role: "hero",
    localPath: "/images/animals/wolf-spider/wolf-spider-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wolf_spider_(Lycosidae).jpg",
    author: "Bidgee",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Bidgee, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "A wolf spider (Lycosidae) on a pale woven surface, showing its robust body and long legs.",
    caption: "A wolf spider (family Lycosidae).",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "black-widow-wikimedia-001",
    animalSlug: "black-widow",
    pagePath: "/animals/black-widow",
    role: "hero",
    localPath: "/images/animals/black-widow/black-widow-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Black_widow_spider.jpg",
    author: "Ken Thomas",
    license: "Public domain",
    licenseUrl: "",
    attribution: "Photo by Ken Thomas, public domain, via Wikimedia Commons.",
    alt: "A black widow spider (Latrodectus mactans) hanging in its web, showing the red hourglass on the underside of the abdomen.",
    caption: "A female black widow spider (Latrodectus mactans) in its web. This is an educational photograph; the species should not be handled.",
    width: 1600,
    height: 900,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Public domain — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "harvestman-wikimedia-001",
    animalSlug: "harvestman",
    pagePath: "/animals/harvestman",
    role: "hero",
    localPath: "/images/animals/harvestman/harvestman-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Harvestman_on_a_rock.jpg",
    author: "John Sears",
    license: "CC BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    attribution: "Photo by John Sears, CC BY 4.0, via Wikimedia Commons.",
    alt: "A harvestman (Opiliones) standing on a lichen-covered rock, showing its single oval body and very long thin legs.",
    caption: "A harvestman on a rock in the Catskill Mountains, New York. Harvestmen are arachnids but are not spiders.",
    width: 1600,
    height: 1067,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "army-ant-wikimedia-001",
    animalSlug: "army-ant",
    pagePath: "/animals/army-ant",
    role: "hero",
    localPath: "/images/animals/army-ant/army-ant-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Eciton_burchellii_(14336577830).jpg",
    author: "Graham Wise from Brisbane, Australia",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    attribution: "Photo by Graham Wise from Brisbane, Australia, CC BY 2.0, via Wikimedia Commons.",
    alt: "An army ant (Eciton burchellii) on a branch, showing its large curved mandibles.",
    caption: "An army ant (Eciton burchellii) worker.",
    width: 1600,
    height: 1178,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "fire-ant-wikimedia-001",
    animalSlug: "fire-ant",
    pagePath: "/animals/fire-ant",
    role: "hero",
    localPath: "/images/animals/fire-ant/fire-ant-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Solenopsis_invicta1.jpg",
    author: "Alexander Wild",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Alexander Wild, released under CC0, via Wikimedia Commons.",
    alt: "Macro portrait of a red imported fire ant (Solenopsis invicta) against a blue background.",
    caption: "A red imported fire ant (Solenopsis invicta).",
    width: 1600,
    height: 1135,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "swallowtail-butterfly-wikimedia-001",
    animalSlug: "swallowtail-butterfly",
    pagePath: "/animals/swallowtail-butterfly",
    role: "hero",
    localPath: "/images/animals/swallowtail-butterfly/swallowtail-butterfly-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Papilio_machaon_02_04102009.jpg",
    author: "Bernie",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0",
    attribution: "Photo by Bernie, CC BY-SA 3.0, via Wikimedia Commons.",
    alt: "An Old World swallowtail butterfly (Papilio machaon) with wings closed, showing pale yellow wings with black veining and a red eyespot.",
    caption: "An Old World swallowtail (Papilio machaon).",
    width: 1600,
    height: 1072,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: true,
    verifiedAt: "2026-09-06",
    riskNotes:
      "Share-alike licence — derivative works must be released under the same terms. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
  {
    id: "atlas-moth-wikimedia-001",
    animalSlug: "atlas-moth",
    pagePath: "/animals/atlas-moth",
    role: "hero",
    localPath: "/images/animals/atlas-moth/atlas-moth-hero.webp",
    sourceName: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Attacus_atlas,_the_Atlas_moth,_is_a_large_saturniid_moth_endemic_to_the_forests_of_Asia.jpg",
    author: "Raghith",
    license: "CC0",
    licenseUrl: "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    attribution: "Photo by Raghith, released under CC0, via Wikimedia Commons.",
    alt: "An atlas moth (Attacus atlas) resting with wings spread against a pale wall, showing translucent wing windows and hooked wingtips.",
    caption: "An atlas moth (Attacus atlas); the hooked forewing tips are marked to resemble a snake's head.",
    width: 1600,
    height: 1200,
    commercialUseAllowed: true,
    modificationsAllowed: true,
    attributionRequired: false,
    verifiedAt: "2026-09-06",
    riskNotes:
      "CC0 dedication — no attribution legally required; credited anyway as a matter of editorial policy. Species identification checked against the file's own description and categories on Commons, not its filename; the image was also inspected visually before use.",
  },
];
