/**
 * Regional discovery layer for the Red List dataset.
 *
 * IMPORTANT COMPLIANCE NOTES:
 *  - A region listing means the species' native range / regular occurrence
 *    falls in that region, as established in the authoritative sources already
 *    linked on each record. It is NOT a claim of legal protection.
 *  - Global IUCN Red List category is what we show. National/regional legal
 *    status (national Red Books, endangered-species laws) is separate and
 *    varies by country — see the methodology page.
 *  - We do not invent presence. Species appear under a region only where their
 *    native range is well documented. "oceans" is used for marine species whose
 *    range spans ocean basins rather than a single landmass.
 *  - Region assignments are kept in one map here so every claim is reviewable.
 */

export type RedListRegion =
  | "europe"
  | "north-america"
  | "south-america"
  | "africa"
  | "asia"
  | "oceania"
  | "oceans";

export interface RedListRegionMeta {
  region: RedListRegion;
  label: string;
  description: string;
  icon: string;
}

export const RED_LIST_REGIONS: Record<RedListRegion, RedListRegionMeta> = {
  europe: {
    region: "europe",
    label: "Europe",
    description:
      "Threatened species native to Europe, from Iberian forests to the Danube basin.",
    icon: "🇪🇺",
  },
  "north-america": {
    region: "north-america",
    label: "North America",
    description:
      "Threatened species of North and Central America and the Caribbean.",
    icon: "🌎",
  },
  "south-america": {
    region: "south-america",
    label: "South America",
    description:
      "Threatened species of the Andes, Amazon, Atlantic Forest, and beyond.",
    icon: "🌴",
  },
  africa: {
    region: "africa",
    label: "Africa",
    description:
      "Threatened species across the African continent and Madagascar.",
    icon: "🦁",
  },
  asia: {
    region: "asia",
    label: "Asia",
    description:
      "Threatened species from the Himalayas and Southeast Asian forests to East Asia.",
    icon: "🐯",
  },
  oceania: {
    region: "oceania",
    label: "Oceania",
    description:
      "Threatened species of Australia, New Zealand, New Guinea, and the Pacific.",
    icon: "🦘",
  },
  oceans: {
    region: "oceans",
    label: "Oceans",
    description:
      "Marine species whose range spans ocean basins — whales, sharks, rays, turtles, and corals.",
    icon: "🌊",
  },
};

export const REGION_ORDER: RedListRegion[] = [
  "africa",
  "asia",
  "north-america",
  "south-america",
  "europe",
  "oceania",
  "oceans",
];

/**
 * region -> species slugs. A slug may appear in several regions. Slugs that do
 * not match a live record are simply ignored by `getByRegion`.
 */
export const REGION_SPECIES: Record<RedListRegion, string[]> = {
  europe: [
    "barbary-macaque",
    "spanish-imperial-eagle",
    "eastern-imperial-eagle",
    "adriatic-sturgeon",
    "ship-sturgeon",
    "iberian-lynx",
    "european-mink",
    "european-hamster",
    "olm",
    "european-eel",
    "beluga-sturgeon",
    "russian-sturgeon",
    "sterlet",
    "angelshark",
    "saker-falcon",
    "aquatic-warbler",
    "egyptian-vulture",
    "atlantic-puffin",
    "polar-bear",
  ],
  "north-america": [
    "geoffroys-spider-monkey",
    "military-macaw",
    "central-american-river-turtle",
    "bog-turtle",
    "houston-toad",
    "yosemite-toad",
    "dusky-gopher-frog",
    "variable-harlequin-frog",
    "mountain-yellow-legged-frog",
    "morelets-tree-frog",
    "totoaba",
    "black-abalone",
    "california-condor",
    "whooping-crane",
    "vaquita",
    "sea-otter",
    "west-indian-manatee",
    "north-atlantic-right-whale",
    "hawaiian-monk-seal",
    "red-wolf",
    "black-footed-ferret",
    "vancouver-island-marmot",
    "polar-bear",
    "axolotl",
    "panamanian-golden-frog",
    "lemur-leaf-frog",
    "mountain-chicken-frog",
    "wyoming-toad",
    "california-tiger-salamander",
    "kemps-ridley-turtle",
    "american-crocodile",
    "cuban-crocodile",
    "grand-cayman-blue-iguana",
    "jamaican-iguana",
    "harpy-eagle",
    "great-green-macaw",
    "lined-seahorse",
    "nassau-grouper",
    "atlantic-goliath-grouper",
    "american-eel",
    "giant-sea-bass",
    "shortnose-sturgeon",
    "staghorn-coral",
    "elkhorn-coral",
    "lobed-star-coral",
    "boulder-star-coral",
    "mountainous-star-coral",
    "rough-cactus-coral",
    "pillar-coral",
    "white-abalone",
    "rusty-patched-bumble-bee",
    "franklins-bumble-bee",
    "american-burying-beetle",
    "migratory-monarch-butterfly",
  ],
  "south-america": [
    "geoffroys-spider-monkey",
    "brown-spider-monkey",
    "darwins-fox",
    "franciscana",
    "mountain-tapir",
    "red-fronted-macaw",
    "military-macaw",
    "golden-parakeet",
    "waved-albatross",
    "junin-grebe",
    "aruba-island-rattlesnake",
    "darwins-frog",
    "golden-lion-tamarin",
    "spixs-macaw",
    "hyacinth-macaw",
    "great-green-macaw",
    "harpy-eagle",
    "galapagos-penguin",
    "andean-condor",
    "lears-macaw",
    "blue-throated-macaw",
    "humboldt-penguin",
    "hooded-grebe",
    "titicaca-water-frog",
    "golden-poison-frog",
    "lehmanns-poison-frog",
    "amazon-river-dolphin",
    "amazonian-manatee",
    "giant-anteater",
    "giant-armadillo",
    "cotton-top-tamarin",
    "northern-muriqui",
    "maned-three-toed-sloth",
    "giant-otter",
    "andean-bear",
    "orinoco-crocodile",
    "american-crocodile",
    "galapagos-marine-iguana",
    "galapagos-land-iguana",
    "lemur-leaf-frog",
  ],
  africa: [
    "drill",
    "mandrill",
    "barbary-macaque",
    "verreauxs-sifaka",
    "greater-bamboo-lemur",
    "black-footed-cat",
    "fossa",
    "scimitar-horned-oryx",
    "dama-gazelle",
    "wattled-crane",
    "cape-vulture",
    "northern-bald-ibis",
    "spider-tortoise",
    "round-island-keel-scaled-boa",
    "slender-snouted-crocodile",
    "lake-oku-clawed-frog",
    "western-gorilla",
    "eastern-gorilla",
    "chimpanzee",
    "bonobo",
    "ring-tailed-lemur",
    "indri",
    "black-and-white-ruffed-lemur",
    "aye-aye",
    "lion",
    "leopard",
    "cheetah",
    "black-rhinoceros",
    "african-forest-elephant",
    "african-bush-elephant",
    "giraffe",
    "african-wild-dog",
    "ethiopian-wolf",
    "okapi",
    "pygmy-hippopotamus",
    "common-hippopotamus",
    "addax",
    "grevys-zebra",
    "african-penguin",
    "secretarybird",
    "shoebill",
    "egyptian-vulture",
    "blue-crane",
    "hooded-vulture",
    "white-backed-vulture",
    "grey-parrot",
    "martial-eagle",
    "madagascar-fish-eagle",
    "grey-crowned-crane",
    "ploughshare-tortoise",
    "radiated-tortoise",
    "geometric-tortoise",
    "egyptian-tortoise",
    "kihansi-spray-toad",
    "golden-mantella",
    "table-mountain-ghost-frog",
    "knysna-seahorse",
    "coelacanth",
  ],
  asia: [
    "hainan-gibbon",
    "western-hoolock-gibbon",
    "pileated-gibbon",
    "red-shanked-douc",
    "pygmy-slow-loris",
    "tonkin-snub-nosed-monkey",
    "flat-headed-cat",
    "indus-river-dolphin",
    "malayan-tapir",
    "pere-davids-deer",
    "hooded-crane",
    "white-naped-crane",
    "sarus-crane",
    "red-headed-vulture",
    "slender-billed-vulture",
    "eastern-imperial-eagle",
    "philippine-cockatoo",
    "short-tailed-albatross",
    "giant-ibis",
    "northern-bald-ibis",
    "bengal-florican",
    "forest-owlet",
    "tomistoma",
    "yangtze-giant-softshell-turtle",
    "burmese-roofed-turtle",
    "chinese-crocodile-lizard",
    "ganges-shark",
    "speartooth-shark",
    "chinese-bahaba",
    "kaluga",
    "sakhalin-sturgeon",
    "ship-sturgeon",
    "sumatran-orangutan",
    "bornean-orangutan",
    "tapanuli-orangutan",
    "proboscis-monkey",
    "tiger",
    "snow-leopard",
    "lion",
    "leopard",
    "cheetah",
    "sumatran-rhinoceros",
    "javan-rhinoceros",
    "greater-one-horned-rhinoceros",
    "asian-elephant",
    "giant-panda",
    "red-panda",
    "sunda-pangolin",
    "ganges-river-dolphin",
    "dugong",
    "dhole",
    "saola",
    "clouded-leopard",
    "fishing-cat",
    "lion-tailed-macaque",
    "golden-snub-nosed-monkey",
    "siamang",
    "lar-gibbon",
    "wild-bactrian-camel",
    "gaur",
    "banteng",
    "chinese-pangolin",
    "indian-pangolin",
    "gharial",
    "chinese-alligator",
    "komodo-dragon",
    "philippine-crocodile",
    "siamese-crocodile",
    "egyptian-tortoise",
    "chinese-giant-salamander",
    "japanese-giant-salamander",
    "purple-frog",
    "philippine-eagle",
    "siberian-crane",
    "bali-myna",
    "white-rumped-vulture",
    "egyptian-vulture",
    "steller-sea-eagle",
    "red-crowned-crane",
    "indian-vulture",
    "yellow-crested-cockatoo",
    "helmeted-hornbill",
    "great-indian-bustard",
    "spoon-billed-sandpiper",
    "crested-ibis",
    "black-faced-spoonbill",
    "saker-falcon",
    "christmas-frigatebird",
    "beluga-sturgeon",
    "chinese-sturgeon",
    "russian-sturgeon",
    "sterlet",
    "japanese-eel",
    "mekong-giant-catfish",
    "banggai-cardinalfish",
    "bumphead-parrotfish",
    "indonesian-coelacanth",
    "giant-freshwater-stingray",
    "chinese-paddlefish",
    "bowmouth-guitarfish",
    "humphead-wrasse",
  ],
  oceania: [
    "grey-headed-flying-fox",
    "greater-bilby",
    "hectors-dolphin",
    "sarus-crane",
    "erect-crested-penguin",
    "fiordland-penguin",
    "kagu",
    "archeys-frog",
    "northern-corroboree-frog",
    "speartooth-shark",
    "maugean-skate",
    "murray-cod",
    "spotted-handfish",
    "tasmanian-devil",
    "kakapo",
    "yellow-eyed-penguin",
    "regent-honeyeater",
    "kea",
    "swift-parrot",
    "orange-bellied-parrot",
    "night-parrot",
    "christmas-frigatebird",
    "northern-royal-albatross",
    "numbat",
    "koala",
    "northern-hairy-nosed-wombat",
    "leadbeaters-possum",
    "matschies-tree-kangaroo",
    "dugong",
    "dwarf-sawfish",
    "fiji-crested-iguana",
    "southern-corroboree-frog",
    "lord-howe-stick-insect",
  ],
  oceans: [
    "north-pacific-right-whale",
    "hectors-dolphin",
    "franciscana",
    "northern-rockhopper-penguin",
    "macaroni-penguin",
    "tristan-albatross",
    "waved-albatross",
    "short-tailed-albatross",
    "round-island-keel-scaled-boa",
    "dusky-shark",
    "silky-shark",
    "tope-shark",
    "smooth-hammerhead",
    "spiny-dogfish",
    "maugean-skate",
    "totoaba",
    "sakhalin-sturgeon",
    "black-abalone",
    "vaquita",
    "sea-otter",
    "west-indian-manatee",
    "blue-whale",
    "fin-whale",
    "sei-whale",
    "north-atlantic-right-whale",
    "hawaiian-monk-seal",
    "dugong",
    "hawksbill-turtle",
    "kemps-ridley-turtle",
    "green-turtle",
    "leatherback-turtle",
    "loggerhead-turtle",
    "olive-ridley-turtle",
    "whale-shark",
    "great-white-shark",
    "scalloped-hammerhead",
    "great-hammerhead",
    "oceanic-whitetip-shark",
    "shortfin-mako",
    "giant-manta-ray",
    "reef-manta-ray",
    "largetooth-sawfish",
    "smalltooth-sawfish",
    "green-sawfish",
    "dwarf-sawfish",
    "bowmouth-guitarfish",
    "angelshark",
    "basking-shark",
    "porbeagle",
    "sand-tiger-shark",
    "european-eel",
    "american-eel",
    "humphead-wrasse",
    "bumphead-parrotfish",
    "coelacanth",
    "lined-seahorse",
    "southern-bluefin-tuna",
    "bigeye-tuna",
    "nassau-grouper",
    "atlantic-goliath-grouper",
    "giant-sea-bass",
    "wandering-albatross",
    "northern-royal-albatross",
    "atlantic-puffin",
    "staghorn-coral",
    "elkhorn-coral",
    "lobed-star-coral",
    "boulder-star-coral",
    "mountainous-star-coral",
    "rough-cactus-coral",
    "pillar-coral",
    "white-abalone",
  ],
};

export function getRegionMeta(region: RedListRegion): RedListRegionMeta {
  return RED_LIST_REGIONS[region];
}

/** Regions a given slug is listed under (for record display). */
export function regionsForSlug(slug: string): RedListRegion[] {
  return REGION_ORDER.filter((r) => REGION_SPECIES[r].includes(slug));
}
