import type { RedListSpeciesRecord } from "./types";
import { adw, noaa, fishbase, fws, birdlife, amphibiaweb, rec } from "./_builders";

/**
 * Red List Batch 4 — verified index records with regional diversity emphasis,
 * supporting the /endangered-animals/regions layer. Same compliance posture as
 * earlier batches; region assignments live in regions.ts. All index-only.
 */
export const RED_LIST_SPECIES_BATCH4: readonly RedListSpeciesRecord[] = [
  // --- Mammals: Asia ---
  rec({
    slug: "clouded-leopard",
    commonName: "Clouded Leopard",
    scientificName: "Neofelis nebulosa",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Neofelis_nebulosa")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "fishing-cat",
    commonName: "Fishing Cat",
    scientificName: "Prionailurus viverrinus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Prionailurus_viverrinus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lion-tailed-macaque",
    commonName: "Lion-tailed Macaque",
    scientificName: "Macaca silenus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Macaca_silenus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "golden-snub-nosed-monkey",
    commonName: "Golden Snub-nosed Monkey",
    scientificName: "Rhinopithecus roxellana",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Rhinopithecus_roxellana")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "siamang",
    commonName: "Siamang",
    scientificName: "Symphalangus syndactylus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Symphalangus_syndactylus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lar-gibbon",
    commonName: "Lar Gibbon",
    scientificName: "Hylobates lar",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Hylobates_lar")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "wild-bactrian-camel",
    commonName: "Wild Bactrian Camel",
    scientificName: "Camelus ferus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Camelus_bactrianus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "The wild Bactrian camel (Camelus ferus) is the threatened wild form; the linked reference covers Bactrian camels broadly.",
  }),
  rec({
    slug: "gaur",
    commonName: "Gaur",
    scientificName: "Bos gaurus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [fws("gaur-bos-gaurus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "banteng",
    commonName: "Banteng",
    scientificName: "Bos javanicus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Bos_javanicus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "chinese-pangolin",
    commonName: "Chinese Pangolin",
    scientificName: "Manis pentadactyla",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Manis_pentadactyla")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "indian-pangolin",
    commonName: "Indian Pangolin",
    scientificName: "Manis crassicaudata",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Manis_crassicaudata")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Mammals: South America ---
  rec({
    slug: "cotton-top-tamarin",
    commonName: "Cotton-top Tamarin",
    scientificName: "Saguinus oedipus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Saguinus_oedipus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "northern-muriqui",
    commonName: "Northern Muriqui",
    scientificName: "Brachyteles hypoxanthus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Brachyteles_hypoxanthus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "maned-three-toed-sloth",
    commonName: "Maned Three-toed Sloth",
    scientificName: "Bradypus torquatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Bradypus_torquatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giant-otter",
    commonName: "Giant Otter",
    scientificName: "Pteronura brasiliensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Rivers and wetlands of tropical South America, centred on the Amazon basin and the Pantanal.",
    primaryThreats: [
      "Habitat degradation and deforestation",
      "Historical hunting for pelts",
      "Pollution including mining-related mercury",
    ],
    sourceUrls: [adw("Pteronura_brasiliensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "andean-bear",
    commonName: "Andean Bear",
    scientificName: "Tremarctos ornatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Tremarctos_ornatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "South America's only bear species; also called the spectacled bear.",
  }),
  rec({
    slug: "giant-armadillo",
    commonName: "Giant Armadillo",
    scientificName: "Priodontes maximus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Priodontes_maximus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Mammals: Europe & North America ---
  rec({
    slug: "european-mink",
    commonName: "European Mink",
    scientificName: "Mustela lutreola",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Mustela_lutreola")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "european-hamster",
    commonName: "European Hamster",
    scientificName: "Cricetus cricetus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Cricetus_cricetus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Up-listed to Critically Endangered in 2020 after steep declines across Europe.",
  }),
  rec({
    slug: "vancouver-island-marmot",
    commonName: "Vancouver Island Marmot",
    scientificName: "Marmota vancouverensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Marmota_vancouverensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Mammals: Oceania ---
  rec({
    slug: "numbat",
    commonName: "Numbat",
    scientificName: "Myrmecobius fasciatus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Myrmecobius_fasciatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "koala",
    commonName: "Koala",
    scientificName: "Phascolarctos cinereus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Phascolarctos_cinereus")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "koala",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "northern-hairy-nosed-wombat",
    commonName: "Northern Hairy-nosed Wombat",
    scientificName: "Lasiorhinus krefftii",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Lasiorhinus_krefftii")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "leadbeaters-possum",
    commonName: "Leadbeater's Possum",
    scientificName: "Gymnobelideus leadbeateri",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Gymnobelideus_leadbeateri")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "matschies-tree-kangaroo",
    commonName: "Matschie's Tree-kangaroo",
    scientificName: "Dendrolagus matschiei",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Dendrolagus_matschiei")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Birds (BirdLife) ---
  rec({
    slug: "saker-falcon",
    commonName: "Saker Falcon",
    scientificName: "Falco cherrug",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("saker-falcon-falco-cherrug")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "aquatic-warbler",
    commonName: "Aquatic Warbler",
    scientificName: "Acrocephalus paludicola",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [birdlife("aquatic-warbler-acrocephalus-paludicola")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "grey-crowned-crane",
    commonName: "Grey Crowned Crane",
    scientificName: "Balearica regulorum",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("grey-crowned-crane-balearica-regulorum")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "hooded-grebe",
    commonName: "Hooded Grebe",
    scientificName: "Podiceps gallardoi",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("hooded-grebe-podiceps-gallardoi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "night-parrot",
    commonName: "Night Parrot",
    scientificName: "Pezoporus occidentalis",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("night-parrot-pezoporus-occidentalis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "christmas-frigatebird",
    commonName: "Christmas Frigatebird",
    scientificName: "Fregata andrewsi",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("christmas-island-frigatebird-fregata-andrewsi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "northern-royal-albatross",
    commonName: "Northern Royal Albatross",
    scientificName: "Diomedea sanfordi",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("northern-royal-albatross-diomedea-sanfordi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Reptiles & Amphibians ---
  rec({
    slug: "galapagos-land-iguana",
    commonName: "Galápagos Land Iguana",
    scientificName: "Conolophus subcristatus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [adw("Conolophus_subcristatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "california-tiger-salamander",
    commonName: "California Tiger Salamander",
    scientificName: "Ambystoma californiense",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [amphibiaweb("Ambystoma", "californiense")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Fish ---
  rec({
    slug: "giant-sea-bass",
    commonName: "Giant Sea Bass",
    scientificName: "Stereolepis gigas",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Stereolepis-gigas")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "shortnose-sturgeon",
    commonName: "Shortnose Sturgeon",
    scientificName: "Acipenser brevirostrum",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [noaa("shortnose-sturgeon"), fishbase("Acipenser-brevirostrum")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Invertebrates ---
  rec({
    slug: "pillar-coral",
    commonName: "Pillar Coral",
    scientificName: "Dendrogyra cylindrus",
    taxonGroup: "invertebrates",
    redListCategory: "VU",
    sourceUrls: [noaa("pillar-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Caribbean reef coral severely affected by stony coral tissue loss disease; confirm the current category on the live IUCN entry.",
  }),
];
