import type { RedListSpeciesRecord } from "./types";
import { adw, noaa, fishbase, amphibiaweb, reptiledb, rec } from "./_builders";

/**
 * Red List Batch 3 — verified index records (fish + reptiles & amphibians).
 *
 * Same compliance posture as Phase 1 and Batch 2. Fish use FishBase / NOAA;
 * amphibians use AmphibiaWeb (UC Berkeley); reptiles use ADW / NOAA. Region
 * assignments live in regions.ts. All records are index-only.
 */
export const RED_LIST_SPECIES_BATCH3: readonly RedListSpeciesRecord[] = [
  // --- Fish ---
  rec({
    slug: "southern-bluefin-tuna",
    commonName: "Southern Bluefin Tuna",
    scientificName: "Thunnus maccoyii",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Thunnus-maccoyii")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bigeye-tuna",
    commonName: "Bigeye Tuna",
    scientificName: "Thunnus obesus",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [fishbase("Thunnus-obesus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "nassau-grouper",
    commonName: "Nassau Grouper",
    scientificName: "Epinephelus striatus",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [noaa("nassau-grouper"), fishbase("Epinephelus-striatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "atlantic-goliath-grouper",
    commonName: "Atlantic Goliath Grouper",
    scientificName: "Epinephelus itajara",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [fishbase("Epinephelus-itajara")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Down-listed from Critically Endangered to Vulnerable in 2018.",
  }),
  rec({
    slug: "basking-shark",
    commonName: "Basking Shark",
    scientificName: "Cetorhinus maximus",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Cetorhinus-maximus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "porbeagle",
    commonName: "Porbeagle",
    scientificName: "Lamna nasus",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [fishbase("Lamna-nasus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sand-tiger-shark",
    commonName: "Sand Tiger Shark",
    scientificName: "Carcharias taurus",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Carcharias-taurus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "green-sawfish",
    commonName: "Green Sawfish",
    scientificName: "Pristis zijsron",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Pristis-zijsron")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "dwarf-sawfish",
    commonName: "Dwarf Sawfish",
    scientificName: "Pristis clavata",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Pristis-clavata")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bowmouth-guitarfish",
    commonName: "Bowmouth Guitarfish",
    scientificName: "Rhina ancylostoma",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Rhina-ancylostoma")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "angelshark",
    commonName: "Angelshark",
    scientificName: "Squatina squatina",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Squatina-squatina")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "russian-sturgeon",
    commonName: "Russian Sturgeon",
    scientificName: "Acipenser gueldenstaedtii",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Acipenser-gueldenstaedtii")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sterlet",
    commonName: "Sterlet",
    scientificName: "Acipenser ruthenus",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [fishbase("Acipenser-ruthenus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "american-eel",
    commonName: "American Eel",
    scientificName: "Anguilla rostrata",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Anguilla-rostrata")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "japanese-eel",
    commonName: "Japanese Eel",
    scientificName: "Anguilla japonica",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Anguilla-japonica")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "mekong-giant-catfish",
    commonName: "Mekong Giant Catfish",
    scientificName: "Pangasianodon gigas",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Pangasianodon-gigas")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "banggai-cardinalfish",
    commonName: "Banggai Cardinalfish",
    scientificName: "Pterapogon kauderni",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Pterapogon-kauderni")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bumphead-parrotfish",
    commonName: "Bumphead Parrotfish",
    scientificName: "Bolbometopon muricatum",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [fishbase("Bolbometopon-muricatum")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "knysna-seahorse",
    commonName: "Knysna Seahorse",
    scientificName: "Hippocampus capensis",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Hippocampus-capensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "indonesian-coelacanth",
    commonName: "Indonesian Coelacanth",
    scientificName: "Latimeria menadoensis",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [fishbase("Latimeria-menadoensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giant-freshwater-stingray",
    commonName: "Giant Freshwater Stingray",
    scientificName: "Urogymnus polylepis",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Urogymnus-polylepis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "chinese-paddlefish",
    commonName: "Chinese Paddlefish",
    scientificName: "Psephurus gladius",
    taxonGroup: "fish",
    redListCategory: "EX",
    sourceUrls: [fishbase("Psephurus-gladius")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Declared Extinct by the IUCN in 2022; one of the largest freshwater fish.",
  }),

  // --- Reptiles ---
  rec({
    slug: "olive-ridley-turtle",
    commonName: "Olive Ridley Turtle",
    scientificName: "Lepidochelys olivacea",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [noaa("olive-ridley-turtle"), adw("Lepidochelys_olivacea")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "american-crocodile",
    commonName: "American Crocodile",
    scientificName: "Crocodylus acutus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [adw("Crocodylus_acutus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "orinoco-crocodile",
    commonName: "Orinoco Crocodile",
    scientificName: "Crocodylus intermedius",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [reptiledb("Crocodylus", "intermedius")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "philippine-crocodile",
    commonName: "Philippine Crocodile",
    scientificName: "Crocodylus mindorensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Crocodylus_mindorensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "cuban-crocodile",
    commonName: "Cuban Crocodile",
    scientificName: "Crocodylus rhombifer",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Crocodylus_rhombifer")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "siamese-crocodile",
    commonName: "Siamese Crocodile",
    scientificName: "Crocodylus siamensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [reptiledb("Crocodylus", "siamensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "geometric-tortoise",
    commonName: "Geometric Tortoise",
    scientificName: "Psammobates geometricus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Psammobates_geometricus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "egyptian-tortoise",
    commonName: "Egyptian Tortoise",
    scientificName: "Testudo kleinmanni",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [reptiledb("Testudo", "kleinmanni")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "galapagos-marine-iguana",
    commonName: "Galápagos Marine Iguana",
    scientificName: "Amblyrhynchus cristatus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [adw("Amblyrhynchus_cristatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "fiji-crested-iguana",
    commonName: "Fiji Crested Iguana",
    scientificName: "Brachylophus vitiensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [reptiledb("Brachylophus", "vitiensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "grand-cayman-blue-iguana",
    commonName: "Grand Cayman Blue Iguana",
    scientificName: "Cyclura lewisi",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [reptiledb("Cyclura", "lewisi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Recovered from the brink of extinction; down-listed from Critically Endangered to Endangered in 2012.",
  }),
  rec({
    slug: "jamaican-iguana",
    commonName: "Jamaican Iguana",
    scientificName: "Cyclura collei",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [reptiledb("Cyclura", "collei")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Once thought extinct; rediscovered in 1990.",
  }),

  // --- Amphibians (AmphibiaWeb) ---
  rec({
    slug: "japanese-giant-salamander",
    commonName: "Japanese Giant Salamander",
    scientificName: "Andrias japonicus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [amphibiaweb("Andrias", "japonicus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "golden-poison-frog",
    commonName: "Golden Poison Frog",
    scientificName: "Phyllobates terribilis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [amphibiaweb("Phyllobates", "terribilis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lehmanns-poison-frog",
    commonName: "Lehmann's Poison Frog",
    scientificName: "Oophaga lehmanni",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [amphibiaweb("Oophaga", "lehmanni")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "southern-corroboree-frog",
    commonName: "Southern Corroboree Frog",
    scientificName: "Pseudophryne corroboree",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [amphibiaweb("Pseudophryne", "corroboree")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "wyoming-toad",
    commonName: "Wyoming Toad",
    scientificName: "Anaxyrus baxteri",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EW",
    sourceUrls: [amphibiaweb("Anaxyrus", "baxteri")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Listed Extinct in the Wild; survives through captive breeding and reintroduction.",
  }),
  rec({
    slug: "golden-mantella",
    commonName: "Golden Mantella",
    scientificName: "Mantella aurantiaca",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [amphibiaweb("Mantella", "aurantiaca")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "purple-frog",
    commonName: "Purple Frog",
    scientificName: "Nasikabatrachus sahyadrensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [amphibiaweb("Nasikabatrachus", "sahyadrensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "table-mountain-ghost-frog",
    commonName: "Table Mountain Ghost Frog",
    scientificName: "Heleophryne rosei",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [amphibiaweb("Heleophryne", "rosei")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
];
