import type { RedListSpeciesRecord } from "./types";
import { adw, noaa, fishbase, amphibiaweb, reptiledb, rec } from "./_builders";

/**
 * Red List Batch 3 — verified index records (fish + reptiles & amphibians).
 *
 * Same compliance posture as Phase 1 and Batch 2. Fish use FishBase / NOAA;
 * amphibians use AmphibiaWeb (UC Berkeley); reptiles use ADW / NOAA. Region
 * assignments live in regions.ts. All records are index-only.
 */
export const RED_LIST_SPECIES_BATCH3: readonly RedListSpeciesRecord[] = [
  // --- Fish ---
  rec({
    slug: "southern-bluefin-tuna",
    commonName: "Southern Bluefin Tuna",
    scientificName: "Thunnus maccoyii",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "The temperate and cold open waters of the southern oceans.",
    primaryThreats: [
      "Past severe overfishing",
      "Continued fishing pressure",
      "Slow maturation",
    ],
    sourceUrls: [fishbase("Thunnus-maccoyii")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bigeye-tuna",
    commonName: "Bigeye Tuna",
    scientificName: "Thunnus obesus",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Tropical and subtropical open oceans worldwide.",
    primaryThreats: [
      "Overfishing",
      "Catch of juveniles around fish-aggregating devices",
      "High fishing pressure",
    ],
    sourceUrls: [fishbase("Thunnus-obesus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "nassau-grouper",
    commonName: "Nassau Grouper",
    scientificName: "Epinephelus striatus",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Coral reefs of the western Atlantic and Caribbean.",
    primaryThreats: [
      "Overfishing, especially at spawning aggregations",
      "Habitat loss",
    ],
    sourceUrls: [noaa("nassau-grouper"), fishbase("Epinephelus-striatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "atlantic-goliath-grouper",
    commonName: "Atlantic Goliath Grouper",
    scientificName: "Epinephelus itajara",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "increasing",
    rangeSummary:
      "Warm coastal waters of the western Atlantic.",
    primaryThreats: [
      "Past severe overfishing",
      "Habitat loss (mangroves)",
      "Slow maturation",
    ],
    sourceUrls: [fishbase("Epinephelus-itajara")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Down-listed from Critically Endangered to Vulnerable in 2018.",
  }),
  rec({
    slug: "basking-shark",
    commonName: "Basking Shark",
    scientificName: "Cetorhinus maximus",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Temperate coastal and open waters worldwide.",
    primaryThreats: [
      "Past targeted fishing",
      "Bycatch and disturbance",
      "A very slow reproductive rate",
    ],
    sourceUrls: [fishbase("Cetorhinus-maximus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "porbeagle",
    commonName: "Porbeagle",
    scientificName: "Lamna nasus",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Cold and temperate waters of the North Atlantic and Southern Hemisphere.",
    primaryThreats: [
      "Overfishing for meat and fins",
      "Bycatch",
      "A low reproductive rate",
    ],
    sourceUrls: [fishbase("Lamna-nasus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sand-tiger-shark",
    commonName: "Sand Tiger Shark",
    scientificName: "Carcharias taurus",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Warm coastal waters worldwide (excluding the eastern Pacific).",
    primaryThreats: [
      "Overfishing and bycatch",
      "A very low reproductive rate",
      "Past culling",
    ],
    sourceUrls: [fishbase("Carcharias-taurus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "green-sawfish",
    commonName: "Green Sawfish",
    scientificName: "Pristis zijsron",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Coastal and estuarine waters of the Indo-West Pacific, much reduced.",
    primaryThreats: [
      "Entanglement in fishing nets",
      "Habitat loss",
      "Past targeted fishing",
    ],
    sourceUrls: [fishbase("Pristis-zijsron")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "dwarf-sawfish",
    commonName: "Dwarf Sawfish",
    scientificName: "Pristis clavata",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Coastal and estuarine waters of the Indo-West Pacific, much reduced.",
    primaryThreats: [
      "Entanglement in fishing nets",
      "Habitat loss",
      "Past fishing",
    ],
    sourceUrls: [fishbase("Pristis-clavata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bowmouth-guitarfish",
    commonName: "Bowmouth Guitarfish",
    scientificName: "Rhina ancylostoma",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Coastal waters of the Indo-West Pacific.",
    primaryThreats: [
      "Overfishing for fins and meat",
      "Bycatch",
      "Habitat loss",
    ],
    sourceUrls: [fishbase("Rhina-ancylostoma")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "angelshark",
    commonName: "Angelshark",
    scientificName: "Squatina squatina",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Coastal waters of the eastern Atlantic and Mediterranean, much reduced.",
    primaryThreats: [
      "Bycatch in trawls and nets",
      "Habitat disturbance",
      "Slow reproduction",
    ],
    sourceUrls: [fishbase("Squatina-squatina")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "russian-sturgeon",
    commonName: "Russian Sturgeon",
    scientificName: "Acipenser gueldenstaedtii",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The Caspian and Black Sea basins and their rivers.",
    primaryThreats: [
      "Overfishing for caviar",
      "Poaching",
      "Dams blocking spawning migrations",
    ],
    sourceUrls: [fishbase("Acipenser-gueldenstaedtii")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sterlet",
    commonName: "Sterlet",
    scientificName: "Acipenser ruthenus",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Rivers of Eurasia draining to the Black, Caspian, and Arctic seas.",
    primaryThreats: [
      "Overfishing",
      "Dams and habitat change",
      "Pollution",
    ],
    sourceUrls: [fishbase("Acipenser-ruthenus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "american-eel",
    commonName: "American Eel",
    scientificName: "Anguilla rostrata",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Born in the Atlantic's Sargasso Sea; lives in fresh and coastal waters of eastern North America.",
    primaryThreats: [
      "Barriers such as dams",
      "Overfishing of young eels",
      "Habitat loss and changing ocean conditions",
    ],
    sourceUrls: [fishbase("Anguilla-rostrata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "japanese-eel",
    commonName: "Japanese Eel",
    scientificName: "Anguilla japonica",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Rivers and coasts of East Asia, spawning far out in the western Pacific.",
    primaryThreats: [
      "Overfishing of young eels",
      "Barriers such as dams",
      "Habitat loss and ocean change",
    ],
    sourceUrls: [fishbase("Anguilla-japonica")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "mekong-giant-catfish",
    commonName: "Mekong Giant Catfish",
    scientificName: "Pangasianodon gigas",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The Mekong River basin of Southeast Asia.",
    primaryThreats: [
      "Dams blocking migration",
      "Overfishing",
      "Habitat change and reduced flow",
    ],
    sourceUrls: [fishbase("Pangasianodon-gigas")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "banggai-cardinalfish",
    commonName: "Banggai Cardinalfish",
    scientificName: "Pterapogon kauderni",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "A small area around the Banggai Islands of Indonesia.",
    primaryThreats: [
      "Collection for the aquarium trade",
      "A tiny range",
      "Habitat damage",
    ],
    sourceUrls: [fishbase("Pterapogon-kauderni")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bumphead-parrotfish",
    commonName: "Bumphead Parrotfish",
    scientificName: "Bolbometopon muricatum",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Coral reefs of the Indo-Pacific.",
    primaryThreats: [
      "Overfishing, especially night spearfishing",
      "Reef degradation",
    ],
    sourceUrls: [fishbase("Bolbometopon-muricatum")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "knysna-seahorse",
    commonName: "Knysna Seahorse",
    scientificName: "Hippocampus capensis",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "A few estuaries on the south coast of South Africa.",
    primaryThreats: [
      "Estuary degradation and pollution",
      "Development and disturbance",
      "A tiny range",
    ],
    sourceUrls: [fishbase("Hippocampus-capensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "indonesian-coelacanth",
    commonName: "Indonesian Coelacanth",
    scientificName: "Latimeria menadoensis",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Deep waters off Sulawesi, Indonesia.",
    primaryThreats: [
      "Accidental capture in deep fishing gear",
      "A very small, slow-breeding population",
    ],
    sourceUrls: [fishbase("Latimeria-menadoensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giant-freshwater-stingray",
    commonName: "Giant Freshwater Stingray",
    scientificName: "Urogymnus polylepis",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Large rivers and estuaries of Southeast Asia.",
    primaryThreats: [
      "Overfishing and bycatch",
      "Habitat degradation",
      "Dams and pollution",
    ],
    sourceUrls: [fishbase("Urogymnus-polylepis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "chinese-paddlefish",
    commonName: "Chinese Paddlefish",
    scientificName: "Psephurus gladius",
    taxonGroup: "fish",
    redListCategory: "EX",
    populationTrend: "unknown",
    rangeSummary:
      "Formerly the Yangtze River of China.",
    primaryThreats: [
      "Overfishing",
      "Dams that blocked spawning migrations",
      "Habitat loss",
    ],
    sourceUrls: [fishbase("Psephurus-gladius")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Declared Extinct by the IUCN in 2022; one of the largest freshwater fish.",
  }),

  // --- Reptiles ---
  rec({
    slug: "olive-ridley-turtle",
    commonName: "Olive Ridley Turtle",
    scientificName: "Lepidochelys olivacea",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Tropical waters of the Pacific, Indian, and Atlantic Oceans.",
    primaryThreats: [
      "Bycatch",
      "Egg collection and coastal development",
      "Pollution",
    ],
    sourceUrls: [noaa("olive-ridley-turtle"), adw("Lepidochelys_olivacea")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "american-crocodile",
    commonName: "American Crocodile",
    scientificName: "Crocodylus acutus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "stable",
    rangeSummary:
      "Coastal areas from southern Florida through Central America and the Caribbean to northern South America.",
    primaryThreats: [
      "Habitat loss and coastal development",
      "Historical hunting for skins",
      "Human-wildlife conflict",
    ],
    sourceUrls: [adw("Crocodylus_acutus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "orinoco-crocodile",
    commonName: "Orinoco Crocodile",
    scientificName: "Crocodylus intermedius",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "stable",
    rangeSummary:
      "The Orinoco River basin of Colombia and Venezuela.",
    primaryThreats: [
      "Past hunting for skins",
      "Egg and habitat loss",
      "A very small population",
    ],
    sourceUrls: [reptiledb("Crocodylus", "intermedius")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "philippine-crocodile",
    commonName: "Philippine Crocodile",
    scientificName: "Crocodylus mindorensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Freshwater wetlands of the Philippines.",
    primaryThreats: [
      "Past killing and persecution",
      "Habitat loss",
      "Entanglement and a tiny population",
    ],
    sourceUrls: [adw("Crocodylus_mindorensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "cuban-crocodile",
    commonName: "Cuban Crocodile",
    scientificName: "Crocodylus rhombifer",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Two swamp areas of Cuba.",
    primaryThreats: [
      "A tiny range",
      "Hybridisation with American crocodiles",
      "Past hunting",
    ],
    sourceUrls: [adw("Crocodylus_rhombifer")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "siamese-crocodile",
    commonName: "Siamese Crocodile",
    scientificName: "Crocodylus siamensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Freshwater wetlands of Southeast Asia.",
    primaryThreats: [
      "Past collection for crocodile farms",
      "Habitat loss",
      "Hybridisation and a tiny wild population",
    ],
    sourceUrls: [reptiledb("Crocodylus", "siamensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "geometric-tortoise",
    commonName: "Geometric Tortoise",
    scientificName: "Psammobates geometricus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A small area of lowland fynbos in the Western Cape of South Africa.",
    primaryThreats: [
      "Loss of fynbos habitat",
      "Fires",
      "A tiny, fragmented range",
    ],
    sourceUrls: [adw("Psammobates_geometricus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "egyptian-tortoise",
    commonName: "Egyptian Tortoise",
    scientificName: "Testudo kleinmanni",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Deserts of North Africa and the Middle East, around the eastern Mediterranean.",
    primaryThreats: [
      "Collection for the pet trade",
      "Habitat loss to agriculture",
      "A tiny remaining range",
    ],
    sourceUrls: [reptiledb("Testudo", "kleinmanni")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "galapagos-marine-iguana",
    commonName: "Galápagos Marine Iguana",
    scientificName: "Amblyrhynchus cristatus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "stable",
    rangeSummary:
      "The coasts of the Galápagos Islands.",
    primaryThreats: [
      "Introduced predators (cats, dogs, rats)",
      "Oil spills and pollution",
      "Ocean changes such as El Niño",
    ],
    sourceUrls: [adw("Amblyrhynchus_cristatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "fiji-crested-iguana",
    commonName: "Fiji Crested Iguana",
    scientificName: "Brachylophus vitiensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A few islands of Fiji in the South Pacific.",
    primaryThreats: [
      "Habitat loss and fires",
      "Introduced predators and goats",
      "A tiny range",
    ],
    sourceUrls: [reptiledb("Brachylophus", "vitiensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "grand-cayman-blue-iguana",
    commonName: "Grand Cayman Blue Iguana",
    scientificName: "Cyclura lewisi",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "The island of Grand Cayman in the Caribbean.",
    primaryThreats: [
      "Past habitat loss and predation by introduced animals",
      "Road deaths",
      "A small range",
    ],
    sourceUrls: [reptiledb("Cyclura", "lewisi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Recovered from the brink of extinction; down-listed from Critically Endangered to Endangered in 2012.",
  }),
  rec({
    slug: "jamaican-iguana",
    commonName: "Jamaican Iguana",
    scientificName: "Cyclura collei",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "The Hellshire Hills of Jamaica.",
    primaryThreats: [
      "Introduced predators (mongooses, cats, dogs, pigs)",
      "Habitat loss",
      "A tiny range",
    ],
    sourceUrls: [reptiledb("Cyclura", "collei")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Once thought extinct; rediscovered in 1990.",
  }),

  // --- Amphibians (AmphibiaWeb) ---
  rec({
    slug: "japanese-giant-salamander",
    commonName: "Japanese Giant Salamander",
    scientificName: "Andrias japonicus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Cool rivers and streams of Japan.",
    primaryThreats: [
      "Habitat alteration (dams and river works)",
      "Hybridisation with introduced salamanders",
      "Pollution",
    ],
    sourceUrls: [amphibiaweb("Andrias", "japonicus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "golden-poison-frog",
    commonName: "Golden Poison Frog",
    scientificName: "Phyllobates terribilis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "A small area of rainforest on the Pacific coast of Colombia.",
    primaryThreats: [
      "Deforestation",
      "Habitat degradation",
      "A very small range",
    ],
    sourceUrls: [amphibiaweb("Phyllobates", "terribilis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "lehmanns-poison-frog",
    commonName: "Lehmann's Poison Frog",
    scientificName: "Oophaga lehmanni",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A very small area of forest in western Colombia.",
    primaryThreats: [
      "Habitat loss",
      "Collection for the illegal pet trade",
      "A tiny range",
    ],
    sourceUrls: [amphibiaweb("Oophaga", "lehmanni")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "southern-corroboree-frog",
    commonName: "Southern Corroboree Frog",
    scientificName: "Pseudophryne corroboree",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A small alpine area of south-eastern Australia.",
    primaryThreats: [
      "The amphibian fungal disease chytridiomycosis",
      "Habitat change and drought",
      "A tiny range",
    ],
    sourceUrls: [amphibiaweb("Pseudophryne", "corroboree")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "wyoming-toad",
    commonName: "Wyoming Toad",
    scientificName: "Anaxyrus baxteri",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EW",
    populationTrend: "unknown",
    rangeSummary:
      "A small area of Wyoming, USA; survives through captive breeding and reintroduction.",
    primaryThreats: [
      "The amphibian fungal disease chytridiomycosis",
      "Past habitat change and pesticides",
      "A tiny range",
    ],
    sourceUrls: [amphibiaweb("Anaxyrus", "baxteri")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Listed Extinct in the Wild; survives through captive breeding and reintroduction.",
  }),
  rec({
    slug: "golden-mantella",
    commonName: "Golden Mantella",
    scientificName: "Mantella aurantiaca",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A small area of central-eastern Madagascar.",
    primaryThreats: [
      "Loss of its specialised breeding wetlands",
      "Habitat degradation",
      "Past collection",
    ],
    sourceUrls: [amphibiaweb("Mantella", "aurantiaca")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "purple-frog",
    commonName: "Purple Frog",
    scientificName: "Nasikabatrachus sahyadrensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "The Western Ghats of India.",
    primaryThreats: [
      "Habitat loss to agriculture",
      "Dams and land-use change",
      "Collection of tadpoles in places",
    ],
    sourceUrls: [amphibiaweb("Nasikabatrachus", "sahyadrensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "table-mountain-ghost-frog",
    commonName: "Table Mountain Ghost Frog",
    scientificName: "Heleophryne rosei",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Streams on Table Mountain near Cape Town, South Africa.",
    primaryThreats: [
      "Altered stream flow and dams",
      "Fires and erosion",
      "An extremely small range",
    ],
    sourceUrls: [amphibiaweb("Heleophryne", "rosei")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
];
