import type { RedListSpeciesRecord } from "./types";
import { adw, noaa, szoo, fws, birdlife, fishbase, amphibiaweb, rec } from "./_builders";
import { RED_LIST_SPECIES_BATCH2 } from "./species-batch2";
import { RED_LIST_SPECIES_BATCH3 } from "./species-batch3";
import { RED_LIST_SPECIES_BATCH4 } from "./species-batch4";
import { RED_LIST_SPECIES_BATCH5 } from "./species-batch5";

/**
 * Red List Species Intelligence — Phase 1 index dataset (100 records).
 *
 * COMPLIANCE POSTURE (read before editing):
 *  - Categories reflect widely published IUCN Red List assessments for
 *    well-documented, stably classified species. They are shown for
 *    educational orientation and are flagged `source-review-pending` unless a
 *    record has been individually re-verified.
 *  - No population numbers are stored anywhere. Population trend, range, and
 *    threats appear only on records we have reviewed — never guessed.
 *  - Every `sourceUrls` entry was confirmed reachable (HTTP 200) on the
 *    review date below, matching the project's existing source-link standard.
 *  - `iucnUrl` is an IUCN Red List lookup link for the species. IUCN blocks
 *    automated requests, so these are human-facing lookup links, not scraped
 *    assessment pages, and never fabricated assessment IDs.
 *  - Index-only records never become standalone pages. Detailed profiles live
 *    at /endangered-animals/species/[slug]; existing-profile-linked records
 *    point at /animals/[slug].
 *
 * Later batches (2/3/4) live in species-batch2/3/4.ts and are concatenated
 * below. Region assignments live in regions.ts (REGION_BY_SLUG), kept separate
 * so every claim about where a species occurs is reviewable in one place.
 *
 * Verify any record against the live IUCN Red List entry before treating it as
 * definitive: https://www.iucnredlist.org/
 */

const PHASE1_SPECIES: readonly RedListSpeciesRecord[] = [
  // ===========================================================================
  // MAMMALS (34)
  // ===========================================================================
  rec({
    slug: "sumatran-orangutan",
    commonName: "Sumatran Orangutan",
    scientificName: "Pongo abelii",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Restricted to fragmented rainforest in the north of Sumatra, Indonesia.",
    primaryThreats: [
      "Deforestation for agriculture and palm oil",
      "Habitat fragmentation",
      "Illegal capture for the pet trade",
    ],
    sourceUrls: [adw("Pongo_abelii"), szoo("orangutan")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "bornean-orangutan",
    commonName: "Bornean Orangutan",
    scientificName: "Pongo pygmaeus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The island of Borneo, shared by Indonesia and Malaysia.",
    primaryThreats: [
      "Deforestation for agriculture and palm oil",
      "Habitat fragmentation",
      "Killing and illegal capture",
    ],
    sourceUrls: [adw("Pongo_pygmaeus"), szoo("orangutan")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "tapanuli-orangutan",
    commonName: "Tapanuli Orangutan",
    scientificName: "Pongo tapanuliensis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A small area of forest in the Batang Toru region of northern Sumatra, Indonesia.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "A planned hydroelectric development in its range",
      "Killing and capture",
    ],
    sourceUrls: [szoo("orangutan")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Described in 2017; one of the most range-restricted great apes, in the Batang Toru ecosystem of Sumatra.",
  }),
  rec({
    slug: "western-gorilla",
    commonName: "Western Gorilla",
    scientificName: "Gorilla gorilla",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Gorilla_gorilla"), szoo("western-lowland-gorilla")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "gorilla",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "eastern-gorilla",
    commonName: "Eastern Gorilla",
    scientificName: "Gorilla beringei",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Mountain and lowland forests of the eastern Democratic Republic of the Congo, Rwanda, and Uganda.",
    primaryThreats: [
      "Poaching",
      "Civil unrest and habitat loss",
      "Disease",
    ],
    sourceUrls: [adw("Gorilla_beringei")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Includes the mountain gorilla, whose closely monitored sub-population has shown localised recovery.",
  }),
  rec({
    slug: "chimpanzee",
    commonName: "Chimpanzee",
    scientificName: "Pan troglodytes",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Pan_troglodytes")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "chimpanzee",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bonobo",
    commonName: "Bonobo",
    scientificName: "Pan paniscus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Lowland rainforest south of the Congo River in the Democratic Republic of the Congo.",
    primaryThreats: [
      "Poaching for bushmeat",
      "Habitat loss and fragmentation",
      "Civil instability across its range",
    ],
    sourceUrls: [adw("Pan_paniscus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "ring-tailed-lemur",
    commonName: "Ring-tailed Lemur",
    scientificName: "Lemur catta",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Lemur_catta")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "lemur",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "indri",
    commonName: "Indri",
    scientificName: "Indri indri",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Rainforests of eastern Madagascar.",
    primaryThreats: [
      "Deforestation and slash-and-burn agriculture",
      "Hunting",
      "Habitat fragmentation",
    ],
    sourceUrls: [adw("Indri_indri")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "black-and-white-ruffed-lemur",
    commonName: "Black-and-white Ruffed Lemur",
    scientificName: "Varecia variegata",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Rainforests of eastern Madagascar.",
    primaryThreats: [
      "Deforestation and slash-and-burn agriculture",
      "Hunting",
      "Fragmentation",
    ],
    sourceUrls: [adw("Varecia_variegata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "aye-aye",
    commonName: "Aye-aye",
    scientificName: "Daubentonia madagascariensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests across Madagascar.",
    primaryThreats: [
      "Habitat loss",
      "Killing due to local superstition",
      "Fragmentation",
    ],
    sourceUrls: [adw("Daubentonia_madagascariensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "proboscis-monkey",
    commonName: "Proboscis Monkey",
    scientificName: "Nasalis larvatus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Endemic to Borneo, mainly in coastal mangrove, swamp, and riverine forest.",
    primaryThreats: [
      "Loss of mangrove and lowland forest",
      "Conversion of habitat to oil-palm plantations",
      "Hunting",
    ],
    sourceUrls: [adw("Nasalis_larvatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "golden-lion-tamarin",
    commonName: "Golden Lion Tamarin",
    scientificName: "Leontopithecus rosalia",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "stable",
    rangeSummary:
      "Remnant Atlantic Forest in the state of Rio de Janeiro, Brazil.",
    primaryThreats: [
      "Loss and fragmentation of Atlantic Forest",
      "Small, isolated populations",
    ],
    sourceUrls: [adw("Leontopithecus_rosalia"), szoo("golden-lion-tamarin")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "A long-running reintroduction programme in Brazil's Atlantic Forest is often cited as a conservation success story.",
  }),
  rec({
    slug: "tiger",
    commonName: "Tiger",
    scientificName: "Panthera tigris",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Panthera_tigris"), szoo("tiger")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "tiger",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "snow-leopard",
    commonName: "Snow Leopard",
    scientificName: "Panthera uncia",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "High mountains of Central and South Asia, across the Himalaya, Tibetan Plateau, and neighbouring ranges.",
    primaryThreats: [
      "Poaching and illegal trade in pelts and bones",
      "Retaliatory killing over livestock losses",
      "Loss and fragmentation of mountain habitat",
    ],
    sourceUrls: [adw("Uncia_uncia")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "lion",
    commonName: "Lion",
    scientificName: "Panthera leo",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Panthera_leo"), szoo("lion")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "lion",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "leopard",
    commonName: "Leopard",
    scientificName: "Panthera pardus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Panthera_pardus")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "leopard",
    imageStatus: "not-planned",
    notes:
      "Several leopard subspecies (e.g. the Amur and Arabian leopard) are assessed at higher risk than the species as a whole.",
  }),
  rec({
    slug: "cheetah",
    commonName: "Cheetah",
    scientificName: "Acinonyx jubatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Acinonyx_jubatus"), szoo("cheetah")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "cheetah",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sumatran-rhinoceros",
    commonName: "Sumatran Rhinoceros",
    scientificName: "Dicerorhinus sumatrensis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Survives only in small, scattered rainforest populations on Sumatra and Borneo, Indonesia.",
    primaryThreats: [
      "Very small, fragmented populations with few breeding opportunities",
      "Historical poaching for horn",
      "Habitat loss and isolation",
    ],
    sourceUrls: [adw("Dicerorhinus_sumatrensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "javan-rhinoceros",
    commonName: "Javan Rhinoceros",
    scientificName: "Rhinoceros sondaicus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "stable",
    rangeSummary:
      "Survives in a single wild population in Ujung Kulon National Park, Java, Indonesia.",
    primaryThreats: [
      "An extremely small, single population vulnerable to disease and disaster",
      "Historical poaching for horn",
      "Loss of habitat and competition from invasive plants",
    ],
    sourceUrls: [adw("Rhinoceros_sondaicus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "black-rhinoceros",
    commonName: "Black Rhinoceros",
    scientificName: "Diceros bicornis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "Found in fragmented populations across eastern and southern Africa, including Namibia, South Africa, Kenya, and Zimbabwe.",
    primaryThreats: [
      "Poaching for horn",
      "Habitat loss and fragmentation",
      "Small, isolated populations",
    ],
    sourceUrls: [adw("Diceros_bicornis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "greater-one-horned-rhinoceros",
    commonName: "Greater One-horned Rhinoceros",
    scientificName: "Rhinoceros unicornis",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "increasing",
    rangeSummary:
      "Floodplain grasslands and forests of northern India and Nepal.",
    primaryThreats: [
      "Poaching for horn",
      "Habitat loss to agriculture",
      "Concentration in few protected areas",
    ],
    sourceUrls: [adw("Rhinoceros_unicornis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Also called the Indian rhinoceros; recovery in India and Nepal is often cited as a conservation success.",
  }),
  rec({
    slug: "african-forest-elephant",
    commonName: "African Forest Elephant",
    scientificName: "Loxodonta cyclotis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Rainforests of central and West Africa.",
    primaryThreats: [
      "Poaching for ivory",
      "Habitat loss and fragmentation",
      "Slow reproduction",
    ],
    sourceUrls: [adw("Loxodonta_cyclotis"), adw("Loxodonta_africana")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Recognised as a separate species from the African bush elephant in the 2021 IUCN assessment.",
  }),
  rec({
    slug: "african-bush-elephant",
    commonName: "African Bush Elephant",
    scientificName: "Loxodonta africana",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Loxodonta_africana")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "elephant",
    imageStatus: "not-planned",
    notes:
      "Assessed separately from the African forest elephant since 2021. FaunaHub's general elephant profile is linked.",
  }),
  rec({
    slug: "asian-elephant",
    commonName: "Asian Elephant",
    scientificName: "Elephas maximus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Scattered across South and Southeast Asia, from India and Sri Lanka to Thailand, Indonesia, and southern China.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "Human-elephant conflict",
      "Poaching and illegal capture",
    ],
    sourceUrls: [adw("Elephas_maximus"), szoo("asian-elephant")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "giant-panda",
    commonName: "Giant Panda",
    scientificName: "Ailuropoda melanoleuca",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Ailuropoda_melanoleuca"), szoo("giant-panda")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "panda",
    imageStatus: "not-planned",
    notes:
      "Down-listed from Endangered to Vulnerable in 2016 following decades of habitat protection — a frequently cited example of status change.",
  }),
  rec({
    slug: "red-panda",
    commonName: "Red Panda",
    scientificName: "Ailurus fulgens",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Ailurus_fulgens"), szoo("red-panda")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "red-panda",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giraffe",
    commonName: "Giraffe",
    scientificName: "Giraffa camelopardalis",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Giraffa_camelopardalis")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "giraffe",
    imageStatus: "not-planned",
    notes:
      "Giraffe taxonomy is under active revision; some authorities now recognise multiple species and subspecies with differing risk levels.",
  }),
  rec({
    slug: "vaquita",
    commonName: "Vaquita",
    scientificName: "Phocoena sinus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Endemic to the northern Gulf of California (Sea of Cortez), Mexico — the smallest range of any porpoise.",
    primaryThreats: [
      "Drowning as bycatch in illegal gillnets (especially those set for the totoaba fish)",
      "An extremely small remaining population",
    ],
    sourceUrls: [adw("Phocoena_sinus"), noaa("vaquita")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "A porpoise endemic to the northern Gulf of California; widely reported as the world's most endangered marine mammal.",
  }),
  rec({
    slug: "amur-leopard",
    commonName: "Amur Leopard",
    scientificName: "Panthera pardus orientalis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "A leopard subspecies of the temperate forests of the Russian Far East and adjacent north-east China.",
    primaryThreats: [
      "Poaching of leopards and of the prey they depend on",
      "Habitat loss from logging and fires",
      "A very small population with low genetic diversity",
    ],
    sourceUrls: [adw("Panthera_pardus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "The Amur leopard is a northern subspecies of the leopard (Panthera pardus); cross-border protection has reportedly lifted its numbers from a few dozen to over a hundred.",
  }),
  rec({
    slug: "sea-otter",
    commonName: "Sea Otter",
    scientificName: "Enhydra lutris",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "Coastal North Pacific, from California through Alaska to the Russian Far East and northern Japan.",
    primaryThreats: [
      "Oil spills",
      "Historical fur hunting (now recovering)",
      "Entanglement and prey-related pressures",
    ],
    sourceUrls: [adw("Enhydra_lutris")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "african-wild-dog",
    commonName: "African Wild Dog",
    scientificName: "Lycaon pictus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Fragmented populations across sub-Saharan Africa, with strongholds in southern and eastern Africa.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "Conflict with livestock farmers",
      "Infectious disease and road deaths",
    ],
    sourceUrls: [adw("Lycaon_pictus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "polar-bear",
    commonName: "Polar Bear",
    scientificName: "Ursus maritimus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "unknown",
    rangeSummary:
      "Circumpolar across the Arctic sea ice of Canada, the United States (Alaska), Russia, Greenland, and Norway.",
    primaryThreats: [
      "Loss of sea-ice habitat linked to a warming climate",
      "Pollution",
      "Disturbance from industrial activity",
    ],
    sourceUrls: [adw("Ursus_maritimus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "sunda-pangolin",
    commonName: "Sunda Pangolin",
    scientificName: "Manis javanica",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests of Southeast Asia, including Indonesia, Malaysia, Thailand, and Vietnam.",
    primaryThreats: [
      "Poaching and trafficking for scales and meat",
      "Habitat loss",
    ],
    sourceUrls: [adw("Manis_javanica")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Pangolins are widely reported among the most trafficked wild mammals.",
  }),
  rec({
    slug: "tasmanian-devil",
    commonName: "Tasmanian Devil",
    scientificName: "Sarcophilus harrisii",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "The Australian island of Tasmania.",
    primaryThreats: [
      "A contagious facial-tumour disease (DFTD)",
      "Road deaths",
      "Past persecution",
    ],
    sourceUrls: [adw("Sarcophilus_harrisii")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),

  // ===========================================================================
  // BIRDS (20)
  // ===========================================================================
  rec({
    slug: "california-condor",
    commonName: "California Condor",
    scientificName: "Gymnogyps californianus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "A small, intensively managed population in the south-western United States and Baja California, Mexico.",
    primaryThreats: [
      "Lead poisoning from spent ammunition",
      "Habitat loss",
      "Collisions and micro-trash ingestion",
    ],
    sourceUrls: [
      fws("california-condor-gymnogyps-californianus"),
      adw("Gymnogyps_californianus"),
    ],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Recovered from a low of 22 birds in the 1980s through captive breeding and release; still dependent on active management.",
  }),
  rec({
    slug: "philippine-eagle",
    commonName: "Philippine Eagle",
    scientificName: "Pithecophaga jefferyi",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Endemic to old-growth rainforest on four Philippine islands: Luzon, Samar, Leyte, and Mindanao.",
    primaryThreats: [
      "Deforestation and loss of old-growth forest",
      "Hunting and shooting",
      "A very low reproductive rate",
    ],
    sourceUrls: [adw("Pithecophaga_jefferyi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "kakapo",
    commonName: "Kākāpō",
    scientificName: "Strigops habroptilus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "Survives only on predator-free islands of New Zealand under intensive management.",
    primaryThreats: [
      "Introduced mammalian predators",
      "Very small population size",
      "Disease and low genetic diversity",
    ],
    sourceUrls: [adw("Strigops_habroptila")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "A flightless nocturnal parrot from New Zealand managed on predator-free islands.",
  }),
  rec({
    slug: "spixs-macaw",
    commonName: "Spix's Macaw",
    scientificName: "Cyanopsitta spixii",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "unknown",
    rangeSummary:
      "Native to a small area of north-eastern Brazil; reintroduction from captive-bred birds is under way.",
    primaryThreats: [
      "Past trapping for the cage-bird trade",
      "Loss of its specialised dry-forest habitat",
      "Tiny founder population",
    ],
    sourceUrls: [adw("Cyanopsitta_spixii")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Considered Critically Endangered (long regarded as extinct in the wild); subject of an ongoing reintroduction effort in Brazil.",
  }),
  rec({
    slug: "hyacinth-macaw",
    commonName: "Hyacinth Macaw",
    scientificName: "Anodorhynchus hyacinthinus",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "stable",
    rangeSummary:
      "Central and eastern South America, especially the Pantanal wetlands of Brazil.",
    primaryThreats: [
      "Past trapping for the pet trade",
      "Habitat loss and conversion",
    ],
    sourceUrls: [adw("Anodorhynchus_hyacinthinus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "great-green-macaw",
    commonName: "Great Green Macaw",
    scientificName: "Ara ambiguus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests from Central America to north-western South America.",
    primaryThreats: [
      "Deforestation",
      "Trapping for the pet trade",
      "Loss of key nesting trees",
    ],
    sourceUrls: [birdlife("great-green-macaw-ara-ambiguus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "whooping-crane",
    commonName: "Whooping Crane",
    scientificName: "Grus americana",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "North America; the main wild flock migrates between Canada and the Texas Gulf coast, with additional reintroduced flocks.",
    primaryThreats: [
      "A very small population",
      "Habitat loss along migration routes",
      "Collisions and disturbance",
    ],
    sourceUrls: [adw("Grus_americana"), szoo("whooping-crane")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "siberian-crane",
    commonName: "Siberian Crane",
    scientificName: "Leucogeranus leucogeranus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds in Arctic Russia and migrates to wintering grounds, chiefly in China.",
    primaryThreats: [
      "Loss of wetland stopover and wintering sites",
      "Dams altering rivers",
      "Disturbance",
    ],
    sourceUrls: [adw("Grus_leucogeranus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bali-myna",
    commonName: "Bali Myna",
    scientificName: "Leucopsar rothschildi",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "stable",
    rangeSummary:
      "The island of Bali, Indonesia.",
    primaryThreats: [
      "Trapping for the cage-bird trade",
      "A tiny range",
      "Habitat loss",
    ],
    sourceUrls: [birdlife("bali-myna-leucopsar-rothschildi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "white-rumped-vulture",
    commonName: "White-rumped Vulture",
    scientificName: "Gyps bengalensis",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "South and Southeast Asia.",
    primaryThreats: [
      "Poisoning by the veterinary drug diclofenac in livestock carcasses",
      "Reduced food",
      "Habitat change",
    ],
    sourceUrls: [adw("Gyps_bengalensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "South Asian vulture declines have been widely linked to the veterinary drug diclofenac.",
  }),
  rec({
    slug: "egyptian-vulture",
    commonName: "Egyptian Vulture",
    scientificName: "Neophron percnopterus",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Southern Europe, Africa, the Middle East, and South Asia.",
    primaryThreats: [
      "Poisoning",
      "Veterinary drugs in carcasses",
      "Electrocution and habitat change",
    ],
    sourceUrls: [adw("Neophron_percnopterus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "steller-sea-eagle",
    commonName: "Steller's Sea Eagle",
    scientificName: "Haliaeetus pelagicus",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Coasts of north-eastern Asia, especially the Russian Far East, wintering around Japan and Korea.",
    primaryThreats: [
      "Habitat alteration along rivers and coasts",
      "Lead poisoning from carcasses",
      "Overfishing of prey",
    ],
    sourceUrls: [adw("Haliaeetus_pelagicus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "harpy-eagle",
    commonName: "Harpy Eagle",
    scientificName: "Harpia harpyja",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Lowland tropical rainforest from southern Mexico through Central America to northern Argentina.",
    primaryThreats: [
      "Deforestation",
      "Shooting",
      "A naturally low reproductive rate",
    ],
    sourceUrls: [adw("Harpia_harpyja")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "african-penguin",
    commonName: "African Penguin",
    scientificName: "Spheniscus demersus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds on the coasts and islands of South Africa and Namibia.",
    primaryThreats: [
      "Shortage of prey fish (sardines and anchovies)",
      "Oil spills",
      "Historical egg and guano collection",
    ],
    sourceUrls: [adw("Spheniscus_demersus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Reported as up-listed to Critically Endangered in 2024 amid steep colony declines; confirm the current category on the live IUCN entry.",
  }),
  rec({
    slug: "galapagos-penguin",
    commonName: "Galápagos Penguin",
    scientificName: "Spheniscus mendiculus",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "The Galápagos Islands, on the equator.",
    primaryThreats: [
      "Ocean changes that reduce food (such as El Niño)",
      "Introduced predators and disease",
      "Bycatch",
    ],
    sourceUrls: [adw("Spheniscus_mendiculus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "yellow-eyed-penguin",
    commonName: "Yellow-eyed Penguin",
    scientificName: "Megadyptes antipodes",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Coasts of southern New Zealand and nearby sub-Antarctic islands.",
    primaryThreats: [
      "Disease and food shortages",
      "Introduced predators",
      "Habitat disturbance and bycatch",
    ],
    sourceUrls: [adw("Megadyptes_antipodes")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "atlantic-puffin",
    commonName: "Atlantic Puffin",
    scientificName: "Fratercula arctica",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Coasts and islands of the North Atlantic, breeding from North America to Europe.",
    primaryThreats: [
      "Shortage of small prey fish",
      "Changing ocean conditions",
      "Invasive predators at colonies",
    ],
    sourceUrls: [adw("Fratercula_arctica")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "shoebill",
    commonName: "Shoebill",
    scientificName: "Balaeniceps rex",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Freshwater swamps of central tropical Africa, notably South Sudan, Uganda, and Zambia.",
    primaryThreats: [
      "Wetland degradation and drainage",
      "Disturbance and nest destruction",
      "Capture for the bird trade",
    ],
    sourceUrls: [adw("Balaeniceps_rex")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "secretarybird",
    commonName: "Secretarybird",
    scientificName: "Sagittarius serpentarius",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Grasslands and savannas across sub-Saharan Africa.",
    primaryThreats: [
      "Loss and degradation of grassland",
      "Disturbance",
      "Collisions and poisoning",
    ],
    sourceUrls: [adw("Sagittarius_serpentarius")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "regent-honeyeater",
    commonName: "Regent Honeyeater",
    scientificName: "Anthochaera phrygia",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "South-eastern Australia.",
    primaryThreats: [
      "Loss of woodland habitat",
      "A small, scattered population",
      "Loss of song culture as numbers fall",
    ],
    sourceUrls: [birdlife("regent-honeyeater-anthochaera-phrygia")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // ===========================================================================
  // REPTILES & AMPHIBIANS (18)
  // ===========================================================================
  rec({
    slug: "hawksbill-turtle",
    commonName: "Hawksbill Turtle",
    scientificName: "Eretmochelys imbricata",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Tropical and subtropical reefs and coastal waters across the Atlantic, Indian, and Pacific Oceans.",
    primaryThreats: [
      "Historical and ongoing tortoiseshell trade",
      "Coral-reef and nesting-beach habitat loss",
      "Fisheries bycatch and egg collection",
    ],
    sourceUrls: [noaa("hawksbill-turtle"), adw("Eretmochelys_imbricata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "kemps-ridley-turtle",
    commonName: "Kemp's Ridley Turtle",
    scientificName: "Lepidochelys kempii",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "unknown",
    rangeSummary:
      "Mainly the Gulf of Mexico and the western Atlantic, nesting principally on the coast of Mexico.",
    primaryThreats: [
      "Bycatch in fishing gear",
      "Past egg collection",
      "Coastal development and pollution",
    ],
    sourceUrls: [noaa("kemps-ridley-turtle"), adw("Lepidochelys_kempii")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "green-turtle",
    commonName: "Green Turtle",
    scientificName: "Chelonia mydas",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [noaa("green-turtle"), adw("Chelonia_mydas")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "sea-turtle",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "leatherback-turtle",
    commonName: "Leatherback Turtle",
    scientificName: "Dermochelys coriacea",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "The most wide-ranging sea turtle, found across tropical and temperate oceans worldwide.",
    primaryThreats: [
      "Fisheries bycatch",
      "Egg collection and loss of nesting beaches",
      "Plastic ingestion and vessel strikes",
    ],
    sourceUrls: [noaa("leatherback-turtle"), adw("Dermochelys_coriacea")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Globally Vulnerable, but several regional sub-populations are assessed as Critically Endangered.",
  }),
  rec({
    slug: "loggerhead-turtle",
    commonName: "Loggerhead Turtle",
    scientificName: "Caretta caretta",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Temperate and tropical oceans worldwide, nesting on many continents' coasts.",
    primaryThreats: [
      "Bycatch in fishing gear",
      "Loss of nesting beaches",
      "Pollution and climate effects",
    ],
    sourceUrls: [noaa("loggerhead-turtle"), adw("Caretta_caretta")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "gharial",
    commonName: "Gharial",
    scientificName: "Gavialis gangeticus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "unknown",
    rangeSummary:
      "A few river systems of the northern Indian subcontinent, chiefly in India and Nepal.",
    primaryThreats: [
      "Loss of riverine sandbank habitat",
      "Dams and water extraction",
      "Fishing nets and egg collection",
    ],
    sourceUrls: [adw("Gavialis_gangeticus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "chinese-alligator",
    commonName: "Chinese Alligator",
    scientificName: "Alligator sinensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The lower Yangtze River region of eastern China.",
    primaryThreats: [
      "Loss of wetland habitat to agriculture",
      "A tiny wild range",
      "Past persecution",
    ],
    sourceUrls: [adw("Alligator_sinensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "ploughshare-tortoise",
    commonName: "Ploughshare Tortoise",
    scientificName: "Astrochelys yniphora",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A small area of north-western Madagascar.",
    primaryThreats: [
      "Poaching for the illegal pet trade",
      "Habitat fires",
      "A tiny range",
    ],
    sourceUrls: [adw("Astrochelys_yniphora")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "radiated-tortoise",
    commonName: "Radiated Tortoise",
    scientificName: "Astrochelys radiata",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Dry southern Madagascar.",
    primaryThreats: [
      "Poaching for food and the pet trade",
      "Habitat loss",
    ],
    sourceUrls: [adw("Astrochelys_radiata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "komodo-dragon",
    commonName: "Komodo Dragon",
    scientificName: "Varanus komodoensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [adw("Varanus_komodoensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "komodo-dragon",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "axolotl",
    commonName: "Axolotl",
    scientificName: "Ambystoma mexicanum",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Native only to the remnant lake and canal system of Xochimilco near Mexico City.",
    primaryThreats: [
      "Habitat loss and urban water pollution",
      "Invasive introduced fish such as tilapia and carp",
      "Reduced and degraded wetland habitat",
    ],
    sourceUrls: [adw("Ambystoma_mexicanum")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Abundant in captivity and research, but the wild population in Xochimilco is assessed as Critically Endangered.",
  }),
  rec({
    slug: "chinese-giant-salamander",
    commonName: "Chinese Giant Salamander",
    scientificName: "Andrias davidianus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Mountain streams and rivers of central, southern, and eastern China.",
    primaryThreats: [
      "Collection for food and farming",
      "Habitat loss and degradation",
      "Pollution",
    ],
    sourceUrls: [adw("Andrias_davidianus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "One of the largest living amphibians.",
  }),
  rec({
    slug: "panamanian-golden-frog",
    commonName: "Panamanian Golden Frog",
    scientificName: "Atelopus zeteki",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Streams and forests of central Panama.",
    primaryThreats: [
      "The amphibian fungal disease chytridiomycosis",
      "Habitat loss",
      "Past collection",
    ],
    sourceUrls: [amphibiaweb("Atelopus", "zeteki")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Amphibian declines have been widely linked to the chytrid fungus alongside habitat loss.",
  }),
  rec({
    slug: "lemur-leaf-frog",
    commonName: "Lemur Leaf Frog",
    scientificName: "Agalychnis lemur",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests of Central America, including Costa Rica and Panama.",
    primaryThreats: [
      "The amphibian fungal disease chytridiomycosis",
      "Habitat loss",
      "A declining range",
    ],
    sourceUrls: [amphibiaweb("Agalychnis", "lemur")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "mountain-chicken-frog",
    commonName: "Mountain Chicken Frog",
    scientificName: "Leptodactylus fallax",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The Caribbean islands of Dominica and Montserrat.",
    primaryThreats: [
      "The amphibian fungal disease chytridiomycosis",
      "Past hunting for food",
      "Volcanic activity and habitat loss",
    ],
    sourceUrls: [amphibiaweb("Leptodactylus", "fallax")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "kihansi-spray-toad",
    commonName: "Kihansi Spray Toad",
    scientificName: "Nectophrynoides asperginis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EW",
    sourceUrls: [amphibiaweb("Nectophrynoides", "asperginis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Listed Extinct in the Wild; subject of a captive-breeding and reintroduction programme in Tanzania.",
  }),
  rec({
    slug: "olm",
    commonName: "Olm",
    scientificName: "Proteus anguinus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Underground waters of the Dinaric karst in south-eastern Europe.",
    primaryThreats: [
      "Water pollution reaching aquifers",
      "Disturbance of cave systems",
      "Its restricted, fragile habitat",
    ],
    sourceUrls: [adw("Proteus_anguinus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "A cave-dwelling, aquatic salamander of the Western Balkans.",
  }),
  rec({
    slug: "titicaca-water-frog",
    commonName: "Lake Titicaca Water Frog",
    scientificName: "Telmatobius culeus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Lake Titicaca, on the border of Peru and Bolivia.",
    primaryThreats: [
      "Harvesting for food and drinks",
      "Pollution",
      "Introduced trout and disease",
    ],
    sourceUrls: [adw("Telmatobius_culeus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // ===========================================================================
  // FISH (16)
  // ===========================================================================
  rec({
    slug: "whale-shark",
    commonName: "Whale Shark",
    scientificName: "Rhincodon typus",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "The largest living fish, found in warm-temperate and tropical oceans worldwide.",
    primaryThreats: [
      "Targeted and incidental fishing",
      "Vessel strikes",
      "Disturbance at aggregation sites",
    ],
    sourceUrls: [adw("Rhincodon_typus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "great-white-shark",
    commonName: "Great White Shark",
    scientificName: "Carcharodon carcharias",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "unknown",
    rangeSummary:
      "Coastal and offshore temperate and subtropical seas around the world.",
    primaryThreats: [
      "Targeted and incidental fishing",
      "Bycatch in other fisheries",
      "Demand for jaws, teeth, and fins",
    ],
    sourceUrls: [noaa("white-shark"), adw("Carcharodon_carcharias")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "scalloped-hammerhead",
    commonName: "Scalloped Hammerhead",
    scientificName: "Sphyrna lewini",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Warm coastal and offshore waters worldwide.",
    primaryThreats: [
      "Overfishing, including for the shark-fin trade",
      "Bycatch",
    ],
    sourceUrls: [noaa("scalloped-hammerhead-shark"), adw("Sphyrna_lewini")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "great-hammerhead",
    commonName: "Great Hammerhead",
    scientificName: "Sphyrna mokarran",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Warm coastal and offshore waters worldwide.",
    primaryThreats: [
      "Overfishing, including for fins",
      "Bycatch",
      "A low reproductive rate",
    ],
    sourceUrls: [adw("Sphyrna_mokarran")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "oceanic-whitetip-shark",
    commonName: "Oceanic Whitetip Shark",
    scientificName: "Carcharhinus longimanus",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Open tropical and subtropical oceans worldwide.",
    primaryThreats: [
      "Overfishing and the fin trade",
      "Bycatch",
    ],
    sourceUrls: [noaa("oceanic-whitetip-shark"), adw("Carcharhinus_longimanus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "shortfin-mako",
    commonName: "Shortfin Mako",
    scientificName: "Isurus oxyrinchus",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Temperate and tropical oceans worldwide.",
    primaryThreats: [
      "Overfishing (targeted and bycatch)",
      "Demand for meat and fins",
      "A low reproductive rate",
    ],
    sourceUrls: [noaa("shortfin-mako-shark"), adw("Isurus_oxyrinchus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giant-manta-ray",
    commonName: "Giant Manta Ray",
    scientificName: "Mobula birostris",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Tropical and subtropical oceans worldwide, mostly in the open sea.",
    primaryThreats: [
      "Targeted fishing for gill plates",
      "Bycatch",
      "A very low reproductive rate",
    ],
    sourceUrls: [noaa("giant-manta-ray"), adw("Manta_birostris")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "reef-manta-ray",
    commonName: "Reef Manta Ray",
    scientificName: "Mobula alfredi",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Tropical and subtropical coastal and reef waters of the Indo-Pacific and beyond.",
    primaryThreats: [
      "Fishing for gill plates",
      "Bycatch",
      "A very low reproductive rate",
    ],
    sourceUrls: [adw("Manta_alfredi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "largetooth-sawfish",
    commonName: "Largetooth Sawfish",
    scientificName: "Pristis pristis",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Historically widespread in warm coastal waters and rivers; now greatly reduced.",
    primaryThreats: [
      "Entanglement in fishing nets (its saw is easily caught)",
      "Habitat loss",
      "Past targeted fishing",
    ],
    sourceUrls: [noaa("largetooth-sawfish")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "smalltooth-sawfish",
    commonName: "Smalltooth Sawfish",
    scientificName: "Pristis pectinata",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Warm coastal and estuarine waters, much reduced from a once-wide range.",
    primaryThreats: [
      "Entanglement in fishing nets (its saw snags easily)",
      "Habitat loss",
      "Past targeted fishing",
    ],
    sourceUrls: [noaa("smalltooth-sawfish"), adw("Pristis_pectinata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "european-eel",
    commonName: "European Eel",
    scientificName: "Anguilla anguilla",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Born in the Atlantic's Sargasso Sea; lives in fresh and coastal waters across Europe and North Africa.",
    primaryThreats: [
      "Barriers to migration (dams and weirs)",
      "Overfishing of young eels",
      "Disease and changing ocean conditions",
    ],
    sourceUrls: [adw("Anguilla_anguilla")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "beluga-sturgeon",
    commonName: "Beluga Sturgeon",
    scientificName: "Huso huso",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The Caspian and Black Sea basins and their large rivers.",
    primaryThreats: [
      "Overfishing for caviar",
      "Poaching",
      "Dams blocking spawning migrations",
    ],
    sourceUrls: [adw("Huso_huso")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Source of beluga caviar; heavily affected by overfishing.",
  }),
  rec({
    slug: "chinese-sturgeon",
    commonName: "Chinese Sturgeon",
    scientificName: "Acipenser sinensis",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The Yangtze River and adjacent seas of China.",
    primaryThreats: [
      "Dams blocking spawning migrations",
      "Pollution and habitat loss",
      "Past overfishing",
    ],
    sourceUrls: [fishbase("Acipenser-sinensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "humphead-wrasse",
    commonName: "Humphead Wrasse",
    scientificName: "Cheilinus undulatus",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Coral reefs of the Indo-Pacific.",
    primaryThreats: [
      "Overfishing for the live-reef-food-fish trade",
      "Cyanide and destructive fishing",
      "A slow reproductive rate",
    ],
    sourceUrls: [fishbase("Cheilinus-undulatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Also called the Napoleon wrasse; a large, slow-growing reef fish.",
  }),
  rec({
    slug: "coelacanth",
    commonName: "West Indian Ocean Coelacanth",
    scientificName: "Latimeria chalumnae",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Deep waters off eastern Africa, including around the Comoros.",
    primaryThreats: [
      "Accidental capture by deep-set fishing gear",
      "A very small, slow-breeding population",
    ],
    sourceUrls: [adw("Latimeria_chalumnae")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "A deep-water 'living fossil' lineage once thought extinct until rediscovery in 1938.",
  }),
  rec({
    slug: "lined-seahorse",
    commonName: "Lined Seahorse",
    scientificName: "Hippocampus erectus",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [adw("Hippocampus_erectus")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "seahorse",
    imageStatus: "not-planned",
  }),

  // ===========================================================================
  // INVERTEBRATES (12)
  // ===========================================================================
  rec({
    slug: "staghorn-coral",
    commonName: "Staghorn Coral",
    scientificName: "Acropora cervicornis",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A fast-growing branching coral of Caribbean and western Atlantic reefs.",
    primaryThreats: [
      "Ocean warming and coral bleaching",
      "Coral disease",
      "Ocean acidification and storm damage",
    ],
    sourceUrls: [noaa("staghorn-coral")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "elkhorn-coral",
    commonName: "Elkhorn Coral",
    scientificName: "Acropora palmata",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Shallow Caribbean reefs.",
    primaryThreats: [
      "Warming-driven bleaching",
      "Coral disease",
      "Storms and pollution",
    ],
    sourceUrls: [noaa("elkhorn-coral")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lobed-star-coral",
    commonName: "Lobed Star Coral",
    scientificName: "Orbicella franksi",
    taxonGroup: "invertebrates",
    redListCategory: "VU",
    sourceUrls: [noaa("lobed-star-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "boulder-star-coral",
    commonName: "Boulder Star Coral",
    scientificName: "Orbicella annularis",
    taxonGroup: "invertebrates",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Caribbean and western Atlantic reefs.",
    primaryThreats: [
      "Warming-driven bleaching",
      "Coral disease",
      "Pollution and reef degradation",
    ],
    sourceUrls: [noaa("boulder-star-coral")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "white-abalone",
    commonName: "White Abalone",
    scientificName: "Haliotis sorenseni",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Rocky seabeds off southern California, USA, and Baja California, Mexico.",
    primaryThreats: [
      "Past overfishing",
      "Very low numbers limiting reproduction",
      "Disease",
    ],
    sourceUrls: [noaa("white-abalone")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "rusty-patched-bumble-bee",
    commonName: "Rusty Patched Bumble Bee",
    scientificName: "Bombus affinis",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Eastern and midwestern North America, in a much-reduced range.",
    primaryThreats: [
      "Disease spread from managed bees",
      "Pesticides",
      "Habitat loss",
    ],
    sourceUrls: [fws("rusty-patched-bumble-bee-bombus-affinis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "franklins-bumble-bee",
    commonName: "Franklin's Bumble Bee",
    scientificName: "Bombus franklini",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A very small area of southern Oregon and northern California, USA.",
    primaryThreats: [
      "Disease spread from managed bees",
      "Pesticides",
      "Habitat loss",
    ],
    sourceUrls: [fws("franklins-bumble-bee-bombus-franklini")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Has not been seen since 2006 and may be extinct.",
  }),
  rec({
    slug: "american-burying-beetle",
    commonName: "American Burying Beetle",
    scientificName: "Nicrophorus americanus",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Scattered sites in North America, much reduced from its former range.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "Loss of suitable carcasses for breeding",
      "Light pollution and other pressures",
    ],
    sourceUrls: [fws("american-burying-beetle-nicrophorus-americanus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "migratory-monarch-butterfly",
    commonName: "Monarch Butterfly (migratory)",
    scientificName: "Danaus plexippus plexippus",
    taxonGroup: "invertebrates",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "North America, with famous long-distance migrations to overwintering sites in Mexico and coastal California.",
    primaryThreats: [
      "Loss of milkweed and breeding habitat",
      "Loss and degradation of overwintering forest",
      "Pesticides and climate extremes",
    ],
    sourceUrls: [
      fws("monarch-butterfly-danaus-plexippus"),
      adw("Danaus_plexippus"),
    ],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "The 2022 Endangered listing applies to the migratory monarch subspecies. The wider species was assessed separately; confirm the relevant entry on the live IUCN list.",
  }),
  rec({
    slug: "mountainous-star-coral",
    commonName: "Mountainous Star Coral",
    scientificName: "Orbicella faveolata",
    taxonGroup: "invertebrates",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Caribbean and western Atlantic reefs.",
    primaryThreats: [
      "Warming-driven bleaching",
      "Coral disease",
      "Pollution and reef degradation",
    ],
    sourceUrls: [noaa("mountainous-star-coral")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lord-howe-stick-insect",
    commonName: "Lord Howe Island Stick Insect",
    scientificName: "Dryococelus australis",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "stable",
    rangeSummary:
      "Lord Howe Island group in the Tasman Sea, between Australia and New Zealand.",
    primaryThreats: [
      "Introduced rats (which wiped it out on the main island)",
      "A tiny natural range",
      "Vulnerability of a small population",
    ],
    sourceUrls: ["https://zoo.org.au/melbourne/animals/lord-howe-island-stick-insect/"],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Rediscovered on Ball's Pyramid after being thought extinct; subject of a captive-breeding programme.",
  }),
  rec({
    slug: "rough-cactus-coral",
    commonName: "Rough Cactus Coral",
    scientificName: "Mycetophyllia ferox",
    taxonGroup: "invertebrates",
    redListCategory: "VU",
    sourceUrls: [noaa("rough-cactus-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
];

/**
 * The full Red List dataset: Phase 1 plus every later batch, concatenated in
 * one frozen array. All consumers import RED_LIST_SPECIES from here.
 */
export const RED_LIST_SPECIES: readonly RedListSpeciesRecord[] = [
  ...PHASE1_SPECIES,
  ...RED_LIST_SPECIES_BATCH2,
  ...RED_LIST_SPECIES_BATCH3,
  ...RED_LIST_SPECIES_BATCH4,
  ...RED_LIST_SPECIES_BATCH5,
];

export const RED_LIST_SPECIES_COUNT = RED_LIST_SPECIES.length;
