import type { RedListSpeciesRecord } from "./types";
import { RED_LIST_LAST_REVIEW } from "./methodology";

/**
 * Red List Species Intelligence — Phase 1 index dataset (100 records).
 *
 * COMPLIANCE POSTURE (read before editing):
 *  - Categories reflect widely published IUCN Red List assessments for
 *    well-documented, stably classified species. They are shown for
 *    educational orientation and are flagged `source-review-pending` unless a
 *    record has been individually re-verified.
 *  - No population numbers are stored anywhere. Population trend, range, and
 *    threats appear only on records we have reviewed — never guessed.
 *  - Every `sourceUrls` entry was confirmed reachable (HTTP 200) on the
 *    review date below, matching the project's existing source-link standard.
 *  - `iucnUrl` is an IUCN Red List lookup link for the species. IUCN blocks
 *    automated requests, so these are human-facing lookup links, not scraped
 *    assessment pages, and never fabricated assessment IDs.
 *  - Index-only records never become standalone pages. Detailed profiles live
 *    at /endangered-animals/species/[slug]; existing-profile-linked records
 *    point at /animals/[slug].
 *
 * Verify any record against the live IUCN Red List entry before treating it as
 * definitive: https://www.iucnredlist.org/
 */

const LAST_VERIFIED = RED_LIST_LAST_REVIEW;

/** Animal Diversity Web species account (University of Michigan). */
const adw = (binomial: string): string =>
  `https://animaldiversity.org/accounts/${binomial}/`;
/** NOAA Fisheries species page. */
const noaa = (slug: string): string =>
  `https://www.fisheries.noaa.gov/species/${slug}`;
/** Smithsonian's National Zoo & Conservation Biology Institute species page. */
const szoo = (slug: string): string =>
  `https://nationalzoo.si.edu/animals/${slug}`;
/** U.S. Fish & Wildlife Service species profile. */
const fws = (slug: string): string => `https://www.fws.gov/species/${slug}`;
/** BirdLife International DataZone factsheet (the Red List authority for birds). */
const birdlife = (slug: string): string =>
  `http://datazone.birdlife.org/species/factsheet/${slug}`;
/** FishBase species summary. */
const fishbase = (binomialDash: string): string =>
  `https://www.fishbase.se/summary/${binomialDash}.html`;
/** AmphibiaWeb species query (University of California, Berkeley). */
const amphibiaweb = (genus: string, species: string): string =>
  `https://amphibiaweb.org/cgi/amphib_query?where-genus=${genus}&where-species=${species}`;
/** IUCN Red List species lookup link (human-facing, not a scraped page). */
const iucn = (scientificName: string): string =>
  `https://www.iucnredlist.org/search?query=${encodeURIComponent(
    scientificName,
  )}&searchType=species`;

const CAT_LABEL = {
  CR: "Critically Endangered",
  EN: "Endangered",
  VU: "Vulnerable",
  NT: "Near Threatened",
  LC: "Least Concern",
  DD: "Data Deficient",
  EW: "Extinct in the Wild",
  EX: "Extinct",
  NE: "Not Evaluated",
} as const;

/** Builds a record with shared defaults to keep the dataset DRY and consistent. */
function rec(
  r: Omit<RedListSpeciesRecord, "redListCategoryLabel" | "lastVerified" | "iucnUrl"> & {
    iucnUrl?: string;
  },
): RedListSpeciesRecord {
  return {
    ...r,
    redListCategoryLabel: CAT_LABEL[r.redListCategory],
    iucnUrl: r.iucnUrl ?? iucn(r.scientificName),
    lastVerified: LAST_VERIFIED,
  };
}

export const RED_LIST_SPECIES: readonly RedListSpeciesRecord[] = [
  // ===========================================================================
  // MAMMALS (34)
  // ===========================================================================
  rec({
    slug: "sumatran-orangutan",
    commonName: "Sumatran Orangutan",
    scientificName: "Pongo abelii",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Restricted to fragmented rainforest in the north of Sumatra, Indonesia.",
    primaryThreats: [
      "Deforestation for agriculture and palm oil",
      "Habitat fragmentation",
      "Illegal capture for the pet trade",
    ],
    sourceUrls: [adw("Pongo_abelii"), szoo("orangutan")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "bornean-orangutan",
    commonName: "Bornean Orangutan",
    scientificName: "Pongo pygmaeus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Pongo_pygmaeus"), szoo("orangutan")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "tapanuli-orangutan",
    commonName: "Tapanuli Orangutan",
    scientificName: "Pongo tapanuliensis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [szoo("orangutan")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Described in 2017; one of the most range-restricted great apes, in the Batang Toru ecosystem of Sumatra.",
  }),
  rec({
    slug: "western-gorilla",
    commonName: "Western Gorilla",
    scientificName: "Gorilla gorilla",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Gorilla_gorilla"), szoo("western-lowland-gorilla")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "gorilla",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "eastern-gorilla",
    commonName: "Eastern Gorilla",
    scientificName: "Gorilla beringei",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Gorilla_beringei")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Includes the mountain gorilla, whose closely monitored sub-population has shown localised recovery.",
  }),
  rec({
    slug: "chimpanzee",
    commonName: "Chimpanzee",
    scientificName: "Pan troglodytes",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Pan_troglodytes")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "chimpanzee",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bonobo",
    commonName: "Bonobo",
    scientificName: "Pan paniscus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Pan_paniscus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "ring-tailed-lemur",
    commonName: "Ring-tailed Lemur",
    scientificName: "Lemur catta",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Lemur_catta")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "lemur",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "indri",
    commonName: "Indri",
    scientificName: "Indri indri",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Indri_indri")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "black-and-white-ruffed-lemur",
    commonName: "Black-and-white Ruffed Lemur",
    scientificName: "Varecia variegata",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Varecia_variegata")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "aye-aye",
    commonName: "Aye-aye",
    scientificName: "Daubentonia madagascariensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Daubentonia_madagascariensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "proboscis-monkey",
    commonName: "Proboscis Monkey",
    scientificName: "Nasalis larvatus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Nasalis_larvatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "golden-lion-tamarin",
    commonName: "Golden Lion Tamarin",
    scientificName: "Leontopithecus rosalia",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Leontopithecus_rosalia"), szoo("golden-lion-tamarin")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "A long-running reintroduction programme in Brazil's Atlantic Forest is often cited as a conservation success story.",
  }),
  rec({
    slug: "tiger",
    commonName: "Tiger",
    scientificName: "Panthera tigris",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Panthera_tigris"), szoo("tiger")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "tiger",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "snow-leopard",
    commonName: "Snow Leopard",
    scientificName: "Panthera uncia",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Uncia_uncia")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lion",
    commonName: "Lion",
    scientificName: "Panthera leo",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Panthera_leo"), szoo("lion")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "lion",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "leopard",
    commonName: "Leopard",
    scientificName: "Panthera pardus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Panthera_pardus")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "leopard",
    imageStatus: "not-planned",
    notes:
      "Several leopard subspecies (e.g. the Amur and Arabian leopard) are assessed at higher risk than the species as a whole.",
  }),
  rec({
    slug: "cheetah",
    commonName: "Cheetah",
    scientificName: "Acinonyx jubatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Acinonyx_jubatus"), szoo("cheetah")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "cheetah",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sumatran-rhinoceros",
    commonName: "Sumatran Rhinoceros",
    scientificName: "Dicerorhinus sumatrensis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Dicerorhinus_sumatrensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "javan-rhinoceros",
    commonName: "Javan Rhinoceros",
    scientificName: "Rhinoceros sondaicus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Rhinoceros_sondaicus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "black-rhinoceros",
    commonName: "Black Rhinoceros",
    scientificName: "Diceros bicornis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Diceros_bicornis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "greater-one-horned-rhinoceros",
    commonName: "Greater One-horned Rhinoceros",
    scientificName: "Rhinoceros unicornis",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Rhinoceros_unicornis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Also called the Indian rhinoceros; recovery in India and Nepal is often cited as a conservation success.",
  }),
  rec({
    slug: "african-forest-elephant",
    commonName: "African Forest Elephant",
    scientificName: "Loxodonta cyclotis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Loxodonta_cyclotis"), adw("Loxodonta_africana")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Recognised as a separate species from the African bush elephant in the 2021 IUCN assessment.",
  }),
  rec({
    slug: "african-bush-elephant",
    commonName: "African Bush Elephant",
    scientificName: "Loxodonta africana",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Loxodonta_africana")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "elephant",
    imageStatus: "not-planned",
    notes:
      "Assessed separately from the African forest elephant since 2021. FaunaHub's general elephant profile is linked.",
  }),
  rec({
    slug: "asian-elephant",
    commonName: "Asian Elephant",
    scientificName: "Elephas maximus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Elephas_maximus"), szoo("asian-elephant")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giant-panda",
    commonName: "Giant Panda",
    scientificName: "Ailuropoda melanoleuca",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Ailuropoda_melanoleuca"), szoo("giant-panda")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "panda",
    imageStatus: "not-planned",
    notes:
      "Down-listed from Endangered to Vulnerable in 2016 following decades of habitat protection — a frequently cited example of status change.",
  }),
  rec({
    slug: "red-panda",
    commonName: "Red Panda",
    scientificName: "Ailurus fulgens",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Ailurus_fulgens"), szoo("red-panda")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "red-panda",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giraffe",
    commonName: "Giraffe",
    scientificName: "Giraffa camelopardalis",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Giraffa_camelopardalis")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "giraffe",
    imageStatus: "not-planned",
    notes:
      "Giraffe taxonomy is under active revision; some authorities now recognise multiple species and subspecies with differing risk levels.",
  }),
  rec({
    slug: "vaquita",
    commonName: "Vaquita",
    scientificName: "Phocoena sinus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Phocoena_sinus"), noaa("vaquita")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "A porpoise endemic to the northern Gulf of California; widely reported as one of the world's most threatened marine mammals.",
  }),
  rec({
    slug: "sea-otter",
    commonName: "Sea Otter",
    scientificName: "Enhydra lutris",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Enhydra_lutris")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "african-wild-dog",
    commonName: "African Wild Dog",
    scientificName: "Lycaon pictus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Lycaon_pictus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "polar-bear",
    commonName: "Polar Bear",
    scientificName: "Ursus maritimus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Ursus_maritimus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sunda-pangolin",
    commonName: "Sunda Pangolin",
    scientificName: "Manis javanica",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Manis_javanica")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Pangolins are widely reported among the most trafficked wild mammals.",
  }),
  rec({
    slug: "tasmanian-devil",
    commonName: "Tasmanian Devil",
    scientificName: "Sarcophilus harrisii",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Sarcophilus_harrisii")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // ===========================================================================
  // BIRDS (20)
  // ===========================================================================
  rec({
    slug: "california-condor",
    commonName: "California Condor",
    scientificName: "Gymnogyps californianus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "A small, intensively managed population in the south-western United States and Baja California, Mexico.",
    primaryThreats: [
      "Lead poisoning from spent ammunition",
      "Habitat loss",
      "Collisions and micro-trash ingestion",
    ],
    sourceUrls: [
      fws("california-condor-gymnogyps-californianus"),
      adw("Gymnogyps_californianus"),
    ],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Recovered from a low of 22 birds in the 1980s through captive breeding and release; still dependent on active management.",
  }),
  rec({
    slug: "philippine-eagle",
    commonName: "Philippine Eagle",
    scientificName: "Pithecophaga jefferyi",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [adw("Pithecophaga_jefferyi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "kakapo",
    commonName: "Kākāpō",
    scientificName: "Strigops habroptilus",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [adw("Strigops_habroptila")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "A flightless nocturnal parrot from New Zealand managed on predator-free islands.",
  }),
  rec({
    slug: "spixs-macaw",
    commonName: "Spix's Macaw",
    scientificName: "Cyanopsitta spixii",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [adw("Cyanopsitta_spixii")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Considered Critically Endangered (long regarded as extinct in the wild); subject of an ongoing reintroduction effort in Brazil.",
  }),
  rec({
    slug: "hyacinth-macaw",
    commonName: "Hyacinth Macaw",
    scientificName: "Anodorhynchus hyacinthinus",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [adw("Anodorhynchus_hyacinthinus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "great-green-macaw",
    commonName: "Great Green Macaw",
    scientificName: "Ara ambiguus",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("great-green-macaw-ara-ambiguus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "whooping-crane",
    commonName: "Whooping Crane",
    scientificName: "Grus americana",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [adw("Grus_americana"), szoo("whooping-crane")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "siberian-crane",
    commonName: "Siberian Crane",
    scientificName: "Leucogeranus leucogeranus",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [adw("Grus_leucogeranus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "bali-myna",
    commonName: "Bali Myna",
    scientificName: "Leucopsar rothschildi",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("bali-myna-leucopsar-rothschildi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "white-rumped-vulture",
    commonName: "White-rumped Vulture",
    scientificName: "Gyps bengalensis",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [adw("Gyps_bengalensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "South Asian vulture declines have been widely linked to the veterinary drug diclofenac.",
  }),
  rec({
    slug: "egyptian-vulture",
    commonName: "Egyptian Vulture",
    scientificName: "Neophron percnopterus",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [adw("Neophron_percnopterus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "steller-sea-eagle",
    commonName: "Steller's Sea Eagle",
    scientificName: "Haliaeetus pelagicus",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [adw("Haliaeetus_pelagicus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "harpy-eagle",
    commonName: "Harpy Eagle",
    scientificName: "Harpia harpyja",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [adw("Harpia_harpyja")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "african-penguin",
    commonName: "African Penguin",
    scientificName: "Spheniscus demersus",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [adw("Spheniscus_demersus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Reported as up-listed to Critically Endangered in 2024 amid steep colony declines; confirm the current category on the live IUCN entry.",
  }),
  rec({
    slug: "galapagos-penguin",
    commonName: "Galápagos Penguin",
    scientificName: "Spheniscus mendiculus",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [adw("Spheniscus_mendiculus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "yellow-eyed-penguin",
    commonName: "Yellow-eyed Penguin",
    scientificName: "Megadyptes antipodes",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [adw("Megadyptes_antipodes")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "atlantic-puffin",
    commonName: "Atlantic Puffin",
    scientificName: "Fratercula arctica",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [adw("Fratercula_arctica")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "shoebill",
    commonName: "Shoebill",
    scientificName: "Balaeniceps rex",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [adw("Balaeniceps_rex")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "secretarybird",
    commonName: "Secretarybird",
    scientificName: "Sagittarius serpentarius",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [adw("Sagittarius_serpentarius")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "regent-honeyeater",
    commonName: "Regent Honeyeater",
    scientificName: "Anthochaera phrygia",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("regent-honeyeater-anthochaera-phrygia")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // ===========================================================================
  // REPTILES & AMPHIBIANS (18)
  // ===========================================================================
  rec({
    slug: "hawksbill-turtle",
    commonName: "Hawksbill Turtle",
    scientificName: "Eretmochelys imbricata",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Tropical and subtropical reefs and coastal waters across the Atlantic, Indian, and Pacific Oceans.",
    primaryThreats: [
      "Historical and ongoing tortoiseshell trade",
      "Coral-reef and nesting-beach habitat loss",
      "Fisheries bycatch and egg collection",
    ],
    sourceUrls: [noaa("hawksbill-turtle"), adw("Eretmochelys_imbricata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "kemps-ridley-turtle",
    commonName: "Kemp's Ridley Turtle",
    scientificName: "Lepidochelys kempii",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [noaa("kemps-ridley-turtle"), adw("Lepidochelys_kempii")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "green-turtle",
    commonName: "Green Turtle",
    scientificName: "Chelonia mydas",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [noaa("green-turtle"), adw("Chelonia_mydas")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "sea-turtle",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "leatherback-turtle",
    commonName: "Leatherback Turtle",
    scientificName: "Dermochelys coriacea",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [noaa("leatherback-turtle"), adw("Dermochelys_coriacea")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Globally Vulnerable, but several regional sub-populations are assessed as Critically Endangered.",
  }),
  rec({
    slug: "loggerhead-turtle",
    commonName: "Loggerhead Turtle",
    scientificName: "Caretta caretta",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [noaa("loggerhead-turtle"), adw("Caretta_caretta")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "gharial",
    commonName: "Gharial",
    scientificName: "Gavialis gangeticus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Gavialis_gangeticus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "chinese-alligator",
    commonName: "Chinese Alligator",
    scientificName: "Alligator sinensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Alligator_sinensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "ploughshare-tortoise",
    commonName: "Ploughshare Tortoise",
    scientificName: "Astrochelys yniphora",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Astrochelys_yniphora")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "radiated-tortoise",
    commonName: "Radiated Tortoise",
    scientificName: "Astrochelys radiata",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Astrochelys_radiata")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "komodo-dragon",
    commonName: "Komodo Dragon",
    scientificName: "Varanus komodoensis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [adw("Varanus_komodoensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "komodo-dragon",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "axolotl",
    commonName: "Axolotl",
    scientificName: "Ambystoma mexicanum",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Native only to the remnant lake and canal system of Xochimilco near Mexico City.",
    primaryThreats: [
      "Habitat loss and urban water pollution",
      "Invasive introduced fish such as tilapia and carp",
      "Reduced and degraded wetland habitat",
    ],
    sourceUrls: [adw("Ambystoma_mexicanum")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Abundant in captivity and research, but the wild population in Xochimilco is assessed as Critically Endangered.",
  }),
  rec({
    slug: "chinese-giant-salamander",
    commonName: "Chinese Giant Salamander",
    scientificName: "Andrias davidianus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [adw("Andrias_davidianus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "One of the largest living amphibians.",
  }),
  rec({
    slug: "panamanian-golden-frog",
    commonName: "Panamanian Golden Frog",
    scientificName: "Atelopus zeteki",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [amphibiaweb("Atelopus", "zeteki")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Amphibian declines have been widely linked to the chytrid fungus alongside habitat loss.",
  }),
  rec({
    slug: "lemur-leaf-frog",
    commonName: "Lemur Leaf Frog",
    scientificName: "Agalychnis lemur",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [amphibiaweb("Agalychnis", "lemur")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "mountain-chicken-frog",
    commonName: "Mountain Chicken Frog",
    scientificName: "Leptodactylus fallax",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "CR",
    sourceUrls: [amphibiaweb("Leptodactylus", "fallax")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "kihansi-spray-toad",
    commonName: "Kihansi Spray Toad",
    scientificName: "Nectophrynoides asperginis",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EW",
    sourceUrls: [amphibiaweb("Nectophrynoides", "asperginis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Listed Extinct in the Wild; subject of a captive-breeding and reintroduction programme in Tanzania.",
  }),
  rec({
    slug: "olm",
    commonName: "Olm",
    scientificName: "Proteus anguinus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    sourceUrls: [adw("Proteus_anguinus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "A cave-dwelling, aquatic salamander of the Western Balkans.",
  }),
  rec({
    slug: "titicaca-water-frog",
    commonName: "Lake Titicaca Water Frog",
    scientificName: "Telmatobius culeus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "EN",
    sourceUrls: [adw("Telmatobius_culeus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // ===========================================================================
  // FISH (16)
  // ===========================================================================
  rec({
    slug: "whale-shark",
    commonName: "Whale Shark",
    scientificName: "Rhincodon typus",
    taxonGroup: "fish",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "The largest living fish, found in warm-temperate and tropical oceans worldwide.",
    primaryThreats: [
      "Targeted and incidental fishing",
      "Vessel strikes",
      "Disturbance at aggregation sites",
    ],
    sourceUrls: [adw("Rhincodon_typus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "great-white-shark",
    commonName: "Great White Shark",
    scientificName: "Carcharodon carcharias",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [noaa("white-shark"), adw("Carcharodon_carcharias")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "scalloped-hammerhead",
    commonName: "Scalloped Hammerhead",
    scientificName: "Sphyrna lewini",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [noaa("scalloped-hammerhead-shark"), adw("Sphyrna_lewini")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "great-hammerhead",
    commonName: "Great Hammerhead",
    scientificName: "Sphyrna mokarran",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [adw("Sphyrna_mokarran")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "oceanic-whitetip-shark",
    commonName: "Oceanic Whitetip Shark",
    scientificName: "Carcharhinus longimanus",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [noaa("oceanic-whitetip-shark"), adw("Carcharhinus_longimanus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "shortfin-mako",
    commonName: "Shortfin Mako",
    scientificName: "Isurus oxyrinchus",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [noaa("shortfin-mako-shark"), adw("Isurus_oxyrinchus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giant-manta-ray",
    commonName: "Giant Manta Ray",
    scientificName: "Mobula birostris",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [noaa("giant-manta-ray"), adw("Manta_birostris")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "reef-manta-ray",
    commonName: "Reef Manta Ray",
    scientificName: "Mobula alfredi",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [adw("Manta_alfredi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "largetooth-sawfish",
    commonName: "Largetooth Sawfish",
    scientificName: "Pristis pristis",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [noaa("largetooth-sawfish")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "smalltooth-sawfish",
    commonName: "Smalltooth Sawfish",
    scientificName: "Pristis pectinata",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [noaa("smalltooth-sawfish"), adw("Pristis_pectinata")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "european-eel",
    commonName: "European Eel",
    scientificName: "Anguilla anguilla",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [adw("Anguilla_anguilla")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "beluga-sturgeon",
    commonName: "Beluga Sturgeon",
    scientificName: "Huso huso",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [adw("Huso_huso")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Source of beluga caviar; heavily affected by overfishing.",
  }),
  rec({
    slug: "chinese-sturgeon",
    commonName: "Chinese Sturgeon",
    scientificName: "Acipenser sinensis",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [fishbase("Acipenser-sinensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "humphead-wrasse",
    commonName: "Humphead Wrasse",
    scientificName: "Cheilinus undulatus",
    taxonGroup: "fish",
    redListCategory: "EN",
    sourceUrls: [fishbase("Cheilinus-undulatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Also called the Napoleon wrasse; a large, slow-growing reef fish.",
  }),
  rec({
    slug: "coelacanth",
    commonName: "West Indian Ocean Coelacanth",
    scientificName: "Latimeria chalumnae",
    taxonGroup: "fish",
    redListCategory: "CR",
    sourceUrls: [adw("Latimeria_chalumnae")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "A deep-water 'living fossil' lineage once thought extinct until rediscovery in 1938.",
  }),
  rec({
    slug: "lined-seahorse",
    commonName: "Lined Seahorse",
    scientificName: "Hippocampus erectus",
    taxonGroup: "fish",
    redListCategory: "VU",
    sourceUrls: [adw("Hippocampus_erectus")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "seahorse",
    imageStatus: "not-planned",
  }),

  // ===========================================================================
  // INVERTEBRATES (12)
  // ===========================================================================
  rec({
    slug: "staghorn-coral",
    commonName: "Staghorn Coral",
    scientificName: "Acropora cervicornis",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A fast-growing branching coral of Caribbean and western Atlantic reefs.",
    primaryThreats: [
      "Ocean warming and coral bleaching",
      "Coral disease",
      "Ocean acidification and storm damage",
    ],
    sourceUrls: [noaa("staghorn-coral")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "elkhorn-coral",
    commonName: "Elkhorn Coral",
    scientificName: "Acropora palmata",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    sourceUrls: [noaa("elkhorn-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lobed-star-coral",
    commonName: "Lobed Star Coral",
    scientificName: "Orbicella franksi",
    taxonGroup: "invertebrates",
    redListCategory: "VU",
    sourceUrls: [noaa("lobed-star-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "boulder-star-coral",
    commonName: "Boulder Star Coral",
    scientificName: "Orbicella annularis",
    taxonGroup: "invertebrates",
    redListCategory: "EN",
    sourceUrls: [noaa("boulder-star-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "white-abalone",
    commonName: "White Abalone",
    scientificName: "Haliotis sorenseni",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    sourceUrls: [noaa("white-abalone")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "rusty-patched-bumble-bee",
    commonName: "Rusty Patched Bumble Bee",
    scientificName: "Bombus affinis",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    sourceUrls: [fws("rusty-patched-bumble-bee-bombus-affinis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "franklins-bumble-bee",
    commonName: "Franklin's Bumble Bee",
    scientificName: "Bombus franklini",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    sourceUrls: [fws("franklins-bumble-bee-bombus-franklini")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Has not been seen since 2006 and may be extinct.",
  }),
  rec({
    slug: "american-burying-beetle",
    commonName: "American Burying Beetle",
    scientificName: "Nicrophorus americanus",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    sourceUrls: [fws("american-burying-beetle-nicrophorus-americanus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "migratory-monarch-butterfly",
    commonName: "Monarch Butterfly (migratory)",
    scientificName: "Danaus plexippus plexippus",
    taxonGroup: "invertebrates",
    redListCategory: "EN",
    sourceUrls: [
      fws("monarch-butterfly-danaus-plexippus"),
      adw("Danaus_plexippus"),
    ],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "The 2022 Endangered listing applies to the migratory monarch subspecies. The wider species was assessed separately; confirm the relevant entry on the live IUCN list.",
  }),
  rec({
    slug: "mountainous-star-coral",
    commonName: "Mountainous Star Coral",
    scientificName: "Orbicella faveolata",
    taxonGroup: "invertebrates",
    redListCategory: "EN",
    sourceUrls: [noaa("mountainous-star-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "lord-howe-stick-insect",
    commonName: "Lord Howe Island Stick Insect",
    scientificName: "Dryococelus australis",
    taxonGroup: "invertebrates",
    redListCategory: "CR",
    sourceUrls: ["https://zoo.org.au/melbourne/animals/lord-howe-island-stick-insect/"],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Rediscovered on Ball's Pyramid after being thought extinct; subject of a captive-breeding programme.",
  }),
  rec({
    slug: "rough-cactus-coral",
    commonName: "Rough Cactus Coral",
    scientificName: "Mycetophyllia ferox",
    taxonGroup: "invertebrates",
    redListCategory: "VU",
    sourceUrls: [noaa("rough-cactus-coral")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
];

export const RED_LIST_SPECIES_COUNT = RED_LIST_SPECIES.length;
