import type { RedListSpeciesRecord } from "./types";
import { adw, noaa, fws, birdlife, rec } from "./_builders";

/**
 * Red List Batch 2 — verified index records (mammals + birds).
 *
 * Same compliance posture as Phase 1: confident, widely published IUCN
 * categories; every sourceUrl confirmed reachable; no invented status,
 * population numbers, trends, threats, ranges, or taxonomy. Region assignments
 * live in regions.ts. All records are index-only unless noted.
 */
export const RED_LIST_SPECIES_BATCH2: readonly RedListSpeciesRecord[] = [
  // --- Mammals ---
  rec({
    slug: "ganges-river-dolphin",
    commonName: "Ganges River Dolphin",
    scientificName: "Platanista gangetica",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Platanista_gangetica")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "amazon-river-dolphin",
    commonName: "Amazon River Dolphin",
    scientificName: "Inia geoffrensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Inia_geoffrensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "west-indian-manatee",
    commonName: "West Indian Manatee",
    scientificName: "Trichechus manatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Trichechus_manatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "amazonian-manatee",
    commonName: "Amazonian Manatee",
    scientificName: "Trichechus inunguis",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Trichechus_inunguis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "dugong",
    commonName: "Dugong",
    scientificName: "Dugong dugon",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Dugong_dugon")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Globally Vulnerable, but several regional sub-populations are assessed at higher risk.",
  }),
  rec({
    slug: "blue-whale",
    commonName: "Blue Whale",
    scientificName: "Balaenoptera musculus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [noaa("blue-whale"), adw("Balaenoptera_musculus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "The largest animal known to have lived.",
  }),
  rec({
    slug: "fin-whale",
    commonName: "Fin Whale",
    scientificName: "Balaenoptera physalus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [noaa("fin-whale"), adw("Balaenoptera_physalus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "sei-whale",
    commonName: "Sei Whale",
    scientificName: "Balaenoptera borealis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [noaa("sei-whale"), adw("Balaenoptera_borealis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "north-atlantic-right-whale",
    commonName: "North Atlantic Right Whale",
    scientificName: "Eubalaena glacialis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [noaa("north-atlantic-right-whale"), adw("Eubalaena_glacialis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "hawaiian-monk-seal",
    commonName: "Hawaiian Monk Seal",
    scientificName: "Neomonachus schauinslandi",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [noaa("hawaiian-monk-seal")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "red-wolf",
    commonName: "Red Wolf",
    scientificName: "Canis rufus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [fws("red-wolf-canis-rufus"), adw("Canis_rufus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "ethiopian-wolf",
    commonName: "Ethiopian Wolf",
    scientificName: "Canis simensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Canis_simensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Africa's most threatened carnivore and rarest canid.",
  }),
  rec({
    slug: "dhole",
    commonName: "Dhole",
    scientificName: "Cuon alpinus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Scattered populations across South, Southeast, and East Asia.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "Depletion of wild prey",
      "Persecution and disease from domestic dogs",
    ],
    sourceUrls: [adw("Cuon_alpinus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "iberian-lynx",
    commonName: "Iberian Lynx",
    scientificName: "Lynx pardinus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Lynx_pardinus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes:
      "Reported as down-listed from Endangered to Vulnerable in 2024 after sustained recovery; confirm the current category on the live IUCN entry.",
  }),
  rec({
    slug: "okapi",
    commonName: "Okapi",
    scientificName: "Okapia johnstoni",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Endemic to the rainforests of the northern and eastern Democratic Republic of the Congo.",
    primaryThreats: [
      "Habitat loss from logging and settlement",
      "Hunting for meat and skins",
      "Instability across parts of its range",
    ],
    sourceUrls: [adw("Okapia_johnstoni")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "pygmy-hippopotamus",
    commonName: "Pygmy Hippopotamus",
    scientificName: "Choeropsis liberiensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Hexaprotodon_liberiensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "common-hippopotamus",
    commonName: "Common Hippopotamus",
    scientificName: "Hippopotamus amphibius",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Hippopotamus_amphibius")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "black-footed-ferret",
    commonName: "Black-footed Ferret",
    scientificName: "Mustela nigripes",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [fws("black-footed-ferret-mustela-nigripes"), adw("Mustela_nigripes")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "addax",
    commonName: "Addax",
    scientificName: "Addax nasomaculatus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Addax_nasomaculatus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "grevys-zebra",
    commonName: "Grévy's Zebra",
    scientificName: "Equus grevyi",
    taxonGroup: "mammals",
    redListCategory: "EN",
    sourceUrls: [adw("Equus_grevyi")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "saola",
    commonName: "Saola",
    scientificName: "Pseudoryx nghetinhensis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    sourceUrls: [adw("Pseudoryx_nghetinhensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "One of the rarest large mammals; rarely seen since its 1992 description.",
  }),
  rec({
    slug: "giant-anteater",
    commonName: "Giant Anteater",
    scientificName: "Myrmecophaga tridactyla",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Myrmecophaga_tridactyla")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),

  // --- Birds (BirdLife International DataZone) ---
  rec({
    slug: "red-crowned-crane",
    commonName: "Red-crowned Crane",
    scientificName: "Grus japonensis",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [birdlife("red-crowned-crane-grus-japonensis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "blue-crane",
    commonName: "Blue Crane",
    scientificName: "Grus paradisea",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [birdlife("blue-crane-anthropoides-paradiseus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "indian-vulture",
    commonName: "Indian Vulture",
    scientificName: "Gyps indicus",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("indian-vulture-gyps-indicus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "hooded-vulture",
    commonName: "Hooded Vulture",
    scientificName: "Necrosyrtes monachus",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("hooded-vulture-necrosyrtes-monachus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "white-backed-vulture",
    commonName: "White-backed Vulture",
    scientificName: "Gyps africanus",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("white-backed-vulture-gyps-africanus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "andean-condor",
    commonName: "Andean Condor",
    scientificName: "Vultur gryphus",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "The Andes and adjacent Pacific coasts of South America, from Venezuela to Tierra del Fuego.",
    primaryThreats: [
      "Poisoning, often secondary from baited carcasses",
      "Persecution",
      "Collisions and reduced food availability",
    ],
    sourceUrls: [birdlife("andean-condor-vultur-gryphus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "grey-parrot",
    commonName: "Grey Parrot",
    scientificName: "Psittacus erithacus",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("grey-parrot-psittacus-erithacus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
    notes: "Heavily affected by the cage-bird trade.",
  }),
  rec({
    slug: "lears-macaw",
    commonName: "Lear's Macaw",
    scientificName: "Anodorhynchus leari",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("lears-macaw-anodorhynchus-leari")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "blue-throated-macaw",
    commonName: "Blue-throated Macaw",
    scientificName: "Ara glaucogularis",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("blue-throated-macaw-ara-glaucogularis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "yellow-crested-cockatoo",
    commonName: "Yellow-crested Cockatoo",
    scientificName: "Cacatua sulphurea",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("yellow-crested-cockatoo-cacatua-sulphurea")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "kea",
    commonName: "Kea",
    scientificName: "Nestor notabilis",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("kea-nestor-notabilis")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "swift-parrot",
    commonName: "Swift Parrot",
    scientificName: "Lathamus discolor",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("swift-parrot-lathamus-discolor")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "orange-bellied-parrot",
    commonName: "Orange-bellied Parrot",
    scientificName: "Neophema chrysogaster",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("orange-bellied-parrot-neophema-chrysogaster")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "helmeted-hornbill",
    commonName: "Helmeted Hornbill",
    scientificName: "Rhinoplax vigil",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("helmeted-hornbill-rhinoplax-vigil")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "great-indian-bustard",
    commonName: "Great Indian Bustard",
    scientificName: "Ardeotis nigriceps",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("great-indian-bustard-ardeotis-nigriceps")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "spoon-billed-sandpiper",
    commonName: "Spoon-billed Sandpiper",
    scientificName: "Calidris pygmaea",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("spoon-billed-sandpiper-calidris-pygmaea")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "crested-ibis",
    commonName: "Crested Ibis",
    scientificName: "Nipponia nippon",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("asian-crested-ibis-nipponia-nippon")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "black-faced-spoonbill",
    commonName: "Black-faced Spoonbill",
    scientificName: "Platalea minor",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("black-faced-spoonbill-platalea-minor")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "wandering-albatross",
    commonName: "Wandering Albatross",
    scientificName: "Diomedea exulans",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [birdlife("wandering-albatross-diomedea-exulans")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "humboldt-penguin",
    commonName: "Humboldt Penguin",
    scientificName: "Spheniscus humboldti",
    taxonGroup: "birds",
    redListCategory: "VU",
    sourceUrls: [birdlife("humboldt-penguin-spheniscus-humboldti")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "martial-eagle",
    commonName: "Martial Eagle",
    scientificName: "Polemaetus bellicosus",
    taxonGroup: "birds",
    redListCategory: "EN",
    sourceUrls: [birdlife("martial-eagle-polemaetus-bellicosus")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "madagascar-fish-eagle",
    commonName: "Madagascar Fish Eagle",
    scientificName: "Haliaeetus vociferoides",
    taxonGroup: "birds",
    redListCategory: "CR",
    sourceUrls: [birdlife("madagascar-fish-eagle-haliaeetus-vociferoides")],
    dataConfidence: "source-review-pending",
    profileStatus: "index-only",
    imageStatus: "not-planned",
  }),
];
