import type { RedListSpeciesRecord } from "./types";
import { adw, noaa, fishbase, fws, birdlife, amphibiaweb, rec } from "./_builders";

/**
 * Red List Batch 4 — verified index records with regional diversity emphasis,
 * supporting the /endangered-animals/regions layer. Same compliance posture as
 * earlier batches; region assignments live in regions.ts. All index-only.
 */
export const RED_LIST_SPECIES_BATCH4: readonly RedListSpeciesRecord[] = [
  // --- Mammals: Asia ---
  rec({
    slug: "clouded-leopard",
    commonName: "Clouded Leopard",
    scientificName: "Neofelis nebulosa",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests of South and Southeast Asia, from the Himalayan foothills to mainland Southeast Asia.",
    primaryThreats: [
      "Deforestation",
      "Poaching for skins and parts",
      "Prey depletion",
    ],
    sourceUrls: [adw("Neofelis_nebulosa")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "fishing-cat",
    commonName: "Fishing Cat",
    scientificName: "Prionailurus viverrinus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Wetlands of South and Southeast Asia.",
    primaryThreats: [
      "Destruction and drainage of wetlands",
      "Persecution and hunting",
      "Pollution and reduced fish",
    ],
    sourceUrls: [adw("Prionailurus_viverrinus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "lion-tailed-macaque",
    commonName: "Lion-tailed Macaque",
    scientificName: "Macaca silenus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Rainforests of the Western Ghats in southern India.",
    primaryThreats: [
      "Fragmentation of rainforest",
      "Roads and human disturbance",
      "Small, isolated populations",
    ],
    sourceUrls: [adw("Macaca_silenus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "golden-snub-nosed-monkey",
    commonName: "Golden Snub-nosed Monkey",
    scientificName: "Rhinopithecus roxellana",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Cold mountain forests of central and south-western China.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "Past hunting",
      "Small, isolated populations",
    ],
    sourceUrls: [adw("Rhinopithecus_roxellana")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "siamang",
    commonName: "Siamang",
    scientificName: "Symphalangus syndactylus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Rainforests of Sumatra and the Malay Peninsula.",
    primaryThreats: [
      "Deforestation",
      "Capture for the pet trade",
      "Habitat fragmentation",
    ],
    sourceUrls: [adw("Symphalangus_syndactylus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "lar-gibbon",
    commonName: "Lar Gibbon",
    scientificName: "Hylobates lar",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests of Southeast Asia, including Thailand, Malaysia, and Sumatra.",
    primaryThreats: [
      "Deforestation",
      "Capture for the pet trade",
      "Hunting",
    ],
    sourceUrls: [adw("Hylobates_lar")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "wild-bactrian-camel",
    commonName: "Wild Bactrian Camel",
    scientificName: "Camelus ferus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Remote deserts of north-western China and Mongolia, including the Gobi.",
    primaryThreats: [
      "Hunting",
      "Competition with livestock and hybridisation",
      "Scarce water and habitat loss",
    ],
    sourceUrls: [adw("Camelus_bactrianus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "The wild Bactrian camel (Camelus ferus) is the threatened wild form; the linked reference covers Bactrian camels broadly.",
  }),
  rec({
    slug: "gaur",
    commonName: "Gaur",
    scientificName: "Bos gaurus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests and grasslands of South and Southeast Asia.",
    primaryThreats: [
      "Hunting and poaching",
      "Habitat loss",
      "Diseases from domestic cattle",
    ],
    sourceUrls: [fws("gaur-bos-gaurus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "banteng",
    commonName: "Banteng",
    scientificName: "Bos javanicus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests of Southeast Asia, with populations on Java, Borneo, and the mainland.",
    primaryThreats: [
      "Hunting and poaching",
      "Habitat loss",
      "Hybridisation with domestic cattle",
    ],
    sourceUrls: [adw("Bos_javanicus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "chinese-pangolin",
    commonName: "Chinese Pangolin",
    scientificName: "Manis pentadactyla",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Southern China, the Himalayan foothills, and parts of Southeast Asia.",
    primaryThreats: [
      "Poaching and trafficking for scales and meat",
      "Habitat loss",
    ],
    sourceUrls: [adw("Manis_pentadactyla")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "indian-pangolin",
    commonName: "Indian Pangolin",
    scientificName: "Manis crassicaudata",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "South Asia, including India, Pakistan, Nepal, Sri Lanka, and Bangladesh.",
    primaryThreats: [
      "Poaching and trafficking for scales and meat",
      "Habitat loss",
    ],
    sourceUrls: [adw("Manis_crassicaudata")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // --- Mammals: South America ---
  rec({
    slug: "cotton-top-tamarin",
    commonName: "Cotton-top Tamarin",
    scientificName: "Saguinus oedipus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A small area of tropical forest in north-western Colombia.",
    primaryThreats: [
      "Deforestation",
      "Past capture for the pet trade and research",
      "A very small range",
    ],
    sourceUrls: [adw("Saguinus_oedipus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "northern-muriqui",
    commonName: "Northern Muriqui",
    scientificName: "Brachyteles hypoxanthus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Remnant Atlantic Forest of south-eastern Brazil.",
    primaryThreats: [
      "Loss and fragmentation of Atlantic Forest",
      "Small, isolated populations",
      "Past hunting",
    ],
    sourceUrls: [adw("Brachyteles_hypoxanthus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "maned-three-toed-sloth",
    commonName: "Maned Three-toed Sloth",
    scientificName: "Bradypus torquatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Remnant Atlantic Forest of south-eastern Brazil.",
    primaryThreats: [
      "Loss and fragmentation of Atlantic Forest",
      "Small, isolated populations",
    ],
    sourceUrls: [adw("Bradypus_torquatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "giant-otter",
    commonName: "Giant Otter",
    scientificName: "Pteronura brasiliensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Rivers and wetlands of tropical South America, centred on the Amazon basin and the Pantanal.",
    primaryThreats: [
      "Habitat degradation and deforestation",
      "Historical hunting for pelts",
      "Pollution including mining-related mercury",
    ],
    sourceUrls: [adw("Pteronura_brasiliensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "andean-bear",
    commonName: "Andean Bear",
    scientificName: "Tremarctos ornatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Andean cloud forests and high grasslands of western South America.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "Conflict with farmers",
      "Hunting",
    ],
    sourceUrls: [adw("Tremarctos_ornatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes: "South America's only bear species; also called the spectacled bear.",
  }),
  rec({
    slug: "giant-armadillo",
    commonName: "Giant Armadillo",
    scientificName: "Priodontes maximus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests and grasslands of South America, east of the Andes.",
    primaryThreats: [
      "Hunting",
      "Habitat loss",
      "A naturally low density and slow reproduction",
    ],
    sourceUrls: [adw("Priodontes_maximus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),

  // --- Mammals: Europe & North America ---
  rec({
    slug: "european-mink",
    commonName: "European Mink",
    scientificName: "Mustela lutreola",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Fragmented populations in parts of Europe, much reduced from its former range.",
    primaryThreats: [
      "Competition from the introduced American mink",
      "Habitat loss",
      "Pollution and a small population",
    ],
    sourceUrls: [adw("Mustela_lutreola")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "european-hamster",
    commonName: "European Hamster",
    scientificName: "Cricetus cricetus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Farmland and grassland across parts of Europe and western Asia.",
    primaryThreats: [
      "Intensive agriculture",
      "Loss of habitat and food",
      "A collapsing reproductive rate",
    ],
    sourceUrls: [adw("Cricetus_cricetus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "Up-listed to Critically Endangered in 2020 after steep declines across Europe.",
  }),
  rec({
    slug: "vancouver-island-marmot",
    commonName: "Vancouver Island Marmot",
    scientificName: "Marmota vancouverensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "Mountains of Vancouver Island, Canada.",
    primaryThreats: [
      "A tiny population",
      "Predation",
      "Habitat change and past logging effects",
    ],
    sourceUrls: [adw("Marmota_vancouverensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // --- Mammals: Oceania ---
  rec({
    slug: "numbat",
    commonName: "Numbat",
    scientificName: "Myrmecobius fasciatus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Remnant woodlands of south-western Australia.",
    primaryThreats: [
      "Introduced foxes and cats",
      "Habitat loss and fragmentation",
      "A small population",
    ],
    sourceUrls: [adw("Myrmecobius_fasciatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "koala",
    commonName: "Koala",
    scientificName: "Phascolarctos cinereus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    sourceUrls: [adw("Phascolarctos_cinereus")],
    dataConfidence: "source-review-pending",
    profileStatus: "existing-profile-linked",
    existingAnimalSlug: "koala",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "northern-hairy-nosed-wombat",
    commonName: "Northern Hairy-nosed Wombat",
    scientificName: "Lasiorhinus krefftii",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "A tiny area of Queensland, Australia.",
    primaryThreats: [
      "An extremely small range",
      "Predation and competition",
      "Vulnerability to disasters",
    ],
    sourceUrls: [adw("Lasiorhinus_krefftii")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "leadbeaters-possum",
    commonName: "Leadbeater's Possum",
    scientificName: "Gymnobelideus leadbeateri",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Mountain ash forests of Victoria, Australia.",
    primaryThreats: [
      "Loss of old-growth forest with nesting hollows",
      "Bushfires",
      "Logging",
    ],
    sourceUrls: [adw("Gymnobelideus_leadbeateri")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "matschies-tree-kangaroo",
    commonName: "Matschie's Tree-kangaroo",
    scientificName: "Dendrolagus matschiei",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Mountain rainforests of the Huon Peninsula, Papua New Guinea.",
    primaryThreats: [
      "Hunting",
      "Habitat loss",
      "A small, restricted range",
    ],
    sourceUrls: [adw("Dendrolagus_matschiei")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // --- Birds (BirdLife) ---
  rec({
    slug: "saker-falcon",
    commonName: "Saker Falcon",
    scientificName: "Falco cherrug",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Open country from eastern Europe and the Middle East across Central Asia.",
    primaryThreats: [
      "Capture for falconry",
      "Electrocution on power lines",
      "Habitat change and reduced prey",
    ],
    sourceUrls: [birdlife("saker-falcon-falco-cherrug")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "aquatic-warbler",
    commonName: "Aquatic Warbler",
    scientificName: "Acrocephalus paludicola",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds in fen mires of central and eastern Europe and winters in West Africa.",
    primaryThreats: [
      "Loss and drainage of fen wetlands",
      "Habitat change on migration and wintering grounds",
      "A fragmented population",
    ],
    sourceUrls: [birdlife("aquatic-warbler-acrocephalus-paludicola")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "grey-crowned-crane",
    commonName: "Grey Crowned Crane",
    scientificName: "Balearica regulorum",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Wetlands and grasslands of eastern and southern Africa.",
    primaryThreats: [
      "Loss and drainage of wetlands",
      "Capture for the live-bird trade",
      "Disturbance",
    ],
    sourceUrls: [birdlife("grey-crowned-crane-balearica-regulorum")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "hooded-grebe",
    commonName: "Hooded Grebe",
    scientificName: "Podiceps gallardoi",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Remote lakes of Patagonia in Argentina.",
    primaryThreats: [
      "Introduced predators (mink and gulls)",
      "Climate and habitat change at its lakes",
      "A small population",
    ],
    sourceUrls: [birdlife("hooded-grebe-podiceps-gallardoi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "night-parrot",
    commonName: "Night Parrot",
    scientificName: "Pezoporus occidentalis",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "stable",
    rangeSummary:
      "Remote arid interior of Australia.",
    primaryThreats: [
      "Introduced cats and foxes",
      "Changed fire regimes",
      "An extremely small, scattered population",
    ],
    sourceUrls: [birdlife("night-parrot-pezoporus-occidentalis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "christmas-frigatebird",
    commonName: "Christmas Frigatebird",
    scientificName: "Fregata andrewsi",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds only on Christmas Island in the Indian Ocean.",
    primaryThreats: [
      "A tiny breeding range",
      "Past habitat disturbance",
      "Pollution and introduced species",
    ],
    sourceUrls: [birdlife("christmas-island-frigatebird-fregata-andrewsi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "northern-royal-albatross",
    commonName: "Northern Royal Albatross",
    scientificName: "Diomedea sanfordi",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds on islands off New Zealand and forages across the Southern Ocean.",
    primaryThreats: [
      "Longline fishing bycatch",
      "Storms and disturbance at colonies",
      "Plastic and pollution",
    ],
    sourceUrls: [birdlife("northern-royal-albatross-diomedea-sanfordi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // --- Reptiles & Amphibians ---
  rec({
    slug: "galapagos-land-iguana",
    commonName: "Galápagos Land Iguana",
    scientificName: "Conolophus subcristatus",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "stable",
    rangeSummary:
      "Several islands of the Galápagos.",
    primaryThreats: [
      "Introduced predators and grazers",
      "Past habitat damage",
      "Restricted island range",
    ],
    sourceUrls: [adw("Conolophus_subcristatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "california-tiger-salamander",
    commonName: "California Tiger Salamander",
    scientificName: "Ambystoma californiense",
    taxonGroup: "reptiles-amphibians",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Grasslands and oak woodlands of California, USA.",
    primaryThreats: [
      "Loss of breeding pools and habitat",
      "Hybridisation with introduced salamanders",
      "Roads and development",
    ],
    sourceUrls: [amphibiaweb("Ambystoma", "californiense")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // --- Fish ---
  rec({
    slug: "giant-sea-bass",
    commonName: "Giant Sea Bass",
    scientificName: "Stereolepis gigas",
    taxonGroup: "fish",
    redListCategory: "CR",
    populationTrend: "increasing",
    rangeSummary:
      "The eastern Pacific off California, USA, and Mexico.",
    primaryThreats: [
      "Past severe overfishing",
      "Slow maturation",
      "Bycatch",
    ],
    sourceUrls: [fishbase("Stereolepis-gigas")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "shortnose-sturgeon",
    commonName: "Shortnose Sturgeon",
    scientificName: "Acipenser brevirostrum",
    taxonGroup: "fish",
    redListCategory: "VU",
    populationTrend: "stable",
    rangeSummary:
      "Rivers and estuaries along the Atlantic coast of North America.",
    primaryThreats: [
      "Dams blocking migration",
      "Pollution and habitat change",
      "Past overfishing and bycatch",
    ],
    sourceUrls: [noaa("shortnose-sturgeon"), fishbase("Acipenser-brevirostrum")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),

  // --- Invertebrates ---
  rec({
    slug: "pillar-coral",
    commonName: "Pillar Coral",
    scientificName: "Dendrogyra cylindrus",
    taxonGroup: "invertebrates",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Caribbean and western Atlantic reefs.",
    primaryThreats: [
      "Warming-driven bleaching",
      "Coral disease",
      "Pollution and reef degradation",
    ],
    sourceUrls: [noaa("pillar-coral")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes:
      "Caribbean reef coral severely affected by stony coral tissue loss disease; confirm the current category on the live IUCN entry.",
  }),
];
