import type { RedListSpeciesRecord } from "./types";
import {
  adw,
  noaa,
  birdlife,
  fishbase,
  amphibiaweb,
  reptiledb,
  rec,
} from "./_builders";

/**
 * Red List Batch 5 — additional verified index records (controlled expansion
 * toward the 600 milestone). Same compliance posture as earlier batches:
 * confident, widely published IUCN categories; every sourceUrl confirmed
 * reachable; no invented status/numbers/trends/threats/ranges/taxonomy. Region
 * assignments live in regions.ts. All records are index-only.
 */
export const RED_LIST_SPECIES_BATCH5: readonly RedListSpeciesRecord[] = [
  // ===========================================================================
  // MAMMALS
  // ===========================================================================
  rec({ slug: "hainan-gibbon", commonName: "Hainan Gibbon", scientificName: "Nomascus hainanus", taxonGroup: "mammals", redListCategory: "CR", sourceUrls: [adw("Nomascus_hainanus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Often cited as the world's rarest ape." }),
  rec({ slug: "western-hoolock-gibbon", commonName: "Western Hoolock Gibbon", scientificName: "Hoolock hoolock", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Bunopithecus_hoolock")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Reference uses the former genus Bunopithecus." }),
  rec({ slug: "pileated-gibbon", commonName: "Pileated Gibbon", scientificName: "Hylobates pileatus", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Hylobates_pileatus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "drill", commonName: "Drill", scientificName: "Mandrillus leucophaeus", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Mandrillus_leucophaeus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "mandrill", commonName: "Mandrill", scientificName: "Mandrillus sphinx", taxonGroup: "mammals", redListCategory: "VU", sourceUrls: [adw("Mandrillus_sphinx")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "barbary-macaque", commonName: "Barbary Macaque", scientificName: "Macaca sylvanus", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Macaca_sylvanus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "geoffroys-spider-monkey", commonName: "Geoffroy's Spider Monkey", scientificName: "Ateles geoffroyi", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Ateles_geoffroyi")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "brown-spider-monkey", commonName: "Brown Spider Monkey", scientificName: "Ateles hybridus", taxonGroup: "mammals", redListCategory: "CR", sourceUrls: [adw("Ateles_hybridus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "red-shanked-douc", commonName: "Red-shanked Douc", scientificName: "Pygathrix nemaeus", taxonGroup: "mammals", redListCategory: "CR", sourceUrls: [adw("Pygathrix_nemaeus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "verreauxs-sifaka", commonName: "Verreaux's Sifaka", scientificName: "Propithecus verreauxi", taxonGroup: "mammals", redListCategory: "CR", sourceUrls: [adw("Propithecus_verreauxi")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "greater-bamboo-lemur", commonName: "Greater Bamboo Lemur", scientificName: "Prolemur simus", taxonGroup: "mammals", redListCategory: "CR", sourceUrls: [adw("Prolemur_simus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "pygmy-slow-loris", commonName: "Pygmy Slow Loris", scientificName: "Xanthonycticebus pygmaeus", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Nycticebus_pygmaeus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Recently moved to the genus Xanthonycticebus; the linked reference uses the former Nycticebus name." }),
  rec({ slug: "tonkin-snub-nosed-monkey", commonName: "Tonkin Snub-nosed Monkey", scientificName: "Rhinopithecus avunculus", taxonGroup: "mammals", redListCategory: "CR", sourceUrls: [adw("Rhinopithecus_avunculus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "black-footed-cat", commonName: "Black-footed Cat", scientificName: "Felis nigripes", taxonGroup: "mammals", redListCategory: "VU", sourceUrls: [adw("Felis_nigripes")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "flat-headed-cat", commonName: "Flat-headed Cat", scientificName: "Prionailurus planiceps", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Prionailurus_planiceps")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "darwins-fox", commonName: "Darwin's Fox", scientificName: "Lycalopex fulvipes", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Lycalopex_fulvipes")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "fossa", commonName: "Fossa", scientificName: "Cryptoprocta ferox", taxonGroup: "mammals", redListCategory: "VU", sourceUrls: [adw("Cryptoprocta_ferox")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Madagascar's largest carnivore." }),
  rec({ slug: "north-pacific-right-whale", commonName: "North Pacific Right Whale", scientificName: "Eubalaena japonica", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [noaa("north-pacific-right-whale")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "hectors-dolphin", commonName: "Hector's Dolphin", scientificName: "Cephalorhynchus hectori", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Cephalorhynchus_hectori")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "The Maui dolphin sub-population is assessed at even higher risk." }),
  rec({ slug: "franciscana", commonName: "Franciscana", scientificName: "Pontoporia blainvillei", taxonGroup: "mammals", redListCategory: "VU", sourceUrls: [adw("Pontoporia_blainvillei")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "indus-river-dolphin", commonName: "Indus River Dolphin", scientificName: "Platanista minor", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Platanista_minor")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "grey-headed-flying-fox", commonName: "Grey-headed Flying Fox", scientificName: "Pteropus poliocephalus", taxonGroup: "mammals", redListCategory: "VU", sourceUrls: [adw("Pteropus_poliocephalus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "scimitar-horned-oryx", commonName: "Scimitar-horned Oryx", scientificName: "Oryx dammah", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Oryx_dammah")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Formerly Extinct in the Wild; reassessed Endangered in 2023 following reintroduction in Chad." }),
  rec({ slug: "dama-gazelle", commonName: "Dama Gazelle", scientificName: "Nanger dama", taxonGroup: "mammals", redListCategory: "CR", sourceUrls: [adw("Nanger_dama")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "mountain-tapir", commonName: "Mountain Tapir", scientificName: "Tapirus pinchaque", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Tapirus_pinchaque")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "malayan-tapir", commonName: "Malayan Tapir", scientificName: "Tapirus indicus", taxonGroup: "mammals", redListCategory: "EN", sourceUrls: [adw("Tapirus_indicus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "pere-davids-deer", commonName: "Père David's Deer", scientificName: "Elaphurus davidianus", taxonGroup: "mammals", redListCategory: "EW", sourceUrls: [adw("Elaphurus_davidianus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Listed Extinct in the Wild; survives in managed and reintroduced herds in China." }),
  rec({ slug: "greater-bilby", commonName: "Greater Bilby", scientificName: "Macrotis lagotis", taxonGroup: "mammals", redListCategory: "VU", sourceUrls: [adw("Macrotis_lagotis")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),

  // ===========================================================================
  // BIRDS (BirdLife International DataZone)
  // ===========================================================================
  rec({ slug: "hooded-crane", commonName: "Hooded Crane", scientificName: "Grus monacha", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("hooded-crane-grus-monacha")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "white-naped-crane", commonName: "White-naped Crane", scientificName: "Antigone vipio", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("white-naped-crane-grus-vipio")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "sarus-crane", commonName: "Sarus Crane", scientificName: "Antigone antigone", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("sarus-crane-grus-antigone")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "wattled-crane", commonName: "Wattled Crane", scientificName: "Bugeranus carunculatus", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("wattled-crane-bugeranus-carunculatus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "red-headed-vulture", commonName: "Red-headed Vulture", scientificName: "Sarcogyps calvus", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("red-headed-vulture-sarcogyps-calvus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "slender-billed-vulture", commonName: "Slender-billed Vulture", scientificName: "Gyps tenuirostris", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("slender-billed-vulture-gyps-tenuirostris")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "cape-vulture", commonName: "Cape Vulture", scientificName: "Gyps coprotheres", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("cape-vulture-gyps-coprotheres")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "spanish-imperial-eagle", commonName: "Spanish Imperial Eagle", scientificName: "Aquila adalberti", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("spanish-imperial-eagle-aquila-adalberti")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "eastern-imperial-eagle", commonName: "Eastern Imperial Eagle", scientificName: "Aquila heliaca", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("eastern-imperial-eagle-aquila-heliaca")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "red-fronted-macaw", commonName: "Red-fronted Macaw", scientificName: "Ara rubrogenys", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("red-fronted-macaw-ara-rubrogenys")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "military-macaw", commonName: "Military Macaw", scientificName: "Ara militaris", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("military-macaw-ara-militaris")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "golden-parakeet", commonName: "Golden Parakeet", scientificName: "Guaruba guarouba", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("golden-parakeet-guaruba-guarouba")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "philippine-cockatoo", commonName: "Philippine Cockatoo", scientificName: "Cacatua haematuropygia", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("philippine-cockatoo-cacatua-haematuropygia")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "northern-rockhopper-penguin", commonName: "Northern Rockhopper Penguin", scientificName: "Eudyptes moseleyi", taxonGroup: "birds", redListCategory: "EN", sourceUrls: [birdlife("northern-rockhopper-penguin-eudyptes-moseleyi")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "macaroni-penguin", commonName: "Macaroni Penguin", scientificName: "Eudyptes chrysolophus", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("macaroni-penguin-eudyptes-chrysolophus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "erect-crested-penguin", commonName: "Erect-crested Penguin", scientificName: "Eudyptes sclateri", taxonGroup: "birds", redListCategory: "EN", sourceUrls: [birdlife("erect-crested-penguin-eudyptes-sclateri")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "fiordland-penguin", commonName: "Fiordland Penguin", scientificName: "Eudyptes pachyrhynchus", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("fiordland-penguin-eudyptes-pachyrhynchus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "tristan-albatross", commonName: "Tristan Albatross", scientificName: "Diomedea dabbenena", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("tristan-albatross-diomedea-dabbenena")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "waved-albatross", commonName: "Waved Albatross", scientificName: "Phoebastria irrorata", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("waved-albatross-phoebastria-irrorata")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "short-tailed-albatross", commonName: "Short-tailed Albatross", scientificName: "Phoebastria albatrus", taxonGroup: "birds", redListCategory: "VU", sourceUrls: [birdlife("short-tailed-albatross-phoebastria-albatrus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "giant-ibis", commonName: "Giant Ibis", scientificName: "Thaumatibis gigantea", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("giant-ibis-thaumatibis-gigantea")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "northern-bald-ibis", commonName: "Northern Bald Ibis", scientificName: "Geronticus eremita", taxonGroup: "birds", redListCategory: "EN", sourceUrls: [birdlife("northern-bald-ibis-geronticus-eremita")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "bengal-florican", commonName: "Bengal Florican", scientificName: "Houbaropsis bengalensis", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("bengal-florican-houbaropsis-bengalensis")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "forest-owlet", commonName: "Forest Owlet", scientificName: "Athene blewitti", taxonGroup: "birds", redListCategory: "EN", sourceUrls: [birdlife("forest-owlet-athene-blewitti")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "kagu", commonName: "Kagu", scientificName: "Rhynochetos jubatus", taxonGroup: "birds", redListCategory: "EN", sourceUrls: [birdlife("kagu-rhynochetos-jubatus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "junin-grebe", commonName: "Junín Grebe", scientificName: "Podiceps taczanowskii", taxonGroup: "birds", redListCategory: "CR", sourceUrls: [birdlife("junin-grebe-podiceps-taczanowskii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),

  // ===========================================================================
  // REPTILES & AMPHIBIANS
  // ===========================================================================
  rec({ slug: "tomistoma", commonName: "Tomistoma", scientificName: "Tomistoma schlegelii", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [reptiledb("Tomistoma", "schlegelii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "yangtze-giant-softshell-turtle", commonName: "Yangtze Giant Softshell Turtle", scientificName: "Rafetus swinhoei", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [reptiledb("Rafetus", "swinhoei")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Among the rarest turtles on Earth." }),
  rec({ slug: "burmese-roofed-turtle", commonName: "Burmese Roofed Turtle", scientificName: "Batagur trivittata", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [reptiledb("Batagur", "trivittata")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "central-american-river-turtle", commonName: "Central American River Turtle", scientificName: "Dermatemys mawii", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [reptiledb("Dermatemys", "mawii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "bog-turtle", commonName: "Bog Turtle", scientificName: "Glyptemys muhlenbergii", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [reptiledb("Glyptemys", "muhlenbergii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "spider-tortoise", commonName: "Spider Tortoise", scientificName: "Pyxis arachnoides", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [reptiledb("Pyxis", "arachnoides")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "chinese-crocodile-lizard", commonName: "Chinese Crocodile Lizard", scientificName: "Shinisaurus crocodilurus", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [reptiledb("Shinisaurus", "crocodilurus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "round-island-keel-scaled-boa", commonName: "Round Island Keel-scaled Boa", scientificName: "Casarea dussumieri", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [reptiledb("Casarea", "dussumieri")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "aruba-island-rattlesnake", commonName: "Aruba Island Rattlesnake", scientificName: "Crotalus unicolor", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [reptiledb("Crotalus", "unicolor")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "slender-snouted-crocodile", commonName: "West African Slender-snouted Crocodile", scientificName: "Mecistops cataphractus", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [reptiledb("Mecistops", "cataphractus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "houston-toad", commonName: "Houston Toad", scientificName: "Anaxyrus houstonensis", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [amphibiaweb("Anaxyrus", "houstonensis")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "yosemite-toad", commonName: "Yosemite Toad", scientificName: "Anaxyrus canorus", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [amphibiaweb("Anaxyrus", "canorus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "dusky-gopher-frog", commonName: "Dusky Gopher Frog", scientificName: "Lithobates sevosus", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [amphibiaweb("Lithobates", "sevosus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "darwins-frog", commonName: "Darwin's Frog", scientificName: "Rhinoderma darwinii", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [amphibiaweb("Rhinoderma", "darwinii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "lake-oku-clawed-frog", commonName: "Lake Oku Clawed Frog", scientificName: "Xenopus longipes", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [amphibiaweb("Xenopus", "longipes")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "variable-harlequin-frog", commonName: "Variable Harlequin Frog", scientificName: "Atelopus varius", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [amphibiaweb("Atelopus", "varius")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "archeys-frog", commonName: "Archey's Frog", scientificName: "Leiopelma archeyi", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [amphibiaweb("Leiopelma", "archeyi")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "mountain-yellow-legged-frog", commonName: "Mountain Yellow-legged Frog", scientificName: "Rana muscosa", taxonGroup: "reptiles-amphibians", redListCategory: "EN", sourceUrls: [amphibiaweb("Rana", "muscosa")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "northern-corroboree-frog", commonName: "Northern Corroboree Frog", scientificName: "Pseudophryne pengilleyi", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [amphibiaweb("Pseudophryne", "pengilleyi")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "morelets-tree-frog", commonName: "Morelet's Tree Frog", scientificName: "Agalychnis moreletii", taxonGroup: "reptiles-amphibians", redListCategory: "CR", sourceUrls: [amphibiaweb("Agalychnis", "moreletii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),

  // ===========================================================================
  // FISH
  // ===========================================================================
  rec({ slug: "dusky-shark", commonName: "Dusky Shark", scientificName: "Carcharhinus obscurus", taxonGroup: "fish", redListCategory: "EN", sourceUrls: [fishbase("Carcharhinus-obscurus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "silky-shark", commonName: "Silky Shark", scientificName: "Carcharhinus falciformis", taxonGroup: "fish", redListCategory: "VU", sourceUrls: [fishbase("Carcharhinus-falciformis")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "tope-shark", commonName: "Tope Shark", scientificName: "Galeorhinus galeus", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Galeorhinus-galeus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "smooth-hammerhead", commonName: "Smooth Hammerhead", scientificName: "Sphyrna zygaena", taxonGroup: "fish", redListCategory: "VU", sourceUrls: [fishbase("Sphyrna-zygaena")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "spiny-dogfish", commonName: "Spiny Dogfish", scientificName: "Squalus acanthias", taxonGroup: "fish", redListCategory: "VU", sourceUrls: [fishbase("Squalus-acanthias")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "ganges-shark", commonName: "Ganges Shark", scientificName: "Glyphis gangeticus", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Glyphis-gangeticus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "speartooth-shark", commonName: "Speartooth Shark", scientificName: "Glyphis glyphis", taxonGroup: "fish", redListCategory: "EN", sourceUrls: [fishbase("Glyphis-glyphis")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "maugean-skate", commonName: "Maugean Skate", scientificName: "Zearaja maugeana", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Zearaja-maugeana")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "totoaba", commonName: "Totoaba", scientificName: "Totoaba macdonaldi", taxonGroup: "fish", redListCategory: "VU", sourceUrls: [noaa("totoaba"), fishbase("Totoaba-macdonaldi")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned", notes: "Endemic to the Gulf of California; its swim-bladder trade also drives vaquita bycatch." }),
  rec({ slug: "chinese-bahaba", commonName: "Chinese Bahaba", scientificName: "Bahaba taipingensis", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Bahaba-taipingensis")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "adriatic-sturgeon", commonName: "Adriatic Sturgeon", scientificName: "Acipenser naccarii", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Acipenser-naccarii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "kaluga", commonName: "Kaluga", scientificName: "Huso dauricus", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Huso-dauricus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "sakhalin-sturgeon", commonName: "Sakhalin Sturgeon", scientificName: "Acipenser mikadoi", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Acipenser-mikadoi")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "ship-sturgeon", commonName: "Ship Sturgeon", scientificName: "Acipenser nudiventris", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Acipenser-nudiventris")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "murray-cod", commonName: "Murray Cod", scientificName: "Maccullochella peelii", taxonGroup: "fish", redListCategory: "VU", sourceUrls: [fishbase("Maccullochella-peelii")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
  rec({ slug: "spotted-handfish", commonName: "Spotted Handfish", scientificName: "Brachionichthys hirsutus", taxonGroup: "fish", redListCategory: "CR", sourceUrls: [fishbase("Brachionichthys-hirsutus")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),

  // ===========================================================================
  // INVERTEBRATES
  // ===========================================================================
  rec({ slug: "black-abalone", commonName: "Black Abalone", scientificName: "Haliotis cracherodii", taxonGroup: "invertebrates", redListCategory: "CR", sourceUrls: [noaa("black-abalone")], dataConfidence: "source-review-pending", profileStatus: "index-only", imageStatus: "not-planned" }),
];
