import type { RedListSpeciesRecord } from "./types";
import { adw, noaa, fws, birdlife, rec } from "./_builders";

/**
 * Red List Batch 2 — verified index records (mammals + birds).
 *
 * Same compliance posture as Phase 1: confident, widely published IUCN
 * categories; every sourceUrl confirmed reachable; no invented status,
 * population numbers, trends, threats, ranges, or taxonomy. Region assignments
 * live in regions.ts. All records are index-only unless noted.
 */
export const RED_LIST_SPECIES_BATCH2: readonly RedListSpeciesRecord[] = [
  // --- Mammals ---
  rec({
    slug: "ganges-river-dolphin",
    commonName: "Ganges River Dolphin",
    scientificName: "Platanista gangetica",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "The Ganges, Brahmaputra, and associated river systems of South Asia.",
    primaryThreats: [
      "Dams and barrages fragmenting rivers",
      "Bycatch in fishing nets",
      "Pollution and reduced water flow",
    ],
    sourceUrls: [adw("Platanista_gangetica")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "amazon-river-dolphin",
    commonName: "Amazon River Dolphin",
    scientificName: "Inia geoffrensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "The Amazon and Orinoco river systems of South America.",
    primaryThreats: [
      "Use as fishing bait",
      "Entanglement and dams",
      "Pollution including mercury",
    ],
    sourceUrls: [adw("Inia_geoffrensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "west-indian-manatee",
    commonName: "West Indian Manatee",
    scientificName: "Trichechus manatus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Coastal and river waters of the southeastern United States, the Caribbean, and parts of Central and South America.",
    primaryThreats: [
      "Boat strikes",
      "Habitat loss and cold stress",
      "Entanglement",
    ],
    sourceUrls: [adw("Trichechus_manatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "amazonian-manatee",
    commonName: "Amazonian Manatee",
    scientificName: "Trichechus inunguis",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "The Amazon River basin of South America.",
    primaryThreats: [
      "Hunting for meat",
      "Bycatch and habitat change",
      "Pollution and reduced water quality",
    ],
    sourceUrls: [adw("Trichechus_inunguis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "dugong",
    commonName: "Dugong",
    scientificName: "Dugong dugon",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Warm coastal waters of the Indian and western Pacific Oceans.",
    primaryThreats: [
      "Loss of seagrass meadows",
      "Entanglement and bycatch",
      "Boat strikes and hunting",
    ],
    sourceUrls: [adw("Dugong_dugon")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Globally Vulnerable, but several regional sub-populations are assessed at higher risk.",
  }),
  rec({
    slug: "blue-whale",
    commonName: "Blue Whale",
    scientificName: "Balaenoptera musculus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "Found in oceans worldwide, migrating between cold feeding waters and warmer breeding areas.",
    primaryThreats: [
      "Ship strikes",
      "Entanglement in fishing gear",
      "Past commercial whaling (now recovering)",
    ],
    sourceUrls: [noaa("blue-whale"), adw("Balaenoptera_musculus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes: "The largest animal known to have lived.",
  }),
  rec({
    slug: "fin-whale",
    commonName: "Fin Whale",
    scientificName: "Balaenoptera physalus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "increasing",
    rangeSummary:
      "Found in oceans worldwide, mainly in deep offshore waters.",
    primaryThreats: [
      "Past commercial whaling (now recovering)",
      "Ship strikes",
      "Entanglement and noise",
    ],
    sourceUrls: [noaa("fin-whale"), adw("Balaenoptera_physalus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "sei-whale",
    commonName: "Sei Whale",
    scientificName: "Balaenoptera borealis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "Found in oceans worldwide, mostly in deep offshore waters.",
    primaryThreats: [
      "Past commercial whaling",
      "Ship strikes",
      "Entanglement",
    ],
    sourceUrls: [noaa("sei-whale"), adw("Balaenoptera_borealis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "north-atlantic-right-whale",
    commonName: "North Atlantic Right Whale",
    scientificName: "Eubalaena glacialis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Western North Atlantic, along the eastern coasts of the United States and Canada.",
    primaryThreats: [
      "Ship strikes",
      "Entanglement in fishing gear",
      "A very small remaining population",
    ],
    sourceUrls: [noaa("north-atlantic-right-whale"), adw("Eubalaena_glacialis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "hawaiian-monk-seal",
    commonName: "Hawaiian Monk Seal",
    scientificName: "Neomonachus schauinslandi",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "The Hawaiian Islands, mainly the remote north-western chain.",
    primaryThreats: [
      "Entanglement in marine debris",
      "Food limitation for young seals",
      "Disease and human disturbance",
    ],
    sourceUrls: [noaa("hawaiian-monk-seal")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "red-wolf",
    commonName: "Red Wolf",
    scientificName: "Canis rufus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A small reintroduced wild population in eastern North Carolina, USA, plus captive-bred animals.",
    primaryThreats: [
      "A very small population",
      "Hybridisation with coyotes",
      "Human-caused deaths",
    ],
    sourceUrls: [fws("red-wolf-canis-rufus"), adw("Canis_rufus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "ethiopian-wolf",
    commonName: "Ethiopian Wolf",
    scientificName: "Canis simensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Restricted to a few isolated Afroalpine mountain areas in the Ethiopian Highlands.",
    primaryThreats: [
      "A very small, fragmented range",
      "Disease caught from domestic dogs (rabies, distemper)",
      "Habitat loss to farming",
    ],
    sourceUrls: [adw("Canis_simensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes: "Africa's most threatened carnivore and rarest canid.",
  }),
  rec({
    slug: "dhole",
    commonName: "Dhole",
    scientificName: "Cuon alpinus",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Scattered populations across South, Southeast, and East Asia.",
    primaryThreats: [
      "Habitat loss and fragmentation",
      "Depletion of wild prey",
      "Persecution and disease from domestic dogs",
    ],
    sourceUrls: [adw("Cuon_alpinus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "iberian-lynx",
    commonName: "Iberian Lynx",
    scientificName: "Lynx pardinus",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "increasing",
    rangeSummary:
      "Found in Mediterranean scrubland and woodland in parts of Spain and Portugal, on the Iberian Peninsula.",
    primaryThreats: [
      "Past collapse of its main prey, the European rabbit",
      "Habitat loss and fragmentation",
      "Road collisions",
    ],
    sourceUrls: [adw("Lynx_pardinus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes:
      "Reported as down-listed from Endangered to Vulnerable in 2024 after sustained recovery; confirm the current category on the live IUCN entry.",
  }),
  rec({
    slug: "okapi",
    commonName: "Okapi",
    scientificName: "Okapia johnstoni",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Endemic to the rainforests of the northern and eastern Democratic Republic of the Congo.",
    primaryThreats: [
      "Habitat loss from logging and settlement",
      "Hunting for meat and skins",
      "Instability across parts of its range",
    ],
    sourceUrls: [adw("Okapia_johnstoni")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "pygmy-hippopotamus",
    commonName: "Pygmy Hippopotamus",
    scientificName: "Choeropsis liberiensis",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Forests and wetlands of West Africa, mainly Liberia.",
    primaryThreats: [
      "Deforestation and habitat loss",
      "Hunting",
      "A small, fragmented population",
    ],
    sourceUrls: [adw("Hexaprotodon_liberiensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "common-hippopotamus",
    commonName: "Common Hippopotamus",
    scientificName: "Hippopotamus amphibius",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "stable",
    rangeSummary:
      "Rivers, lakes, and wetlands across sub-Saharan Africa.",
    primaryThreats: [
      "Poaching for meat and ivory teeth",
      "Habitat loss and water diversion",
      "Conflict with people",
    ],
    sourceUrls: [adw("Hippopotamus_amphibius")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "black-footed-ferret",
    commonName: "Black-footed Ferret",
    scientificName: "Mustela nigripes",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "Grasslands of central North America, in reintroduced populations.",
    primaryThreats: [
      "Loss of prairie dogs (its main prey)",
      "Disease (plague and distemper)",
      "Habitat loss",
    ],
    sourceUrls: [fws("black-footed-ferret-mustela-nigripes"), adw("Mustela_nigripes")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "addax",
    commonName: "Addax",
    scientificName: "Addax nasomaculatus",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "A desert antelope of the Sahara, now reduced to tiny remnant numbers in the wild, mainly in Niger and Chad.",
    primaryThreats: [
      "Uncontrolled hunting",
      "Disturbance from oil exploration",
      "Drought and habitat degradation",
    ],
    sourceUrls: [adw("Addax_nasomaculatus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "grevys-zebra",
    commonName: "Grévy's Zebra",
    scientificName: "Equus grevyi",
    taxonGroup: "mammals",
    redListCategory: "EN",
    populationTrend: "stable",
    rangeSummary:
      "Dry grasslands and scrub of Kenya and Ethiopia.",
    primaryThreats: [
      "Competition with livestock for water and grazing",
      "Habitat loss",
      "Hunting",
    ],
    sourceUrls: [adw("Equus_grevyi")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "saola",
    commonName: "Saola",
    scientificName: "Pseudoryx nghetinhensis",
    taxonGroup: "mammals",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "The Annamite Mountains along the border of Vietnam and Laos.",
    primaryThreats: [
      "Snaring set for other animals",
      "Hunting",
      "A very small, elusive population",
    ],
    sourceUrls: [adw("Pseudoryx_nghetinhensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
    notes: "One of the rarest large mammals; rarely seen since its 1992 description.",
  }),
  rec({
    slug: "giant-anteater",
    commonName: "Giant Anteater",
    scientificName: "Myrmecophaga tridactyla",
    taxonGroup: "mammals",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Grasslands and forests from Central America to South America.",
    primaryThreats: [
      "Habitat loss and fires",
      "Road deaths",
      "Hunting",
    ],
    sourceUrls: [adw("Myrmecophaga_tridactyla")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),

  // --- Birds (BirdLife International DataZone) ---
  rec({
    slug: "red-crowned-crane",
    commonName: "Red-crowned Crane",
    scientificName: "Grus japonensis",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Wetlands of East Asia, including parts of China, Japan, Korea, and Russia.",
    primaryThreats: [
      "Loss and drainage of wetlands",
      "Disturbance",
      "A small population",
    ],
    sourceUrls: [birdlife("red-crowned-crane-grus-japonensis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "blue-crane",
    commonName: "Blue Crane",
    scientificName: "Grus paradisea",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Grasslands and farmland of southern Africa, mainly South Africa.",
    primaryThreats: [
      "Poisoning (deliberate and accidental)",
      "Collisions with power lines",
      "Habitat change",
    ],
    sourceUrls: [birdlife("blue-crane-anthropoides-paradiseus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "indian-vulture",
    commonName: "Indian Vulture",
    scientificName: "Gyps indicus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "stable",
    rangeSummary:
      "South Asia, including India and Pakistan.",
    primaryThreats: [
      "Poisoning by the veterinary drug diclofenac in livestock carcasses",
      "Reduced food",
      "Habitat change",
    ],
    sourceUrls: [birdlife("indian-vulture-gyps-indicus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "hooded-vulture",
    commonName: "Hooded Vulture",
    scientificName: "Necrosyrtes monachus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Sub-Saharan Africa.",
    primaryThreats: [
      "Poisoning",
      "Killing for belief-based use and bushmeat",
      "Habitat change",
    ],
    sourceUrls: [birdlife("hooded-vulture-necrosyrtes-monachus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "white-backed-vulture",
    commonName: "White-backed Vulture",
    scientificName: "Gyps africanus",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Savannas across sub-Saharan Africa.",
    primaryThreats: [
      "Poisoning of carcasses",
      "Killing linked to poaching",
      "Loss of food and habitat",
    ],
    sourceUrls: [birdlife("white-backed-vulture-gyps-africanus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "andean-condor",
    commonName: "Andean Condor",
    scientificName: "Vultur gryphus",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "The Andes and adjacent Pacific coasts of South America, from Venezuela to Tierra del Fuego.",
    primaryThreats: [
      "Poisoning, often secondary from baited carcasses",
      "Persecution",
      "Collisions and reduced food availability",
    ],
    sourceUrls: [birdlife("andean-condor-vultur-gryphus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "grey-parrot",
    commonName: "Grey Parrot",
    scientificName: "Psittacus erithacus",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Rainforests of central and western Africa.",
    primaryThreats: [
      "Trapping for the international pet trade",
      "Habitat loss",
    ],
    sourceUrls: [birdlife("grey-parrot-psittacus-erithacus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
    notes: "Heavily affected by the cage-bird trade.",
  }),
  rec({
    slug: "lears-macaw",
    commonName: "Lear's Macaw",
    scientificName: "Anodorhynchus leari",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "A small area of dry scrubland (caatinga) in north-eastern Brazil.",
    primaryThreats: [
      "Past trapping for the pet trade",
      "Habitat loss",
      "A very small range",
    ],
    sourceUrls: [birdlife("lears-macaw-anodorhynchus-leari")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "blue-throated-macaw",
    commonName: "Blue-throated Macaw",
    scientificName: "Ara glaucogularis",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "stable",
    rangeSummary:
      "A small area of seasonally flooded savanna in northern Bolivia.",
    primaryThreats: [
      "Past trapping for the pet trade",
      "Loss of nesting palms",
      "A very small range",
    ],
    sourceUrls: [birdlife("blue-throated-macaw-ara-glaucogularis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "yellow-crested-cockatoo",
    commonName: "Yellow-crested Cockatoo",
    scientificName: "Cacatua sulphurea",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Islands of Indonesia and Timor-Leste.",
    primaryThreats: [
      "Trapping for the cage-bird trade",
      "Habitat loss",
    ],
    sourceUrls: [birdlife("yellow-crested-cockatoo-cacatua-sulphurea")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "kea",
    commonName: "Kea",
    scientificName: "Nestor notabilis",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Mountains of the South Island of New Zealand.",
    primaryThreats: [
      "Introduced predators",
      "Conflict with people and past culling",
      "Lead poisoning from buildings",
    ],
    sourceUrls: [birdlife("kea-nestor-notabilis")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "swift-parrot",
    commonName: "Swift Parrot",
    scientificName: "Lathamus discolor",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds in Tasmania and migrates to mainland south-eastern Australia.",
    primaryThreats: [
      "Loss of breeding and foraging trees",
      "Predation by introduced sugar gliders",
      "A small population",
    ],
    sourceUrls: [birdlife("swift-parrot-lathamus-discolor")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "orange-bellied-parrot",
    commonName: "Orange-bellied Parrot",
    scientificName: "Neophema chrysogaster",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds in south-western Tasmania and migrates to coastal south-eastern Australia.",
    primaryThreats: [
      "A tiny population",
      "Loss of coastal habitat",
      "Predation and competition",
    ],
    sourceUrls: [birdlife("orange-bellied-parrot-neophema-chrysogaster")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "helmeted-hornbill",
    commonName: "Helmeted Hornbill",
    scientificName: "Rhinoplax vigil",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Rainforests of the Malay Peninsula, Sumatra, and Borneo.",
    primaryThreats: [
      "Poaching for its solid casque ('red ivory')",
      "Deforestation",
    ],
    sourceUrls: [birdlife("helmeted-hornbill-rhinoplax-vigil")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "great-indian-bustard",
    commonName: "Great Indian Bustard",
    scientificName: "Ardeotis nigriceps",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Dry grasslands of India and Pakistan.",
    primaryThreats: [
      "Collisions with power lines",
      "Habitat loss to farming and development",
      "A tiny population",
    ],
    sourceUrls: [birdlife("great-indian-bustard-ardeotis-nigriceps")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
  rec({
    slug: "spoon-billed-sandpiper",
    commonName: "Spoon-billed Sandpiper",
    scientificName: "Calidris pygmaea",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Breeds in north-eastern Russia and migrates along the East Asian coast to wintering sites in South and Southeast Asia.",
    primaryThreats: [
      "Loss of coastal stopover wetlands",
      "Trapping on the wintering grounds",
      "A tiny population",
    ],
    sourceUrls: [birdlife("spoon-billed-sandpiper-calidris-pygmaea")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "crested-ibis",
    commonName: "Crested Ibis",
    scientificName: "Nipponia nippon",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "East Asia; the wild population is centred in central China, with reintroductions elsewhere.",
    primaryThreats: [
      "Past habitat loss and hunting",
      "A small founder population",
      "Pesticides reducing food",
    ],
    sourceUrls: [birdlife("asian-crested-ibis-nipponia-nippon")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "black-faced-spoonbill",
    commonName: "Black-faced Spoonbill",
    scientificName: "Platalea minor",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "increasing",
    rangeSummary:
      "Coastal East Asia, breeding on islands off the Korean Peninsula and wintering farther south.",
    primaryThreats: [
      "Loss of coastal wetlands and tidal flats",
      "Pollution",
      "Disturbance",
    ],
    sourceUrls: [birdlife("black-faced-spoonbill-platalea-minor")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "wandering-albatross",
    commonName: "Wandering Albatross",
    scientificName: "Diomedea exulans",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "The Southern Ocean, breeding on remote sub-Antarctic islands.",
    primaryThreats: [
      "Drowning on longline fishing hooks",
      "Plastic pollution",
      "Invasive predators at colonies",
    ],
    sourceUrls: [birdlife("wandering-albatross-diomedea-exulans")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "humboldt-penguin",
    commonName: "Humboldt Penguin",
    scientificName: "Spheniscus humboldti",
    taxonGroup: "birds",
    redListCategory: "VU",
    populationTrend: "decreasing",
    rangeSummary:
      "Coasts of Peru and Chile, along the cold Humboldt Current.",
    primaryThreats: [
      "Overfishing of prey",
      "Ocean changes such as El Niño",
      "Disturbance and bycatch",
    ],
    sourceUrls: [birdlife("humboldt-penguin-spheniscus-humboldti")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "martial-eagle",
    commonName: "Martial Eagle",
    scientificName: "Polemaetus bellicosus",
    taxonGroup: "birds",
    redListCategory: "EN",
    populationTrend: "decreasing",
    rangeSummary:
      "Open habitats across sub-Saharan Africa.",
    primaryThreats: [
      "Persecution by farmers",
      "Collisions and electrocution",
      "Prey and habitat loss",
    ],
    sourceUrls: [birdlife("martial-eagle-polemaetus-bellicosus")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "has-image",
  }),
  rec({
    slug: "madagascar-fish-eagle",
    commonName: "Madagascar Fish Eagle",
    scientificName: "Haliaeetus vociferoides",
    taxonGroup: "birds",
    redListCategory: "CR",
    populationTrend: "decreasing",
    rangeSummary:
      "Coasts and wetlands of western Madagascar.",
    primaryThreats: [
      "Habitat loss and disturbance",
      "Competition for fish and nest sites",
      "A tiny population",
    ],
    sourceUrls: [birdlife("madagascar-fish-eagle-haliaeetus-vociferoides")],
    dataConfidence: "partial",
    profileStatus: "detailed-profile",
    imageStatus: "not-planned",
  }),
];
