import type { SourceLink } from "@/lib/educational/types";
import { ANIMAL_SOURCES, SRC_ADW } from "@/lib/educational/animal-sources";
import type { FaunaContinentRecord } from "./types";

/**
 * Continent distribution records for existing FaunaHub animal profiles.
 *
 * Sourcing: each record reuses the species' already-verified authoritative
 * sources (ANIMAL_SOURCES) so distribution claims rest on the same accounts
 * that document the animal's range. A small set of profiles not covered by
 * ANIMAL_SOURCES use a verified ADW account here (FAUNA_EXTRA_SOURCES).
 *
 * Scope: this layer covers LAND, freshwater, and coastal fauna only. Purely
 * marine/aquarium species (sharks, whales, reef fish, etc.) are intentionally
 * excluded and reserved for the future ocean-by-depth layer.
 *
 * No invented ranges. Widespread groups are marked "broad-range" and described
 * cautiously; nothing here is a complete range map.
 */

const adwAccount = (binomial: string, label: string): SourceLink => ({
  label: `Animal Diversity Web — ${label}`,
  url: `https://animaldiversity.org/accounts/${binomial}/`,
  type: "university",
  note: "University of Michigan species account",
});

/** Verified ADW accounts for profiles not present in ANIMAL_SOURCES. */
const FAUNA_EXTRA_SOURCES: Record<string, SourceLink[]> = {
  bear: [adwAccount("Ursus_arctos", "Ursus arctos (brown bear)"), SRC_ADW],
  fox: [adwAccount("Vulpes_vulpes", "Vulpes vulpes (red fox)"), SRC_ADW],
  giraffe: [
    adwAccount("Giraffa_camelopardalis", "Giraffa camelopardalis (giraffe)"),
    SRC_ADW,
  ],
  kangaroo: [adwAccount("Macropus_rufus", "Macropus rufus (red kangaroo)"), SRC_ADW],
  koala: [
    adwAccount("Phascolarctos_cinereus", "Phascolarctos cinereus (koala)"),
    SRC_ADW,
  ],
  owl: [adwAccount("Strigidae", "Strigidae (typical owls)"), SRC_ADW],
  panda: [
    adwAccount("Ailuropoda_melanoleuca", "Ailuropoda melanoleuca (giant panda)"),
    SRC_ADW,
  ],
  zebra: [adwAccount("Equus_quagga", "Equus quagga (plains zebra)"), SRC_ADW],
};

/** Resolve a profile's authoritative source links for fauna distribution. */
export function resolveFaunaSourceLinks(animalSlug: string): SourceLink[] {
  return ANIMAL_SOURCES[animalSlug] ?? FAUNA_EXTRA_SOURCES[animalSlug] ?? [];
}

type RawRecord = Omit<FaunaContinentRecord, "sourceUrls"> & {
  sourceUrls?: string[];
};

function fc(r: RawRecord): FaunaContinentRecord {
  const sourceUrls =
    r.sourceUrls ?? resolveFaunaSourceLinks(r.animalSlug).map((s) => s.url);
  return { ...r, sourceUrls };
}

export const FAUNA_RECORDS: readonly FaunaContinentRecord[] = [
  // --- Mammals ---
  fc({ animalSlug: "lion", commonName: "Lion", continentSlugs: ["africa", "asia"], habitatTags: ["savanna", "grassland"], distributionNote: "Found across much of sub-Saharan Africa, with a small population in the Gir Forest of India.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "leopard", commonName: "Leopard", continentSlugs: ["africa", "asia"], habitatTags: ["forest", "savanna", "mountain"], distributionNote: "Widely distributed across Africa and parts of Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "cheetah", commonName: "Cheetah", continentSlugs: ["africa", "asia"], habitatTags: ["savanna", "grassland"], distributionNote: "Mainly sub-Saharan Africa, with a tiny remnant population in Iran.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "tiger", commonName: "Tiger", continentSlugs: ["asia"], habitatTags: ["forest", "grassland", "wetland"], distributionNote: "Native to scattered parts of Asia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "jaguar", commonName: "Jaguar", continentSlugs: ["south-america", "north-america"], habitatTags: ["forest", "wetland"], distributionNote: "Ranges from parts of the southern United States through Central and South America.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "elephant", commonName: "Elephant", continentSlugs: ["africa", "asia"], habitatTags: ["savanna", "forest", "grassland"], distributionNote: "African elephants occur across sub-Saharan Africa; the Asian elephant lives in South and Southeast Asia.", confidence: "verified", isNativeRange: true, notes: "Distinct species on each continent." }),
  fc({ animalSlug: "giraffe", commonName: "Giraffe", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland"], distributionNote: "Native to sub-Saharan Africa.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "zebra", commonName: "Zebra", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland"], distributionNote: "Native to eastern and southern Africa.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "gorilla", commonName: "Gorilla", continentSlugs: ["africa"], habitatTags: ["forest", "mountain"], distributionNote: "Equatorial African rainforests.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "chimpanzee", commonName: "Chimpanzee", continentSlugs: ["africa"], habitatTags: ["forest", "savanna"], distributionNote: "Forests and savanna-woodland of equatorial Africa.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "hyena", commonName: "Hyena", continentSlugs: ["africa", "asia"], habitatTags: ["savanna", "grassland", "desert"], distributionNote: "Across Africa and into parts of the Middle East and Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "meerkat", commonName: "Meerkat", continentSlugs: ["africa"], habitatTags: ["desert", "savanna"], distributionNote: "Dry savanna and deserts of southern Africa.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "lemur", commonName: "Lemur", continentSlugs: ["africa"], habitatTags: ["forest"], distributionNote: "Found only on Madagascar, off the south-east African coast.", confidence: "verified", isNativeRange: true, notes: "Endemic to Madagascar." }),
  fc({ animalSlug: "red-panda", commonName: "Red Panda", continentSlugs: ["asia"], habitatTags: ["forest", "mountain"], distributionNote: "Eastern Himalaya and mountains of south-western China.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "panda", commonName: "Giant Panda", continentSlugs: ["asia"], habitatTags: ["forest", "mountain"], distributionNote: "Mountain bamboo forests of central China.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "tapir", commonName: "Tapir", continentSlugs: ["south-america", "north-america", "asia"], habitatTags: ["forest", "wetland"], distributionNote: "Tapir species occur in Central and South America and in South-east Asia.", confidence: "broad-range", isNativeRange: true, notes: "Several distinct species." }),
  fc({ animalSlug: "sloth", commonName: "Sloth", continentSlugs: ["south-america", "north-america"], habitatTags: ["forest"], distributionNote: "Tropical forests of Central and South America.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "armadillo", commonName: "Armadillo", continentSlugs: ["south-america", "north-america"], habitatTags: ["grassland", "forest"], distributionNote: "The Americas; the nine-banded armadillo ranges into the southern United States.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "porcupine", commonName: "Porcupine", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america"], habitatTags: ["forest", "grassland", "desert"], distributionNote: "Old World and New World porcupines occur across several continents.", confidence: "broad-range", isNativeRange: true, notes: "Two distinct families." }),
  fc({ animalSlug: "wolf", commonName: "Wolf", continentSlugs: ["north-america", "europe", "asia"], habitatTags: ["forest", "tundra", "grassland", "mountain"], distributionNote: "Across much of the Northern Hemisphere.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "fox", commonName: "Fox", continentSlugs: ["europe", "asia", "north-america", "africa"], habitatTags: ["forest", "grassland", "urban-adapted", "tundra"], distributionNote: "The red fox is one of the most widespread wild carnivores; foxes also occur on other continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "bear", commonName: "Bear", continentSlugs: ["north-america", "europe", "asia"], habitatTags: ["forest", "mountain", "tundra"], distributionNote: "The brown bear ranges across North America, Europe, and Asia; other bears occur in these regions too.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "lynx", commonName: "Lynx", continentSlugs: ["europe", "asia", "north-america"], habitatTags: ["forest", "mountain", "tundra"], distributionNote: "Lynx species occur across Europe, Asia, and North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "deer", commonName: "Deer", continentSlugs: ["europe", "asia", "north-america", "south-america"], habitatTags: ["forest", "grassland"], distributionNote: "Deer occur natively across many continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "moose", commonName: "Moose", continentSlugs: ["north-america", "europe", "asia"], habitatTags: ["forest", "wetland"], distributionNote: "Northern forests of North America and northern Eurasia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "raccoon", commonName: "Raccoon", continentSlugs: ["north-america"], habitatTags: ["forest", "wetland", "urban-adapted"], distributionNote: "Native to North America; introduced to parts of Europe and Asia.", confidence: "verified", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "otter", commonName: "Otter", continentSlugs: ["europe", "asia", "north-america", "south-america", "africa"], habitatTags: ["freshwater", "wetland", "coastal"], distributionNote: "Otter species occur on most continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "beaver", commonName: "Beaver", continentSlugs: ["north-america", "europe", "asia"], habitatTags: ["freshwater", "wetland"], distributionNote: "North American and Eurasian beavers.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "badger", commonName: "Badger", continentSlugs: ["europe", "asia", "north-america"], habitatTags: ["forest", "grassland"], distributionNote: "Badger species occur across Eurasia and North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "hedgehog", commonName: "Hedgehog", continentSlugs: ["europe", "asia", "africa"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Native to Europe, Asia, and Africa — not naturally to the Americas or Australia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "bat", commonName: "Bat", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["forest", "urban-adapted", "coastal"], distributionNote: "Bats occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "kangaroo", commonName: "Kangaroo", continentSlugs: ["oceania"], habitatTags: ["grassland", "savanna", "desert"], distributionNote: "Native to Australia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "koala", commonName: "Koala", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Eucalyptus forests of eastern Australia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "wombat", commonName: "Wombat", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland"], distributionNote: "Native to Australia and Tasmania.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "platypus", commonName: "Platypus", continentSlugs: ["oceania"], habitatTags: ["freshwater", "wetland"], distributionNote: "Freshwater systems of eastern Australia and Tasmania.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "rabbit", commonName: "Rabbit", continentSlugs: ["europe"], habitatTags: ["grassland", "urban-adapted"], distributionNote: "The European rabbit is native to the Iberian Peninsula and widely introduced elsewhere.", confidence: "verified", isNativeRange: true, isIntroducedRange: true }),

  // --- Birds ---
  fc({ animalSlug: "eagle", commonName: "Eagle", continentSlugs: ["north-america", "europe", "asia", "africa"], habitatTags: ["mountain", "forest", "coastal"], distributionNote: "Eagle species occur on several continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "owl", commonName: "Owl", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Owls occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "falcon", commonName: "Falcon", continentSlugs: ["north-america", "europe", "asia", "africa", "oceania", "south-america"], habitatTags: ["grassland", "mountain", "urban-adapted"], distributionNote: "The peregrine falcon is among the most widely distributed birds.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "hawk", commonName: "Hawk", continentSlugs: ["north-america", "south-america"], habitatTags: ["forest", "grassland"], distributionNote: "Hawks are widespread; the red-tailed hawk ranges across North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "vulture", commonName: "Vulture", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america"], habitatTags: ["savanna", "mountain"], distributionNote: "Old World and New World vultures occur across several continents.", confidence: "broad-range", isNativeRange: true, notes: "Two distinct groups." }),
  fc({ animalSlug: "penguin", commonName: "Penguin", continentSlugs: ["antarctica", "oceania", "south-america", "africa"], habitatTags: ["coastal", "polar", "island"], distributionNote: "Southern Hemisphere; several species are associated with Antarctic coasts and the Southern Ocean.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "pelican", commonName: "Pelican", continentSlugs: ["north-america", "south-america", "europe", "asia", "africa", "oceania"], habitatTags: ["coastal", "wetland"], distributionNote: "Pelicans occur on coasts and inland waters across continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "flamingo", commonName: "Flamingo", continentSlugs: ["africa", "south-america", "asia", "europe"], habitatTags: ["wetland", "coastal"], distributionNote: "Flamingo species occur in Africa, the Americas, and parts of Eurasia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "peacock", commonName: "Peacock", continentSlugs: ["asia"], habitatTags: ["forest", "grassland"], distributionNote: "Indian peafowl are native to South Asia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "toucan", commonName: "Toucan", continentSlugs: ["south-america", "north-america"], habitatTags: ["forest"], distributionNote: "Tropical forests of Central and South America.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "hummingbird", commonName: "Hummingbird", continentSlugs: ["south-america", "north-america"], habitatTags: ["forest", "mountain"], distributionNote: "Found only in the Americas.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "woodpecker", commonName: "Woodpecker", continentSlugs: ["north-america", "europe", "asia", "africa", "south-america"], habitatTags: ["forest"], distributionNote: "Woodpeckers occur on most continents (absent from Australia and Antarctica).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "robin", commonName: "Robin", continentSlugs: ["europe"], habitatTags: ["forest", "urban-adapted"], distributionNote: "The European robin is common across Europe.", confidence: "verified", isNativeRange: true, notes: "Distinct from the American robin." }),
  fc({ animalSlug: "sparrow", commonName: "Sparrow", continentSlugs: ["europe", "asia", "africa", "north-america", "south-america", "oceania"], habitatTags: ["urban-adapted", "grassland"], distributionNote: "The house sparrow has spread across much of the world alongside people.", confidence: "broad-range", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "crow", commonName: "Crow", continentSlugs: ["north-america", "europe", "asia", "oceania"], habitatTags: ["urban-adapted", "forest", "grassland"], distributionNote: "Crows are widespread and highly adaptable.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "raven", commonName: "Raven", continentSlugs: ["north-america", "europe", "asia"], habitatTags: ["mountain", "tundra", "forest"], distributionNote: "The common raven ranges across the Northern Hemisphere.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "pigeon", commonName: "Pigeon", continentSlugs: ["europe", "asia", "africa", "north-america", "south-america", "oceania"], habitatTags: ["urban-adapted", "coastal"], distributionNote: "The rock dove is found worldwide, especially around cities.", confidence: "broad-range", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "swan", commonName: "Swan", continentSlugs: ["europe", "asia", "north-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "Swan species occur across the Northern Hemisphere; the black swan is native to Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "stork", commonName: "Stork", continentSlugs: ["europe", "africa", "asia"], habitatTags: ["wetland", "grassland"], distributionNote: "The white stork breeds across Europe, with migrations to Africa and Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "duck", commonName: "Duck", continentSlugs: ["europe", "asia", "north-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "The mallard is widespread across the Northern Hemisphere.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "goose", commonName: "Goose", continentSlugs: ["europe", "asia"], habitatTags: ["freshwater", "wetland", "grassland"], distributionNote: "The greylag goose breeds across Europe and Asia.", confidence: "broad-range", isNativeRange: true }),

  // --- Reptiles & Amphibians ---
  fc({ animalSlug: "crocodile", commonName: "Crocodile", continentSlugs: ["africa", "asia", "oceania"], habitatTags: ["wetland", "freshwater", "coastal"], distributionNote: "Crocodile species occur in Africa, Asia, and northern Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "alligator", commonName: "Alligator", continentSlugs: ["north-america", "asia"], habitatTags: ["wetland", "freshwater"], distributionNote: "The American alligator lives in the south-eastern US; the Chinese alligator in eastern China.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "caiman", commonName: "Caiman", continentSlugs: ["south-america", "north-america"], habitatTags: ["wetland", "freshwater"], distributionNote: "Wetlands of Central and South America.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "komodo-dragon", commonName: "Komodo Dragon", continentSlugs: ["asia"], habitatTags: ["island", "forest"], distributionNote: "A few islands in Indonesia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "monitor-lizard", commonName: "Monitor Lizard", continentSlugs: ["africa", "asia", "oceania"], habitatTags: ["forest", "savanna", "wetland"], distributionNote: "Monitor lizards occur across Africa, Asia, and Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "iguana", commonName: "Iguana", continentSlugs: ["south-america", "north-america"], habitatTags: ["forest", "coastal"], distributionNote: "Green iguanas range across Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "chameleon", commonName: "Chameleon", continentSlugs: ["africa", "asia", "europe"], habitatTags: ["forest", "savanna"], distributionNote: "Most chameleon species live in Africa and Madagascar, with some in southern Europe and Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "gecko", commonName: "Gecko", continentSlugs: ["asia", "oceania", "africa", "north-america", "south-america", "europe"], habitatTags: ["forest", "desert", "urban-adapted"], distributionNote: "Geckos are a large, widespread group across warm regions of the world.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "snake", commonName: "Snake", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["forest", "grassland", "desert", "wetland"], distributionNote: "Snakes occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "anaconda", commonName: "Anaconda", continentSlugs: ["south-america"], habitatTags: ["wetland", "freshwater"], distributionNote: "The green anaconda lives in tropical South America.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "turtle", commonName: "Turtle", continentSlugs: ["north-america", "asia", "europe", "africa", "south-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "Freshwater and terrestrial turtles occur widely across continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "frog", commonName: "Frog", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["wetland", "freshwater", "forest"], distributionNote: "Frogs occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "toad", commonName: "Toad", continentSlugs: ["europe", "asia", "africa", "north-america", "south-america"], habitatTags: ["grassland", "forest", "urban-adapted"], distributionNote: "True toads are widespread across continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "salamander", commonName: "Salamander", continentSlugs: ["north-america", "europe", "asia"], habitatTags: ["freshwater", "forest"], distributionNote: "Salamanders are concentrated in the Northern Hemisphere.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "newt", commonName: "Newt", continentSlugs: ["europe", "asia", "north-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "Newts occur across the Northern Hemisphere.", confidence: "broad-range", isNativeRange: true }),

  // --- Coastal / polar ---
  fc({ animalSlug: "seal", commonName: "Seal", continentSlugs: ["antarctica", "north-america", "europe", "oceania", "south-america", "africa"], habitatTags: ["coastal", "polar"], distributionNote: "Seals occur on coasts and in cold seas worldwide, including around Antarctica.", confidence: "broad-range", isNativeRange: true }),

  // --- Notable invertebrates ---
  fc({ animalSlug: "bee", commonName: "Bee", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["grassland", "forest", "urban-adapted"], distributionNote: "Bees occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "butterfly", commonName: "Butterfly", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["grassland", "forest"], distributionNote: "Butterflies occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "ant", commonName: "Ant", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Ants occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "spider", commonName: "Spider", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Spiders occur on every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "dragonfly", commonName: "Dragonfly", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["wetland", "freshwater"], distributionNote: "Dragonflies are found near fresh water across every continent except Antarctica.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "ladybug", commonName: "Ladybug", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["grassland", "urban-adapted"], distributionNote: "Lady beetles are widespread across the world's land continents.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "praying-mantis", commonName: "Praying Mantis", continentSlugs: ["africa", "asia", "europe", "north-america", "south-america", "oceania"], habitatTags: ["grassland", "forest"], distributionNote: "Mantises occur in warmer regions across many continents.", confidence: "broad-range", isNativeRange: true }),

  // === Regional Fauna: Africa Expansion (2026-06-27) ===
  // New African profiles + previously-unrecorded existing African animals.
  // Cautious range framing; native vs introduced distinguished; no completeness claim.
  fc({ animalSlug: "african-buffalo", commonName: "African Buffalo", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "wetland"], distributionNote: "Found in parts of sub-Saharan Africa, in savanna, grassland, and wetland edges with reliable water.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "wildebeest", commonName: "Wildebeest", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland"], distributionNote: "Eastern and southern Africa; famous for large seasonal migrations on the savanna.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "okapi", commonName: "Okapi", continentSlugs: ["africa"], habitatTags: ["forest"], distributionNote: "Endemic to the rainforests of the northeastern Democratic Republic of the Congo.", confidence: "verified", isNativeRange: true, notes: "Narrow, forest-restricted range." }),
  fc({ animalSlug: "aardvark", commonName: "Aardvark", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "forest"], distributionNote: "Occurs across parts of sub-Saharan Africa where termites and ants are plentiful.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "mandrill", commonName: "Mandrill", continentSlugs: ["africa"], habitatTags: ["forest"], distributionNote: "Rainforests of west-central Africa (e.g. Cameroon, Gabon, Congo).", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "gelada", commonName: "Gelada", continentSlugs: ["africa"], habitatTags: ["mountain", "grassland"], distributionNote: "Endemic to the high grasslands of the Ethiopian Highlands.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "hippopotamus", commonName: "Hippopotamus", continentSlugs: ["africa"], habitatTags: ["freshwater", "wetland", "savanna"], distributionNote: "Rivers, lakes, and wetlands across parts of sub-Saharan Africa.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "marabou-stork", commonName: "Marabou Stork", continentSlugs: ["africa"], habitatTags: ["wetland", "savanna", "urban-adapted"], distributionNote: "Widespread in sub-Saharan Africa, around wetlands, savannas, and human settlements.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "african-grey-parrot", commonName: "African Grey Parrot", continentSlugs: ["africa"], habitatTags: ["forest"], distributionNote: "Rainforests of western and central Africa; Endangered, with wild capture for the pet trade a key pressure.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "secretary-bird", commonName: "Secretary Bird", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland"], distributionNote: "Open grasslands and savannas across parts of sub-Saharan Africa.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "ostrich", commonName: "Ostrich", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "desert"], distributionNote: "Open and arid habitats across parts of Africa.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "nile-crocodile", commonName: "Nile Crocodile", continentSlugs: ["africa"], habitatTags: ["freshwater", "wetland"], distributionNote: "Rivers, lakes, and wetlands across parts of sub-Saharan Africa and the Nile basin.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "rock-python", commonName: "African Rock Python", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "forest"], distributionNote: "Sub-Saharan Africa, in savanna, grassland, and forest edge, often near water.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "puff-adder", commonName: "Puff Adder", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "desert"], distributionNote: "Widely across sub-Saharan Africa (and parts of Arabia), in savanna, grassland, and semi-desert.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "mamba", commonName: "Black Mamba", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "forest"], distributionNote: "The black mamba ranges across parts of sub-Saharan Africa in savanna and woodland.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "clawed-frog", commonName: "African Clawed Frog", continentSlugs: ["africa"], habitatTags: ["freshwater", "wetland"], distributionNote: "Native to ponds and wetlands of southern Africa; widely introduced elsewhere in the world.", confidence: "verified", isNativeRange: true, isIntroducedRange: true, notes: "Introduced/invasive in several regions outside Africa." }),
  fc({ animalSlug: "nile-perch", commonName: "Nile Perch", continentSlugs: ["africa"], habitatTags: ["freshwater"], distributionNote: "Native to parts of Africa (Nile, Congo and other systems); introduced into Lake Victoria, where it is invasive.", confidence: "verified", isNativeRange: true, isIntroducedRange: true, notes: "Invasive in Lake Victoria; linked to native cichlid declines." }),
  fc({ animalSlug: "tilapia", commonName: "Tilapia", continentSlugs: ["africa"], habitatTags: ["freshwater"], distributionNote: "Native to parts of Africa (and the Levant); the Nile tilapia is widely farmed and introduced worldwide.", confidence: "broad-range", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "dung-beetle", commonName: "Dung Beetle", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "forest"], distributionNote: "Highly diverse across Africa (and worldwide except Antarctica); abundant in savannas with large herbivores.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "termite", commonName: "Termite", continentSlugs: ["africa"], habitatTags: ["savanna", "grassland", "forest"], distributionNote: "Diverse across Africa (and warm regions worldwide); mound-builders are prominent in African savannas.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "tsetse-fly", commonName: "Tsetse Fly", continentSlugs: ["africa"], habitatTags: ["savanna", "forest", "wetland"], distributionNote: "Found in parts of sub-Saharan Africa, in savanna woodland and riverine forest.", confidence: "broad-range", isNativeRange: true }),

  // === Regional Fauna: Asia Expansion (2026-06-27) ===
  // New Asian profiles + previously-unrecorded existing Asian animals.
  // Cautious range framing; native vs introduced vs domestic distinguished; no completeness claim.
  fc({ animalSlug: "snow-leopard", commonName: "Snow Leopard", continentSlugs: ["asia"], habitatTags: ["mountain"], distributionNote: "High mountains of Central and South Asia (Himalayas, Tibetan Plateau, Altai).", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "asian-black-bear", commonName: "Asian Black Bear", continentSlugs: ["asia"], habitatTags: ["forest", "mountain"], distributionNote: "Forests across parts of South, East, and Southeast Asia and the Himalayas.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "musk-deer", commonName: "Musk Deer", continentSlugs: ["asia"], habitatTags: ["forest", "mountain"], distributionNote: "Forested and alpine habitats across parts of Asia (Himalayas, Siberia, China).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "sarus-crane", commonName: "Sarus Crane", continentSlugs: ["asia"], habitatTags: ["wetland", "grassland"], distributionNote: "Wetlands and farmland in parts of the Indian subcontinent and Southeast Asia (also northern Australia).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "mandarin-duck", commonName: "Mandarin Duck", continentSlugs: ["asia"], habitatTags: ["wetland", "freshwater", "forest"], distributionNote: "Native to East Asia (China, Japan, Korea, Russian Far East); introduced populations occur in Europe.", confidence: "verified", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "king-cobra", commonName: "King Cobra", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Forests across parts of South and Southeast Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "reticulated-python", commonName: "Reticulated Python", continentSlugs: ["asia"], habitatTags: ["forest", "grassland", "freshwater"], distributionNote: "Forests, grasslands, and rivers across parts of South and Southeast Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "asian-giant-salamander", commonName: "Asian Giant Salamander", continentSlugs: ["asia"], habitatTags: ["freshwater"], distributionNote: "Cool, clear streams and rivers in parts of East Asia (Japan and China).", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "arowana", commonName: "Asian Arowana", continentSlugs: ["asia"], habitatTags: ["freshwater", "wetland"], distributionNote: "Slow rivers, swamps, and flooded forests of parts of Southeast Asia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "mahseer", commonName: "Mahseer", continentSlugs: ["asia"], habitatTags: ["freshwater"], distributionNote: "Fast-flowing rivers and streams across parts of South and Southeast Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "mekong-giant-catfish", commonName: "Mekong Giant Catfish", continentSlugs: ["asia"], habitatTags: ["freshwater"], distributionNote: "Native to the Mekong River basin in Southeast Asia.", confidence: "verified", isNativeRange: true, notes: "Critically Endangered; restricted to the Mekong basin." }),
  fc({ animalSlug: "asian-giant-hornet", commonName: "Asian Giant Hornet", continentSlugs: ["asia"], habitatTags: ["forest", "grassland"], distributionNote: "Native to parts of East and South Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "silkworm", commonName: "Silkworm", continentSlugs: ["asia"], habitatTags: ["urban-adapted"], distributionNote: "A fully domesticated insect (Bombyx mori), reared for silk and not found in the wild; sericulture began in ancient China.", confidence: "verified", notes: "Domesticated; no wild range." }),
  fc({ animalSlug: "clouded-leopard", commonName: "Clouded Leopard", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Forests of parts of South and Southeast Asia and the Himalayan foothills.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "sun-bear", commonName: "Sun Bear", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Tropical forests of parts of Southeast Asia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "takin", commonName: "Takin", continentSlugs: ["asia"], habitatTags: ["mountain", "forest"], distributionNote: "Mountain forests of the eastern Himalayas and parts of China and Myanmar.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "proboscis-monkey", commonName: "Proboscis Monkey", continentSlugs: ["asia"], habitatTags: ["forest", "wetland"], distributionNote: "Endemic to the island of Borneo, in mangrove and riverine forest.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "orangutan", commonName: "Orangutan", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Rainforests of the islands of Borneo and Sumatra.", confidence: "verified", isNativeRange: true, notes: "Restricted to Borneo and Sumatra." }),
  fc({ animalSlug: "gibbon", commonName: "Gibbon", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Tropical forests across parts of South and Southeast Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "hornbill", commonName: "Hornbill", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Many hornbills live in forests of parts of Asia (others occur in sub-Saharan Africa).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "gharial", commonName: "Gharial", continentSlugs: ["asia"], habitatTags: ["freshwater"], distributionNote: "Rivers of the northern Indian subcontinent (e.g. the Ganges basin).", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "saiga", commonName: "Saiga", continentSlugs: ["asia"], habitatTags: ["grassland", "desert"], distributionNote: "Steppe and semi-desert of Central Asia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "macaque", commonName: "Macaque", continentSlugs: ["asia"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Widespread across parts of Asia (with one species in North Africa).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "slow-loris", commonName: "Slow Loris", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Forests of parts of South and Southeast Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "binturong", commonName: "Binturong", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Forests of parts of South and Southeast Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "colugo", commonName: "Colugo", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Rainforests of parts of Southeast Asia.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "tarsier", commonName: "Tarsier", continentSlugs: ["asia"], habitatTags: ["forest", "island"], distributionNote: "Islands of Southeast Asia (e.g. the Philippines, Borneo, and Sulawesi).", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "douc", commonName: "Douc", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Forests of parts of Indochina (Vietnam, Laos, and Cambodia).", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "langur", commonName: "Langur", continentSlugs: ["asia"], habitatTags: ["forest"], distributionNote: "Forests across parts of South and Southeast Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "rhinoceros", commonName: "Rhinoceros", continentSlugs: ["asia"], habitatTags: ["grassland", "forest", "wetland"], distributionNote: "Asian rhinos (Indian, Javan, Sumatran) live in parts of South and Southeast Asia; African species occur on another continent.", confidence: "broad-range", isNativeRange: true, notes: "Distinct species in Asia and Africa." }),
  fc({ animalSlug: "camel", commonName: "Camel", continentSlugs: ["asia"], habitatTags: ["desert", "grassland"], distributionNote: "The wild Bactrian camel is native to Central Asia; camels are also widely domesticated across Asia.", confidence: "broad-range", isNativeRange: true, isDomesticContext: true }),
  fc({ animalSlug: "catfish", commonName: "Catfish", continentSlugs: ["asia"], habitatTags: ["freshwater"], distributionNote: "Catfish are diverse in the rivers and lakes of parts of Asia (and worldwide).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "carp", commonName: "Carp", continentSlugs: ["asia"], habitatTags: ["freshwater"], distributionNote: "Native to parts of Asia and Europe; widely farmed and introduced around the world.", confidence: "broad-range", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "horseshoe-crab", commonName: "Horseshoe Crab", continentSlugs: ["asia"], habitatTags: ["coastal"], distributionNote: "Asian horseshoe crabs (Tachypleus, Carcinoscorpius) live on coasts of parts of Asia (other species on American coasts).", confidence: "broad-range", isNativeRange: true }),

  // === Regional Fauna: Europe Expansion (2026-06-27) ===
  // 20 new European profiles + previously-unrecorded existing European animals.
  // Cautious range framing; reintroduction noted in distributionNote/notes (no schema change); native vs introduced distinguished; no completeness claim.
  fc({ animalSlug: "european-bison", commonName: "European Bison", continentSlugs: ["europe"], habitatTags: ["forest", "grassland"], distributionNote: "Forest and forest-edge mosaics in parts of Europe; restored by reintroduction after becoming extinct in the wild (e.g. Białowieża).", confidence: "verified", isNativeRange: true, notes: "Reintroduced from captive-bred stock; recovering." }),
  fc({ animalSlug: "eurasian-lynx", commonName: "Eurasian Lynx", continentSlugs: ["europe"], habitatTags: ["forest", "mountain"], distributionNote: "Forests across parts of Europe and northern Asia; several European populations are reintroduced.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "european-badger", commonName: "European Badger", continentSlugs: ["europe"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Woodland, grassland and farmland across parts of Europe and into parts of Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "red-deer", commonName: "Red Deer", continentSlugs: ["europe"], habitatTags: ["forest", "grassland", "mountain"], distributionNote: "Woodland, moorland and open hills in parts of Europe (and beyond).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "roe-deer", commonName: "Roe Deer", continentSlugs: ["europe"], habitatTags: ["forest", "grassland"], distributionNote: "Woodland edges and farmland across parts of Europe.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "european-hare", commonName: "European Hare", continentSlugs: ["europe"], habitatTags: ["grassland"], distributionNote: "Open grassland and farmland in parts of Europe.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "european-hedgehog", commonName: "European Hedgehog", continentSlugs: ["europe"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Gardens, hedgerows, woodland and grassland in parts of western and northern Europe.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "european-otter", commonName: "European Otter", continentSlugs: ["europe"], habitatTags: ["freshwater", "wetland", "coastal"], distributionNote: "Rivers, lakes, wetlands and some coasts across parts of Europe and Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "alpine-ibex", commonName: "Alpine Ibex", continentSlugs: ["europe"], habitatTags: ["mountain"], distributionNote: "Steep rocky slopes of the European Alps; restored across the Alps by reintroduction from a single remnant population.", confidence: "verified", isNativeRange: true, notes: "Famous recovery from near-extinction." }),
  fc({ animalSlug: "white-stork", commonName: "White Stork", continentSlugs: ["europe"], habitatTags: ["wetland", "grassland"], distributionNote: "Breeds in wetlands and farmland in parts of Europe; a long-distance migrant to sub-Saharan Africa (and parts of Asia).", confidence: "broad-range", isNativeRange: true, notes: "European range is the breeding range; winters in Africa." }),
  fc({ animalSlug: "barn-owl", commonName: "Barn Owl", continentSlugs: ["europe"], habitatTags: ["grassland", "urban-adapted"], distributionNote: "Farmland and open country in parts of Europe; one of the most widespread birds in the world.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "golden-eagle", commonName: "Golden Eagle", continentSlugs: ["europe"], habitatTags: ["mountain", "grassland"], distributionNote: "Mountains and open upland country across parts of Europe, Asia, North America and North Africa.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "capercaillie", commonName: "Western Capercaillie", continentSlugs: ["europe"], habitatTags: ["forest"], distributionNote: "Mature coniferous and mixed forest in parts of Europe and northern Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "european-viper", commonName: "European Adder", continentSlugs: ["europe"], habitatTags: ["forest", "grassland", "wetland"], distributionNote: "Heath, moor, woodland edge and damp ground across parts of Europe and Asia; the only snake found within the Arctic Circle.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "grass-snake", commonName: "Grass Snake", continentSlugs: ["europe"], habitatTags: ["wetland", "freshwater", "grassland"], distributionNote: "Wetlands, ponds and damp grassland in parts of Europe.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "european-tree-frog", commonName: "European Tree Frog", continentSlugs: ["europe"], habitatTags: ["wetland", "forest"], distributionNote: "Shrubs, reeds and trees near water in parts of Europe.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "atlantic-salmon", commonName: "Atlantic Salmon", continentSlugs: ["europe"], habitatTags: ["freshwater", "coastal"], distributionNote: "Native to rivers draining to the North Atlantic in parts of Europe (and North America); also widely farmed.", confidence: "broad-range", isNativeRange: true, notes: "Wild populations have declined; also farmed at scale." }),
  fc({ animalSlug: "european-eel", commonName: "European Eel", continentSlugs: ["europe"], habitatTags: ["freshwater", "wetland", "coastal"], distributionNote: "Fresh and brackish waters across parts of Europe; thought to spawn in the Sargasso Sea.", confidence: "verified", isNativeRange: true, notes: "Critically Endangered; oceanic spawning still uncertain." }),
  fc({ animalSlug: "brown-trout", commonName: "Brown Trout", continentSlugs: ["europe"], habitatTags: ["freshwater", "coastal"], distributionNote: "Native to fresh and coastal waters of parts of Europe (and western Asia / North Africa); widely introduced on other continents.", confidence: "broad-range", isNativeRange: true, notes: "Introduced widely outside its native range." }),
  fc({ animalSlug: "stag-beetle", commonName: "Stag Beetle", continentSlugs: ["europe"], habitatTags: ["forest", "urban-adapted"], distributionNote: "Woodland, parks and gardens with dead wood in parts of Europe.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "pine-marten", commonName: "Pine Marten", continentSlugs: ["europe"], habitatTags: ["forest"], distributionNote: "Woodland across parts of Europe and into parts of Asia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "fire-salamander", commonName: "Fire Salamander", continentSlugs: ["europe"], habitatTags: ["forest", "freshwater"], distributionNote: "Damp broadleaf woodland near streams in parts of central and southern Europe.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "wild-boar", commonName: "Wild Boar", continentSlugs: ["europe"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Woodland and farmland across much of Europe (and beyond); also lives around some towns.", confidence: "broad-range", isNativeRange: true }),

  // === Regional Fauna: North America Expansion (2026-06-28) ===
  // 20 new NA profiles + previously-unrecorded existing NA animals.
  // Cautious range; native vs introduced distinguished; Arctic/circumpolar + migration noted; no completeness claim.
  fc({ animalSlug: "bighorn-sheep", commonName: "Bighorn Sheep", continentSlugs: ["north-america"], habitatTags: ["mountain", "grassland"], distributionNote: "Mountains, foothills and rocky terrain in parts of western North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "mountain-goat", commonName: "Mountain Goat", continentSlugs: ["north-america"], habitatTags: ["mountain"], distributionNote: "Steep alpine cliffs and high mountains in parts of north-western North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "cougar", commonName: "Cougar", continentSlugs: ["north-america"], habitatTags: ["forest", "mountain", "grassland", "desert"], distributionNote: "Wide-ranging; found in parts of North America (and South America), from forests to deserts.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "american-black-bear", commonName: "American Black Bear", continentSlugs: ["north-america"], habitatTags: ["forest"], distributionNote: "Forests across much of North America (Canada, the United States and parts of Mexico).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "polar-bear", commonName: "Polar Bear", continentSlugs: ["north-america"], habitatTags: ["polar", "coastal"], distributionNote: "Sea ice and coasts of the Arctic, including parts of northern North America; circumpolar.", confidence: "verified", isNativeRange: true, notes: "Vulnerable; depends on sea ice." }),
  fc({ animalSlug: "arctic-fox", commonName: "Arctic Fox", continentSlugs: ["north-america"], habitatTags: ["polar", "tundra"], distributionNote: "Arctic tundra of parts of northern North America; circumpolar.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "bald-eagle", commonName: "Bald Eagle", continentSlugs: ["north-america"], habitatTags: ["coastal", "freshwater", "wetland", "forest"], distributionNote: "Near lakes, rivers and coasts across much of North America.", confidence: "broad-range", isNativeRange: true, notes: "Recovered after DDT was restricted." }),
  fc({ animalSlug: "wild-turkey", commonName: "Wild Turkey", continentSlugs: ["north-america"], habitatTags: ["forest", "grassland"], distributionNote: "Woodlands and forest edges across parts of North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "whooping-crane", commonName: "Whooping Crane", continentSlugs: ["north-america"], habitatTags: ["wetland"], distributionNote: "A small migratory population breeds in Canada and winters on the Texas Gulf coast; very rare.", confidence: "verified", isNativeRange: true, notes: "Endangered; intensively managed recovery." }),
  fc({ animalSlug: "sandhill-crane", commonName: "Sandhill Crane", continentSlugs: ["north-america"], habitatTags: ["wetland", "grassland"], distributionNote: "Wetlands, grasslands and farmland across parts of North America (and north-eastern Asia).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "california-condor", commonName: "California Condor", continentSlugs: ["north-america"], habitatTags: ["mountain"], distributionNote: "Reintroduced to parts of the south-western US and Mexico after becoming Extinct in the Wild.", confidence: "verified", isNativeRange: true, notes: "Critically Endangered; captive-bred and released." }),
  fc({ animalSlug: "snowy-owl", commonName: "Snowy Owl", continentSlugs: ["north-america"], habitatTags: ["polar", "tundra", "grassland"], distributionNote: "Breeds on Arctic tundra (including parts of northern North America); moves south irregularly in winter.", confidence: "broad-range", isNativeRange: true, notes: "Vulnerable." }),
  fc({ animalSlug: "common-loon", commonName: "Common Loon", continentSlugs: ["north-america"], habitatTags: ["freshwater", "wetland", "coastal"], distributionNote: "Clear northern lakes across parts of North America; winters on coasts.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "american-alligator", commonName: "American Alligator", continentSlugs: ["north-america"], habitatTags: ["wetland", "freshwater"], distributionNote: "Fresh and brackish wetlands, swamps and rivers of the south-eastern United States.", confidence: "verified", isNativeRange: true, notes: "Recovered after legal protection." }),
  fc({ animalSlug: "snapping-turtle", commonName: "Snapping Turtle", continentSlugs: ["north-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "Ponds, lakes and slow rivers across much of central and eastern North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "chinook-salmon", commonName: "Chinook Salmon", continentSlugs: ["north-america"], habitatTags: ["freshwater", "coastal"], distributionNote: "Native to the North Pacific and rivers of western North America; also hatchery-raised and introduced (e.g. the Great Lakes).", confidence: "broad-range", isNativeRange: true, isIntroducedRange: true, notes: "Conservation is population-specific." }),
  fc({ animalSlug: "alligator-gar", commonName: "Alligator Gar", continentSlugs: ["north-america"], habitatTags: ["freshwater"], distributionNote: "Large rivers, reservoirs and swamps of the southern United States and parts of Mexico.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "lake-sturgeon", commonName: "Lake Sturgeon", continentSlugs: ["north-america"], habitatTags: ["freshwater"], distributionNote: "Great Lakes, Mississippi and Hudson Bay drainages in parts of North America.", confidence: "broad-range", isNativeRange: true, notes: "Of conservation concern in many states/provinces." }),
  fc({ animalSlug: "monarch-butterfly", commonName: "Monarch Butterfly", continentSlugs: ["north-america"], habitatTags: ["grassland", "forest", "urban-adapted"], distributionNote: "Breeds across much of North America; migrates to overwintering sites in central Mexico and coastal California.", confidence: "broad-range", isNativeRange: true, notes: "Migratory population of significant conservation concern." }),
  fc({ animalSlug: "luna-moth", commonName: "Luna Moth", continentSlugs: ["north-america"], habitatTags: ["forest"], distributionNote: "Hardwood forests of parts of eastern North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "pronghorn", commonName: "Pronghorn", continentSlugs: ["north-america"], habitatTags: ["grassland", "desert"], distributionNote: "Grasslands and shrub-steppe of western and central North America; the fastest land animal in the Americas.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "elk", commonName: "Elk", continentSlugs: ["north-america"], habitatTags: ["forest", "grassland", "mountain"], distributionNote: "Forests, meadows and mountains across parts of North America (also parts of Asia).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "bobcat", commonName: "Bobcat", continentSlugs: ["north-america"], habitatTags: ["forest", "desert", "grassland"], distributionNote: "Forests, scrub and deserts across much of North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "coyote", commonName: "Coyote", continentSlugs: ["north-america"], habitatTags: ["grassland", "forest", "desert", "urban-adapted"], distributionNote: "Highly adaptable; found across much of North America, including around towns and cities.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "skunk", commonName: "Skunk", continentSlugs: ["north-america"], habitatTags: ["forest", "grassland", "urban-adapted"], distributionNote: "Striped and spotted skunks are widespread across much of North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "bison", commonName: "American Bison", continentSlugs: ["north-america"], habitatTags: ["grassland"], distributionNote: "The American bison of the Great Plains and parts of North America; restored after near-extinction.", confidence: "verified", isNativeRange: true, notes: "Recovered from near-extinction in the late 1800s." }),
  fc({ animalSlug: "rattlesnake", commonName: "Rattlesnake", continentSlugs: ["north-america"], habitatTags: ["desert", "grassland", "forest"], distributionNote: "Many rattlesnake species live across parts of North America (and into South America).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "gila-monster", commonName: "Gila Monster", continentSlugs: ["north-america"], habitatTags: ["desert"], distributionNote: "Deserts and arid scrub of the south-western United States and north-western Mexico.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "axolotl", commonName: "Axolotl", continentSlugs: ["north-america"], habitatTags: ["freshwater"], distributionNote: "Restricted to a small area of lakes and canals near Mexico City; Critically Endangered in the wild.", confidence: "verified", isNativeRange: true, notes: "Endemic and Critically Endangered in the wild." }),
  fc({ animalSlug: "bullfrog", commonName: "American Bullfrog", continentSlugs: ["north-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "Native to parts of eastern North America; widely introduced elsewhere, where it can be invasive.", confidence: "broad-range", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "horseshoe-crab", commonName: "Horseshoe Crab", continentSlugs: ["north-america"], habitatTags: ["coastal"], distributionNote: "The Atlantic horseshoe crab lives along the eastern coasts of North America (and Central America).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "scorpion", commonName: "Scorpion", continentSlugs: ["north-america"], habitatTags: ["desert"], distributionNote: "Several scorpion species live in deserts and drylands of parts of North America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "salmon", commonName: "Salmon", continentSlugs: ["north-america"], habitatTags: ["freshwater", "coastal"], distributionNote: "Pacific and Atlantic salmon occur in rivers and seas of parts of North America.", confidence: "broad-range", isNativeRange: true }),

  // === Regional Fauna: South America Expansion (2026-06-28) ===
  // 20 new SA profiles + previously-unrecorded existing SA animals.
  // Cautious range; Galapagos endemics tied to the islands; Andes/Amazon scoped; domestic (llama) flagged; no completeness claim.
  fc({ animalSlug: "giant-anteater", commonName: "Giant Anteater", continentSlugs: ["south-america"], habitatTags: ["grassland", "savanna", "wetland", "forest"], distributionNote: "Grasslands, savannas, wetlands and forests in parts of Central and South America.", confidence: "broad-range", isNativeRange: true, notes: "Vulnerable." }),
  fc({ animalSlug: "vicuna", commonName: "Vicuna", continentSlugs: ["south-america"], habitatTags: ["mountain", "grassland"], distributionNote: "High Andean grasslands (puna) in parts of South America; a famous conservation recovery.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "guanaco", commonName: "Guanaco", continentSlugs: ["south-america"], habitatTags: ["mountain", "grassland", "desert"], distributionNote: "Andes, Patagonian steppe and shrublands in parts of South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "llama", commonName: "Llama", continentSlugs: ["south-america"], habitatTags: ["mountain", "grassland"], distributionNote: "A domesticated Andean camelid, descended from the wild guanaco; not a wild species.", confidence: "verified", isNativeRange: true, isDomesticContext: true, notes: "Domestic animal." }),
  fc({ animalSlug: "spectacled-bear", commonName: "Spectacled Bear", continentSlugs: ["south-america"], habitatTags: ["forest", "mountain", "grassland"], distributionNote: "Andean cloud forests, paramo and other habitats along parts of the Andes in South America.", confidence: "verified", isNativeRange: true, notes: "Vulnerable; the only bear native to South America." }),
  fc({ animalSlug: "pink-river-dolphin", commonName: "Pink River Dolphin", continentSlugs: ["south-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "The Amazon and Orinoco river systems in parts of South America.", confidence: "verified", isNativeRange: true, notes: "Endangered." }),
  fc({ animalSlug: "giant-otter", commonName: "Giant Otter", continentSlugs: ["south-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "Rivers, lakes and wetlands (e.g. the Amazon and Pantanal) in parts of South America.", confidence: "verified", isNativeRange: true, notes: "Endangered; the largest otter." }),
  fc({ animalSlug: "harpy-eagle", commonName: "Harpy Eagle", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Lowland tropical rainforest in parts of Central and South America.", confidence: "broad-range", isNativeRange: true, notes: "Vulnerable." }),
  fc({ animalSlug: "andean-condor", commonName: "Andean Condor", continentSlugs: ["south-america"], habitatTags: ["mountain", "coastal"], distributionNote: "The Andes and adjacent coasts in parts of South America.", confidence: "broad-range", isNativeRange: true, notes: "Vulnerable." }),
  fc({ animalSlug: "macaw", commonName: "Macaw", continentSlugs: ["south-america"], habitatTags: ["forest", "wetland"], distributionNote: "Forests and woodlands of parts of Central and South America; status varies by species.", confidence: "broad-range", isNativeRange: true, notes: "Status varies; some species threatened by trade and habitat loss." }),
  fc({ animalSlug: "rhea", commonName: "Rhea", continentSlugs: ["south-america"], habitatTags: ["grassland", "savanna"], distributionNote: "Open grasslands, pampas and scrub in parts of South America; status varies by species.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "king-vulture", commonName: "King Vulture", continentSlugs: ["south-america"], habitatTags: ["forest", "savanna"], distributionNote: "Lowland forests and savannas in parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "scarlet-ibis", commonName: "Scarlet Ibis", continentSlugs: ["south-america"], habitatTags: ["wetland", "coastal"], distributionNote: "Coastal wetlands, mudflats and mangroves in parts of northern South America (and the Caribbean).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "marine-iguana", commonName: "Marine Iguana", continentSlugs: ["south-america"], habitatTags: ["coastal", "island"], distributionNote: "Endemic to the Galapagos Islands (Ecuador); the only sea-foraging lizard.", confidence: "verified", isNativeRange: true, notes: "Vulnerable; Galapagos endemic." }),
  fc({ animalSlug: "galapagos-tortoise", commonName: "Galapagos Tortoise", continentSlugs: ["south-america"], habitatTags: ["island", "grassland"], distributionNote: "Endemic to the Galapagos Islands (Ecuador); a species complex with status varying by island.", confidence: "verified", isNativeRange: true, notes: "Several species threatened; status varies by island." }),
  fc({ animalSlug: "arapaima", commonName: "Arapaima", continentSlugs: ["south-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "The Amazon basin and nearby river systems in parts of South America.", confidence: "broad-range", isNativeRange: true, notes: "Air-breathing; depleted by overfishing in places." }),
  fc({ animalSlug: "blue-morpho-butterfly", commonName: "Blue Morpho Butterfly", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Rainforests of parts of Central and South America; a group of Morpho species.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "leafcutter-ant", commonName: "Leafcutter Ant", continentSlugs: ["south-america"], habitatTags: ["forest", "grassland"], distributionNote: "Forests and open habitats of parts of Central and South America (genera Atta and Acromyrmex).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "goliath-birdeater", commonName: "Goliath Birdeater", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Rainforest of parts of northern South America; the largest spider by body mass.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "amazonian-giant-centipede", commonName: "Amazonian Giant Centipede", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Parts of northern South America (and nearby); one of the largest centipedes.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "capybara", commonName: "Capybara", continentSlugs: ["south-america"], habitatTags: ["wetland", "grassland", "freshwater"], distributionNote: "Wetlands, grasslands and riverbanks across much of South America; the largest rodent.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "maned-wolf", commonName: "Maned Wolf", continentSlugs: ["south-america"], habitatTags: ["grassland", "savanna"], distributionNote: "Grasslands and savannas (e.g. the Cerrado) in parts of central South America.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "ocelot", commonName: "Ocelot", continentSlugs: ["south-america"], habitatTags: ["forest", "grassland"], distributionNote: "Forests and scrub across parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "howler-monkey", commonName: "Howler Monkey", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Forests of parts of Central and South America; among the loudest land animals.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "spider-monkey", commonName: "Spider Monkey", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Tropical forests of parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "hoatzin", commonName: "Hoatzin", continentSlugs: ["south-america"], habitatTags: ["wetland", "forest"], distributionNote: "Riverside and swamp forests of the Amazon and Orinoco basins in parts of South America.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "poison-dart-frog", commonName: "Poison Dart Frog", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Tropical forests of parts of Central and South America (family Dendrobatidae).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "piranha", commonName: "Piranha", continentSlugs: ["south-america"], habitatTags: ["freshwater"], distributionNote: "Rivers and lakes of parts of South America (several species).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "electric-eel", commonName: "Electric Eel", continentSlugs: ["south-america"], habitatTags: ["freshwater", "wetland"], distributionNote: "Slow fresh waters of the Amazon and Orinoco basins in parts of South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "boa", commonName: "Boa Constrictor", continentSlugs: ["south-america"], habitatTags: ["forest", "grassland"], distributionNote: "Forests and drier habitats across parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "glass-frog", commonName: "Glass Frog", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Humid forests near streams in parts of Central and South America (family Centrolenidae).", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "coati", commonName: "Coati", continentSlugs: ["south-america"], habitatTags: ["forest", "grassland"], distributionNote: "Forests and woodlands across parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "agouti", commonName: "Agouti", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Tropical forests of parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "kinkajou", commonName: "Kinkajou", continentSlugs: ["south-america"], habitatTags: ["forest"], distributionNote: "Tropical forest canopy in parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "peccary", commonName: "Peccary", continentSlugs: ["south-america"], habitatTags: ["forest", "grassland", "desert"], distributionNote: "Forests, grasslands and drylands across parts of Central and South America.", confidence: "broad-range", isNativeRange: true }),

  // === Regional Fauna: Oceania Expansion (2026-06-28) ===
  // 20 new Oceania profiles + previously-unrecorded existing Oceania animals.
  // STRICT dedupe vs the existing oceania record set (SA-QA lesson); sub-regions distinguished
  // (Australia / Tasmania / New Zealand / New Guinea); marine framed coastal; cane toad introduced.
  fc({ animalSlug: "wallaby", commonName: "Wallaby", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland", "mountain"], distributionNote: "Various species across parts of Australia, New Guinea and nearby islands.", confidence: "broad-range", isNativeRange: true, notes: "Group; status varies by species." }),
  fc({ animalSlug: "dingo", commonName: "Dingo", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland", "desert"], distributionNote: "A wild canid of parts of mainland Australia.", confidence: "broad-range", isNativeRange: true, notes: "Taxonomy and native/feral status are debated." }),
  fc({ animalSlug: "cuscus", commonName: "Cuscus", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Rainforests of New Guinea, far northern Australia and nearby islands.", confidence: "broad-range", isNativeRange: true, notes: "Group; centred on New Guinea." }),
  fc({ animalSlug: "dugong", commonName: "Dugong", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Warm shallow coastal seagrass areas of parts of the Indo-Pacific, including northern Australian waters.", confidence: "broad-range", isNativeRange: true, notes: "Marine; Vulnerable." }),
  fc({ animalSlug: "humpback-whale", commonName: "Humpback Whale", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Migrates along Australian and Pacific coasts; found in oceans worldwide.", confidence: "broad-range", isNativeRange: true, notes: "Marine; global migrant." }),
  fc({ animalSlug: "tree-kangaroo", commonName: "Tree Kangaroo", continentSlugs: ["oceania"], habitatTags: ["forest", "mountain"], distributionNote: "Rainforests of New Guinea and far northeastern Australia.", confidence: "broad-range", isNativeRange: true, notes: "Group; several species threatened." }),
  fc({ animalSlug: "galah", commonName: "Galah", continentSlugs: ["oceania"], habitatTags: ["grassland", "urban-adapted"], distributionNote: "Open country across much of mainland Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "black-swan", commonName: "Black Swan", continentSlugs: ["oceania"], habitatTags: ["wetland", "freshwater"], distributionNote: "Wetlands across parts of Australia; introduced elsewhere (e.g. New Zealand).", confidence: "broad-range", isNativeRange: true, isIntroducedRange: true }),
  fc({ animalSlug: "wedge-tailed-eagle", commonName: "Wedge-tailed Eagle", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland", "mountain"], distributionNote: "Across much of mainland Australia, Tasmania and into southern New Guinea.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "takahe", commonName: "Takahe", continentSlugs: ["oceania"], habitatTags: ["grassland", "mountain"], distributionNote: "Endemic to New Zealand; survives through intensive conservation management.", confidence: "verified", isNativeRange: true, notes: "Endangered; New Zealand endemic." }),
  fc({ animalSlug: "saltwater-crocodile", commonName: "Saltwater Crocodile", continentSlugs: ["oceania"], habitatTags: ["wetland", "coastal", "freshwater"], distributionNote: "Estuaries, rivers and coasts of parts of northern Australia and the broader Indo-Pacific.", confidence: "broad-range", isNativeRange: true, notes: "Broad Indo-Pacific range, not only Oceania." }),
  fc({ animalSlug: "blue-tongued-skink", commonName: "Blue-tongued Skink", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland", "desert", "urban-adapted"], distributionNote: "Parts of Australia, New Guinea and nearby islands.", confidence: "broad-range", isNativeRange: true, notes: "Group; status varies by species." }),
  fc({ animalSlug: "cane-toad", commonName: "Cane Toad", continentSlugs: ["oceania"], habitatTags: ["wetland", "grassland", "urban-adapted"], distributionNote: "Introduced and invasive in parts of Australia; native to the Americas.", confidence: "broad-range", isIntroducedRange: true, notes: "Introduced/invasive in Australia; NOT native there." }),
  fc({ animalSlug: "reef-manta-ray", commonName: "Reef Manta Ray", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Tropical and subtropical reefs and coasts of parts of the Indo-Pacific, including Australian waters.", confidence: "broad-range", isNativeRange: true, notes: "Marine/reef; Vulnerable." }),
  fc({ animalSlug: "leafy-seadragon", commonName: "Leafy Seadragon", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Only along parts of the southern and western coasts of Australia.", confidence: "verified", isNativeRange: true, notes: "Marine; limited Australian range." }),
  fc({ animalSlug: "box-jellyfish", commonName: "Box Jellyfish", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Coastal waters of parts of northern Australia and the Indo-Pacific (several species).", confidence: "broad-range", isNativeRange: true, notes: "Marine; group of species." }),
  fc({ animalSlug: "crown-of-thorns-starfish", commonName: "Crown-of-thorns Starfish", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Indo-Pacific coral reefs, including the Great Barrier Reef.", confidence: "broad-range", isNativeRange: true, notes: "Marine/reef; native coral predator." }),
  fc({ animalSlug: "funnel-web-spider", commonName: "Funnel-web Spider", continentSlugs: ["oceania"], habitatTags: ["forest", "urban-adapted"], distributionNote: "Parts of eastern and southern Australia (several species).", confidence: "broad-range", isNativeRange: true, notes: "Group of species." }),
  fc({ animalSlug: "redback-spider", commonName: "Redback Spider", continentSlugs: ["oceania"], habitatTags: ["grassland", "urban-adapted"], distributionNote: "Widespread across parts of Australia, often around buildings.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "giant-weta", commonName: "Giant Weta", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Endemic to New Zealand (several species).", confidence: "verified", isNativeRange: true, notes: "New Zealand endemic; several species threatened." }),
  fc({ animalSlug: "cassowary", commonName: "Cassowary", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Rainforests of New Guinea and far northeastern Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "emu", commonName: "Emu", continentSlugs: ["oceania"], habitatTags: ["grassland", "forest", "desert"], distributionNote: "Across much of mainland Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "kiwi", commonName: "Kiwi", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Endemic to New Zealand (several species).", confidence: "verified", isNativeRange: true, notes: "New Zealand endemic." }),
  fc({ animalSlug: "kakapo", commonName: "Kakapo", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Endemic to New Zealand; Critically Endangered and intensively managed.", confidence: "verified", isNativeRange: true, notes: "NZ endemic; Critically Endangered." }),
  fc({ animalSlug: "kea", commonName: "Kea", continentSlugs: ["oceania"], habitatTags: ["mountain", "forest"], distributionNote: "Mountains of the South Island of New Zealand.", confidence: "verified", isNativeRange: true, notes: "New Zealand endemic." }),
  fc({ animalSlug: "lyrebird", commonName: "Lyrebird", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Forests of parts of southeastern Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "bird-of-paradise", commonName: "Bird-of-paradise", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Mainly the rainforests of New Guinea and nearby areas (and parts of northeastern Australia).", confidence: "broad-range", isNativeRange: true, notes: "Group; mainly New Guinea." }),
  fc({ animalSlug: "tuatara", commonName: "Tuatara", continentSlugs: ["oceania"], habitatTags: ["forest", "coastal"], distributionNote: "Endemic to New Zealand; the only living rhynchocephalian reptile.", confidence: "verified", isNativeRange: true, notes: "New Zealand endemic." }),
  fc({ animalSlug: "frilled-lizard", commonName: "Frilled Lizard", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland"], distributionNote: "Northern Australia and southern New Guinea.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "thorny-devil", commonName: "Thorny Devil", continentSlugs: ["oceania"], habitatTags: ["desert"], distributionNote: "Arid interior of parts of Australia.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "quokka", commonName: "Quokka", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland"], distributionNote: "Parts of southwestern Australia, notably Rottnest Island.", confidence: "verified", isNativeRange: true }),
  fc({ animalSlug: "sugar-glider", commonName: "Sugar Glider", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Forests of parts of eastern and northern Australia and New Guinea.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "echidna", commonName: "Echidna", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland", "desert"], distributionNote: "Across much of Australia and New Guinea; an egg-laying monotreme.", confidence: "broad-range", isNativeRange: true }),
  fc({ animalSlug: "tasmanian-devil", commonName: "Tasmanian Devil", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland"], distributionNote: "Endemic to the island of Tasmania, Australia.", confidence: "verified", isNativeRange: true, notes: "Tasmania; Endangered." }),
  fc({ animalSlug: "sea-turtle", commonName: "Sea Turtle", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Several species occur in Australian and Pacific waters (e.g. green turtles on the Great Barrier Reef).", confidence: "broad-range", isNativeRange: true, notes: "Marine; group of species." }),
  fc({ animalSlug: "blue-ringed-octopus", commonName: "Blue-ringed Octopus", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Tide pools and reefs of parts of Australia and the western Pacific.", confidence: "broad-range", isNativeRange: true, notes: "Marine." }),
  fc({ animalSlug: "clownfish", commonName: "Clownfish", continentSlugs: ["oceania"], habitatTags: ["coastal"], distributionNote: "Coral reefs of the Indo-Pacific, including the Great Barrier Reef.", confidence: "broad-range", isNativeRange: true, notes: "Marine/reef." }),
  fc({ animalSlug: "stick-insect", commonName: "Stick Insect", continentSlugs: ["oceania"], habitatTags: ["forest"], distributionNote: "Many species across parts of Australia, New Guinea and the Pacific.", confidence: "broad-range", isNativeRange: true, notes: "Group of species." }),
  fc({ animalSlug: "numbat", commonName: "Numbat", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland"], distributionNote: "Parts of southwestern Australia; Endangered.", confidence: "verified", isNativeRange: true, notes: "Endangered." }),
  fc({ animalSlug: "bilby", commonName: "Bilby", continentSlugs: ["oceania"], habitatTags: ["desert", "grassland"], distributionNote: "Arid and semi-arid parts of Australia; Vulnerable.", confidence: "verified", isNativeRange: true, notes: "Vulnerable." }),
  fc({ animalSlug: "quoll", commonName: "Quoll", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland"], distributionNote: "Parts of Australia and New Guinea (several species).", confidence: "broad-range", isNativeRange: true, notes: "Group of species." }),
  fc({ animalSlug: "bandicoot", commonName: "Bandicoot", continentSlugs: ["oceania"], habitatTags: ["forest", "grassland"], distributionNote: "Parts of Australia and New Guinea (several species).", confidence: "broad-range", isNativeRange: true, notes: "Group of species." }),
  fc({ animalSlug: "magpie", commonName: "Australian Magpie", continentSlugs: ["oceania"], habitatTags: ["grassland", "forest", "urban-adapted"], distributionNote: "The Australian magpie is widespread across much of Australia (and southern New Guinea).", confidence: "broad-range", isNativeRange: true, notes: "Australian magpie." }),
];

export const FAUNA_RECORD_COUNT = FAUNA_RECORDS.length;
